Repository owncloud/core, pull requests merged in 2018-07, with the labels that each got.

#31953 [stable10] Backport of Fixing the transfer of child shares for transferShare
  apps/files/lib/Command/TransferOwnership.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  tests/acceptance/features/apiMain/transfer-ownership.feature
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#31135 Ability to log extra fields + trigger event when logging
  lib/private/Log.php
  lib/private/Log/Owncloud.php
  tests/lib/LoggerTest.php
Labels: 3 - To Review

#31972 [stable10] Disable jquery globalEval
  core/js/js.js
Labels: 3 - To Review

#31971 Disable jquery globalEval
  core/js/js.js
Labels: 3 - To Review, backport-request

#31967 Log debug message for InsufficientStorage exception
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
Labels: 3 - To Review

#31960 Update PR template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 3 - To Review

#31974 [stable10] Update changelog for 10.0.9 RC3
  CHANGELOG.md
Labels: 3 - To Review

#31943 Add search API to capabilities
  apps/dav/lib/Capabilities.php
  apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
  apps/dav/tests/unit/Connector/Sabre/FilesSearchReportPluginTest.php
Labels: 3 - To Review, backport-request

#31976 notify on build failures when pushed/tagged on core
  .drone.yml
Labels: 3 - To Review

#31981 [stable10] fix translation de
  core/l10n/de.js
  core/l10n/de.json
  core/l10n/de_DE.js
  core/l10n/de_DE.json
  lib/l10n/de.js
  lib/l10n/de.json
  lib/l10n/de_DE.js
  lib/l10n/de_DE.json
Labels: 4 - To release

#31977 [Stable10] notify build failure
  .drone.yml
Labels: 3 - To Review

#31781 Update the sql query to delete duplicate sub share
  lib/private/Repair/RepairSubShares.php
  tests/lib/Repair/RepairSubSharesTest.php
Labels: 3 - To Review

#31926 Update php parser
  Makefile
  build/OCPSinceChecker.php
  composer.json
  composer.lock
  lib/private/App/CodeChecker/CodeChecker.php
  tests/drone/test-phpunit.sh
  tests/lib/Command/AsyncBusTest.php
Labels: 3 - To Review

#31988 empty path has no parents
  lib/private/Files/Cache/Propagator.php
  tests/lib/Files/Cache/PropagatorTest.php
Labels: 3 - To Review, app:federation, app:files, backport-request, bug, p2-high, sev3-medium

#31984 Remove sensitive shared_secret data from occ config:list output
  lib/private/SystemConfig.php
  tests/lib/SystemConfigTest.php
Labels: 3 - To Review, backport-request, bug

#31989 Fix Cache::update() to reset column on oracle
  lib/private/Files/Cache/Cache.php
  tests/lib/Files/Cache/CacheTest.php
Labels: 4 - To release, backport-request, bug, p3-medium

#31963 Add symfony events for login action
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#31998 Dont check for avatar folder if not enabled
  lib/private/TemplateLayout.php
Labels: 3 - To Review, backport-request, bug, feature:avatars, server

#30140 Store installed at version
  core/Command/Status.php
  lib/private/Setup.php
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 3 - To Review, enhancement

#31869 Add UI for switching public mail notification language
  lib/private/Helper/LocaleHelper.php
  lib/private/Settings/SettingsManager.php
  settings/Application.php
  settings/Panels/Admin/FileSharing.php
  settings/Panels/Personal/Profile.php
  settings/js/admin.js
  settings/templates/language.php
  settings/templates/panels/admin/filesharing.php
  settings/templates/panels/personal/profile.php
  tests/Settings/Controller/SettingsPageControllerTest.php
  tests/Settings/Panels/Personal/ProfileTest.php
  tests/lib/Helper/LocaleHelperTest.php
Labels: 3 - To Review, backport-request, feature:sharing

#32003 UI tests for adminSharingSettings
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32015 Fixes 32012 - read the correct translations
  lib/private/Helper/LocaleHelper.php
Labels: 3 - To Review, bug

#32010 Add webDAV acceptance tests for upload-download-propfind of unusual file names
  tests/acceptance/features/apiWebdav/webdav-related.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#32017 [Stable10] UI test admin sharing settings
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
Labels: 3 - To Review, dev:acceptance-tests

#32019 map the webhook to the value which slack plugin expects
  .drone.yml
Labels: 3 - To Review

#32011 Store schedule-calendar-transp as integer in the database
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackendTest.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 3 - To Review, backport-request

#32023 [stable10] notify secrets mapping
  .drone.yml
Labels: 3 - To Review

#32016 [stable10] Add webDAV acceptance tests for upload-download-propfind of unusual file names
  tests/acceptance/features/apiWebdav/webdav-related.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#32021 UI tests for adminAppsSettings
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIAdminAppsSettingsContext.php
  tests/acceptance/features/lib/AdminAppsSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32022 Document security implications of enabling debug in production
  config/config.sample.php
Labels: 4 - To release, backport-request, enhancement, p3-medium, security

#32029 [stable10] Document security implications of enabling debug in production
  config/config.sample.php
Labels: 4 - To release, Waiting On Review/Feedback, enhancement, p3-medium, security

#32041 [stable10] Protect debug statement in token invalidation code
  lib/private/User/Session.php
Labels: 4 - To release, p2-high

#31778 [master] log token related changes
  lib/private/Authentication/Token/DefaultTokenProvider.php
  lib/private/User/Session.php
Labels: 4 - To release

#32043 Add methods to toggle disable/enable sharing settings
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30712 Remove user from the storage setting or storage when user is deleted
  lib/private/Files/External/Service/GlobalStoragesService.php
  lib/private/Files/External/Service/UserStoragesService.php
  lib/private/User/User.php
  lib/public/Files/External/Service/IGlobalStoragesService.php
  lib/public/Files/External/Service/IUserStoragesService.php
  tests/lib/Files/External/Service/GlobalStoragesServiceDeleteUserTest.php
  tests/lib/Files/External/Service/UserStoragesServiceTest.php
Labels: 3 - To Review

#32047 Remove deprecated BackGroundJob API
  lib/base.php
  lib/private/AppFramework/Core/API.php
  lib/public/BackgroundJob.php
Labels: 3 - To Review

#32035 Improve logging text in config.sample.php
  config/config.sample.php
Labels: 4 - To release, Sys Admin

#32061 Remove deprecated Controller methods which have been deprecated in ow…
  lib/public/AppFramework/Controller.php
  tests/lib/AppFramework/Controller/ControllerTest.php
Labels: 3 - To Review

#32052 moves duplicated steps to background
  tests/acceptance/features/apiSharing-v1/accessToShare.feature
  tests/acceptance/features/apiSharing-v1/changingFilesShare.feature
  tests/acceptance/features/apiSharing-v1/createShare.feature
  tests/acceptance/features/apiSharing-v1/deleteShare.feature
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
  tests/acceptance/features/apiSharing-v1/downloadFromShare.feature
  tests/acceptance/features/apiSharing-v1/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiSharing-v1/gettingShares.feature
  tests/acceptance/features/apiSharing-v1/mergeShare.feature
  tests/acceptance/features/apiSharing-v1/moveReceivedShare.feature
  tests/acceptance/features/apiSharing-v1/reShare.feature
  tests/acceptance/features/apiSharing-v1/updateShare.feature
  tests/acceptance/features/apiSharing-v1/uploadToShare.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32024 [stable10] fixes #32007 - store integer values in database for calend…
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackendTest.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 4 - To release, bug, status/STALE

#31948 [stable10] If token based authentication is mandatory a login failed …
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 4 - To release, status/STALE

#31882 [stable10] fixes #26746 - birthday calendar exposes no access share s…
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/Plugin.php
  apps/dav/tests/unit/CalDAV/CalendarTest.php
  apps/dav/tests/unit/CalDAV/PluginTest.php
Labels: 4 - To release, bug, comp:caldav, p3-medium, status/STALE

#31818 [stable10] Add Roave Security Advisories as a development dependency
  composer.json
  composer.lock
Labels: 4 - To release

#31877 [stable10] Added a blank to display names of shared objects
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: 3 - To Review, status/STALE

#32069 [stable10] Backport of Remove user from the storage setting or storag…
  apps/files_external/lib/Lib/Backend/AmazonS3.php
  apps/files_external/lib/Lib/Backend/DAV.php
  apps/files_external/lib/Lib/Backend/Google.php
  apps/files_external/lib/Lib/Backend/Local.php
  apps/files_external/lib/Lib/Backend/OwnCloud.php
  apps/files_external/lib/Lib/Backend/SFTP.php
  apps/files_external/lib/Lib/Backend/SFTP_Key.php
  apps/files_external/lib/Lib/Backend/SMB.php
  apps/files_external/lib/Lib/Backend/SMB_OC.php
  apps/files_external/lib/Lib/Backend/Swift.php
  lib/private/Files/External/Service/GlobalStoragesService.php
  lib/private/Files/External/Service/UserStoragesService.php
  lib/private/User/User.php
  lib/public/Files/External/Service/IGlobalStoragesService.php
  lib/public/Files/External/Service/IUserStoragesService.php
  tests/lib/Files/External/Service/GlobalStoragesServiceDeleteUserTest.php
  tests/lib/Files/External/Service/UserStoragesServiceTest.php
Labels: 4 - To release, app:files_external, bug, server

#32049 [stable10] Improve logging text in config.sample.php
  config/config.sample.php
Labels: 4 - To release, Sys Admin

#32031 [Stable10] UI test admin apps settings
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIAdminAppsSettingsContext.php
  tests/acceptance/features/lib/AdminAppsSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature
Labels: 4 - To release, dev:acceptance-tests

#32027 [stable10] Backport of Set encrypted to zero in file cache after decr…
  lib/private/Encryption/DecryptAll.php
  tests/lib/Encryption/DecryptAllTest.php
Labels: 4 - To release, status/STALE

#32079 [stable10] make sharing tests work correctly with ocs api v2
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#32000 [stable10] Store installed at version
  core/Command/Status.php
  lib/private/Setup.php
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 4 - To release, status/STALE

#31997 [stable10] Remove sensitive shared_secret data from occ config:list output
  lib/private/SystemConfig.php
  tests/lib/SystemConfigTest.php
Labels: 4 - To release, status/STALE

#31996 [stable10] Fix Cache:update() to reset columns on oracle
  lib/private/Files/Cache/Cache.php
  tests/lib/Files/Cache/CacheTest.php
Labels: 4 - To release, status/STALE

#31992 [stable10] empty path has no parents
  lib/private/Files/Cache/Propagator.php
  tests/lib/Files/Cache/PropagatorTest.php
Labels: 4 - To release, app:federation, app:files, bug, p3-medium, sev3-medium, status/STALE

#31986 [stable10] Backport of Fix login exception in decryptall
  apps/encryption/lib/AppInfo/Application.php
  apps/encryption/lib/Crypto/DecryptAll.php
  apps/encryption/tests/Crypto/DecryptAllTest.php
Labels: 4 - To release, status/STALE

#31985 [stable10] Backport of Add symfony events for login action
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 4 - To release

#31978 [stable10] Backport of Log debug message for InsufficientStorage exce…
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
Labels: 4 - To release, status/STALE

#31946 [stable10] Search api stable10
  apps/dav/lib/Capabilities.php
  apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/Files/Xml/SearchRequest.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/FilesSearchReportPluginTest.php
Labels: 4 - To release, status/STALE

#31935 [stable10] return all failed recipients in sendLinkShareMailFromBody
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 4 - To release, feature:sharing, status/STALE

#31928 [Stable10] Lock dialog form fields while processing
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
Labels: 4 - To release, bug, design, p3-medium, status/STALE

#31918 [stable10] AppManager text typo and PHPdoc return tags
  apps/dav/lib/CardDAV/CardDavBackend.php
  lib/private/App/AppManager.php
  lib/private/App/DependencyAnalyzer.php
  lib/private/App/PlatformRepository.php
  lib/private/Encryption/Manager.php
  lib/private/Files/Filesystem.php
  lib/private/Installer.php
  lib/private/Share/Helper.php
  lib/private/legacy/defaults.php
  lib/private/legacy/template/functions.php
Labels: 4 - To release, status/STALE

#31912 [stable10] Bump symfony 3.4.11 to 3.4.12
  composer.lock
Labels: 3 - To Review, dependencies, status/STALE

#32072 make sharing tests work correctly with ocs api v2
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#31891 [stable10] Optimize PUT - with custom mtime, use storage instead of view
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Connector/Sabre/Node.php
Labels: 4 - To release, status/STALE

#31889 [stable10] remove dead code
  apps/files_sharing/lib/Migration.php
Labels: 4 - To release, status/STALE

#31858 [stable10] Handle SSL certificate verifications for others than Let's Encrypt
  .htaccess
  lib/private/Setup.php
Labels: 4 - To release, status/STALE

#31824 [stable10] Add can_share to capabilities
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/tests/CapabilitiesTest.php
  lib/private/Share20/Manager.php
  lib/private/legacy/util.php
  tests/TestHelpers/AppConfigHelper.php
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/lib/UtilTest.php
Labels: 4 - To release, status/STALE

#31803 [stable10] Skip filecache repair step for version greater than 10.0.4
  apps/files/lib/Command/Scan.php
  lib/private/Repair.php
  lib/private/Repair/RepairMismatchFileCachePath.php
  tests/lib/Repair/RepairMismatchFileCachePathTest.php
Labels: 4 - To release, status/STALE

#31798 [stable10] Reload the filelist view when accepting or rejecting a share
  apps/files_sharing/js/app.js
  apps/files_sharing/tests/js/appSpec.js
Labels: 4 - To release, feature:sharing, status/STALE

#31783 [Stable10] Do not throw an error when the same theme enabled twice
  lib/private/App/AppManager.php
  tests/lib/App/ManagerTest.php
Labels: 4 - To release, bug, feature:theming, status/STALE

#31768 [stable10] Optimize PUT - don't fetch and update checksum again, reuse the one from part file
  apps/dav/lib/Connector/Sabre/File.php
  lib/private/Files/Stream/Checksum.php
Labels: status/STALE

#31767 [Stable10] Allow different language in public link share email
  core/ajax/share.php
  lib/private/Share/MailNotifications.php
  lib/private/legacy/template.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 4 - To release, enhancement, p3-medium, status/STALE

#31174 [master] Option to reenable users when syncing with a backend
  core/Command/User/SyncBackend.php
  lib/private/User/SyncService.php
  tests/lib/Command/User/SyncBackendTest.php
  tests/lib/User/SyncServiceTest.php
Labels: 4 - To release, app:user_ldap, backport-request, comp:console-occ, enhancement, p3-medium, status/STALE

#31146 [stable10] Update the sql query to delete duplicate sub share
  lib/private/Repair/RepairSubShares.php
  tests/lib/Repair/RepairSubSharesTest.php
Labels: 4 - To release, bug, status/STALE

#31959 Revert "Revert "[stable10] Cleanup the encryption keys after file deletion""
  apps/files_trashbin/lib/Trashbin.php
  apps/files_trashbin/tests/TrashbinTest.php
Labels: 4 - To release, status/STALE

#32077 [stable10] moves duplicated steps to background
  tests/acceptance/features/apiSharing-v1/accessToShare.feature
  tests/acceptance/features/apiSharing-v1/changingFilesShare.feature
  tests/acceptance/features/apiSharing-v1/createShare.feature
  tests/acceptance/features/apiSharing-v1/deleteShare.feature
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
  tests/acceptance/features/apiSharing-v1/downloadFromShare.feature
  tests/acceptance/features/apiSharing-v1/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiSharing-v1/gettingShares.feature
  tests/acceptance/features/apiSharing-v1/mergeShare.feature
  tests/acceptance/features/apiSharing-v1/moveReceivedShare.feature
  tests/acceptance/features/apiSharing-v1/reShare.feature
  tests/acceptance/features/apiSharing-v1/updateShare.feature
  tests/acceptance/features/apiSharing-v1/uploadToShare.feature
Labels: 3 - To Review, dev:acceptance-tests

#32074 Test sharing with ocs api v2
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharing-v1/accessToShare.feature
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
  tests/acceptance/features/apiSharing/acceptShares.feature
  tests/acceptance/features/apiSharing/accessToShare.feature
  tests/acceptance/features/apiSharing/changingFilesShare.feature
  tests/acceptance/features/apiSharing/createShare.feature
  tests/acceptance/features/apiSharing/deleteShare.feature
  tests/acceptance/features/apiSharing/disableSharing.feature
  tests/acceptance/features/apiSharing/downloadFromShare.feature
  tests/acceptance/features/apiSharing/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiSharing/gettingShares.feature
  tests/acceptance/features/apiSharing/mergeShare.feature
  tests/acceptance/features/apiSharing/moveReceivedShare.feature
  tests/acceptance/features/apiSharing/multilinksharing.feature
  tests/acceptance/features/apiSharing/reShare.feature
  tests/acceptance/features/apiSharing/updateShare.feature
  tests/acceptance/features/apiSharing/uploadToShare.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31962 Trigger mountConfigLoaded event properly, and initialize events after
  apps/files_external/js/settings.js
  apps/files_external/tests/js/settingsSpec.js
Labels: 3 - To Review, backport-request

#32099 add create-bucket command
  .drone.yml
Labels: 2 - Developing, backport-request

#32100 [stable10] add create-bucket command
  .drone.yml
Labels: 3 - To Review

#32097 allow public uploads to fail when expected
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32096 allow the public to upload a file from source in acceptance tests
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32102 [stable10] allow the public to upload a file from source in acceptance tests
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#32101 [stable10] allow public uploads to fail when expected
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#32091 [stable10] test sharing with OCS API v2
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharing-v1/accessToShare.feature
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
  tests/acceptance/features/apiSharing/acceptShares.feature
  tests/acceptance/features/apiSharing/accessToShare.feature
  tests/acceptance/features/apiSharing/changingFilesShare.feature
  tests/acceptance/features/apiSharing/createShare.feature
  tests/acceptance/features/apiSharing/deleteShare.feature
  tests/acceptance/features/apiSharing/disableSharing.feature
  tests/acceptance/features/apiSharing/downloadFromShare.feature
  tests/acceptance/features/apiSharing/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiSharing/gettingShares.feature
  tests/acceptance/features/apiSharing/mergeShare.feature
  tests/acceptance/features/apiSharing/moveReceivedShare.feature
  tests/acceptance/features/apiSharing/multilinksharing.feature
  tests/acceptance/features/apiSharing/reShare.feature
  tests/acceptance/features/apiSharing/updateShare.feature
  tests/acceptance/features/apiSharing/uploadToShare.feature
Labels: 3 - To Review, dev:acceptance-tests

#32108 calculate num of chunks in acceptance tests
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#32106 Bump paragonie/random_compat v2.0.15 to v2.0.17
  composer.lock
Labels: 3 - To Review, dependencies

#32107 [stable10] Bump paragonie/random_compat v2.0.15 to v2.0.17
  composer.lock
Labels: 3 - To Review, dependencies

#32109 [stable10] calculate num of chunks in acceptance tests
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#32086 Cleanup federation phase 1
  apps/dav/appinfo/v1/publicwebdav.php
  apps/federatedfilesharing/appinfo/app.php
  apps/federatedfilesharing/appinfo/routes.php
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/lib/FedShareManager.php
  apps/federatedfilesharing/lib/RequestHandler.php
  apps/federatedfilesharing/tests/Controller/RequestHandlerTest.php
  apps/federatedfilesharing/tests/FedShareManagerTest.php
  apps/files_sharing/ajax/external.php
  apps/files_sharing/ajax/shareinfo.php
  apps/files_sharing/lib/ShareBackend/File.php
  core/routes.php
  lib/private/AppFramework/Routing/RouteConfig.php
  lib/private/Route/Router.php
  ocs/routes.php
Labels: 3 - To Review, backport-request

#32073 Move common scenarios in web dav to separate file
  tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
  tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature
  tests/acceptance/features/apiWebdav/webdav-related.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32115 Bump nikic/php-parser v4.0.2 to v4.0.3
  composer.lock
Labels: 3 - To Review, dependencies

#32118 deleted unused variable
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32119 [stable10] deleted unused variable
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#32123 Remove unused modifyTextOfFile
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32093 [stable10] files:scan : add number of items per second on printed result
  apps/files/lib/Command/Scan.php
Labels: 3 - To Review, enhancement

#32054 [Stable10] Add methods to toggle disable/enable sharing settings
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
Labels: 4 - To release, dev:acceptance-tests

#32051 Remove deprecated interface OCP\Files\Storage in favor of OCP\Files\S…
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
  apps/dav/tests/unit/Connector/Sabre/NodeTest.php
  apps/federation/tests/DbHandlerTest.php
  apps/files_sharing/lib/SharedStorage.php
  apps/files_sharing/tests/API/Share20OCSTest.php
  apps/files_sharing/tests/MountProviderTest.php
  apps/files_sharing/tests/SharedStorageTest.php
  lib/private/Encryption/EncryptionWrapper.php
  lib/private/Files/External/Auth/Password/SessionCredentials.php
  lib/private/Files/External/ConfigAdapter.php
  lib/private/Files/External/PersonalMount.php
  lib/private/Files/External/SessionStorageWrapper.php
  lib/private/Files/External/StorageModifierTrait.php
  lib/private/Files/FileInfo.php
  lib/private/Files/Meta/MetaFileVersionNode.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/FailedStorage.php
  lib/private/Files/Storage/Local.php
  lib/private/Files/Storage/Storage.php
  lib/private/Files/Storage/StorageFactory.php
  lib/private/Files/Storage/Wrapper/Availability.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Quota.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/private/Share20/Manager.php
  lib/private/legacy/util.php
  lib/public/Files/FileInfo.php
  lib/public/Files/Node.php
  lib/public/Files/Storage.php
  lib/public/Files/Storage/IStorage.php
  tests/lib/Files/Mount/MountPointTest.php
  tests/lib/Files/Node/NodeTest.php
  tests/lib/Files/Storage/Storage.php
  tests/lib/Files/Storage/StorageFactoryTest.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
  tests/lib/Files/ViewTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#32062 Tech dept/remove deprecated owncloud 8.0.0 calls
  apps/files/templates/simplelist.php
  apps/files_versions/lib/Storage.php
  core/js/config.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Preview/Office.php
  lib/private/Share/Share.php
  lib/private/legacy/util.php
  lib/public/Config.php
  lib/public/Constants.php
  lib/public/Template.php
  public.php
  tests/lib/PublicNamespace/OCPConfigTest.php
  tests/lib/UtilTest.php
Labels: 3 - To Review

#32004 [Stable10] Add UI for switching public mail notification language
  lib/private/Helper/LocaleHelper.php
  lib/private/Settings/SettingsManager.php
  settings/Application.php
  settings/Panels/Admin/FileSharing.php
  settings/Panels/Personal/Profile.php
  settings/js/admin.js
  settings/templates/language.php
  settings/templates/panels/admin/filesharing.php
  settings/templates/panels/personal/profile.php
  tests/Settings/Controller/SettingsPageControllerTest.php
  tests/Settings/Panels/Personal/ProfileTest.php
  tests/lib/Helper/LocaleHelperTest.php
Labels: 4 - To release, feature:sharing

#32128 Delete excess phpdoc public upload content
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32130 [stable10] Delete excess phpdoc public upload content
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
Labels: 3 - To Review, dev:acceptance-tests

#32126 [stable10] Remove unused modifyTextOfFile
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 3 - To Review, dev:acceptance-tests

#32131 [Stable10] Fix overriding for gif images in themes for CLI scripts
  lib/base.php
  lib/private/Server.php
  lib/private/URLGenerator.php
  tests/lib/UrlGeneratorTest.php
Labels: 3 - To Review, bug, feature:theming

#32002 Report "Wrong current password" to user
  settings/ChangePassword/Controller.php
  tests/acceptance/features/apiProvisioning-v1/addToGroup.feature
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/webUIPersonalSettings/changePasswordFromSetting.feature
Labels: 3 - To Review, backport-request, bug, p4-low

#32144 Workaround mink selenium2 driver regressions
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/OwncloudPage.php
Labels: 3 - To Review, dev:acceptance-tests

#32145 [stable10] workaround mink selenium2 driver regressions
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/OwncloudPage.php
Labels: 3 - To Review, dependencies, dev:acceptance-tests

#32146 [stable10] Report "Wrong current password" to user
  settings/ChangePassword/Controller.php
  tests/acceptance/features/apiProvisioning-v1/addToGroup.feature
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/webUIPersonalSettings/changePasswordFromSetting.feature
Labels: 4 - To release

#32095 [stable10] Mountconfigloaded event fix stable10
  apps/files_external/js/settings.js
  apps/files_external/tests/js/settingsSpec.js
Labels: 3 - To Review, app:files_external, settings:personal

#32147 throw exception when json_decode of log fails
  tests/acceptance/features/bootstrap/Logging.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31109 [stable10] do not urlencode group id
  settings/js/users/groups.js
  tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature
Labels: 4 - To release, blue-ticket, bug, p4-low, settings:users, sev3-medium

#32148 [stable10] throw exception when json_decode of log fails
  tests/acceptance/features/bootstrap/Logging.php
Labels: 3 - To Review, dev:acceptance-tests

#32122 Remove unneeded steps in recreate master key feature
  tests/acceptance/features/apiMain/recreatemasterkey.feature
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 3 - To Review, dev:acceptance-tests

#32151 [stable10] Remove unneeded steps in recreate master key feature
  tests/acceptance/features/apiMain/recreatemasterkey.feature
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 3 - To Review, dev:acceptance-tests

#31105 Introduce IStorage based Node, Folder & File, make avatar manager wor…
  lib/private/Avatar.php
  lib/private/AvatarManager.php
  lib/private/Files/Storage/File.php
  lib/private/Files/Storage/Folder.php
  lib/private/Files/Storage/Node.php
  lib/public/Files/Storage/IStorage.php
  tests/lib/AvatarManagerTest.php
  tests/lib/AvatarTest.php
  tests/lib/Files/Storage/FileTest.php
  tests/lib/Files/Storage/FolderTest.php
  tests/lib/Files/Storage/NodeTest.php
Labels: 3 - To Review, bug, comp:filesystem, feature:avatars, p3-medium, performance, settings:users

#31740 [stable10] Sharing blacklist groups stable10
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/js/settings.js
  apps/files_sharing/lib/API/OCSShareWrapper.php
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/lib/Panels/Admin/SettingsPanel.php
  apps/files_sharing/lib/SharingBlacklist.php
  apps/files_sharing/templates/settings.php
  apps/files_sharing/tests/API/Share20OCSTest.php
  apps/files_sharing/tests/API/ShareesTest.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Panels/Admin/SettingsPanelTest.php
  apps/files_sharing/tests/SharingBlacklistTest.php
Labels: 4 - To release, feature:sharing

#31925 Prevent PHP CS scanning stray folders
  .gitignore
  .php_cs.dist
Labels: 3 - To Review, backport-request

#31348 Merging api web ui acceptance test scripts
  .drone.yml
  .travis.yml
  tests/acceptance/run.sh
  tests/drone/test-acceptance.sh
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#32159 [stable10] merging api web ui acceptance test scripts
  .drone.yml
  .travis.yml
  tests/acceptance/run.sh
  tests/drone/test-acceptance.sh
Labels: 3 - To Review, dev:acceptance-tests

#32127 [stable10] Update changelog for upcoming 10.0.10
  CHANGELOG.md
Labels: 3 - To Review

#31890 Fix warning in logs while moving FutureFile after chunk assembly
  apps/dav/lib/Server.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
  tests/acceptance/features/bootstrap/LoggingContext.php
Labels: 3 - To Review, bug, p3-medium

#32157 [stable10] Add php cs exclusions
  .gitignore
  .php_cs.dist
Labels: 3 - To Review

#32162 Fix decrypt of single user in decrypt-all command
  lib/private/Encryption/DecryptAll.php
  tests/lib/Encryption/DecryptAllTest.php
Labels: 3 - To Review, backport-request

#32160 fix acceptance tests when webserver runs in subfolder
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/CommandLine.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/run.sh
Labels: 3 - To Review, dev:acceptance-tests

#32173 [stable10] fix acceptance tests when webserver runs in subfolder
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/CommandLine.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/run.sh
Labels: 3 - To Review, dev:acceptance-tests

#32176 [stable10] use remote occ as much as possible
  tests/acceptance/run.sh
Labels: 3 - To Review, dev:acceptance-tests

#32177 remove duplicate code in acceptance tests script
  tests/acceptance/run.sh
Labels: 3 - To Review, dev:acceptance-tests

#32179 [stable10] remove duplicate code in acceptance tests script
  tests/acceptance/run.sh
Labels: 3 - To Review, dev:acceptance-tests

#32182 [stable10] Acceptance test code style
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/lib/OwncloudPage.php
Labels: 3 - To Review, dev:acceptance-tests

#32168 [stable10] Backport of Fix decrypt of single user in decrypt-all command
  lib/private/Encryption/DecryptAll.php
  tests/lib/Encryption/DecryptAllTest.php
Labels: 3 - To Review, app:encryption, bug, p3-medium

#32120 Fixes #32090 - browser extension urls in origin header do not trigger…
  apps/dav/lib/Connector/Sabre/CorsPlugin.php
  apps/dav/tests/unit/Connector/Sabre/CorsPluginTest.php
Labels: 3 - To Review, backport-request, bug

#32150 Move "no-change" result below all the checks
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/API/Share20OCSTest.php
Labels: 3 - To Review, backport-request, bug, feature:sharing, p2-high

#32189 [stable10] Fixes #32090 - browser extension urls in origin header do …
  apps/dav/lib/Connector/Sabre/CorsPlugin.php
  apps/dav/tests/unit/Connector/Sabre/CorsPluginTest.php
Labels: 3 - To Review, bug

#32193 Revert "Introduce IStorage based Node, Folder & File, make avatar manager wor…"
  lib/private/Avatar.php
  lib/private/AvatarManager.php
  lib/private/Files/Storage/File.php
  lib/private/Files/Storage/Folder.php
  lib/private/Files/Storage/Node.php
  lib/public/Files/Storage/IStorage.php
  tests/lib/AvatarManagerTest.php
  tests/lib/AvatarTest.php
  tests/lib/Files/Storage/FileTest.php
  tests/lib/Files/Storage/FolderTest.php
  tests/lib/Files/Storage/NodeTest.php
Labels: 3 - To Review

#32164 Revert API breakage in IStorage
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Common.php
  lib/private/Files/Storage/FailedStorage.php
  lib/private/Files/Storage/Local.php
  lib/private/Files/Storage/Storage.php
  lib/private/Files/Storage/Wrapper/Availability.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  lib/private/Files/Storage/Wrapper/Jail.php
  lib/private/Files/Storage/Wrapper/Quota.php
  lib/private/Files/Storage/Wrapper/Wrapper.php
  lib/public/Files/Storage.php
  lib/public/Files/Storage/IStorage.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
  tests/lib/Files/ViewTest.php
Labels: 3 - To Review

#32190 fix restoring settings to original state after testrun
  tests/TestHelpers/AppConfigHelper.php
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#32191 [stable10] fix reset settings to original state after testrun
  tests/TestHelpers/AppConfigHelper.php
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#32202 [stable10] Add url parameter which open a specific details tab right …
  apps/files/js/app.js
  apps/files/js/filelist.js
  apps/files/lib/Controller/ViewController.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
Labels: 3 - To Review

#32203 Remove $CLASSPATH - this is no longer needed. Apps are using proper n…
  apps/files_external/3rdparty/composer.json
  apps/files_external/3rdparty/composer/autoload_classmap.php
  apps/files_external/3rdparty/composer/autoload_files.php
  apps/files_external/3rdparty/composer/autoload_real.php
  apps/files_external/3rdparty/composer/autoload_static.php
  apps/files_external/appinfo/app.php
  lib/autoloader.php
Labels: 4 - To release

#32028 Unit tests for validatePassword event
  tests/lib/Share/ShareTest.php
  tests/lib/Share20/ManagerTest.php
  tests/lib/User/ManagerTest.php
Labels: 4 - To release, backport-request

#32013 [stable10] Read mtime from both properties
  apps/files/js/file-upload.js
  apps/files/tests/js/fileUploadSpec.js
Labels: 3 - To Review, backport-request
