Repository owncloud/core, pull requests merged in 2018-06, with the labels that each got.

#31608 Add contentOfFileShouldBe acceptance test scripts and refactor
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/apiMain/dav-versions.feature
  tests/acceptance/features/apiSharing-v1/downloadFromShare.feature
  tests/acceptance/features/apiSharing-v1/uploadToShare.feature
  tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
  tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#31611 [stable10] Add contentOfFileShouldBe acceptance test scripts and refactor
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/apiSharing-v1/downloadFromShare.feature
  tests/acceptance/features/apiSharing-v1/uploadToShare.feature
  tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
  tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#31610 [Stable10] api test use feature context
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#31605 [stable10] Use the userid obtained from checkPassword after login is …
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#31597 Proceed encrypt-all by enabling user-keys if no mode is selected by user
  core/Command/Encryption/EncryptAll.php
  tests/Core/Command/Encryption/EncryptAllTest.php
Labels: 3 - To Review, app:encryption, backport-request, bug

#31612 [stable10] Proceed encrypt-all by enabling user-keys if no mode is selected by user
  apps/encryption/lib/AppInfo/Application.php
  apps/encryption/lib/Hooks/UserHooks.php
  apps/encryption/tests/Hooks/UserHooksTest.php
  core/Command/Encryption/EncryptAll.php
  tests/Core/Command/Encryption/EncryptAllTest.php
Labels: 3 - To Review

#31614 Enhance log file contains acceptance test steps
  tests/acceptance/features/bootstrap/Logging.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31615 [stable10] Enhance log file contains acceptance test steps
  tests/acceptance/features/bootstrap/Logging.php
Labels: 3 - To Review, dev:acceptance-tests

#31596 [stable10] Exclude uploads directory from read-only cache mask
  lib/private/Files/Cache/Wrapper/ReadOnlyCachePermissionsMask.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, backport-request, bug, p2-high, sev3-medium

#31619 [stable10] Don`t apply checksum wrapper on read-write streams
  lib/private/Files/Storage/Wrapper/Checksum.php
  tests/lib/Files/Storage/Wrapper/ChecksumTest.php
Labels: 4 - To release

#31102 Don`t apply checksum wrapper to mixed r/w streams
  lib/private/Files/Storage/Wrapper/Checksum.php
  tests/lib/Files/Storage/Wrapper/ChecksumTest.php
Labels: 4 - To release, backport-request

#31589 Remove unneeded package-lock
  build/package-lock.json
Labels: 3 - To Review

#31570 Bump symfony 3.4.9 to 3.4.11
  composer.lock
Labels: 3 - To Review, dependencies

#31571 [stable10] Bump symfony 3.4.9 to 3.4.11
  composer.lock
Labels: 3 - To Review, dependencies

#31493 [stable10] Save timezone as given during login
  core/Controller/LoginController.php
  tests/Core/Controller/LoginControllerTest.php
Labels: 3 - To Review

#31537 Add symfony event for public links shared by email
  core/ajax/share.php
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 3 - To Review

#31266 [stable10] Add events for user preference changes
  lib/base.php
  lib/private/AllConfig.php
  lib/private/Server.php
  tests/lib/AllConfigTest.php
Labels: 3 - To Review, backport-request, enhancement, p3-medium

#31632 [stable10] Add symfony event for public links shared by email
  core/ajax/share.php
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 4 - To release

#31600 [stable10] Use '.part' name appended to the file name for encryptall
  apps/encryption/lib/Crypto/EncryptAll.php
  apps/encryption/tests/Crypto/EncryptAllTest.php
  apps/encryption/tests/HookManagerTest.php
  tests/drone/test-phpunit.sh
Labels: 4 - To release

#31618 [master] fix chunked upload for guest app
  lib/private/Files/Cache/Wrapper/ReadOnlyCachePermissionsMask.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 4 - To release, bug

#31254 [master] Fix mail debug message recipient field
  lib/private/Mail/Mailer.php
  tests/lib/Mail/MailerTest.php
Labels: 3 - To Review

#31642 userCancelsUploadWithId gherkin format fix
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31643 [stable10] userCancelsUploadWithId gherkin format fix
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#31307 [master] Add emitters for user preferences
  lib/base.php
  lib/private/AllConfig.php
  lib/private/Server.php
  tests/lib/AllConfigTest.php
Labels: enhancement

#31646 Bump php-cs-fixer from 2.11 to 2.12
  apps/files_versions/lib/Storage.php
  composer.lock
Labels: 3 - To Review, dependencies

#31648 Mock EventDispatcher instead of creating and listening events
  tests/lib/AllConfigTest.php
Labels: 3 - To Review

#31650 [stable10] Mock EventDispatcher instead of creating and listening events
  tests/lib/AllConfigTest.php
Labels: 3 - To Review

#31620 Provide summarized acceptance test chunking upload steps
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/apiMain/transfer-ownership.feature
  tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
  tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#31621 [stable10] Provide summarized acceptance test chunking upload steps
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/apiMain/transfer-ownership.feature
  tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
  tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#31658 Add provisioning API disableApp feature
  tests/acceptance/features/apiProvisioning-v1/disableApp.feature
  tests/acceptance/features/apiProvisioning-v1/enableApp.feature
  tests/acceptance/features/apiProvisioning-v2/disableApp.feature
  tests/acceptance/features/apiProvisioning-v2/enableApp.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31660 [stable10] Add provisioning API disableApp feature
  tests/acceptance/features/apiProvisioning-v1/disableApp.feature
  tests/acceptance/features/apiProvisioning-v1/enableApp.feature
  tests/acceptance/features/apiProvisioning-v2/disableApp.feature
  tests/acceptance/features/apiProvisioning-v2/enableApp.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, dev:acceptance-tests

#31628 More API test for file versions
  tests/acceptance/features/apiMain/dav-versions.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31569 Fixes #31568 - Validate maximum length of a username before creation
  lib/private/User/Manager.php
  tests/lib/User/ManagerTest.php
Labels: backport-request

#31659 don't delete the source files when generating thumbnails
  lib/private/Preview/MP3.php
  lib/private/Preview/Office.php
  tests/lib/Preview/Provider.php
Labels: 3 - To Review, backport-request, bug, regression, sev1-critical

#31664 [stable10] Fixes #31568 - Validate maximum length of a username befor…
  lib/private/User/Manager.php
  tests/lib/User/ManagerTest.php
Labels: 3 - To Review

#31662 [stable10] Handle enable-disable of apps in acceptance tests
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/run.sh
Labels: 3 - To Review, dev:acceptance-tests

#31661 Handle enable-disable of apps in acceptance tests
  tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
  tests/acceptance/run.sh
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31552 Add a new admin section for Imprint and Privacy Policy settings
  lib/private/Settings/SettingsManager.php
  settings/Application.php
  settings/Controller/LegalSettingsController.php
  settings/Panels/Admin/Legal.php
  settings/js/panels/legal.js
  settings/routes.php
  settings/templates/panels/admin/legal.php
  tests/Settings/Controller/LegalControllerTest.php
  tests/Settings/Panels/Admin/LegalTest.php
Labels: 3 - To Review, backport-request, enhancement, p2-high

#31666 [Stable10] Add a new admin section for Imprint and Privacy Policy settings
  lib/private/Settings/SettingsManager.php
  settings/Application.php
  settings/Controller/LegalSettingsController.php
  settings/Panels/Admin/Legal.php
  settings/js/panels/legal.js
  settings/routes.php
  settings/templates/panels/admin/legal.php
  tests/Settings/Controller/LegalControllerTest.php
  tests/Settings/Panels/Admin/LegalTest.php
Labels: 3 - To Review, enhancement, p2-high

#31677 Fix apiVersion type and createShare call parameters
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#31679 [stable10] Fix apiVersion type and createShare call parameters
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#31674 API test for disableSharing
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31680 Add version restore tests when sharee has moved the shared folder or file
  tests/acceptance/features/apiMain/dav-versions.feature
Labels: 3 - To Review, dev:acceptance-tests

#31144 [stable10] Change lost password email to use separate templates for HTML and plain text
  core/Controller/LostController.php
  core/templates/lostpassword/altemail.php
  core/templates/lostpassword/email.php
  tests/Core/Controller/LostControllerTest.php
Labels: 3 - To Review, status/STALE

#31665 Move notifications context API steps used by core into core
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/WebUINotificationsContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  tests/acceptance/features/lib/Notification.php
  tests/acceptance/features/lib/NotificationsAppDialog.php
  tests/acceptance/features/lib/NotificationsEnabledOwncloudPage.php
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
Labels: 3 - To Review, dev:acceptance-tests

#31687 Remove deprecated SnippetAcceptingContext
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
Labels: 3 - To Review, dev:acceptance-tests

#31688 [stable10] remove deprecated snippet accepting context
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
Labels: 3 - To Review, dev:acceptance-tests

#31689 [Stable10] Properly normalize paths for event, no &$magic needed
  lib/private/Files/View.php
  tests/lib/Files/ViewTest.php
Labels: 4 - To release, app:files, comp:filesystem, enhancement, p3-medium

#31675 [Stable10] API more tests for file_versions
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:acceptance-tests

#31695 Remove unused code in acceptance tests Sharing.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#31694 [stable10] API test for disableSharing
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#31683 Add Imprint and Privacy Policy into mails
  core/templates/altmail.php
  core/templates/html.mail.footer.php
  core/templates/internalaltmail.php
  core/templates/internalmail.php
  core/templates/lostpassword/altemail.php
  core/templates/lostpassword/email.php
  core/templates/mail.php
  core/templates/plain.mail.footer.php
  lib/private/legacy/defaults.php
  lib/private/legacy/template.php
Labels: 3 - To Review

#31671 Add accept and reject symfony events for share
  apps/files_sharing/lib/API/OCSShareWrapper.php
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/API/Share20OCSTest.php
  apps/files_sharing/tests/ApiTest.php
Labels: 3 - To Review

#31478 [stable10] Do not load disabled app-themes
  lib/private/Helper/EnvironmentHelper.php
  lib/private/Server.php
  lib/private/Theme/ThemeService.php
  tests/lib/Theme/ThemeServiceTest.php
Labels: 3 - To Review, bug, p3-medium

#30993 Fix deletion of selected files in trashbin
  apps/files/js/filelist.js
  apps/files_trashbin/js/filelist.js
  apps/files_trashbin/tests/js/filelistSpec.js
  tests/acceptance/features/webUITrashbin/restore.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
Labels: 3 - To Review, app:files_trashbin, p3-medium

#31700 [stable10] Fix deletion of selected files in trashbin
  apps/files/js/filelist.js
  apps/files_trashbin/js/filelist.js
  apps/files_trashbin/tests/js/filelistSpec.js
  tests/acceptance/features/webUITrashbin/restore.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
Labels: 4 - To release

#31701 Put defaultMailHeaderColor back
  lib/private/legacy/defaults.php
Labels: 3 - To Review

#31702 [stable10] Add accept and reject symfony events for share
  apps/files_sharing/lib/API/OCSShareWrapper.php
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/API/Share20OCSTest.php
  apps/files_sharing/tests/ApiTest.php
Labels: 4 - To release

#31699 [Stable10] Add Imprint and Privacy Policy into mails
  core/templates/altmail.php
  core/templates/html.mail.footer.php
  core/templates/internalaltmail.php
  core/templates/internalmail.php
  core/templates/lostpassword/altemail.php
  core/templates/lostpassword/email.php
  core/templates/mail.php
  core/templates/plain.mail.footer.php
  lib/private/legacy/defaults.php
  lib/private/legacy/template.php
Labels: 3 - To Review

#31623 [stable10][feature] provide original exception via logging events
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
  lib/private/Log.php
  tests/lib/LoggerTest.php
Labels: 3 - To Review

#31708 API test for disableReShare
  tests/acceptance/features/apiSharing-v1/reShare.feature
Labels: 3 - To Review, dev:acceptance-tests

#31707 [Stable10] api test upload to public share
  tests/acceptance/features/apiSharing-v1/uploadToShare.feature
Labels: 3 - To Review, dev:acceptance-tests

#31711 [stable10] API test for disableReShare
  tests/acceptance/features/apiSharing-v1/reShare.feature
Labels: 3 - To Review, dev:acceptance-tests

#31635 Login test user to enforce storage creation
  .drone.yml
  tests/lib/Encryption/DecryptAllTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#31630 Adding background:queue commands: status and delete
  core/Command/Background/Queue/Delete.php
  core/Command/Background/Queue/Status.php
  core/register_command.php
  db_structure.xml
  lib/private/BackgroundJob/JobList.php
  lib/public/BackgroundJob/IJobList.php
  tests/Core/Command/Background/Queue/DeleteTest.php
  tests/Core/Command/Background/Queue/StatusTest.php
Labels: 3 - To Review, backport-request

#31704 Add Imprint and Privacy Policy to getShortFooter()
  core/css/global.css
  core/css/styles.css
  lib/private/legacy/defaults.php
  tests/lib/legacy/DefaultsTest.php
Labels: 3 - To Review, backport-request, enhancement, p2-high

#31590 [stable10] While decrypting userkey prepareEncryptionModules() must b…
  lib/private/Encryption/DecryptAll.php
  tests/lib/Encryption/DecryptAllTest.php
Labels: 3 - To Review

#31712 Updating ca-bundle.crt
  resources/config/ca-bundle.crt
Labels: 3 - To Review, backport-request

#31715 API test for restrictSharingOutsideTheGroup
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#31730 Stable10 legal imprint footer
  core/css/global.css
  core/css/styles.css
  lib/private/legacy/defaults.php
  tests/lib/legacy/DefaultsTest.php
Labels: 3 - To Review

#31656 Allow different language in public link share email
  core/ajax/share.php
  lib/private/Share/MailNotifications.php
  lib/private/legacy/template.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 3 - To Review, enhancement, p3-medium

#31713 Restrict group admin create groups using userprovision API
  apps/provisioning_api/lib/Groups.php
  apps/provisioning_api/tests/GroupsTest.php
  tests/acceptance/features/apiProvisioning-v1/addGroup.feature
  tests/acceptance/features/apiProvisioning-v2/addGroup.feature
Labels: 3 - To Review

#31726 Acceptance test code style
  tests/TestHelpers/SharingHelper.php
  tests/TestHelpers/TagsHelper.php
  tests/TestHelpers/UserHelper.php
  tests/acceptance/features/bootstrap/Auth.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/Checksums.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebUINotificationsContext.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/NotificationsAppDialog.php
  tests/acceptance/features/lib/PublicLinkFilesPage.php
Labels: 3 - To Review, dev:acceptance-tests

#31728 [stable10] Acceptance test code style
  tests/TestHelpers/SharingHelper.php
  tests/TestHelpers/TagsHelper.php
  tests/TestHelpers/UserHelper.php
  tests/acceptance/features/bootstrap/Auth.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/Checksums.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebUINotificationsContext.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/NotificationsAppDialog.php
  tests/acceptance/features/lib/PublicLinkFilesPage.php
Labels: 3 - To Review, dev:acceptance-tests

#31736 [Stable10] api test sharing restrict sharing outside the group
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, dev:acceptance-tests

#31737 [stable10] Exclude from creating shares if member of any excluded groups
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#31466 Stable10 oracle ilike fix
  lib/private/DB/AdapterOCI8.php
  lib/private/DB/QueryBuilder/ExpressionBuilder/OCIExpressionBuilder.php
  tests/lib/Files/Cache/CacheTest.php
Labels: bug, db:oracle, p3-medium, sev3-medium

#31738 [stable10] Restrict group admin create groups using userprovision API
  apps/provisioning_api/lib/Groups.php
  apps/provisioning_api/tests/GroupsTest.php
  tests/acceptance/features/apiProvisioning-v1/addGroup.feature
  tests/acceptance/features/apiProvisioning-v2/addGroup.feature
Labels: 4 - To release

#31714 Add a notice to the share tooltip when there is no autocomplete
  config/config.sample.php
  core/js/sharedialogview.js
  core/js/tests/specs/sharedialogviewSpec.js
  lib/public/Util/UserSearch.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
Labels: 3 - To Review, bug, p3-medium

#31729 [stable10] Add a notice to the share tooltip when there is no autocomplete
  config/config.sample.php
  core/js/sharedialogview.js
  core/js/tests/specs/sharedialogviewSpec.js
  lib/public/Util/UserSearch.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
Labels: 3 - To Review, bug, p3-medium

#31734 [stable10] Updating ca-bundle.crt
  resources/config/ca-bundle.crt
Labels: 3 - To Review

#31716 Changelog update for upcoming 10.0.9
  CHANGELOG.md
Labels: 3 - To Review

#31733 [stable10] unit test files_primary_s3 on core
  .drone.yml
  tests/drone/install-server.sh
  tests/lib/Files/ObjectStore/SwiftTest.php
Labels: 3 - To Review

#31709 API-test-share-disableGroupShare
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
Labels: 3 - To Review, dev:acceptance-tests

#31685 Bump small stuff
  composer.lock
Labels: 3 - To Review, dependencies

#31686 [stable10] Bump small stuff
  composer.lock
Labels: 3 - To Review, dependencies

#31678 Properly detect home storage on objectstores as well
  lib/private/Files/Cache/Wrapper/ReadOnlyCachePermissionsMask.php
Labels: 3 - To Review, backport-request

#31735 [stable10] fixes #31402 - group principals are now verified as well w…
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Command/CreateCalendar.php
  apps/dav/lib/DAV/GroupPrincipalBackend.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/dav/lib/RootCollection.php
  apps/dav/tests/unit/CalDAV/AbstractCalDavBackendTest.php
  apps/dav/tests/unit/CalDAV/PublicCalendarRootTest.php
  apps/dav/tests/unit/CardDAV/CardDavBackendTest.php
  apps/dav/tests/unit/DAV/GroupPrincipalTest.php
Labels: 3 - To Review, bug, regression

#31744 [stable10] Properly detect home storage on objectstores as well
  lib/private/Files/Cache/Wrapper/ReadOnlyCachePermissionsMask.php
Labels: 4 - To release

#31746 [Stable10] api test sharing group sharing disabled
  tests/acceptance/features/apiSharing-v1/disableSharing.feature
Labels: 3 - To Review, dev:acceptance-tests

#31750 Skip autocompletion tests on LDAP - they rely on a complex user and g…
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31751 [stable10] Skip autocompletion tests on LDAP - they rely on a complex user and g…
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
Labels: 3 - To Review, dev:acceptance-tests

#31755 Make acceptance test function getUserDisplayName more robust
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31756 [stable10] Make acceptance test function getUserDisplayName more robust
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, dev:acceptance-tests

#31757 Fix broken web setup page
  lib/private/legacy/defaults.php
  tests/lib/legacy/DefaultsTest.php
Labels: 3 - To Review, backport-request, bug, p2-high, regression, sev1-critical

#31766 [Stable10] Fix broken web setup page
  lib/private/legacy/defaults.php
  tests/lib/legacy/DefaultsTest.php
Labels: 3 - To Review, bug, p2-high, regression, sev1-critical

#31771 Do not throw an error when the same theme enabled twice
  lib/private/App/AppManager.php
  tests/lib/App/ManagerTest.php
Labels: 3 - To Review, backport-request, bug, feature:theming

#31460 catch duplicate token inserts and log changes
  lib/private/Authentication/Token/DefaultTokenProvider.php
  lib/private/User/Session.php
Labels: backport-request, blue-ticket, comp:authentication, p2-high, sev2-high

#31770 Fixes #31769 - verify the return of an ISqlMigration
  lib/private/DB/MigrationService.php
Labels: 3 - To Review, backport-request, bug

#31777 code standard for acceptance test code
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/AppManagementContext.php
  tests/acceptance/features/bootstrap/Auth.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/CalDavContext.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/CardDavContext.php
  tests/acceptance/features/bootstrap/Checksums.php
  tests/acceptance/features/bootstrap/CommandLine.php
  tests/acceptance/features/bootstrap/Comments.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/Ip.php
  tests/acceptance/features/bootstrap/Logging.php
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/Tags.php
  tests/acceptance/features/bootstrap/Trashbin.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalSecuritySettingsContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/bootstrap/WebUIUserContext.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/DisabledUserPage.php
  tests/acceptance/features/lib/FavoritesPage.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/lib/FilesPageElement/ConflictDialog.php
  tests/acceptance/features/lib/FilesPageElement/FileActionsMenu.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php
  tests/acceptance/features/lib/LoginPage.php
  tests/acceptance/features/lib/OwncloudPage.php
  tests/acceptance/features/lib/OwncloudPageElement/OCDialog.php
  tests/acceptance/features/lib/OwncloudPageElement/SettingsMenu.php
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/lib/PersonalSecuritySettingsPage.php
  tests/acceptance/features/lib/PublicLinkFilesPage.php
  tests/acceptance/features/lib/TrashbinPage.php
  tests/acceptance/features/lib/UserPageElement/GroupList.php
  tests/acceptance/features/lib/UsersPage.php
  tests/acceptance/features/webUIManageUsersGroups/addGroup.feature
  tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/login.feature
Labels: 3 - To Review, dev:acceptance-tests

#31772 Align master and stable10 run.sh
  tests/acceptance/run.sh
Labels: 3 - To Review, dev:acceptance-tests

#31779 [stable10] Fixes #31769 - verify the return of an ISqlMigration
  lib/private/DB/MigrationService.php
Labels: 3 - To Review, bug

#31749 Exceptions need to properly be handled in the preview plugin
  apps/dav/lib/Files/PreviewPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/PreviewPluginTest.php
Labels: 3 - To Review

#31785 Properly detect thumbnail availability in PreviewPlugin
  apps/dav/lib/Files/PreviewPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/PreviewPluginTest.php
  lib/private/PreviewManager.php
  tests/lib/PreviewManagerTest.php
Labels: 3 - To Review, backport-request, bug, p3-medium, regression

#31788 [stable10] Properly detect thumbnail availability in PreviewPlugin
  apps/dav/lib/Files/PreviewPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/PreviewPluginTest.php
  lib/private/PreviewManager.php
  tests/lib/PreviewManagerTest.php
Labels: 3 - To Review

#31791 Web UI test scrolling enhancements
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  tests/acceptance/features/lib/OwncloudPage.php
Labels: 3 - To Review, dev:acceptance-tests

#31793 [stable10] web UI test scrolling enhancements
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  tests/acceptance/features/lib/OwncloudPage.php
Labels: 3 - To Review, dev:acceptance-tests

#31794 [stable10] Remove bogus logException in DefaultTokenProvider
  lib/private/Authentication/Token/DefaultTokenProvider.php
Labels: 4 - To release

#31775 Reorder the buttons for the internal share notification
  apps/files_sharing/lib/Service/NotificationPublisher.php
  apps/files_sharing/tests/Service/NotificationPublisherTest.php
Labels: 3 - To Review, feature:sharing

#31808 Tag scenario that is not relevant to encryption
  tests/acceptance/features/webUILogin/resetPassword.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31809 [stable10] Tag scenario that is not relevant to encryption
  tests/acceptance/features/webUIManageUsersGroups/resetPassword.feature
Labels: 3 - To Review, dev:acceptance-tests

#31805 [stable10] Let CopyPlugin fall back to default impl if no ICopySource
  apps/dav/lib/DAV/CopyPlugin.php
  apps/dav/tests/unit/DAV/CopyPluginTest.php
Labels: 3 - To Review, backport-request, p2-high

#31801 [stable10] implement MetaFileVersionNode::getMountPoint
  lib/private/Files/Meta/MetaFileVersionNode.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Common.php
  tests/lib/Files/MetaFilesTest.php
  tests/lib/Files/ObjectStore/ObjectStoreTest.php
Labels: 4 - To release, app:files_versions, feature:previews, p2-high, regression

#31816 Can share capability
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/tests/CapabilitiesTest.php
  lib/private/Share20/Manager.php
  lib/private/legacy/util.php
  tests/TestHelpers/AppConfigHelper.php
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/lib/UtilTest.php
Labels: 3 - To Review

#31776 [stable10] Reorder the buttons for the internal share notification
  apps/files_sharing/lib/Service/NotificationPublisher.php
  apps/files_sharing/tests/Service/NotificationPublisherTest.php
Labels: 4 - To release, feature:sharing

#31811 [master] Let CopyPlugin fall back to default impl if no ICopySource
  apps/dav/lib/DAV/CopyPlugin.php
  apps/dav/tests/unit/DAV/CopyPluginTest.php
Labels: 4 - To release

#31802 [master] implement MetaFileVersionNode::getMountPoint
  lib/private/Files/Meta/MetaFileVersionNode.php
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/Storage/Common.php
  tests/lib/Files/MetaFilesTest.php
  tests/lib/Files/ObjectStore/ObjectStoreTest.php
Labels: 4 - To release, app:files_versions, feature:previews, p2-high, regression

#31822 [stable10] Exclude users from sharing if they are a member of any excluded group - util.php
  lib/private/Share20/Manager.php
  lib/private/legacy/util.php
  tests/lib/UtilTest.php
Labels: 4 - To release

#31795 Skip filecache repair step for version greater than 10.0.4
  apps/files/lib/Command/Scan.php
  lib/private/Repair.php
  lib/private/Repair/RepairMismatchFileCachePath.php
  tests/lib/Repair/RepairMismatchFileCachePathTest.php
Labels: 3 - To Review

#31834 Use OC_DEFAULT_MODULE constant in core
  lib/private/Encryption/Util.php
Labels: 3 - To Review

#31799 API test use webdav version table
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiMain/favorites.feature
  tests/acceptance/features/apiMain/quota.feature
  tests/acceptance/features/apiWebdav/webdav-related-new-endpoint.feature
  tests/acceptance/features/apiWebdav/webdav-related-old-endpoint.feature
  tests/acceptance/features/apiWebdav/webdav-related.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31807 Add phan as static code analyser
  .drone.yml
  .gitignore
  .phan/config.php
  .phan/stubs/OC_Theme.php
  Makefile
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/Connector/Sabre/AutorenamePlugin.php
  apps/dav/lib/Files/ZsyncPlugin.php
  apps/dav/lib/Upload/AssemblyStreamZsync.php
  apps/dav/lib/Upload/ChunkingPluginZsync.php
  apps/federatedfilesharing/lib/RequestHandler.php
  apps/files_external/lib/Lib/Storage/SMB.php
  apps/files_external/lib/Lib/Storage/Swift.php
  apps/files_external/lib/config.php
  apps/files_trashbin/lib/Trashbin.php
  lib/private/Files/External/LegacyUtil.php
  lib/private/Files/Storage/DAV.php
  lib/private/Memcache/Redis.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/legacy/user.php
Labels: 3 - To Review

#31672 Allow admin to blacklist groups for the files_sharing app
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/js/settings.js
  apps/files_sharing/lib/API/OCSShareWrapper.php
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/lib/Panels/Admin/SettingsPanel.php
  apps/files_sharing/lib/SharingBlacklist.php
  apps/files_sharing/templates/settings.php
  apps/files_sharing/tests/API/Share20OCSTest.php
  apps/files_sharing/tests/API/ShareesTest.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Panels/Admin/SettingsPanelTest.php
  apps/files_sharing/tests/SharingBlacklistTest.php
Labels: 3 - To Review, feature:sharing

#31846 Adjust IProvider2::isAvailable to match IProvider::isAvailable as wel…
  lib/private/Preview/Bitmap.php
  lib/private/Preview/Image.php
  lib/private/Preview/MP3.php
  lib/private/Preview/Movie.php
  lib/private/Preview/Office.php
  lib/private/Preview/SVG.php
  lib/private/Preview/TXT.php
  lib/public/Preview/IProvider2.php
  tests/lib/PreviewManagerTest.php
Labels: 4 - To release, backport-request, p2-high

#31853 Fixes #31849 - delete thumbnails on write hooks
  lib/private/Preview.php
Labels: 3 - To Review, app:files_versions, backport-request, bug, regression

#31862 [stable10] Adjust IProvider2::isAvailable to match IProvider::isAvail…
  lib/private/Preview/Bitmap.php
  lib/private/Preview/Image.php
  lib/private/Preview/MP3.php
  lib/private/Preview/Movie.php
  lib/private/Preview/Office.php
  lib/private/Preview/SVG.php
  lib/private/Preview/TXT.php
  lib/public/Preview/IProvider2.php
  tests/lib/PreviewManagerTest.php
Labels: 4 - To release

#31865 [stable10] Fixes #31849 - delete thumbnails on write hooks
  lib/private/Preview.php
Labels: 4 - To release, app:files_versions, bug, regression

#31866 exclude data from php style checks
  .php_cs.dist
Labels: 3 - To Review

#31867 Fix SharingBlacklistTest setGetBlacklistedReceiverGroupsProvider
  apps/files_sharing/tests/SharingBlacklistTest.php
Labels: 3 - To Review, backport-request, dev:phpunit-tests

#31856 Handle SSL certificate verifications for others than Let's Encrypt
  .htaccess
  lib/private/Setup.php
Labels: 4 - To release

#31857 Introduce IShutdownManager which allows us to order the shutdown func…
  lib/base.php
  lib/private/Log/ErrorHandler.php
  lib/private/Log/Syslog.php
  lib/private/Server.php
  lib/private/Shutdown/ShutDownManager.php
  lib/public/IServerContainer.php
  lib/public/Shutdown/IShutdownManager.php
  tests/lib/ServerTest.php
  tests/lib/Shutdown/ShutdownManagerTest.php
Labels: 2 - Developing

#31765 Reload the filelist view when accepting or rejecting a share
  apps/files_sharing/js/app.js
  apps/files_sharing/tests/js/appSpec.js
Labels: 3 - To Review, feature:sharing

#31825 allow edge to gc chunks
  apps/files/js/file-upload.js
Labels: 3 - To Review, app:files, backport-request, browser:edge, bug, p3-medium, sev3-medium

#31784 Added a blank to display names of shared objects
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/lib/CardDAV/CardDavBackend.php
Labels: 3 - To Review, backport-request

#31875 Booksmarks crt was removed
  resources/codesigning/intermediate.crl.pem
Labels: 3 - To Review, backport-request

#31878 [stable10] Booksmarks crt was removed
  resources/codesigning/intermediate.crl.pem
Labels: 3 - To Review

#31861 Lock dialog form fields while processing
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
Labels: 3 - To Review, backport-request, bug, design, p3-medium

#31833 birthday calendar exposes no access share state and is…
  apps/dav/lib/CalDAV/Calendar.php
  apps/dav/lib/CalDAV/Plugin.php
  apps/dav/tests/unit/CalDAV/CalendarTest.php
  apps/dav/tests/unit/CalDAV/PluginTest.php
Labels: 3 - To Review, backport-request, bug, comp:caldav, p3-medium

#31547 Introduce account modules
  apps/dav/appinfo/v1/caldav.php
  apps/dav/appinfo/v1/carddav.php
  apps/dav/appinfo/v1/webdav.php
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/AuthTest.php
  core/Middleware/AccountModuleMiddleware.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/Authentication/AccountModule/Manager.php
  lib/private/Authentication/Exceptions/AccountCheckException.php
  lib/private/Server.php
  lib/private/legacy/api.php
  lib/private/legacy/json.php
  lib/private/legacy/util.php
  lib/public/Authentication/IAccountModule.php
  lib/public/Authentication/IAccountModuleController.php
  tests/Core/Middleware/AccountModuleMiddlewareTest.php
  tests/lib/Authentication/AccountModule/ManagerTest.php
Labels: 2 - Developing, comp:authentication, enhancement

#31886 [stable10] Sharing notification messages stable10
  apps/federatedfilesharing/appinfo/app.php
  apps/federatedfilesharing/lib/Notifier.php
  apps/federatedfilesharing/lib/RequestHandler.php
  apps/files_sharing/lib/Notifier.php
  apps/files_sharing/lib/Service/NotificationPublisher.php
  apps/files_sharing/tests/NotifierTest.php
  apps/files_sharing/tests/Service/NotificationPublisherTest.php
  tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature
  tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
Labels: 3 - To Review, feature:federated-cloud-sharing, feature:sharing, p2-high

#31884 [stable10] allow edge to gc chunks
  apps/files/js/file-upload.js
Labels: 3 - To Review, blue-ticket

#31908 Bump symfony 3.4.11 to 3.4.12
  composer.lock
Labels: 3 - To Review, dependencies

#31910 Update changelog for 10.0.9 RC2
  CHANGELOG.md
Labels: 3 - To Review

#31881 Adjust notification message for the sharing apps
  apps/federatedfilesharing/appinfo/app.php
  apps/federatedfilesharing/lib/Notifier.php
  apps/federatedfilesharing/lib/RequestHandler.php
  apps/files_sharing/lib/Notifier.php
  apps/files_sharing/lib/Service/NotificationPublisher.php
  apps/files_sharing/tests/NotifierTest.php
  apps/files_sharing/tests/Service/NotificationPublisherTest.php
  tests/acceptance/features/apiSharingNotifications/sharingNotifications.feature
  tests/acceptance/features/webUISharingNotifications/shareWithGroups.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
Labels: 3 - To Review, p2-high

#31224 generated resource routes should allow /
  lib/private/AppFramework/Routing/RouteConfig.php
  tests/lib/Route/RouterTest.php
Labels: backport-request, blue-ticket, bug, p3-medium, p4-low, settings:users

#31930 [stable10] User Management UI tests
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UserPageElement/GroupList.php
  tests/acceptance/features/lib/UsersPage.php
  tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
  tests/acceptance/features/webUIManageUsersGroups/addGroup.feature
  tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature
Labels: 3 - To Review, dev:acceptance-tests

#31487 Remove depreciated function which is not in interface specification
  lib/private/Files/Cache/Cache.php
  tests/lib/Files/Cache/CacheTest.php
  tests/lib/Files/Cache/WatcherTest.php
  tests/lib/Files/ViewTest.php
Labels: 3 - To Review

#31917 AppManager text typo and PHPdoc return tags
  apps/dav/lib/CardDAV/CardDavBackend.php
  lib/private/App/AppManager.php
  lib/private/App/DependencyAnalyzer.php
  lib/private/App/PlatformRepository.php
  lib/private/Encryption/Manager.php
  lib/private/Files/Filesystem.php
  lib/private/Installer.php
  lib/private/Share/Helper.php
  lib/private/legacy/defaults.php
  lib/private/legacy/template/functions.php
Labels: 3 - To Review

#31915 Move AccountCheckException to public api
  apps/dav/lib/Connector/Sabre/Auth.php
  core/Middleware/AccountModuleMiddleware.php
  lib/private/Authentication/AccountModule/Manager.php
  lib/private/User/Session.php
  lib/private/legacy/api.php
  lib/private/legacy/json.php
  lib/private/legacy/util.php
  lib/public/Authentication/Exceptions/AccountCheckException.php
  lib/public/Authentication/IAccountModule.php
  tests/Core/Middleware/AccountModuleMiddlewareTest.php
  tests/lib/User/SessionTest.php
Labels: 2 - Developing

#31888 removed dead code
  apps/files_sharing/lib/Migration.php
Labels: 3 - To Review
