Repository owncloud/core, pull requests merged in 2018-04, with the labels that each got.

#30958 Fix settings page where elements are inline when they shouldn't
  settings/css/settings.css
Labels: 3 - To Review, bug, p2-high, regression, settings:admin

#30950 [stable10] Changelog update for upcoming 10.0.8
  CHANGELOG.md
Labels: 3 - To Review

#30939 flush/rebuild cache only once per matrix on push to branch
  .drone.yml
Labels: 3 - To Review, Drone

#30940 [stable10] flush/rebuild cache only once per matrix on push to branch
  .drone.yml
Labels: 3 - To Review, Drone

#30653 Repair step to fix orphan reshares
  lib/private/Repair.php
  lib/private/Repair/RepairOrphanedSubshare.php
  tests/lib/Repair/RepairOrphanedSubshareTest.php
Labels: 3 - To Review

#30976 Fix webUI acceptance test stalls when checking file content
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
  tests/travis/start_ui_tests.sh
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30974 Silence retried to delete file messages
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  tests/acceptance/features/lib/FilesPageBasic.php
Labels: 3 - To Review, dev:acceptance-tests

#30971 Properly remember groups that have been deleted using the webUI
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, dev:acceptance-tests

#30986 [stable10] Replace emittingCall with separate before and after events
  apps/dav/lib/Connector/Sabre/File.php
Labels: 4 - To release

#30975 [stable10] Silence retried to delete file messages
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  tests/acceptance/features/lib/FilesPageBasic.php
Labels: 3 - To Review, dev:acceptance-tests

#30977 [stable10] Fix webUI acceptance test stalls when checking file content
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
  tests/travis/start_ui_tests.sh
Labels: 3 - To Review, dev:acceptance-tests

#30960 Move SubadminMiddleware to user_management app
  settings/Application.php
  settings/Middleware/SubadminMiddleware.php
  tests/Settings/Middleware/SubadminMiddlewareTest.php
Labels: 3 - To Review

#30771 A new exception to suppress exception logs
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/Connector/Sabre/DirectoryTest.php
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
  lib/public/Files/FileContentNotAllowedException.php
Labels: 3 - To Review, backport-request

#30972 [stable10] Properly remember groups that have been deleted using the webUI
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
Labels: 3 - To Review, dev:acceptance-tests

#30991 [stable10] A new exception to suppress exception logs
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/ExceptionLoggerPlugin.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/Connector/Sabre/DirectoryTest.php
  apps/dav/tests/unit/Connector/Sabre/ExceptionLoggerPluginTest.php
  lib/public/Files/FileContentNotAllowedException.php
Labels: 3 - To Review, 4 - To release

#30988 [stable10] Fix settings page where elements are inline when they shouldn't
  settings/css/settings.css
Labels: 4 - To release, bug, p2-high, regression, settings:admin

#30994 [Stable10] Introduce UserSearch utils
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/tests/CapabilitiesTest.php
  core/js/sharedialogview.js
  core/js/tests/specs/sharedialogviewSpec.js
  lib/private/Group/Manager.php
  lib/private/Server.php
  lib/private/User/Manager.php
  lib/public/Util/UserSearch.php
  tests/acceptance/features/apiSharees/sharees.feature
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
  tests/lib/Files/Config/UserMountCacheTest.php
  tests/lib/Group/ManagerTest.php
  tests/lib/User/ManagerTest.php
Labels: 4 - To release

#30987 Email autocomplete for link shares
  apps/dav/lib/CardDAV/AddressBookImpl.php
  core/ajax/share.php
  core/js/sharedialogmailview.js
Labels: 3 - To Review

#30998 [stable10] Email autocomplete for link shares without local users
  apps/dav/lib/CardDAV/AddressBookImpl.php
  core/ajax/share.php
  core/js/sharedialogmailview.js
Labels: 3 - To Review, p1-urgent

#30999 webUI acceptance tests for trashbin multi delete and restore
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/lib/TrashbinPage.php
  tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
  tests/acceptance/features/webUITrashbin/restore.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31002 Keep track of which groups are possibleToDelete
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31001 [stable10] No public avatars
  apps/dav/lib/Server.php
  core/Controller/AvatarController.php
Labels: 4 - To release

#31003 [stable10] Group events
  lib/private/Group/Group.php
  lib/private/Group/Manager.php
  lib/private/Server.php
  tests/lib/App/ManagerTest.php
  tests/lib/Group/GroupTest.php
  tests/lib/Group/ManagerTest.php
Labels: 4 - To release, comp:core

#31007 [stable10] Keep track of which groups are possibleToDelete
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, dev:acceptance-tests

#31006 [stable10] trashbin multi delete restore tests
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/lib/TrashbinPage.php
  tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
  tests/acceptance/features/webUITrashbin/restore.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
Labels: 3 - To Review, dev:acceptance-tests

#31009 Rework unreliable delete multiple files scenario
  tests/acceptance/features/webUIFiles/deleteFilesFolders.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31005 [stable10] Retry chunks in web UI on stalled uploads
  apps/files/js/app.js
  apps/files/js/file-upload.js
  apps/files/js/filelist.js
  apps/files/lib/App.php
  apps/files/tests/js/fileUploadSpec.js
Labels: 3 - To Review

#31010 [stable10] UI-tests - move reload step into general context
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
Labels: 3 - To Review, dev:acceptance-tests

#31013 catch possible 500 server exception when cleaning up groups in acceptance tests
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, dev:acceptance-tests

#31011 [stable10] catch possible 500 server exception when cleaning up groups in acceptance tests
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31019 api test step to remove user from group
  tests/TestHelpers/UserHelper.php
  tests/acceptance/features/apiSharing/sharing-v1.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, dev:acceptance-tests

#30930 Add symfony events for delete and create share
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/API/Share20OCSTest.php
  apps/files_sharing/tests/ApiTest.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#30485 Introduce single user and seen users sync
  core/Command/User/SyncBackend.php
  core/Migrations/Version20170221114437.php
  lib/private/User/AccountMapper.php
  lib/private/User/Sync/AllUsersIterator.php
  lib/private/User/Sync/SeenUsersIterator.php
  lib/private/User/Sync/UsersIterator.php
  lib/private/User/SyncService.php
  tests/lib/Command/User/SyncBackendTest.php
  tests/lib/User/AccountMapperTest.php
  tests/lib/User/Sync/AllUsersIteratorTest.php
  tests/lib/User/Sync/SeenUsersIteratorTest.php
  tests/lib/User/SyncServiceTest.php
Labels: 3 - To Review, backport-request, enhancement, p1-urgent

#31020 [stable10] api test step to remove user from group
  tests/TestHelpers/UserHelper.php
  tests/acceptance/features/apiSharing/sharing-v1.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, dev:acceptance-tests

#30989 Remove pagination from the repair step
  lib/private/Repair/RepairOrphanedSubshare.php
  tests/lib/Repair/RepairOrphanedSubshareTest.php
Labels: 2 - Developing

#31026 [stable10] Add symfony events for delete and create share
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/API/Share20OCSTest.php
  apps/files_sharing/tests/ApiTest.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review, 4 - To release, p1-urgent

#31025 [stable10] Introduce seen and single user sync command line features
  core/Command/User/SyncBackend.php
  core/Migrations/Version20170221114437.php
  lib/private/User/AccountMapper.php
  lib/private/User/Sync/AllUsersIterator.php
  lib/private/User/Sync/SeenUsersIterator.php
  lib/private/User/Sync/UsersIterator.php
  lib/private/User/SyncService.php
  tests/lib/Command/User/SyncBackendTest.php
  tests/lib/User/AccountMapperTest.php
  tests/lib/User/Sync/AllUsersIteratorTest.php
  tests/lib/User/Sync/SeenUsersIteratorTest.php
  tests/lib/User/SyncServiceTest.php
Labels: 3 - To Review

#31029 Discover new users in single user sync
  core/Command/User/SyncBackend.php
Labels: 4 - To release, backport-request

#30938 Better UX in files sidebar for image previews
  apps/files/js/mainfileinfodetailview.js
Labels: 3 - To Review, status/STALE

#31030 Fix sharing translations
  core/js/sharedialogexpirationview.js
  core/js/sharedialoglinkshareview.js
  tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
Labels: 4 - To release, backport-request, p2-high

#31004 [stable10] Repair step to fix orphan reshares
  lib/private/Repair.php
  lib/private/Repair/RepairOrphanedSubshare.php
  tests/lib/Repair/RepairOrphanedSubshareTest.php
Labels: 4 - To release

#31036 [stable10] Adjust link share wording and fix translations
  core/js/sharedialogexpirationview.js
  core/js/sharedialoglinkshareview.js
  tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
Labels: 4 - To release

#31041 [stable10] Remove "Unlimited" from quota report in personal page
  settings/templates/panels/personal/quota.php
Labels: 3 - To Review

#31040 [stable10] Update changelog again for 10.0.8
  CHANGELOG.md
Labels: 3 - To Review

#31034 webUI deleteFile() correction to information message
  tests/acceptance/features/lib/FilesPageBasic.php
Labels: 3 - To Review, dev:acceptance-tests

#31035 [stable10] webUI deleteFile() correction to information message
  tests/acceptance/features/lib/FilesPageBasic.php
Labels: 3 - To Review, dev:acceptance-tests

#31037 webUI tests - use id to find Public Link Share Dialog permission buttons
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
  tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31044 [stable10] webUI tests - use id to find Public Link Share Dialog permission buttons
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
  tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
Labels: 3 - To Review, dev:acceptance-tests

#31045 [stable10] Fix the emittingCall by adding return
  lib/private/Server.php
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review, 4 - To release

#31046 [stable10] Filter file name when sending internal mail
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 4 - To release, backport-request, p1-urgent

#31047 doc improvement for integrity.ignore.missing.app.signature
  config/config.sample.php
Labels: 4 - To release

#31057 [stable10] Add delay after sending link share email
  core/js/sharedialogmailview.js
  core/js/tests/specs/sharedialogmailviewSpec.js
Labels: 3 - To Review, backport-request, enhancement, feature:sharing, p1-urgent

#31056 [stable10] Filter sender display name in mail notification handler
  lib/private/Share/Filters/MailNotificationFilter.php
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 3 - To Review, backport-request, p1-urgent

#31053 Filter file name when sending internal mail
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 3 - To Review

#30903 Update config.sample.php improving description for key apps_path
  config/config.sample.php
Labels: 4 - To release

#31066 [stable10] doc improvement for integrity.ignore.missing.app.signature
  config/config.sample.php
Labels: 4 - To release

#31065 Share link close delay
  core/js/sharedialogmailview.js
  core/js/tests/specs/sharedialogmailviewSpec.js
Labels: 3 - To Review

#31051 Check basic auth credentials periodically after a timeout instead of …
  lib/private/Server.php
  lib/private/User/BasicAuthModule.php
  lib/private/User/Session.php
  tests/lib/User/BasicAuthModuleTest.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review, backport-request, bug, comp:authentication, p1-urgent

#31076 [stable10] Check basic auth credentials periodically after a timeout instead of …
  lib/private/Server.php
  lib/private/User/BasicAuthModule.php
  lib/private/User/Session.php
  tests/lib/User/BasicAuthModuleTest.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#31074 [stable10] Check apache auth on login form
  core/Controller/LoginController.php
Labels: 3 - To Review, comp:authentication, p1-urgent

#31008 [stable10] Verify checksums command
  apps/files/appinfo/info.xml
  apps/files/lib/Command/VerifyChecksums.php
  apps/files/tests/Command/VerifyChecksumsTest.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/ObjectStore/NoopScanner.php
  lib/private/Files/Storage/Wrapper/Checksum.php
  tests/lib/Files/ViewTest.php
Labels: 4 - To release, backport-request

#31082 [forward_port] Verify checksums command
  apps/files/appinfo/info.xml
  apps/files/lib/Command/VerifyChecksums.php
  apps/files/tests/Command/VerifyChecksumsTest.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/ObjectStore/NoopScanner.php
  lib/private/Files/Storage/Wrapper/Checksum.php
  tests/lib/Files/ViewTest.php
Labels: 3 - To Review

#31083 Update changelog in preparation for 10.0.8 RC1
  CHANGELOG.md
Labels: 3 - To Review, p1-urgent

#31054 Core should check apache auth
  core/Controller/LoginController.php
Labels: 3 - To Review, backport-request, comp:authentication, p1-urgent

#31072 check loglevel before interpolating message
  lib/private/Log.php
Labels: enhancement, performance

#27938 fix probably devastating typo
  lib/private/Installer.php
Labels: 3 - To Review, bug, settings:installation

#31062 Set required php version to 7.1 - PHPStorm synchronizes PHP settings …
  composer.json
Labels: 3 - To Review

#30870 Adding multiple role support in navigation
  lib/private/NavigationManager.php
  tests/lib/NavigationManagerTest.php
Labels: 3 - To Review, regression

#31100 Set minimum php version to 5.6 im composer.json
  composer.json
Labels: 3 - To Review

#31112 [stable10] email test infrastructure
  tests/TestHelpers/EmailHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/MailTool.php
Labels: 3 - To Review, dev:acceptance-tests

#31108 [stable10] getUser of the backend mock needs to return an array
  tests/lib/Command/User/SyncBackendTest.php
Labels: 3 - To Review

#31110 Text improvements in config.sample.php
  config/config.sample.php
Labels: 3 - To Review, backport-request

#31095 UI tests for sharing autocompletion with min-char setting
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31114 [stable10] Text improvements in config.sample.php
  config/config.sample.php
Labels: 3 - To Review

#31121 [stable10] Ability to log extra fields + trigger event when logging
  lib/private/Log.php
  lib/private/Log/Owncloud.php
  tests/lib/LoggerTest.php
Labels: 3 - To Review, backport-request, green-ticket, p2-high

#31088 Fix ApiContoller initialization
  apps/files/lib/AppInfo/Application.php
  apps/files/lib/Service/TagService.php
  apps/files/tests/Service/TagServiceTest.php
  lib/private/PreviewManager.php
  lib/private/Server.php
  tests/lib/PreviewTest.php
Labels: 3 - To Review, backport-request

#31119 Some config.sample.php fixes
  config/config.sample.php
Labels: 4 - To release, backport-request

#31132 Adding symfony events for feature change in group admin
  lib/private/SubAdmin.php
  tests/lib/SubAdminTest.php
Labels: 3 - To Review

#31118 [stable10] Backporting translations
  core/l10n/pt_BR.js
  core/l10n/pt_BR.json
  core/l10n/ru.js
  core/l10n/ru.json
  core/l10n/sq.js
  core/l10n/sq.json
  core/l10n/th_TH.js
  core/l10n/th_TH.json
  settings/l10n/nb_NO.js
  settings/l10n/nb_NO.json
  settings/l10n/pt_BR.js
  settings/l10n/pt_BR.json
  settings/l10n/ru.js
  settings/l10n/ru.json
  settings/l10n/th_TH.js
  settings/l10n/th_TH.json
  settings/l10n/zh_CN.js
  settings/l10n/zh_CN.json
Labels: 3 - To Review

#31092 Update lost password email to use HTML link
  core/Controller/LostController.php
  core/templates/lostpassword/altemail.php
  core/templates/lostpassword/email.php
  tests/Core/Controller/LostControllerTest.php
Labels: 4 - To release

#31107 [stable10] Changes updated by rewriting config.php should sent events
  lib/private/Config.php
  tests/lib/ConfigTest.php
Labels: 4 - To release, backport-request

#31127 [stable10] Some config.sample.php fixes
  config/config.sample.php
Labels: 4 - To release

#31131 Skip failing ui-tests on ldap
  tests/acceptance/features/webUISharingInternalUsers/shareAutocompletion.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31142 [stable10] Add missing public link share dialog features
  core/ajax/share.php
  core/css/share.css
  core/js/sharedialoglinkshareview.js
  core/js/sharedialogmailview.js
  lib/private/Share/MailNotifications.php
Labels: 4 - To release, p1-urgent

#31141 Properly align three button dialogs
  core/css/jquery.ocdialog.css
  core/js/sharedialoglinkshareview.js
Labels: 3 - To Review, backport-request, bug

#31106 Changes updated by rewriting config.php should sent events
  lib/private/Config.php
  tests/lib/ConfigTest.php
Labels: 3 - To Review

#31147 [stable10] Properly align three button dialogs
  core/css/jquery.ocdialog.css
  core/js/sharedialoglinkshareview.js
Labels: 4 - To release, bug

#31027 more tests for federation sharing
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/Federation.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/SharedWithYouPage.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
Labels: 3 - To Review, dev:acceptance-tests

#31143 [stable10] more tests for federation sharing
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/Federation.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/SharedWithYouPage.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingExternal/shareByPublicLink.feature
Labels: 3 - To Review, dev:acceptance-tests

#31101 Improving token_auth_enforced description text in config.sample.php
  config/config.sample.php
Labels: 4 - To release

#31128 [stable10] Improving token_auth_enforced description text
  config/config.sample.php
Labels: 4 - To release

#31156 config.sample.php user.search_min_length
  config/config.sample.php
Labels: 3 - To Review, backport-request

#31160 [stable10] config.sample.php user.search_min_length
  config/config.sample.php
Labels: 3 - To Review

#31163 Prevent share-icon from shrinking
  apps/files_sharing/css/sharetabview.css
Labels: 3 - To Review, bug, regression

#31162 Changelog in preparation for 10.0.8RC2
  CHANGELOG.md
Labels: 3 - To Review

#31124 [stable10] allow reenabling users on sync
  core/Command/User/SyncBackend.php
  lib/private/User/SyncService.php
  tests/lib/Command/User/SyncBackendTest.php
  tests/lib/User/SyncServiceTest.php
Labels: 3 - To Review, app:user_ldap, backport-request, comp:console-occ, enhancement, green-ticket, p1-urgent

#31175 Fix appwebpath detection when OC installed into the subdir and approot is a sibling of oc root dir
  lib/private/App/AppManager.php
  tests/lib/App/ManagerTest.php
Labels: 4 - To release

#31178 [Stable10] Fix appwebpath detection when OC installed into the subdir and approot is a sibling of oc root dir
  lib/private/App/AppManager.php
  tests/lib/App/ManagerTest.php
Labels: 3 - To Review, bug-analysis

#31182 [stable10] Use proper booleans in apps_paths in config.sample.php
  config/config.sample.php
Labels: 3 - To Review

#31183 [stable10] Fix preview generation in files api controller and adding unit tests
  lib/private/PreviewManager.php
  tests/lib/PreviewManagerTest.php
Labels: 4 - To release

#31186 [master] Use proper booleans in apps_paths in config.sample.php
  config/config.sample.php
Labels: 3 - To Review

#31187 Prevent share-icon from shrinking
  apps/files_sharing/css/sharetabview.css
Labels: bug, p3-medium, regression

#31185 Revert "[stable10] Retry chunks in web UI on stalled uploads"
  apps/files/js/app.js
  apps/files/js/file-upload.js
  apps/files/js/filelist.js
  apps/files/lib/App.php
  apps/files/tests/js/fileUploadSpec.js
Labels: 4 - To release

#31181 Changes in preparation of 10.0.8RC3
  CHANGELOG.md
Labels: 2 - Developing

#31184 Fix preview generation in files api controller and adding unit tests
  lib/private/PreviewManager.php
  tests/lib/PreviewManagerTest.php
Labels: 3 - To Review

#31189 [stable10] Prevent background scan to scan non-ready homes
  lib/private/Files/Mount/MountPoint.php
  lib/private/Files/Utils/Scanner.php
  tests/lib/Files/Utils/ScannerTest.php
Labels: 3 - To Review, backport-request, bug, p1-urgent

#31201 [stable10] Use correct expiration variable for link share mail
  core/ajax/share.php
Labels: backport-request, bug, p1-urgent

#31210 [stable10] Add 10.0.8RC4 items to changelog
  CHANGELOG.md
Labels: 3 - To Review

#31212 [stable10] Fix share email with wrong expiration date
  CHANGELOG.md
  core/ajax/share.php
Labels: bug, p1-urgent

#31199 UI tests for app password
  tests/acceptance/features/bootstrap/WebUIPersonalSecuritySettingsContext.php
  tests/acceptance/features/lib/PersonalSecuritySettingsPage.php
  tests/acceptance/features/webUIPersonalSettings/personalSecuritySettings.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31216 Fix extractRequestTokenFromResponse method name
  tests/acceptance/features/bootstrap/Auth.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPageBasic.php
Labels: 3 - To Review, dev:acceptance-tests

#31214 🎉 deprecate Jenkins for pullrequest testing 🎉
  Jenkinsfile
Labels: 3 - To Review

#31217 [stable10] Fix extractRequestTokenFromResponse method name
  tests/acceptance/features/bootstrap/Auth.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPageBasic.php
Labels: 3 - To Review, dev:acceptance-tests

#31208 The example theme now lives in https://github.com/owncloud/theme-example
  apps/theme-example/appinfo/info.xml
  apps/theme-example/core/css/styles.css
  apps/theme-example/core/img/favicon-touch.png
  apps/theme-example/core/img/favicon-touch.svg
  apps/theme-example/core/img/favicon.ico
  apps/theme-example/core/img/favicon.png
  apps/theme-example/core/img/favicon.svg
  apps/theme-example/core/img/logo-icon.png
  apps/theme-example/core/img/logo-icon.svg
  apps/theme-example/core/img/logo-mail.gif
  apps/theme-example/core/img/logo.png
  apps/theme-example/core/img/logo.svg
  apps/theme-example/defaults.php
Labels: 3 - To Review, enhancement, p3-medium

#31197 [master] Respect sharing.federation.allowHttpFallback in FederatedSha…
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/BackgroundJob/RetryJob.php
  apps/federatedfilesharing/lib/Notifications.php
  apps/federatedfilesharing/tests/NotificationsTest.php
  lib/private/Share20/ProviderFactory.php
  ocs/routes.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/run.sh
Labels: 3 - To Review

#31055 Fix version on public API
  lib/public/Files/IPreviewNode.php
  lib/public/Files/IProvidesAdditionalHeaders.php
  lib/public/Files/ObjectStore/IVersionedObjectStorage.php
  lib/public/Files/Storage/IVersionedStorage.php
  lib/public/Preview/IProvider.php
  lib/public/Preview/IProvider2.php
Labels: 3 - To Review, status/STALE

#31193 Bump symfony to 3.4.8 and other pending minor bumps
  composer.lock
Labels: 3 - To Review

#31218 [stable10] UI tests for app password
  tests/acceptance/features/bootstrap/WebUIPersonalSecuritySettingsContext.php
  tests/acceptance/features/lib/PersonalSecuritySettingsPage.php
  tests/acceptance/features/webUIPersonalSettings/personalSecuritySettings.feature
Labels: 3 - To Review, dev:acceptance-tests

#31202 [master] Prevent background scan to scan non-ready homes
  lib/private/Files/Mount/MountPoint.php
  lib/private/Files/Utils/Scanner.php
  tests/lib/Files/Utils/ScannerTest.php
Labels: 3 - To Review

#31222 Bump Sabre Vobject 4.1.5 to 4.1.6
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  composer.lock
Labels: 3 - To Review

#31221 [stable10] Bump symfony to 3.4.8 and other pending minor bumps
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  composer.lock
Labels: 3 - To Review

#31220 no need to call EmailContext everywhere
  tests/TestHelpers/EmailHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/travis/start_ui_tests.sh
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31228 Fix redis tests for phpredis 4.0.0
  tests/lib/Memcache/RedisTest.php
Labels: 3 - To Review

#31229 [stable10] Fix redis tests for phpredis 4.0.0
  tests/lib/Memcache/RedisTest.php
Labels: 3 - To Review

#31225 [stable10] UI tests for reset password
  .drone.yml
  tests/TestHelpers/EmailHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/lib/LoginPage.php
  tests/acceptance/features/webUIManageUsersGroups/resetPassword.feature
  tests/travis/start_ui_tests.sh
Labels: 3 - To Review, dev:acceptance-tests

#31236 Specifically exclude anything other than the core bundled apps
  .php_cs
Labels: 3 - To Review

#31242 Skip mailhog ui tests on travis
  .travis.yml
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/webUILogin/resetPassword.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31232 [stable10] no need to call EmailContext everywhere
  tests/TestHelpers/EmailHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/travis/start_ui_tests.sh
Labels: 3 - To Review, dev:acceptance-tests

#30920 fix changing own email address and fullname
  core/js/js.js
  settings/js/panels/profile.js
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/webUIPersonalSettings/changeOwnEmailAddress.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnFullName.feature
Labels: 3 - To Review, settings:personal, status/STALE

#31245 [stable10] skip mailhog ui tests on travis
  .travis.yml
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/webUIManageUsersGroups/resetPassword.feature
Labels: 3 - To Review, dev:acceptance-tests

#31248 [stable10] Add back robots.txt in the release
  Makefile
Labels: 4 - To release, bug

#31249 [master] Add back robots.txt in the release
  Makefile
Labels: 3 - To Review

#31215 [stable10] deprecate Jenkins for pullrequest testing
  Jenkinsfile
Labels: 3 - To Review

#31247 [stable10] Don't reset inEvent while skipping events
  lib/private/Log.php
Labels: 3 - To Review, backport-request

#31227 [stable10] Fix mail debug message recipient field
  lib/private/Mail/Mailer.php
  tests/lib/Mail/MailerTest.php
Labels: backport-request, bug, p2-high

#31250 Code quality/psr1 and short array
  .php_cs
  apps/dav/tests/unit/Connector/Sabre/SharesPluginTest.php
  apps/federatedfilesharing/tests/RequestHandlerTest.php
  apps/files_sharing/tests/Controllers/ExternalShareControllerTest.php
  apps/files_sharing/tests/External/ManagerTest.php
  apps/testing/lib/Application.php
  core/ajax/share.php
  index.php
  lib/private/Comments/Manager.php
  lib/private/DB/MySqlSchemaColumnDefinitionListener.php
  lib/private/Files/External/LegacyUtil.php
  lib/private/Files/View.php
  lib/private/Group/Manager.php
  lib/private/Installer.php
  lib/private/Preview/Movie.php
  lib/private/Share/MailNotifications.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  lib/private/legacy/app.php
  tests/Core/Controller/LoginControllerTest.php
  tests/TestHelpers/DeleteHelper.php
  tests/TestHelpers/DownloadHelper.php
  tests/TestHelpers/MoveCopyHelper.php
  tests/TestHelpers/TagsHelper.php
  tests/TestHelpers/UploadHelper.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Tags.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageElement/FileActionsMenu.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/OwncloudPage.php
  tests/acceptance/features/lib/PersonalSecuritySettingsPage.php
  tests/docker/mysqlmb4.config.php
  tests/drone/configs/config.files_external.smb-samba.php
  tests/drone/configs/config.files_external.smb-windows.php
  tests/drone/configs/config.files_external.swift.php
  tests/drone/configs/config.files_external.webdav-apache.php
  tests/lib/Comments/ManagerTest.php
  tests/lib/DB/LegacyDBTest.php
  tests/lib/DB/MigratorTest.php
  tests/lib/Events/EventEmitterTraitTest.php
  tests/lib/Group/ManagerTest.php
  tests/lib/IntegrityCheck/CheckerTest.php
  tests/lib/Repair/RepairOrphanedSubshareTest.php
Labels: 3 - To Review

#31258 Fix default lang code example
  config/config.sample.php
Labels: 3 - To Review

#31084 Fix preview for non images
  apps/files/js/mainfileinfodetailview.js
Labels: 3 - To Review

#31190 Convert FileContentNotAllowedException into DAVForbiddenException to …
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
Labels: 3 - To Review, backport-request

#31260 [stable10] Convert FileContentNotAllowedException into DAVForbiddenException to …
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
Labels: 3 - To Review

#31241 UI test to disable user
  tests/acceptance/features/lib/DisabledUserPage.php
Labels: 3 - To Review, dev:acceptance-tests

#31239 [stable10] UI test to disable user
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/DisabledUserPage.php
  tests/acceptance/features/lib/LoginPage.php
  tests/acceptance/features/lib/UsersPage.php
  tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
Labels: 3 - To Review, dev:acceptance-tests

#31148 [stable10] API tests to create and use an app password
  tests/acceptance/features/apiMain/auth.feature
  tests/acceptance/features/apiMain/tokenAuth.feature
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/Auth.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Tags.php
Labels: 3 - To Review, dev:acceptance-tests

#31259 Update verify checksums console output to flow more naturally
  apps/files/lib/Command/VerifyChecksums.php
Labels: backport-request

#31274 fixed missing api version information on userprovisioning API-v1
  tests/acceptance/features/apiProvisioning/addGroup.feature
  tests/acceptance/features/apiProvisioning/addToGroup.feature
  tests/acceptance/features/apiProvisioning/deleteUser.feature
  tests/acceptance/features/apiProvisioning/enableUser.feature
  tests/acceptance/features/apiProvisioning/getGroups.feature
  tests/acceptance/features/apiProvisioning/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning/getUserGroups.feature
  tests/acceptance/features/apiProvisioning/removeFromGroup.feature
Labels: 3 - To Review, dev:acceptance-tests

#31263 API test to test userprovisioning API-v2
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiProvisioning-v1/addGroup.feature
  tests/acceptance/features/apiProvisioning-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v1/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v1/deleteGroup.feature
  tests/acceptance/features/apiProvisioning-v1/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v1/enableUser.feature
  tests/acceptance/features/apiProvisioning-v1/getAppInfo.feature
  tests/acceptance/features/apiProvisioning-v1/getApps.feature
  tests/acceptance/features/apiProvisioning-v1/getGroup.feature
  tests/acceptance/features/apiProvisioning-v1/getGroups.feature
  tests/acceptance/features/apiProvisioning-v1/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioning-v1/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v1/getUser.feature
  tests/acceptance/features/apiProvisioning-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioning-v1/getUsers.feature
  tests/acceptance/features/apiProvisioning-v1/removeFromGroup.feature
  tests/acceptance/features/apiProvisioning-v1/removeSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/addGroup.feature
  tests/acceptance/features/apiProvisioning-v2/addToGroup.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/apiProvisioning-v2/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/deleteGroup.feature
  tests/acceptance/features/apiProvisioning-v2/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/apiProvisioning-v2/getAppInfo.feature
  tests/acceptance/features/apiProvisioning-v2/getApps.feature
  tests/acceptance/features/apiProvisioning-v2/getGroup.feature
  tests/acceptance/features/apiProvisioning-v2/getGroups.feature
  tests/acceptance/features/apiProvisioning-v2/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioning-v2/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v2/getUser.feature
  tests/acceptance/features/apiProvisioning-v2/getUserGroups.feature
  tests/acceptance/features/apiProvisioning-v2/getUsers.feature
  tests/acceptance/features/apiProvisioning-v2/removeFromGroup.feature
  tests/acceptance/features/apiProvisioning-v2/removeSubAdmin.feature
  tests/acceptance/features/apiProvisioning/provisioning-v2.feature
Labels: 3 - To Review, dev:acceptance-tests

#30000 accountMapper either returns an object or throws an exception
  lib/private/User/Manager.php
  tests/lib/User/ManagerTest.php
Labels: 3 - To Review, backport-request, bug, p4-low

#31277 [Stable10] api test api provisioning v2
  .drone.yml
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiProvisioning-v1/addGroup.feature
  tests/acceptance/features/apiProvisioning-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v1/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v1/deleteGroup.feature
  tests/acceptance/features/apiProvisioning-v1/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v1/enableUser.feature
  tests/acceptance/features/apiProvisioning-v1/getAppInfo.feature
  tests/acceptance/features/apiProvisioning-v1/getApps.feature
  tests/acceptance/features/apiProvisioning-v1/getGroup.feature
  tests/acceptance/features/apiProvisioning-v1/getGroups.feature
  tests/acceptance/features/apiProvisioning-v1/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioning-v1/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v1/getUser.feature
  tests/acceptance/features/apiProvisioning-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioning-v1/getUsers.feature
  tests/acceptance/features/apiProvisioning-v1/removeFromGroup.feature
  tests/acceptance/features/apiProvisioning-v1/removeSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/addGroup.feature
  tests/acceptance/features/apiProvisioning-v2/addToGroup.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/apiProvisioning-v2/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/deleteGroup.feature
  tests/acceptance/features/apiProvisioning-v2/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/apiProvisioning-v2/getAppInfo.feature
  tests/acceptance/features/apiProvisioning-v2/getApps.feature
  tests/acceptance/features/apiProvisioning-v2/getGroup.feature
  tests/acceptance/features/apiProvisioning-v2/getGroups.feature
  tests/acceptance/features/apiProvisioning-v2/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioning-v2/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v2/getUser.feature
  tests/acceptance/features/apiProvisioning-v2/getUserGroups.feature
  tests/acceptance/features/apiProvisioning-v2/getUsers.feature
  tests/acceptance/features/apiProvisioning-v2/removeFromGroup.feature
  tests/acceptance/features/apiProvisioning-v2/removeSubAdmin.feature
  tests/acceptance/features/apiProvisioning/provisioning-v2.feature
Labels: 3 - To Review, dev:acceptance-tests

#31269 API tests to create and use an app password
  tests/acceptance/features/apiMain/auth.feature
  tests/acceptance/features/apiMain/tokenAuth.feature
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/Auth.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Tags.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#31286 Remember more created groups
  tests/TestHelpers/UserHelper.php
  tests/acceptance/features/apiProvisioning-v1/deleteGroup.feature
  tests/acceptance/features/apiProvisioning-v1/getGroup.feature
  tests/acceptance/features/apiProvisioning-v1/getGroups.feature
  tests/acceptance/features/apiProvisioning-v2/deleteGroup.feature
  tests/acceptance/features/apiProvisioning-v2/getGroup.feature
  tests/acceptance/features/apiProvisioning-v2/getGroups.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, dev:acceptance-tests
