Repository owncloud/core, pull requests merged in 2018-02, with the labels that each got.

#29935 Share personal cleanup + note
  apps/files_sharing/css/sharetabview.css
  apps/files_versions/tests/js/versionmodelSpec.js
  core/ajax/share.php
  core/css/global.css
  core/css/jquery.ocdialog.css
  core/css/share.css
  core/js/config.php
  core/js/js.js
  core/js/sharedialogexpirationview.js
  core/js/sharedialoglinkshareview.js
  core/js/sharedialogmailview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
  core/js/tests/specs/sharedialogmailviewSpec.js
  lib/private/Share/MailNotifications.php
  tests/ui/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
Labels: 4 - To release, backport-request, blue-ticket, bug, feature:sharing, junior job, p1-urgent, security, technical debt

#30408 Disable enforce password upload only stable10
  apps/files_sharing/tests/ApiTest.php
  core/Migrations/Version20180123131835.php
  core/js/config.php
  core/js/shareconfigmodel.js
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialogexpirationviewSpec.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
  core/js/tests/specs/sharedialogshareelistview.js
  core/js/tests/specs/sharedialogviewSpec.js
  lib/private/Share20/Manager.php
  lib/private/legacy/util.php
  lib/public/Share/IManager.php
  lib/public/Util.php
  settings/Panels/Admin/FileSharing.php
  settings/Panels/Helper.php
  settings/templates/panels/admin/filesharing.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#30440 [stable10] skip UI tests that fail because of issue #30392
  tests/ui/features/sharingExternalOther/shareByPublicLink.feature
Labels: 3 - To Review, browser:ie, dev:acceptance-tests

#30424 [stable10] scroll in modals
  core/css/jquery.ocdialog.css
  core/js/jquery.ocdialog.js
Labels: bug, enhancement

#30302 [stable10] Keep null in getMetaData in Checksum storage wrapper
  apps/files_versions/tests/VersioningTest.php
  lib/private/Files/Storage/Wrapper/Checksum.php
  tests/lib/Files/Storage/Wrapper/ChecksumTest.php
Labels: 3 - To Review

#30450 [hotfix-10.0.7] Check the return value of getUserSession before using it
  lib/private/Log.php
  lib/private/User/User.php
  tests/lib/LoggerTest.php
  tests/lib/User/UserTest.php
Labels: 4 - To release

#30453 Minimize scenario settings calls
  apps/testing/appinfo/routes.php
  apps/testing/lib/Config.php
  tests/TestHelpers/AppConfigHelper.php
  tests/integration/features/bootstrap/AppConfiguration.php
  tests/integration/features/bootstrap/CapabilitiesContext.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/FederationContext.php
  tests/integration/features/bootstrap/ShareesContext.php
  tests/integration/features/bootstrap/Sharing.php
  tests/ui/features/bootstrap/FeatureContext.php
Labels: 3 - To Review, dev:integration-tests

#30260 ltrim is more expensive than you think
  lib/private/AppFramework/Utility/SimpleContainer.php
  lib/private/Server.php
Labels: 3 - To Review, performance

#30456 [stable10] Minimize scenario settings calls
  apps/testing/appinfo/routes.php
  apps/testing/lib/Config.php
  tests/TestHelpers/AppConfigHelper.php
  tests/integration/features/bootstrap/AppConfiguration.php
  tests/integration/features/bootstrap/CapabilitiesContext.php
  tests/integration/features/bootstrap/FeatureContext.php
  tests/integration/features/bootstrap/FederationContext.php
  tests/integration/features/bootstrap/ShareesContext.php
  tests/integration/features/bootstrap/Sharing.php
  tests/ui/features/bootstrap/FeatureContext.php
Labels: 3 - To Review, dev:integration-tests

#28874 Use new DAV endpoint in web UI
  apps/files/js/filelist.js
  apps/files/tests/js/filelistSpec.js
  core/js/files/client.js
  core/js/tests/specs/files/clientSpec.js
Labels: 4 - To release, review carefully!

#30422 [stable10] Remove config value 'appstoreurl' - the appstore is long g…
  config/config.sample.php
Labels: 3 - To Review, server

#29461 Fix breadcrumb size calculation
  apps/files/js/filelist.js
  apps/files/js/files.js
  apps/files/templates/list.php
  apps/files_external/templates/list.php
  apps/files_trashbin/templates/index.php
Labels: 3 - To Review

#30431 [stable10] Update the documentation comments to match the new directory structure
  config/config.sample.php
Labels: 3 - To Review

#30020 Add group option to files:scan command
  apps/files/lib/Command/Scan.php
  apps/files/tests/Command/ScanTest.php
Labels: 3 - To Review

#30466 Minimize scenario settings calls in UI tests
  tests/ui/features/bootstrap/FeatureContext.php
  tests/ui/features/bootstrap/SharingContext.php
Labels: 3 - To Review, dev:acceptance-tests

#30467 [stable10] Minimize scenario settings calls in UI tests
  tests/ui/features/bootstrap/FeatureContext.php
  tests/ui/features/bootstrap/SharingContext.php
Labels: 3 - To Review, dev:acceptance-tests

#30155 [stable10] Don't try decrypting federated shares in decrypt-all command
  lib/private/Encryption/DecryptAll.php
  tests/lib/Encryption/DecryptAllTest.php
Labels: 3 - To Review

#30261 [Stable10] before create called too early
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/API/Share20OCSTest.php
Labels: 4 - To release

#30200 Fix path resolution for appdirs above ocwebroot.
  lib/private/App/AppManager.php
  lib/private/L10N/Factory.php
  lib/private/Server.php
  lib/private/Template/Base.php
  lib/private/Template/CSSResourceLocator.php
  lib/private/Template/JSResourceLocator.php
  lib/private/Template/ResourceLocator.php
  lib/private/TemplateLayout.php
  lib/private/Theme/Theme.php
  lib/private/Theme/ThemeService.php
  lib/private/URLGenerator.php
  lib/private/legacy/template.php
  lib/public/Theme/ITheme.php
  tests/lib/App/ManagerTest.php
  tests/lib/Template/BaseTest.php
  tests/lib/Template/CSSResourceLocatorTest.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/Template/ResourceLocatorTest.php
  tests/lib/Theme/ThemeServiceTest.php
Labels: 3 - To Review, bug, p2-high

#30365 Bugfix/owncloud/oauth2#103
  lib/private/Session/Internal.php
  lib/private/User/BasicAuthModule.php
  lib/private/User/Session.php
  lib/private/User/TokenAuthModule.php
  tests/lib/User/BasicAuthModuleTest.php
  tests/lib/User/SessionTest.php
  tests/lib/User/TokenAuthModuleTest.php
Labels: 3 - To Review, p1-urgent

#30479 [stable10] Bugfix/owncloud/oauth2#103
  lib/private/Session/Internal.php
  lib/private/User/BasicAuthModule.php
  lib/private/User/Session.php
  lib/private/User/TokenAuthModule.php
  tests/lib/User/BasicAuthModuleTest.php
  tests/lib/User/SessionTest.php
  tests/lib/User/TokenAuthModuleTest.php
Labels: 3 - To Review, QA-known, bug

#30483 fixes in drone settings
  .drone.yml
Labels: 3 - To Review, Drone, backport-request, dev:acceptance-tests

#30484 [stable10] fixes in drone settings
  .drone.yml
Labels: 3 - To Review, Drone, dev:acceptance-tests

#30481 [hotfix-10.0.7] When verifying the request authentication …
  lib/private/Session/Internal.php
  lib/private/User/BasicAuthModule.php
  lib/private/User/Session.php
  lib/private/User/TokenAuthModule.php
  tests/lib/User/BasicAuthModuleTest.php
  tests/lib/User/SessionTest.php
  tests/lib/User/TokenAuthModuleTest.php
Labels: 3 - To Review

#30413 New formats for integration test given-when-then step text
  tests/integration/capabilities_features/capabilities.feature
  tests/integration/features/appmanagement.feature
  tests/integration/features/auth.feature
  tests/integration/features/bootstrap/AppConfiguration.php
  tests/integration/features/bootstrap/AppManagementContext.php
  tests/integration/features/bootstrap/Auth.php
  tests/integration/features/bootstrap/BasicStructure.php
  tests/integration/features/bootstrap/CalDavContext.php
  tests/integration/features/bootstrap/CapabilitiesContext.php
  tests/integration/features/bootstrap/CardDavContext.php
  tests/integration/features/bootstrap/Checksums.php
  tests/integration/features/bootstrap/CommandLine.php
  tests/integration/features/bootstrap/Comments.php
  tests/integration/features/bootstrap/Federation.php
  tests/integration/features/bootstrap/Provisioning.php
  tests/integration/features/bootstrap/ShareesContext.php
  tests/integration/features/bootstrap/Sharing.php
  tests/integration/features/bootstrap/Tags.php
  tests/integration/features/bootstrap/Trashbin.php
  tests/integration/features/bootstrap/WebDav.php
  tests/integration/features/caldav.feature
  tests/integration/features/carddav.feature
  tests/integration/features/checksums.feature
  tests/integration/features/comments.feature
  tests/integration/features/dav-versions.feature
  tests/integration/features/external-storage.feature
  tests/integration/features/favorites.feature
  tests/integration/features/multilinksharing.feature
  tests/integration/features/provisioning-v1.feature
  tests/integration/features/provisioning-v2.feature
  tests/integration/features/quota.feature
  tests/integration/features/recreatemasterkey.feature
  tests/integration/features/sharing-v1.feature
  tests/integration/features/status.feature
  tests/integration/features/tags.feature
  tests/integration/features/transfer-ownership.feature
  tests/integration/features/trashbin-new-endpoint.feature
  tests/integration/features/trashbin-old-endpoint.feature
  tests/integration/features/webdav-related-new-endpoint.feature
  tests/integration/features/webdav-related-old-endpoint.feature
  tests/integration/federation_features/federated.feature
  tests/integration/sharees_features/sharees.feature
  tests/integration/sharees_features/sharees_provisioningapiv2.feature
Labels: 3 - To Review, backport-request, dev:integration-tests

#30488 [stable10] New formats for integration test given-when-then step text
  tests/integration/capabilities_features/capabilities.feature
  tests/integration/features/appmanagement.feature
  tests/integration/features/auth.feature
  tests/integration/features/bootstrap/AppConfiguration.php
  tests/integration/features/bootstrap/AppManagementContext.php
  tests/integration/features/bootstrap/Auth.php
  tests/integration/features/bootstrap/BasicStructure.php
  tests/integration/features/bootstrap/CalDavContext.php
  tests/integration/features/bootstrap/CapabilitiesContext.php
  tests/integration/features/bootstrap/CardDavContext.php
  tests/integration/features/bootstrap/Checksums.php
  tests/integration/features/bootstrap/CommandLine.php
  tests/integration/features/bootstrap/Comments.php
  tests/integration/features/bootstrap/Federation.php
  tests/integration/features/bootstrap/Provisioning.php
  tests/integration/features/bootstrap/ShareesContext.php
  tests/integration/features/bootstrap/Sharing.php
  tests/integration/features/bootstrap/Tags.php
  tests/integration/features/bootstrap/Trashbin.php
  tests/integration/features/bootstrap/WebDav.php
  tests/integration/features/caldav.feature
  tests/integration/features/carddav.feature
  tests/integration/features/checksums.feature
  tests/integration/features/comments.feature
  tests/integration/features/external-storage.feature
  tests/integration/features/favorites.feature
  tests/integration/features/multilinksharing.feature
  tests/integration/features/provisioning-v1.feature
  tests/integration/features/provisioning-v2.feature
  tests/integration/features/quota.feature
  tests/integration/features/recreatemasterkey.feature
  tests/integration/features/sharing-v1.feature
  tests/integration/features/status.feature
  tests/integration/features/tags.feature
  tests/integration/features/transfer-ownership.feature
  tests/integration/features/trashbin-new-endpoint.feature
  tests/integration/features/trashbin-old-endpoint.feature
  tests/integration/features/webdav-related-new-endpoint.feature
  tests/integration/features/webdav-related-old-endpoint.feature
  tests/integration/federation_features/federated.feature
  tests/integration/sharees_features/sharees.feature
  tests/integration/sharees_features/sharees_provisioningapiv2.feature
Labels: 3 - To Review, dev:integration-tests

#30457 Refactor infoparser
  core/Command/App/CheckCode.php
  core/register_command.php
  lib/private/App/AppManager.php
  lib/private/App/CodeChecker/InfoChecker.php
  lib/private/App/InfoParser.php
  lib/private/URLGenerator.php
  lib/private/legacy/app.php
  tests/Core/Command/Apps/CheckCodeTest.php
  tests/data/app/invalid-info2.xml
  tests/lib/App/CodeChecker/InfoCheckerTest.php
  tests/lib/App/InfoParserTest.php
Labels: 3 - To Review

#30486 [stable10] Share personal cleanup + note
  apps/files_sharing/css/sharetabview.css
  apps/files_versions/tests/js/versionmodelSpec.js
  core/ajax/share.php
  core/css/global.css
  core/css/jquery.ocdialog.css
  core/css/share.css
  core/js/config.php
  core/js/js.js
  core/js/sharedialogexpirationview.js
  core/js/sharedialoglinkshareview.js
  core/js/sharedialogmailview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
  core/js/tests/specs/sharedialogmailviewSpec.js
  lib/private/Share/MailNotifications.php
  tests/ui/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
Labels: 4 - To release, bug, p1-urgent

#30451 Catch if parent row exists when we try to add it
  lib/private/Repair.php
  lib/private/Repair/RepairMismatchFileCachePath.php
  tests/lib/Repair/RepairMismatchFileCachePathTest.php
Labels: 3 - To Review, backport-request

#30477 [Stable10] Fix path resolution for appdirs above ocwebroot
  lib/private/App/AppManager.php
  lib/private/L10N/Factory.php
  lib/private/Server.php
  lib/private/Template/Base.php
  lib/private/Template/CSSResourceLocator.php
  lib/private/Template/JSResourceLocator.php
  lib/private/Template/ResourceLocator.php
  lib/private/TemplateLayout.php
  lib/private/Theme/Theme.php
  lib/private/Theme/ThemeService.php
  lib/private/URLGenerator.php
  lib/private/legacy/template.php
  lib/public/Theme/ITheme.php
  tests/lib/App/ManagerTest.php
  tests/lib/Template/BaseTest.php
  tests/lib/Template/CSSResourceLocatorTest.php
  tests/lib/Template/JSResourceLocatorTest.php
  tests/lib/Template/ResourceLocatorTest.php
  tests/lib/Theme/ThemeServiceTest.php
Labels: 4 - To release, bug, p2-high

#30490 Trashbin restore to folder
  tests/integration/features/trashbin-new-endpoint.feature
  tests/integration/features/trashbin-old-endpoint.feature
Labels: 3 - To Review, backport-request, dev:integration-tests

#30496 [stable10] Add API tests for restoring a file deleted from a folder
  tests/integration/features/trashbin-new-endpoint.feature
  tests/integration/features/trashbin-old-endpoint.feature
Labels: 3 - To Review, dev:acceptance-tests

#30494 Repair catch stable10
  lib/private/Repair.php
  lib/private/Repair/RepairMismatchFileCachePath.php
  tests/lib/Repair/RepairMismatchFileCachePathTest.php
Labels: 3 - To Review

#30517 Fixup phpcs on UI tests
  phpcs.xml
  tests/ui/features/bootstrap/BasicStructure.php
  tests/ui/features/bootstrap/FilesContext.php
  tests/ui/features/bootstrap/SharingContext.php
  tests/ui/features/lib/FilesPageElement/FileRow.php
Labels: 3 - To Review, dev:acceptance-tests

#30518 [stable10] Fixup phpcs on UI tests
  phpcs.xml
  tests/ui/features/bootstrap/BasicStructure.php
  tests/ui/features/bootstrap/FilesContext.php
  tests/ui/features/bootstrap/SharingContext.php
  tests/ui/features/lib/FilesPageElement/FileRow.php
Labels: 3 - To Review, dev:acceptance-tests

#30495 disable previews for UI tests
  tests/ui/features/bootstrap/FeatureContext.php
  tests/ui/features/files/createFolders.feature
  tests/ui/features/files/createFoldersEdgeCases.feature
  tests/ui/features/files/deleteFilesFolders.feature
  tests/ui/features/files/scrollMenuIntoView.feature
  tests/ui/features/moveFilesFolders/moveFiles.feature
  tests/ui/features/moveFilesFolders/moveFolders.feature
  tests/ui/features/other/favoritesFile.feature
  tests/ui/features/other/login.feature
  tests/ui/features/other/managingGroups.feature
  tests/ui/features/other/managingingUserQuota.feature
  tests/ui/features/other/personalGeneralSettings.feature
  tests/ui/features/other/personalSecuritySettings.feature
  tests/ui/features/other/unfavoriteFile.feature
  tests/ui/features/renameFiles/renameFiles.feature
  tests/ui/features/renameFiles/renameFilesInsideProblematicFolderName.feature
  tests/ui/features/renameFolders/renameFolders.feature
  tests/ui/features/restrictSharing/disableSharing.feature
  tests/ui/features/restrictSharing/restrictReSharing.feature
  tests/ui/features/restrictSharing/restrictSharing.feature
  tests/ui/features/sharingExternalOther/federationSharing.feature
  tests/ui/features/sharingExternalOther/shareAutocompletion.feature
  tests/ui/features/sharingExternalOther/shareByPublicLink.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithGroups.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithGroupsEdgeCases.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithUsers.feature
  tests/ui/features/trashbin/restore.feature
  tests/ui/features/trashbin/trashbinDelete.feature
  tests/ui/features/trashbin/trashbinFilesFolders.feature
  tests/ui/features/upload/upload.feature
  tests/ui/features/upload/uploadEdgecases.feature
  tests/ui/features/upload/uploadFileGreaterThanQuotaSize.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30513 Retry upload overwrite if file locked in UI tests
  tests/ui/features/bootstrap/FeatureContext.php
  tests/ui/features/bootstrap/FilesContext.php
  tests/ui/features/bootstrap/SharingContext.php
  tests/ui/features/bootstrap/bootstrap.php
  tests/ui/features/lib/FilesPage.php
  tests/ui/features/lib/FilesPageBasic.php
  tests/ui/features/lib/PublicLinkFilesPage.php
  tests/ui/features/sharingExternalOther/federationSharing.feature
  tests/ui/features/sharingExternalOther/shareByPublicLink.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithGroups.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithUsers.feature
  tests/ui/features/upload/upload.feature
  tests/ui/features/upload/uploadEdgecases.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30507 Free resources in preview providers
  lib/private/Preview/Bitmap.php
  lib/private/Preview/SVG.php
  lib/private/Preview/TXT.php
Labels: 3 - To Review

#30524 [stable10] disable previews for UI tests
  tests/ui/features/bootstrap/FeatureContext.php
  tests/ui/features/files/createFolders.feature
  tests/ui/features/files/createFoldersEdgeCases.feature
  tests/ui/features/files/deleteFilesFolders.feature
  tests/ui/features/files/scrollMenuIntoView.feature
  tests/ui/features/moveFilesFolders/moveFiles.feature
  tests/ui/features/moveFilesFolders/moveFolders.feature
  tests/ui/features/other/favoritesFile.feature
  tests/ui/features/other/login.feature
  tests/ui/features/other/managingGroups.feature
  tests/ui/features/other/managingingUserQuota.feature
  tests/ui/features/other/personalGeneralSettings.feature
  tests/ui/features/other/personalSecuritySettings.feature
  tests/ui/features/other/unfavoriteFile.feature
  tests/ui/features/renameFiles/renameFiles.feature
  tests/ui/features/renameFiles/renameFilesInsideProblematicFolderName.feature
  tests/ui/features/renameFolders/renameFolders.feature
  tests/ui/features/restrictSharing/disableSharing.feature
  tests/ui/features/restrictSharing/restrictReSharing.feature
  tests/ui/features/restrictSharing/restrictSharing.feature
  tests/ui/features/sharingExternalOther/federationSharing.feature
  tests/ui/features/sharingExternalOther/shareAutocompletion.feature
  tests/ui/features/sharingExternalOther/shareByPublicLink.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithGroups.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithGroupsEdgeCases.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithUsers.feature
  tests/ui/features/trashbin/restore.feature
  tests/ui/features/trashbin/trashbinDelete.feature
  tests/ui/features/trashbin/trashbinFilesFolders.feature
  tests/ui/features/upload/upload.feature
  tests/ui/features/upload/uploadEdgecases.feature
  tests/ui/features/upload/uploadFileGreaterThanQuotaSize.feature
Labels: 3 - To Review, dev:acceptance-tests

#30525 [stable10] Adjust timeout and tests for federated share access
  tests/ui/features/lib/FilesPage.php
  tests/ui/features/sharingExternalOther/federationSharing.feature
Labels: 3 - To Review, dev:acceptance-tests

#30406 Fix error when querying non present "log_secret" parameter
  lib/private/Log.php
Labels: 3 - To Review, backport-request

#30528 [stable10] Retry when doing upload overwrite in UI tests
  tests/ui/features/bootstrap/FeatureContext.php
  tests/ui/features/bootstrap/FilesContext.php
  tests/ui/features/bootstrap/SharingContext.php
  tests/ui/features/bootstrap/bootstrap.php
  tests/ui/features/lib/FilesPage.php
  tests/ui/features/lib/FilesPageBasic.php
  tests/ui/features/lib/PublicLinkFilesPage.php
  tests/ui/features/sharingExternalOther/federationSharing.feature
  tests/ui/features/sharingExternalOther/shareByPublicLink.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithGroups.feature
  tests/ui/features/sharingInternalGroupsUsers/shareWithUsers.feature
  tests/ui/features/upload/upload.feature
  tests/ui/features/upload/uploadEdgecases.feature
Labels: 3 - To Review, dev:acceptance-tests

#30435 Use fileid as string in web UI
  apps/comments/tests/js/commentscollectionSpec.js
  apps/comments/tests/js/commentstabviewSpec.js
  apps/comments/tests/js/filespluginSpec.js
  apps/files/js/fileactions.js
  apps/files/js/fileinfomodel.js
  apps/files/js/filelist.js
  apps/files/tests/js/detailsviewSpec.js
  apps/files/tests/js/favoritesfilelistspec.js
  apps/files/tests/js/fileactionsSpec.js
  apps/files/tests/js/fileactionsmenuSpec.js
  apps/files/tests/js/filelistSpec.js
  apps/files/tests/js/mainfileinfodetailviewSpec.js
  apps/files/tests/js/tagspluginspec.js
  apps/files_sharing/lib/API/Remote.php
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/js/shareSpec.js
  apps/files_sharing/tests/js/sharedfilelistSpec.js
  apps/files_trashbin/tests/js/filelistSpec.js
  apps/files_versions/tests/js/versionmodelSpec.js
  apps/files_versions/tests/js/versionstabviewSpec.js
  apps/systemtags/tests/js/systemtagsfilelistSpec.js
  core/js/files/fileinfo.js
  core/js/shareitemmodel.js
  core/js/tests/specs/files/clientSpec.js
  core/js/tests/specs/sharedialogexpirationviewSpec.js
  core/js/tests/specs/sharedialoglinklistviewSpec.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
  core/js/tests/specs/sharedialogmailviewSpec.js
  core/js/tests/specs/sharedialogshareelistview.js
  core/js/tests/specs/sharedialogviewSpec.js
  core/js/tests/specs/shareitemmodelSpec.js
Labels: 3 - To Review, bug, server

#30504 Use type juggling for comparison on size in chunking plugin
  apps/dav/lib/Upload/ChunkingPlugin.php
  apps/dav/tests/unit/Upload/ChunkingPluginTest.php
Labels: 3 - To Review

#30455 Check exec and stat method before using it
  lib/private/Files/Storage/Local.php
Labels: 3 - To Review

#30538 UI-tests clear lock after scenario
  apps/testing/appinfo/routes.php
  apps/testing/locking/fakedblockingprovider.php
  apps/testing/locking/provisioning.php
  tests/ui/features/bootstrap/FeatureContext.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30533 [Stable10] Free resources in preview providers
  lib/private/Preview/Movie.php
  lib/private/Preview/SVG.php
  lib/private/Preview/TXT.php
Labels: 3 - To Review

#30539 [stable10] UI-tests clear lock after scenario
  apps/testing/appinfo/routes.php
  apps/testing/locking/fakedblockingprovider.php
  apps/testing/locking/provisioning.php
  tests/ui/features/bootstrap/FeatureContext.php
Labels: 3 - To Review, dev:acceptance-tests

#30526 Properly create a session for a pure token based request ...
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#30324 UI tests to change password from user personal settings
  tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
  tests/ui/features/lib/PersonalGeneralSettingsPage.php
  tests/ui/features/other/changePasswordFromSetting.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30547 Bump phpseclib/phpseclib from 2.0.9 to 2.0.10
  composer.lock
Labels: 3 - To Review, dependencies

#30542 [stable10] Properly create a session for a pure token based request ...
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 4 - To release

#30545 [stable10] UI tests to change password from user personal settings
  tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
  tests/ui/features/lib/PersonalGeneralSettingsPage.php
  tests/ui/features/other/changePasswordFromSetting.feature
Labels: 3 - To Review, dev:acceptance-tests

#30551 Fix wording if you are not a member of any groups
  settings/templates/panels/personal/profile.php
Labels: 3 - To Review, backport-request, settings:personal

#30536 Stop searching apps in OC::SERVERROOT sibling
  lib/base.php
Labels: 3 - To Review

#30556 [stable10] Fixing variable dependency
  apps/files/js/files.js
Labels: 3 - To Review

#30554 Improve message when UI test file should be listed check fails
  tests/ui/features/bootstrap/FilesContext.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30559 Skip failing public link share tests on Edge browser
  tests/ui/features/sharingExternalOther/shareByPublicLink.feature
Labels: 3 - To Review, dev:acceptance-tests

#30560 [stable10] Improve message when UI test file should be listed check fails
  tests/ui/features/bootstrap/FilesContext.php
Labels: 3 - To Review, dev:acceptance-tests

#30561 [stable10] Skip failing public link share tests on Edge browser
  tests/ui/features/sharingExternalOther/shareByPublicLink.feature
Labels: 3 - To Review, dev:acceptance-tests

#30508 Fixing variable dependency
  apps/files/js/files.js
Labels: 2 - Developing, p1-urgent, regression

#29610 Catch and convert LoginException to NotAuthenticated to show 401 instead of 503
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/tests/unit/Connector/Sabre/AuthTest.php
  tests/integration/features/webdav-related-new-endpoint.feature
  tests/integration/features/webdav-related-old-endpoint.feature
Labels: 2 - Developing

#27914 Test calendar object with various characters
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 3 - To Review, backport-request

#30563 Improve notificationsShouldBeDisplayedWithTheText failure message
  tests/ui/features/bootstrap/FeatureContext.php
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30564 step for possible/impossible webui login
  tests/ui/features/bootstrap/LoginContext.php
Labels: 3 - To Review, dev:acceptance-tests

#30565 [stable10] Improve notificationsShouldBeDisplayedWithTheText failure message
  tests/ui/features/bootstrap/FeatureContext.php
Labels: 3 - To Review, dev:acceptance-tests

#30566 [stable10] step for possible/impossible webui login
  tests/ui/features/bootstrap/LoginContext.php
Labels: 3 - To Review, dev:acceptance-tests

#30568 Fix link share email subject
  core/ajax/share.php
Labels: backport-request, bug, p1-urgent, regression

#30558 [stable10] FIx wording if you are not a member of any groups
  settings/templates/panels/personal/profile.php
Labels: 3 - To Review, settings:personal

#30555 Bump phpspec/prophecy from 1.7.3 to 1.7.5
  composer.lock
Labels: 3 - To Review, dependencies

#30548 [stable10] Bump phpspec/prophecy from 1.7.3 to 1.7.5
  composer.lock
Labels: 3 - To Review, dependencies

#30567 [stable10] Test calendar object with various characters
  apps/dav/lib/CalDAV/CalDavBackend.php
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
Labels: 3 - To Review

#30574 Add 10.0.7 changelog entries from hotfix-10.0.7 branch
  CHANGELOG.md
Labels: 3 - To Review

#30573 Teach UI tests to know if a user should exist or not
  tests/ui/features/bootstrap/BasicStructure.php
  tests/ui/features/bootstrap/UsersContext.php
  tests/ui/features/other/login.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30571 [stable10] Fix link share email subject
  core/ajax/share.php
Labels: 3 - To Review

#30577 [stable10] Teach UI tests to know if a user should exist or not
  tests/ui/features/bootstrap/BasicStructure.php
  tests/ui/features/bootstrap/UsersContext.php
  tests/ui/features/other/login.feature
Labels: 3 - To Review, dev:acceptance-tests

#30389 Sort out skipped trashbin integration tests
  tests/integration/features/bootstrap/WebDav.php
  tests/integration/features/trashbin-new-endpoint.feature
  tests/integration/features/trashbin-old-endpoint.feature
Labels: 3 - To Review, dev:integration-tests

#30584 Split UI test suites into smaller pieces
  .drone.yml
  .travis.yml
  tests/ui/config/behat.yml
  tests/ui/features/favorites/favoritesFile.feature
  tests/ui/features/favorites/unfavoriteFile.feature
  tests/ui/features/manageQuota/manageUserQuota.feature
  tests/ui/features/manageUsersGroups/login.feature
  tests/ui/features/manageUsersGroups/manageGroups.feature
  tests/ui/features/manageUsersGroups/manageUsers.feature
  tests/ui/features/other/login.feature
  tests/ui/features/personalSettings/changePasswordFromSetting.feature
  tests/ui/features/personalSettings/personalGeneralSettings.feature
  tests/ui/features/personalSettings/personalSecuritySettings.feature
  tests/ui/features/sharingExternal/federationSharing.feature
  tests/ui/features/sharingExternal/shareByPublicLink.feature
  tests/ui/features/sharingInternalGroups/shareWithGroups.feature
  tests/ui/features/sharingInternalGroups/shareWithGroupsEdgeCases.feature
  tests/ui/features/sharingInternalUsers/shareAutocompletion.feature
  tests/ui/features/sharingInternalUsers/shareWithUsers.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#28043 Increase version to 10.1 prealpha
  .drone.yml
  .travis.yml
  Jenkinsfile
  apps/comments/appinfo/info.xml
  apps/dav/appinfo/info.xml
  apps/federatedfilesharing/appinfo/info.xml
  apps/federation/appinfo/info.xml
  apps/files/appinfo/info.xml
  apps/files_external/appinfo/info.xml
  apps/files_sharing/appinfo/info.xml
  apps/files_trashbin/appinfo/info.xml
  apps/files_versions/appinfo/info.xml
  apps/provisioning_api/appinfo/info.xml
  apps/systemtags/appinfo/info.xml
  apps/testing/appinfo/info.xml
  apps/theme-example/appinfo/info.xml
  apps/updatenotification/appinfo/info.xml
  composer.json
  composer.lock
  console.php
  index.php
  lib/private/Files/Storage/Common.php
  lib/private/Lock/MemcacheLockingProvider.php
  lib/private/Memcache/APC.php
  lib/private/Memcache/XCache.php
  tests/lib/DB/AdapterTest.php
  tests/lib/Files/Node/IntegrationTest.php
  tests/lib/Files/ViewTest.php
  tests/lib/Memcache/APCTest.php
  tests/lib/Memcache/XCacheTest.php
  version.php
Labels: 3 - To Review, technical debt

#30588 Fix contexts needed for manageUsersGroups UI test suite
  tests/ui/config/behat.yml
Labels: 3 - To Review, dev:acceptance-tests

#30587 [stable10] Split UI test suites into smaller pieces
  .drone.yml
  .travis.yml
  tests/ui/config/behat.yml
  tests/ui/features/favorites/favoritesFile.feature
  tests/ui/features/favorites/unfavoriteFile.feature
  tests/ui/features/manageQuota/manageUserQuota.feature
  tests/ui/features/manageUsersGroups/login.feature
  tests/ui/features/manageUsersGroups/manageGroups.feature
  tests/ui/features/manageUsersGroups/manageUsers.feature
  tests/ui/features/other/login.feature
  tests/ui/features/personalSettings/changePasswordFromSetting.feature
  tests/ui/features/personalSettings/personalGeneralSettings.feature
  tests/ui/features/personalSettings/personalSecuritySettings.feature
  tests/ui/features/sharingExternal/federationSharing.feature
  tests/ui/features/sharingExternal/shareByPublicLink.feature
  tests/ui/features/sharingInternalGroups/shareWithGroups.feature
  tests/ui/features/sharingInternalGroups/shareWithGroupsEdgeCases.feature
  tests/ui/features/sharingInternalUsers/shareAutocompletion.feature
  tests/ui/features/sharingInternalUsers/shareWithUsers.feature
Labels: 3 - To Review, dev:acceptance-tests

#30575 Changelog entries for the first batch of changes in 10.0.8
  CHANGELOG.md
Labels: 3 - To Review

#30586 [stable10] Modify trashbin integration tests for issue 23151
  tests/integration/features/bootstrap/WebDav.php
  tests/integration/features/trashbin-new-endpoint.feature
  tests/integration/features/trashbin-old-endpoint.feature
Labels: 3 - To Review, dev:integration-tests

#30591 [stable10] Fixing logout for app password scenario
  lib/private/User/BasicAuthModule.php
  lib/private/User/Session.php
  tests/lib/User/BasicAuthModuleTest.php
Labels: 3 - To Review, backport-request, bug, p1-urgent, security

#30589 Be strict on behat runs for UI tests
  tests/travis/start_ui_tests.sh
Labels: 3 - To Review, dev:acceptance-tests

#30503 Properly encode returned Webdav URL in ViewController
  apps/files/lib/Controller/ViewController.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: 3 - To Review, backport-request

#30315 [stable10] Validate email address in mail settings
  settings/Controller/MailSettingsController.php
  tests/Settings/Controller/MailSettingsControllerTest.php
Labels: 3 - To Review, status/STALE

#30593 [stable10] Be strict on behat runs for UI tests
  tests/travis/start_ui_tests.sh
Labels: 3 - To Review, dev:acceptance-tests

#30186 Adding repair step for sub share
  lib/private/Repair.php
  lib/private/Repair/RepairSubShares.php
  tests/lib/Repair/RepairSubSharesTest.php
Labels: 3 - To Review, status/STALE

#30595 [stable10] Properly encode returned Webdav URL in ViewController
  apps/files/lib/Controller/ViewController.php
  apps/files/tests/Controller/ViewControllerTest.php
Labels: 4 - To release

#30597 Fixing logout for app password scenario
  lib/private/User/BasicAuthModule.php
  lib/private/User/Session.php
  tests/lib/User/BasicAuthModuleTest.php
Labels: 4 - To release

#30592 UI test to add group
  tests/ui/features/bootstrap/UsersContext.php
  tests/ui/features/lib/UserPageElement/GroupList.php
  tests/ui/features/lib/UsersPage.php
  tests/ui/features/manageUsersGroups/addGroup.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30605 Move rename-into-folder tests to move suites
  tests/ui/features/moveFilesFolders/moveFiles.feature
  tests/ui/features/moveFilesFolders/moveFolders.feature
  tests/ui/features/renameFiles/renameFiles.feature
  tests/ui/features/renameFolders/renameFolders.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30608 More bumps to PHP 7.1 for Travis
  .travis.yml
Labels: 3 - To Review, dev:acceptance-tests

#30601 Add scenarios for transferring folders without files
  tests/integration/features/bootstrap/WebDav.php
  tests/integration/features/transfer-ownership.feature
Labels: 3 - To Review, backport-request, dev:integration-tests

#30610 [stable10] Move rename-into-folder tests to move suites
  tests/ui/features/moveFilesFolders/moveFiles.feature
  tests/ui/features/moveFilesFolders/moveFolders.feature
  tests/ui/features/renameFiles/renameFiles.feature
  tests/ui/features/renameFolders/renameFolders.feature
Labels: 3 - To Review, dev:acceptance-tests

#30516 Show warning message if no files to be transferred
  apps/files/lib/Command/TransferOwnership.php
  tests/integration/features/transfer-ownership.feature
Labels: 3 - To Review

#30489 Email notifications (core changes)
  lib/private/Notification/Events/RegisterConsumerEventImpl.php
  lib/private/Notification/Events/RegisterNotifierEventImpl.php
  lib/private/Notification/Manager.php
  lib/private/Server.php
  lib/public/Notification/Events/RegisterConsumerEvent.php
  lib/public/Notification/Events/RegisterNotifierEvent.php
  lib/public/Notification/Exceptions/NotifierIdInUseException.php
  tests/lib/Notification/ManagerTest.php
Labels: 3 - To Review, feature:notifications

#30580 Test unlock on exception during scanning
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Storage/Temporary.php
  tests/lib/Files/Cache/ScannerTest.php
Labels: 4 - To release

#29635 Fix files:scan repair + basic tests for files:scan command
  apps/files/lib/Command/Scan.php
  apps/files/tests/Command/ScanTest.php
  tests/lib/Util/User/MemoryAccountMapper.php
Labels: 3 - To Review, backport-request, bug, p1-urgent, regression

#30611 [stable10] Add scenarios for transferring folders without files
  tests/integration/features/bootstrap/WebDav.php
  tests/integration/features/transfer-ownership.feature
Labels: 3 - To Review, dev:integration-tests

#30607 [stable10] UI test to add group
  tests/ui/features/bootstrap/UsersContext.php
  tests/ui/features/lib/UserPageElement/GroupList.php
  tests/ui/features/lib/UsersPage.php
  tests/ui/features/manageUsersGroups/addGroup.feature
Labels: 3 - To Review, dev:acceptance-tests

#30198 Default HTTPS for fed sharing & config option for allowing fallback
  config/config.sample.php
  lib/private/Share/Share.php
  tests/lib/Share/ShareTest.php
Labels: 3 - To Review, app:federation, backport-request, feature:federated-cloud-sharing

#30613 Email notifications stable10
  lib/private/Notification/Events/RegisterConsumerEventImpl.php
  lib/private/Notification/Events/RegisterNotifierEventImpl.php
  lib/private/Notification/Manager.php
  lib/private/Server.php
  lib/public/Notification/Events/RegisterConsumerEvent.php
  lib/public/Notification/Events/RegisterNotifierEvent.php
  lib/public/Notification/Exceptions/NotifierIdInUseException.php
  tests/lib/Notification/ManagerTest.php
Labels: 4 - To release, feature:notifications

#30598 Bump sabre/http from 4.2.3 to v4.2.4
  composer.lock
  tests/integration/features/webdav-related-new-endpoint.feature
  tests/integration/features/webdav-related-old-endpoint.feature
Labels: 3 - To Review, dependencies

#30599 [stable10] Bump sabre/http from 4.2.3 to v4.2.4
  composer.lock
  tests/integration/features/webdav-related-new-endpoint.feature
  tests/integration/features/webdav-related-old-endpoint.feature
Labels: 3 - To Review, dependencies

#30546 [stable10] Check exec and stat method before using it
  lib/private/Files/Storage/Local.php
Labels: 4 - To release

#30615 [stable10] Add group option to files:scan command
  apps/files/lib/Command/Scan.php
  apps/files/tests/Command/ScanTest.php
Labels: 4 - To release

#30612 [stable10] Show warning message if no files to be transferred
  apps/files/lib/Command/TransferOwnership.php
  tests/integration/features/transfer-ownership.feature
Labels: 3 - To Review

#30618 [stable10] Fix repair command + more scan unit tests
  apps/files/lib/Command/Scan.php
  apps/files/tests/Command/ScanTest.php
  tests/lib/Util/User/MemoryAccountMapper.php
Labels: 3 - To Review

#30473 [stable9.1] Catch session unavailable exception
  lib/private/Session/Memory.php
  tests/lib/Session/CryptoSessionDataTest.php
Labels: 3 - To Review

#30632 Wait for personal general settings page to load
  tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
  tests/ui/features/manageUsersGroups/login.feature
Labels: 3 - To Review, backport-request, dev:acceptance-tests

#30634 [stable10] wait for personal general settings page to load
  tests/ui/features/bootstrap/PersonalGeneralSettingsContext.php
  tests/ui/features/manageUsersGroups/login.feature
Labels: 3 - To Review, dev:acceptance-tests

#30635 Integration step definitions for when given
  tests/integration/features/bootstrap/AppConfiguration.php
  tests/integration/features/bootstrap/AppManagementContext.php
  tests/integration/features/bootstrap/Auth.php
  tests/integration/features/bootstrap/BasicStructure.php
  tests/integration/features/bootstrap/CalDavContext.php
  tests/integration/features/bootstrap/CapabilitiesContext.php
  tests/integration/features/bootstrap/CardDavContext.php
  tests/integration/features/bootstrap/Checksums.php
  tests/integration/features/bootstrap/CommandLine.php
  tests/integration/features/bootstrap/Comments.php
  tests/integration/features/bootstrap/Federation.php
  tests/integration/features/bootstrap/Provisioning.php
  tests/integration/features/bootstrap/ShareesContext.php
  tests/integration/features/bootstrap/Sharing.php
  tests/integration/features/bootstrap/Tags.php
  tests/integration/features/bootstrap/Trashbin.php
  tests/integration/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:integration-tests

#30637 [stable10] Integration step definitions for when given
  tests/integration/features/bootstrap/AppConfiguration.php
  tests/integration/features/bootstrap/AppManagementContext.php
  tests/integration/features/bootstrap/Auth.php
  tests/integration/features/bootstrap/BasicStructure.php
  tests/integration/features/bootstrap/CalDavContext.php
  tests/integration/features/bootstrap/CapabilitiesContext.php
  tests/integration/features/bootstrap/CardDavContext.php
  tests/integration/features/bootstrap/Checksums.php
  tests/integration/features/bootstrap/CommandLine.php
  tests/integration/features/bootstrap/Comments.php
  tests/integration/features/bootstrap/Federation.php
  tests/integration/features/bootstrap/Provisioning.php
  tests/integration/features/bootstrap/ShareesContext.php
  tests/integration/features/bootstrap/Sharing.php
  tests/integration/features/bootstrap/Tags.php
  tests/integration/features/bootstrap/Trashbin.php
  tests/integration/features/bootstrap/WebDav.php
Labels: 3 - To Review, dev:integration-tests

#29415 decrypt seen users only
  lib/private/Encryption/DecryptAll.php
  tests/lib/Encryption/DecryptAllTest.php
Labels: 1 - To develop, app:encryption, enhancement, p2-high, performance

#30640 [stable10] Decrypt seen users only
  lib/private/Encryption/DecryptAll.php
  tests/lib/Encryption/DecryptAllTest.php
Labels: 4 - To release

#30639 [Stable10] proper return code on login exception
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/tests/unit/Connector/Sabre/AuthTest.php
  tests/integration/features/webdav-related-new-endpoint.feature
  tests/integration/features/webdav-related-old-endpoint.feature
Labels: 4 - To release

#30623 [stable10] Catch session unavailable exception
  tests/lib/Session/CryptoSessionDataTest.php
Labels: 3 - To Review

#30619 Catch session unavailable exception
  tests/lib/Session/CryptoSessionDataTest.php
Labels: 3 - To Review

#30646 [stable10] Flag to enable http fallback when creating fed shares
  config/config.sample.php
  lib/private/Share/Share.php
  tests/lib/Share/ShareTest.php
Labels: 4 - To release

#30648 Allow regular users to change their CORS domains
  settings/Controller/CorsController.php
Labels: 4 - To release, blue-ticket, security

#30314 [stable9.1] As soon as the password/email is changed the lost token is removed
  core/Controller/LostController.php
  core/css/lostpassword/resetpassword.css
  lib/private/User/User.php
  tests/Core/Controller/LostControllerTest.php
  tests/lib/User/BackendTestCase.php
  tests/lib/User/DatabaseTest.php
  tests/lib/User/DummyTestCase.php
  tests/lib/User/UserTest.php
  tests/lib/UserTest.php
Labels: 3 - To Review

#30629 [phpunit] Fail on warnings
  apps/dav/tests/unit/phpunit.xml
  tests/phpunit-autotest-external.xml
  tests/phpunit-autotest.xml
Labels: 3 - To Review
