Repository owncloud/core, pull requests merged in 2019-10, with the labels that each got.

#36234 Add restic/calens for changelog management
  .htaccess
  changelog/CHANGELOG.tmpl
  changelog/README.md
  changelog/TEMPLATE
Labels: 3 - To Review

#36225 Take accounts.enable_medial_search into account while searching for remote users in share autocomplete
  apps/dav/lib/CardDAV/AddressBookImpl.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/tests/unit/CardDAV/AddressBookImplTest.php
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/tests/API/ShareesTest.php
  changelog/unreleased/36225
Labels: 3 - To Review, blue-ticket, p3-medium

#36253 Updating phpspec/prophecy (1.8.1 => 1.9.0)
  composer.lock
Labels: 3 - To Review, dependencies, php

#36222 only collect shares inside the given path in transfer-ownership command
  apps/files/lib/Command/TransferOwnership.php
  apps/files/tests/Command/TransferOwnershipTest.php
  changelog/unreleased/36222
Labels: 3 - To Review

#36263 Updating sabre/http (5.0.2 => 5.0.4)
  changelog/unreleased/36263
  composer.lock
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavProperties/getQuota.feature
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, dependencies, php

#36286 Avoid PHP_CodeSniffer 3.5.1 due to regression
  vendor-bin/php_codesniffer/composer.json
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36272 Initial drone starlark
  .drone.jsonnet
  .drone.starlark
  .drone.yml
  Makefile
  pipeline.libsonnet
Labels: 3 - To Review, Drone, QA-team

#36291 Adjust phpunit withConsecutive calls
  apps/files_sharing/tests/API/ShareesTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  apps/files_sharing/tests/Service/NotificationPublisherTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 4 - To release, dev:phpunit-tests

#36294 Skip tests which are failing on user_ldap
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36296 drone notify on failure
  .drone.starlark
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#36261 Changelog for Symfony 3.4.32
  changelog/unreleased/36244
Labels: 3 - To Review, dependencies

#36281 Avoid unnecessary "Avatar not found" logs by initializing ViewOnlyPlugin for only files
  apps/dav/lib/Server.php
  apps/dav/tests/unit/ServerTest.php
  changelog/unreleased/36281
Labels: 3 - To Review

#36292 Run sftp unit tests in drone
  .drone.starlark
  .drone.yml
  tests/drone/configs/config.files_external.sftp.php
  tests/drone/test-phpunit.sh
Labels: 3 - To Review, Drone, QA-team

#36300 Updating sabre/dav (4.0.1 => 4.0.2)
  changelog/unreleased/36299
Labels: 3 - To Review, dependencies

#36313 allow to use with new public webdav API
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36304 Only show progressbar if option --progress is set
  changelog/unreleased/issue-36298
  core/Command/System/Cron.php
  tests/Core/Command/System/CronTest.php
Labels: 3 - To Review

#36242 Fix access denied error while listing the contents of the folder
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3 - To Review

#36335 Acceptance tests: remember fed trusted servers only if it exists
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/webUISharingExternal/adminSharingSettings.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36348 Updating psr/log (1.1.0 => 1.1.1)
  composer.lock
Labels: 3 - To Review, dependencies, php

#36337 Disallow sharing and deleting of share_folder and it's parents
  changelog/unreleased/36337
  lib/private/Files/Mount/Manager.php
  lib/private/Files/View.php
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
Labels: 3 - To Review

#36355 Acceptance tests: Restore local trusted servers even if fed server doesnt exists
  tests/acceptance/features/bootstrap/AppConfiguration.php
Labels: 4 - To release, Acceptance tests, QA-team
