Repository owncloud/core, pull requests merged in 2019-08, with the labels that each got.

#35966 Fix translation sync
  l10n/Makefile
Labels: 4 - To release

#35968 acceptance test for attempt to modify group share permissions when group sharing is off
  tests/acceptance/features/apiShareUpdate/updateShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#35954 Keep DAV properties when file goes to trashbin
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/DAV/AbstractCustomPropertiesBackend.php
  apps/dav/lib/DAV/FileCustomPropertiesBackend.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/DAV/FileCustomPropertiesBackendTest.php
  apps/dav/tests/unit/DAV/MiscCustomPropertiesBackendTest.php
Labels: 3 - To Review

#35892 Fix SMB domain usage
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3 - To Review

#35951 Remove swift primary and secondary storage support
  .drone.yml
  apps/files_external/lib/AppInfo/Application.php
  apps/files_external/lib/Lib/Backend/Swift.php
  apps/files_external/lib/Lib/Storage/Swift.php
  apps/files_external/tests/Storage/SwiftTest.php
  apps/files_external/tests/config.php
  apps/files_external/tests/env/start-swift-ceph.sh
  apps/files_external/tests/env/stop-swift-ceph.sh
  build/autotest.sh
  composer.json
  composer.lock
  config/config.sample.php
  lib/private/Files/ObjectStore/Swift.php
  tests/drone/install-server.sh
  tests/drone/test-phpunit.sh
  tests/lib/Files/ObjectStore/SwiftTest.php
  tests/objectstore/start-swift-ceph.sh
  tests/objectstore/stop-swift-ceph.sh
  tests/objectstore/wait-for-connection
Labels: 3 - To Review

#35973 read the correct translations
  lib/private/Helper/LocaleHelper.php
Labels: 3 - To Review

#35884 Refactor share permissions handling
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  apps/files_sharing/tests/ShareTest.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  tests/acceptance/features/apiComments/createComments.feature
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareReshare/reShare.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/lib/Share20/ManagerTest.php
Labels: 4 - To release, release:10.3.0, review carefully!

#35975 acceptance test to directly browse to parents folder
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/webUIFiles/fileDetails.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#35977 obey user min search length configuration on remote shares
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/tests/API/ShareesTest.php
Labels: 3 - To Review

#35978 Updating mikey179/vfsstream (v1.6.6 => v1.6.7)
  composer.lock
Labels: 3 - To Review, dependencies, release:10.3.0

#35989 Updating symfony/polyfill-* (v1.11.0 => v1.12.0)
  composer.lock
Labels: 4 - To release, dependencies, release:10.3.0

#35931 Tell the browser not to autofill those password fields
  settings/js/users/users.js
  settings/templates/setpassword.php
  settings/templates/users/part.createuser.php
Labels: 3 - To Review

#35991 testing app is not needed for unit tests
  .drone.yml
  tests/Core/Command/Apps/AppsDisableTest.php
  tests/Core/Command/Apps/AppsEnableTest.php
  tests/Core/Command/Apps/AppsListTest.php
Labels: 4 - To release, QA-team, dev:phpunit-tests

#35986 Upgrade node dependencies
  build/yarn.lock
Labels: 3 - To Review, security

#35995 Add no comment when locking old issues and pull requests
  .github/lock.yml
Labels: 3 - To Review

#35987 Replace drone matrix config by jsonnet definition
  .drone.jsonnet
  .drone.yml
  pipeline.libsonnet
  tests/drone/composer-install.sh
  tests/drone/configs/config.files_external.smb-samba.php
  tests/drone/configs/config.files_external.webdav-apache.php
  tests/drone/test-javascript.sh
  tests/drone/test-phpunit.sh
  tests/drone/yarn-install.sh
Labels: 3 - To Review

#35999 Fixup drone refs drone-jsonnet->master
  .drone.jsonnet
  .drone.yml
Labels: 3 - To Review, Drone, QA-team

#35932 Feature/public links
  apps/dav/lib/DAV/PublicAuth.php
  apps/dav/lib/Files/PublicFiles/IPublicSharedNode.php
  apps/dav/lib/Files/PublicFiles/NodeFactoryTrait.php
  apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
  apps/dav/lib/Files/PublicFiles/PublicSharedRootNode.php
  apps/dav/lib/Files/PublicFiles/PublicSharingAuth.php
  apps/dav/lib/Files/PublicFiles/RootCollection.php
  apps/dav/lib/Files/PublicFiles/SharedFile.php
  apps/dav/lib/Files/PublicFiles/SharedFolder.php
  apps/dav/lib/Files/PublicFiles/SharedNodeTrait.php
  apps/dav/lib/RootCollection.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/PublicFiles/PublicFilesPluginTest.php
  apps/dav/tests/unit/Files/PublicFiles/PublicSharingAuthTest.php
  core/routes.php
  lib/private/Files/Node/Node.php
  lib/private/Share/Constants.php
  lib/public/Files/Node.php
Labels: 3 - To Review

#36004 Run PHP unit tests on PHP 7.0
  .drone.jsonnet
  .drone.yml
Labels: 4 - To release, QA-team, dev:phpunit-tests

#35972 Move user creation to a separate service
  apps/provisioning_api/appinfo/routes.php
  apps/provisioning_api/lib/Users.php
  apps/provisioning_api/tests/UsersTest.php
  core/Application.php
  core/Command/User/Add.php
  core/Controller/UserController.php
  core/css/setpassword.css
  core/js/setpassword.js
  core/register_command.php
  core/routes.php
  core/templates/new_user/email-html.php
  core/templates/new_user/email-plain_text.php
  core/templates/new_user/resendtokenbymail.php
  core/templates/new_user/setpassword.php
  core/templates/new_user/tokensendnotify.php
  lib/private/User/Service/CreateUserService.php
  lib/private/User/Service/PasswordGeneratorService.php
  lib/private/User/Service/UserSendMailService.php
  lib/public/User/Exceptions/CannotCreateUserException.php
  lib/public/User/Exceptions/EmailSendFailedException.php
  lib/public/User/Exceptions/InvalidEmailException.php
  lib/public/User/Exceptions/InvalidUserTokenException.php
  lib/public/User/Exceptions/UserAlreadyExistsException.php
  lib/public/User/Exceptions/UserTokenException.php
  lib/public/User/Exceptions/UserTokenExpiredException.php
  lib/public/User/Exceptions/UserTokenMismatchException.php
  tests/Core/Command/User/AddTest.php
  tests/Core/Controller/UserControllerTest.php
  tests/lib/User/Service/CreateUserServiceTest.php
  tests/lib/User/Service/PasswordGeneratorServiceTest.php
  tests/lib/User/Service/UserSendMailServiceTest.php
Labels: 3 - To Review

#35948 test 'restoring a file to an already existing path overrides the file'
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36011 Updating sebastian/exporter (3.1.0 => 3.1.1)
  composer.lock
Labels: 4 - To release, QA-team, dependencies

#36014 Revert "removing failing phpunit scality matrix entry"
  .drone.jsonnet
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#36022 Adjust 'Unable to create user' exception message text
  lib/private/User/Service/CreateUserService.php
  tests/lib/User/Service/CreateUserServiceTest.php
Labels: 3 - To Review

#36023 Remove unused encryption acceptance tests
  tests/acceptance/config/behat.yml
  tests/acceptance/features/cliEncryption/recreatemasterkey.feature
  tests/acceptance/features/webUIMasterKeyType/webUIMasterKeys.feature
  tests/acceptance/features/webUIUserKeysType/userKeys.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36026 Updating egulias/email-validator (2.1.10 => 2.1.11)
  composer.lock
Labels: 4 - To release, dependencies, release:10.3.0

#35998 Restrict deletion of share_folder by user
  lib/private/Files/View.php
  tests/lib/Files/ViewTest.php
Labels: 3 - To Review

#36003 Don't send WWW-Authenticate headers with schema Basic for ajax requests
  apps/dav/lib/Connector/Sabre/Auth.php
  apps/dav/tests/unit/Connector/Sabre/AuthTest.php
Labels: 4 - To release, release:10.3.0

#36033 Update the minimum required Node engine version to 8.15.0
  build/package.json
Labels: bug, dependencies, p3-medium

#36031 Respect default app config within the TwoFactorChallendeController
  core/Controller/TwoFactorChallengeController.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
Labels: 3 - To Review, release:10.3.0

#36036 Updating sabre/xml (2.1.2 => 2.1.3)
  composer.lock
Labels: 4 - To release, dependencies, php, release:10.3.0

#36032 Check status on given steps in Comments and WebDav acceptance test code
  tests/acceptance/features/apiMain/quota.feature
  tests/acceptance/features/bootstrap/CommentsContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36039 Make separate 'given' steps in AppManagementContext Auth BasicStructure
  tests/acceptance/features/bootstrap/AppManagementContext.php
  tests/acceptance/features/bootstrap/Auth.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/OCSContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36042 Be flexible about HTTP status code for new chunking uploads
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36013 changelog for 10.3 alpha
  CHANGELOG.md
Labels: 3 - To Review

#36040 run litmus tests on new public webdav endpoint
  .drone.yml
  pipeline.libsonnet
Labels: 4 - To release, QA-team

#36041 rename steps to be 'old' public webdav API
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareOperations/changingFilesShare.feature
  tests/acceptance/features/apiShareOperations/downloadFromShare.feature
  tests/acceptance/features/apiShareOperations/uploadToShare.feature
  tests/acceptance/features/apiShareReshare/reShareAsPublicLink.feature
  tests/acceptance/features/apiShareUpdate/updateShare.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks2/resharedShares.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: 4 - To release, Acceptance tests, QA-team

#36046 Fix public download step text
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36007 Document phoenix.baseUrl in config.sample.php
  config/config.sample.php
Labels: 3 - To Review

#36049 fix file creation with content in public webdav api
  apps/dav/lib/Files/PublicFiles/PublicSharedRootNode.php
Labels: 3 - To Review

#36053 ETag has to be surrounded by double quotes
  apps/dav/lib/Files/PublicFiles/SharedNodeTrait.php
  apps/dav/lib/Meta/MetaFile.php
  apps/dav/lib/TrashBin/AbstractTrashBinNode.php
  apps/dav/tests/unit/Files/PublicFiles/PublicFileTest.php
  apps/dav/tests/unit/Meta/MetaFileTest.php
  apps/dav/tests/unit/TrashBin/TrashBinFileTest.php
  apps/dav/tests/unit/TrashBin/TrashBinFolderTest.php
Labels: 3 - To Review

#36012 reverse proxy
  .drone.jsonnet
  .drone.yml
  pipeline.libsonnet
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36057 Handle error scenario in File::putContent
  apps/dav/lib/Files/PublicFiles/PublicSharedRootNode.php
  lib/private/Files/Node/File.php
Labels: 3 - To Review

#36058 Sharing tests scenario fixes
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiShareOperations/changingFilesShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/cliMain/transfer-ownership.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36021 Don't list files on file drop folders + rename existing files when up…
  apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
  apps/dav/lib/Files/PublicFiles/PublicSharedRootNode.php
  apps/dav/lib/Files/PublicFiles/RootCollection.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/PublicFiles/PublicFilesPluginTest.php
Labels: 3 - To Review

#36059 Handle quota scenario on public-files
  apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/PublicFiles/PublicFilesPluginTest.php
Labels: 3 - To Review

#36054 Do not rely on include path
  lib/private/legacy/app.php
Labels: 3 - To Review

#36051 all results that work in the old public link webDAV API should also work in the new one
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareOperations/changingFilesShare.feature
  tests/acceptance/features/apiShareOperations/downloadFromShare.feature
  tests/acceptance/features/apiShareOperations/uploadToShare.feature
  tests/acceptance/features/apiShareReshare/reShareAsPublicLink.feature
  tests/acceptance/features/apiShareUpdate/updateShare.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks2/resharedShares.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/cliMain/transfer-ownership.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36024 Roles API + allow setting permissions via share attribues
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  core/Application.php
  core/Controller/RolesController.php
  core/routes.php
  lib/public/Roles/AddRolesEvent.php
  tests/Core/Controller/RolesControllerTest.php
Labels: 3 - To Review

#36029 Mountpoint collision
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/SharedMount.php
  apps/files_sharing/tests/ShareTest.php
  apps/files_sharing/tests/TestCase.php
  lib/private/Files/Config/MountProviderCollection.php
  lib/private/Files/Mount/Manager.php
  tests/acceptance/features/apiFederation/federated.feature
Labels: 3 - To Review

#36077 test downloading file from upload-only folder
  tests/acceptance/features/apiShareOperations/downloadFromShare.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36068 Fixes #36067 - start rename index with 2
  apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
  tests/acceptance/features/apiShareOperations/uploadToShare.feature
Labels: 4 - To release

#36081 test download single file public links with new webdav API
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareUpdate/updateShare.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36085 test uploading to a single-file public link
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36074 delete duplication in acceptance test-code
  tests/acceptance/features/apiShareOperations/downloadFromShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36066 Handle no longer existing resource of a link share
  apps/dav/lib/Files/PublicFiles/PublicSharedRootNode.php
  apps/dav/tests/unit/Files/PublicFiles/PublicSharedRootNodeTest.php
  tests/acceptance/features/apiShareOperations/downloadFromShare.feature
Labels: 3 - To Review

#36089 refactor remaining tests steps to be able to use also new public webdav API
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36088 Add downloadPublicFileWithPassword step
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36063 add ocs api for public link share email notification
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/lib/Controller/NotificationController.php
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/Controller/NotificationControllerTest.php
  core/ajax/share.php
  core/js/sharedialogmailview.js
  core/js/tests/specs/sharedialogmailviewSpec.js
  lib/private/Share/Filters/MailNotificationFilter.php
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 3 - To Review

#36087 upload to public links tests with different permissions
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36102 Updating zendframework/zend-filter (2.9.1 => 2.9.2)
  composer.lock
Labels: 4 - To release, dependencies, php, release:10.3.0

#36103 Updating webmozart/assert (1.4.0 => 1.5.0)
  composer.lock
Labels: 4 - To release, dependencies, php

#36047 run federated tests on 10.2.1 tarball
  .drone.jsonnet
  .drone.yml
  pipeline.libsonnet
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36110 if a log-entry does not contain an attribute mark it at not-matching
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36112 Updating zendframework/zend-inputfilter (2.10.0 => 2.10.1)
  composer.lock
Labels: 4 - To release, dependencies, php, release:10.3.0

#36080 PublicFiles: Quote ETag in headers as well
  apps/dav/lib/Files/PublicFiles/PublicSharedRootNode.php
  apps/dav/lib/Files/PublicFiles/SharedFolder.php
Labels: 3 - To Review, QA-team

#36079 IE doesn't redirect to login page when user is not logged in
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
Labels: 3 - To Review, blue-ticket, p2-high

#36073 Fix single trashbin item deletion via DAV endpoint
  apps/dav/lib/TrashBin/TrashBinManager.php
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: 3 - To Review, backport-request

#35888 Session fixes
  config/config.sample.php
  lib/base.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  lib/private/Authentication/Token/DefaultTokenProvider.php
  lib/private/User/Session.php
  settings/Panels/Admin/Certificates.php
  tests/lib/Authentication/Token/DefaultTokenProviderTest.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#36061 Add proper ACLs on PublicSharedRootNode
  apps/dav/lib/Connector/Sabre/DavAclPlugin.php
  apps/dav/lib/Files/PublicFiles/PublicSharedRootNode.php
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareOperations/changingFilesShare.feature
  tests/acceptance/features/apiShareOperations/uploadToShare.feature
  tests/acceptance/features/apiShareUpdate/updateShare.feature
Labels: 3 - To Review

#36116 check Etag in header of file-operation responses
  tests/acceptance/features/apiShareOperations/uploadToShare.feature
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/apiWebdavMove/moveFile.feature
  tests/acceptance/features/apiWebdavUpload/uploadFile.feature
  tests/acceptance/features/apiWebdavUpload/uploadFileUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload/uploadFileUsingOldChunking.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36122 Revert "Move user creation to a separate service"
  apps/provisioning_api/appinfo/routes.php
  apps/provisioning_api/lib/Users.php
  apps/provisioning_api/tests/UsersTest.php
  core/Application.php
  core/Command/User/Add.php
  core/Controller/UserController.php
  core/css/setpassword.css
  core/js/setpassword.js
  core/register_command.php
  core/routes.php
  core/templates/new_user/email-html.php
  core/templates/new_user/email-plain_text.php
  core/templates/new_user/resendtokenbymail.php
  core/templates/new_user/setpassword.php
  core/templates/new_user/tokensendnotify.php
  lib/private/User/Service/CreateUserService.php
  lib/private/User/Service/PasswordGeneratorService.php
  lib/private/User/Service/UserSendMailService.php
  lib/public/User/Exceptions/CannotCreateUserException.php
  lib/public/User/Exceptions/EmailSendFailedException.php
  lib/public/User/Exceptions/InvalidEmailException.php
  lib/public/User/Exceptions/InvalidUserTokenException.php
  lib/public/User/Exceptions/UserAlreadyExistsException.php
  lib/public/User/Exceptions/UserTokenException.php
  lib/public/User/Exceptions/UserTokenExpiredException.php
  lib/public/User/Exceptions/UserTokenMismatchException.php
  tests/Core/Command/User/AddTest.php
  tests/Core/Controller/UserControllerTest.php
  tests/lib/User/Service/CreateUserServiceTest.php
  tests/lib/User/Service/PasswordGeneratorServiceTest.php
  tests/lib/User/Service/UserSendMailServiceTest.php
Labels: 3 - To Review

#36120 only share owner and sharer update or delete share
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  tests/acceptance/features/apiShareManagementBasic/deleteShare.feature
Labels: 4 - To release, release:10.3.0

#36119 Block listing children of upload-only folder on GET request
  apps/dav/lib/Files/PublicFiles/PublicSharedRootNode.php
  apps/dav/tests/unit/Files/PublicFiles/PublicSharedRootNodeTest.php
  tests/acceptance/features/apiShareOperations/downloadFromShare.feature
Labels: 3 - To Review, sev2-high
