Repository owncloud/core, pull requests merged in 2019-02, with the labels that each got.

#34297 Use loadFromFile instead of loadFromFileHandle
  lib/private/Preview/Image.php
Labels: 2 - Developing, backport-request

#34351 Prevent LOCK/UNLOCK methods from public endpoint
  apps/dav/lib/Files/FileLocksBackend.php
  apps/dav/tests/unit/Files/FileLocksBackendTest.php
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks/resharedShares.feature
  tests/acceptance/features/apiWebdavLocks/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks/unlock.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
Labels: 3 - To Review, backport-request

#34352 tests to check webdav requests with locktoken in header
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34355 [stable10] Prevent LOCK/UNLOCK methods from public endpoint
  apps/dav/lib/Files/FileLocksBackend.php
  apps/dav/tests/unit/Files/FileLocksBackendTest.php
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks/resharedShares.feature
  tests/acceptance/features/apiWebdavLocks/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks/unlock.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
Labels: 3 - To Review

#34317 Share file with other user and delete shared with users
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34362 [stable10]Test Share file with other user and delete shared with users
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34361 test multiple users having shared locks and using the resource
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34366 Provide convenience test method getPathFromCoreToAppAcceptanceTests
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34370 testing moving file out of locked folder
  tests/acceptance/features/apiWebdavLocks/folder.feature
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34384 [stable10] testing moving file out of locked folder
  tests/acceptance/features/apiWebdavLocks/folder.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34385 [stable10] test multiple users having shared locks and using the resource
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34390 Bump symfony/process symfony/yaml (v3.4.21 => v3.4.22)
  composer.lock
Labels: 4 - To release, dependencies

#34388 Return only creatable part of the shareFolder path
  apps/files_sharing/lib/Helper.php
  apps/files_sharing/tests/HelperTest.php
Labels: 3 - To Review, backport-request

#34158 add before-after share link auth events
  apps/files_sharing/lib/Controllers/ShareController.php
  apps/files_sharing/tests/Controllers/ShareControllerTest.php
Labels: 3 - To Review

#34262 Reorder query parts and do not reuse query builder instance
  apps/federatedfilesharing/lib/FederatedShareProvider.php
Labels: 3 - To Review, backport-request

#34400 [Stable10]Skip tests that are not supposed to work in encryption
  tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34097 [Stable10] Fix cancel upload and hide 'uploading' message for files_drop shared folders
  apps/files_sharing/js/PublicUploadView.js
  tests/acceptance/features/lib/PublicLinkFilesPage.php
  tests/acceptance/features/webUIUpload/upload.feature
Labels: 4 - To release

#34206 [stable10] Auto accept incoming federated shares from trusted servers
  apps/federatedfilesharing/js/settings-admin.js
  apps/federatedfilesharing/lib/AdminPanel.php
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/templates/settings-admin.php
  apps/federatedfilesharing/tests/AdminPanelTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/federation/lib/AppInfo/Application.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: 4 - To release

#34401 [Stable10] Reorder query parts and do not reuse query builder instance
  apps/federatedfilesharing/lib/FederatedShareProvider.php
Labels: 4 - To release

#34398 make sure there are not more groups in the result than expected
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
Labels: 3 - To Review, QA-team, backport-request, dev:acceptance-tests

#34356 [stable10] Backport of Use loadFromFile instead of loadFromFileHandle
  lib/private/Preview/Image.php
Labels: 4 - To release

#34061 [stable10] Set permissions on log file creation instead of every write.
  lib/private/Log/Owncloud.php
Labels: 4 - To release

#34168 [stable10] Fix visual checkbox issue
  apps/files_external/templates/settings.php
Labels: 4 - To release

#34116 [stable10] Backpot of Fix visibility of static tags in the tags page
  apps/systemtags/js/systemtagsfilelist.js
  apps/systemtags/tests/js/systemtagsfilelistSpec.js
Labels: 4 - To release

#34089 [stable10] Always set headers
  .htaccess
Labels: 4 - To release

#34082 [stable10] Backport of Add regex for shared object file names
  lib/private/Files/Type/Detection.php
  resources/config/mimetypemapping.dist.json
  tests/lib/Files/Type/DetectionTest.php
Labels: 4 - To release

#34057 [stable10] Center the logo and login fields
  core/css/styles.css
Labels: 4 - To release

#34056 [stable10] log broken smb config params
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 4 - To release

#34055 [stable10] write Login failed entry and emit event for per PasswordLo…
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 4 - To release

#34154 Fix reset confirmation mail from occ stable10
  core/Command/User/ResetPassword.php
  tests/Core/Command/User/ResetPasswordTest.php
  tests/acceptance/features/cliProvisioning/resetUserPassword.feature
Labels: 4 - To release

#34395 [Stable10] Return only creatable part of the shareFolder path
  apps/files_sharing/lib/Helper.php
  apps/files_sharing/tests/HelperTest.php
Labels: 3 - To Review

#34403 [stable10] Bump README.md doc links to 10.1
  README.md
Labels: 3 - To Review, QA-team

#34409 [stable10] make sure there are not more groups in the result than expected
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34280 [stable10] Backport of Increase size of login_name from 64 to 255
  core/Migrations/Version20190125162909.php
Labels: 4 - To release, release note

#34255 [stable10] Backport of Fixing email sent to recipient using recipient…
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 4 - To release

#34412 [stable10] bump remaining symfony 3.4.22 components
  composer.lock
Labels: 3 - To Review, dependencies

#34043 [stable10] Bump paragonie/random_compat v2.0.17 => v2.0.18
  composer.lock
Labels: 4 - To release, dependencies

#34413 [stable10] zendframework bumps 20190208
  composer.lock
Labels: 4 - To release, dependencies

#34414 Bump pear/console_getopt (v1.4.1 => v1.4.2)
  composer.lock
Labels: 4 - To release, backport-request, dependencies

#34416 [stable10] bump react promise v2.7.1
  composer.lock
Labels: 4 - To release, dependencies

#34415 [stable10] Bump pear/console_getopt (v1.4.1 => v1.4.2)
  composer.lock
Labels: 4 - To release, dependencies

#34417 [stable10] bump league flysystem 1.0.50
  composer.lock
Labels: 4 - To release, dependencies

#34418 [stable10] remove composer that is now in vendor bin
  composer.lock
Labels: 4 - To release, QA-team, dependencies, dev:acceptance-tests

#34402 Bump README.md doc links to 10.1
  README.md
Labels: 3 - To Review, QA-team

#34422 Skip failing test on encryption
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34321 Send OCM requests as JSON
  apps/federatedfilesharing/lib/Notifications.php
  apps/federatedfilesharing/tests/NotificationsTest.php
Labels: 3 - To Review, backport-request

#34423 [stable10] Skip failing test on encryption
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34424 [stable10] Send OCM requests as JSON
  apps/federatedfilesharing/lib/Notifications.php
  apps/federatedfilesharing/tests/NotificationsTest.php
Labels: 4 - To release

#34420 Expand test scenarios for emojis and Unicode in comments
  tests/acceptance/features/apiComments/deleteComments.feature
  tests/acceptance/features/apiComments/editComments.feature
  tests/acceptance/features/apiWebdavProperties/createFolder.feature
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/lib/OwncloudPage.php
  tests/acceptance/features/webUIComments/comments.feature
  tests/acceptance/features/webUICreateDelete/createFolders.feature
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34436 Revert "[stable10] Bump karma-jasmine from 1.1.2 to 2.0.1 in /build"
  build/package.json
  build/yarn.lock
Labels: 3 - To Review, p1-urgent

#34431 Revert "Bump @bower_components/bowser from 1.6.0 to 2.1.0 in /build"
  build/package.json
  build/yarn.lock
Labels: p1-urgent

#34438 [stable10] Update changelog post 10.1
  CHANGELOG.md
Labels: 3 - To Review

#32230 throw exception when .htaccess file is not writable
  lib/private/Setup.php
  tests/lib/SetupTest.php
Labels: 3 - To Review, backport-request, bug, comp:console-occ

#34427 [stable10] Refactor infoparser
  core/Command/App/CheckCode.php
  core/register_command.php
  lib/private/App/AppManager.php
  lib/private/App/CodeChecker/InfoChecker.php
  lib/private/App/InfoParser.php
  lib/private/legacy/app.php
  tests/Core/Command/Apps/CheckCodeTest.php
  tests/data/app/invalid-info2.xml
  tests/lib/App/CodeChecker/InfoCheckerTest.php
  tests/lib/App/InfoParserTest.php
Labels: 3 - To Review

#34439 Repair subshares earlier to avoid errors
  lib/private/Repair.php
Labels: backport-request, blue-ticket, bug

#34430 [stable10] Expand test scenarios for emojis and Unicode in comments
  tests/acceptance/features/apiComments/deleteComments.feature
  tests/acceptance/features/apiComments/editComments.feature
  tests/acceptance/features/apiWebdavProperties/createFolder.feature
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/lib/OwncloudPage.php
  tests/acceptance/features/webUIComments/comments.feature
  tests/acceptance/features/webUICreateDelete/createFolders.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34429 [stable10] test propagation of etags when sharing between federated servers
  tests/acceptance/features/apiFederation/etagPropagation.feature
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34421 test propagation of etags when sharing between federated servers
  tests/acceptance/features/apiFederation/etagPropagation.feature
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34461 [stable10] throw exception when .htaccess file is not writable
  lib/private/Setup.php
  tests/lib/SetupTest.php
Labels: 4 - To release

#34462 [stable10] Repair subshares earlier to avoid errors
  lib/private/Repair.php
Labels: 3 - To Review

#32513 log previous exceptions
  lib/private/Log.php
Labels: 3 - To Review, backport-request, comp:core, enhancement, p3-medium, sev4-low

#32425 Shorten hostname to relative domain name in status.php
  config/config.sample.php
  lib/public/Util.php
  status.php
  tests/lib/UtilTest.php
Labels: enhancement, junior job

#30188 only parse info.xml once
  lib/private/App/AppManager.php
  lib/private/App/CodeChecker/InfoChecker.php
  lib/private/Installer.php
  lib/private/Repair.php
  lib/private/Repair/UpdateOutdatedOcsIds.php
  lib/private/legacy/app.php
  tests/data/app/expected-info.json
  tests/data/app/valid-info.xml
  tests/lib/Repair/UpdateOutdatedOcsIdsTest.php
  tests/lib/legacy/AppTest.php
Labels: 3 - To Review, p3-medium, performance

#34391 The great CORS fix .....
  apps/dav/lib/Connector/Sabre/CorsPlugin.php
  apps/dav/tests/unit/Connector/Sabre/CorsPluginTest.php
  lib/private/AppFramework/Middleware/Security/CORSMiddleware.php
  lib/private/legacy/api.php
  lib/private/legacy/response.php
  ocs/routes.php
  tests/lib/AppFramework/Middleware/Security/CORSMiddlewareTest.php
Labels: 4 - To release, backport-request

#34475 [stable10] log wrapped exceptions
  lib/private/Log.php
Labels: 4 - To release

#34473 [stable10] Backport of Fix the share permissions evaluation
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/API/Share20OCSTest.php
  apps/files_sharing/tests/ApiTest.php
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
Labels: 3 - To Review

#34160 Prevent password removal if it is enforced
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
Labels: 4 - To release, backport-request, bug, p3-medium, sev3-medium

#34250 Fix the share permissions evaluation
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
Labels: 3 - To Review

#34469 [stable10] Switch to shorten hostname in status.php
  config/config.sample.php
  lib/public/Util.php
  status.php
  tests/lib/UtilTest.php
Labels: 3 - To Review

#34470 Add ownCloud motto change password email
  core/Controller/LostController.php
  core/templates/lostpassword/altnotify.php
  core/templates/lostpassword/notify.php
  settings/ChangePassword/Controller.php
  tests/Core/Controller/LostControllerTest.php
Labels: 3 - To Review, backport-request

#29830 Repair step list and execution from occ
  core/Command/Maintenance/Repair.php
  core/register_command.php
  lib/private/Repair.php
  lib/private/Repair/MoveAvatarOutsideHome.php
  tests/Core/Command/Maintenance/RepairTest.php
Labels: 3 - To Review

#34482 [Stable10] only parse info.xml once
  lib/private/App/AppManager.php
  lib/private/App/CodeChecker/InfoChecker.php
  lib/private/Installer.php
  lib/private/Repair.php
  lib/private/Repair/UpdateOutdatedOcsIds.php
  lib/private/legacy/app.php
  tests/data/app/expected-info.json
  tests/data/app/valid-info.xml
  tests/lib/Repair/UpdateOutdatedOcsIdsTest.php
  tests/lib/legacy/AppTest.php
Labels: 3 - To Review

#34477 StorageNotAvailableException needs to be handled otherwise the PROPFI…
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/tests/unit/Connector/Sabre/FilesPluginTest.php
Labels: 3 - To Review, backport-request

#34478 do not fail update or installation when .htaccess file is not writable
  lib/private/Setup.php
  lib/private/Updater.php
Labels: 3 - To Review, backport-request

#34485 [stable10] StorageNotAvailableException needs to be handled otherwise…
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/dav/tests/unit/Connector/Sabre/FilesPluginTest.php
Labels: 3 - To Review

#30981 Add confirm password after new password
  core/css/lostpassword/resetpassword.css
  core/js/lostpassword.js
  core/templates/lostpassword/resetpassword.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/lib/LoginPage.php
  tests/acceptance/features/webUILogin/resetPassword.feature
Labels: 1 - To develop

#34486 [stable10] do not fail update or installation when .htaccess file is not writable
  lib/private/Setup.php
  lib/private/Updater.php
Labels: 4 - To release, QA-team

#31325 run UI tests in drone on Firefox
  .drone.yml
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUIComments/comments.feature
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnEmailAddress.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: 3 - To Review, QA-team, backport-request, dev:acceptance-tests

#34490 Adjust confirm password web UI words and tests
  core/js/lostpassword.js
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/webUILogin/resetPassword.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34494 [stable10] run UI tests in drone on Firefox
  .drone.yml
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUIComments/comments.feature
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnEmailAddress.feature
  tests/acceptance/features/webUIRenameFiles/renameFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFilesInsideProblematicFolderName.feature
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers/shareWithUsers.feature
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34492 [stable10] Add confirm password after new password
  core/css/lostpassword/resetpassword.css
  core/js/lostpassword.js
  core/templates/lostpassword/resetpassword.php
  settings/css/setpassword.css
  settings/js/setpassword.js
  settings/templates/setpassword.php
  settings/tests/js/setpasswordSpec.js
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/lib/LoginPage.php
  tests/acceptance/features/webUILogin/resetPassword.feature
  tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
Labels: 4 - To release

#34501 No need to pin behat to PHP 5.6
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-team, dev:acceptance-tests

#31607 Prefer API over direct config access
  core/Command/Encryption/Enable.php
  tests/Core/Command/Encryption/EnableTest.php
Labels: p4-low, technical debt

#34505 Remove dead code from EnableTest
  tests/Core/Command/Encryption/EnableTest.php
Labels: 4 - To release

#34503 [stable10] don't wait for AJAX when testing invalid quota strings
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UsersPage.php
  tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34504 [stable10] Backport of Prefer API over direct config access
  core/Command/Encryption/Enable.php
  tests/Core/Command/Encryption/EnableTest.php
Labels: 3 - To Review

#34506 [stable10] Backport of Skip shared files when adding recovery key
  apps/encryption/lib/Recovery.php
  apps/encryption/tests/RecoveryTest.php
Labels: 4 - To release

#34507 skip webdav locking tests on 10.0
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/folder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks/resharedShares.feature
  tests/acceptance/features/apiWebdavLocks/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks/unlock.feature
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34497 [stable10] Prevent password removal if it is enfoced
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
Labels: bug, p3-medium, sev3-medium

#31800 Use the displayname in lost password emails where possible
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: 3 - To Review, enhancement

#34508 [stable10] skip webdav locking tests on 10.0
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/folder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks/resharedShares.feature
  tests/acceptance/features/apiWebdavLocks/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks/unlock.feature
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34467 Store quota overrides in preferences table
  lib/private/User/User.php
Labels: 3 - To Review

#34512 [stable10] Backport of Use the displayname in lost password emails where possible
  core/Controller/LostController.php
  tests/Core/Controller/LostControllerTest.php
Labels: 4 - To release

#34511 Store quota overrides in preferences table
  lib/private/User/User.php
Labels: 3 - To Review

#34480 Happy new year for status.php Copyright
  status.php
Labels: 3 - To Review

#33732 Test create share
  tests/acceptance/features/apiShareManagement/createShare.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34513 [stable10] Acceptance tests for a user who is excluded from sharing
  tests/acceptance/features/apiShareManagement/createShare.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34516 Skip test scenarios for user_ldap-issue-378
  tests/acceptance/features/apiShareManagement/createShare.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34515 [stable10] Skip test scenarios for user_ldap-issue-378
  tests/acceptance/features/apiShareManagement/createShare.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34518 [Stable10] transfer ownership should only be run with cli tests
  tests/acceptance/config/behat.yml
  tests/acceptance/features/cliMain/transfer-ownership.feature
Labels: 4 - To release, QA

#34517 transfer ownership should only be run with cli tests
  tests/acceptance/config/behat.yml
  tests/acceptance/features/cliMain/transfer-ownership.feature
Labels: 4 - To release, QA-team

#34520 wait for Ajax call when opening a file or folder
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34523 [stable10] wait for Ajax call when opening a file or folder
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34521 disable previews on fed server for tests tagged @disablePreviews
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/CommandLine.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34476 [stable10] The great CORS fix ..
  apps/dav/lib/Connector/Sabre/CorsPlugin.php
  apps/dav/tests/unit/Connector/Sabre/CorsPluginTest.php
  lib/private/AppFramework/Middleware/Security/CORSMiddleware.php
  lib/private/legacy/api.php
  lib/private/legacy/response.php
  ocs/routes.php
  tests/lib/AppFramework/Middleware/Security/CORSMiddlewareTest.php
Labels: 3 - To Review

#34525 [stable10] disable previews on fed server for tests tagged @disablePreviews
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/CommandLine.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34529 [stable10] improve waiting creating of shares
  tests/acceptance/features/apiShareManagement/mergeShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34528 improve waiting creating of shares
  tests/acceptance/features/apiShareManagement/mergeShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34527 [stable10] Backport of Integrate HSM changes to encryption
  apps/encryption/appinfo/info.xml
  apps/encryption/lib/AppInfo/Application.php
  apps/encryption/lib/Command/HSMDaemon.php
  apps/encryption/lib/Crypto/Crypt.php
  apps/encryption/lib/Crypto/CryptHSM.php
  apps/encryption/lib/Hooks/UserHooks.php
  apps/encryption/lib/JWT.php
  apps/encryption/lib/KeyManager.php
  apps/encryption/lib/Recovery.php
  apps/encryption/lib/Users/Setup.php
  apps/encryption/tests/Command/HSMDaemonTest.php
  apps/encryption/tests/Crypto/CryptHSMTest.php
  apps/encryption/tests/JWTTest.php
Labels: 4 - To release

#34283 Fixup preview issues with trashbin/versions
  apps/files_trashbin/ajax/preview.php
  apps/files_trashbin/lib/Trashbin.php
  apps/files_versions/lib/AppInfo/Application.php
  apps/files_versions/lib/FileHelper.php
  apps/files_versions/lib/Storage.php
  apps/files_versions/tests/FileHelperTest.php
  lib/private/Preview.php
  tests/lib/PreviewTest.php
Labels: 3 - To Review, backport-request

#34532 [stable10] Skip acceptance test scenarios in various cases
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUILogin/resetPassword.feature
  tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34531 Skip acceptance test scenarios in various cases
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUILogin/resetPassword.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34533 [stable10] Fixup preview issues with trashbin/versions
  apps/files_trashbin/ajax/preview.php
  apps/files_trashbin/lib/Trashbin.php
  apps/files_versions/lib/AppInfo/Application.php
  apps/files_versions/lib/FileHelper.php
  apps/files_versions/lib/Storage.php
  apps/files_versions/tests/FileHelperTest.php
  lib/private/Preview.php
  tests/lib/PreviewTest.php
Labels: 3 - To Review

#32623 Log exception when background job class not found
  lib/private/BackgroundJob/JobList.php
  lib/private/Server.php
  lib/private/legacy/app.php
  tests/lib/BackgroundJob/JobListTest.php
Labels: 4 - To release, backport-request

#34535 [stable10] Update changelog after the latest cleanup action
  CHANGELOG.md
Labels: 4 - To release

#34033 Improve code occ files_external:list --short
  apps/files_external/lib/Command/ListCommand.php
  apps/files_external/tests/Command/ListCommandTest.php
Labels: 3 - To Review, backport-request, enhancement

#33520 stop excessive copying of user ids and object references
  lib/private/User/SyncService.php
  tests/lib/User/SyncServiceTest.php
Labels: 3 - To Review, app:user_ldap, backport-request, bug

#34548 fix composer warnings
  Makefile
  composer.json
Labels: 3 - To Review, backport-request

#34549 [stable10] Improve code occ files_external:list --short
  apps/files_external/lib/Command/ListCommand.php
  apps/files_external/tests/Command/ListCommandTest.php
Labels: 4 - To release, enhancement

#34550 [stable10] fix composer warnings
  Makefile
  composer.json
Labels: 4 - To release

#34551 add acceptance test step theHTTPStatusCodeShouldBeOr
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34552 [stable10] add acceptance test step theHTTPStatusCodeShouldBeOr
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34546 [stable10] stop excessive copying of user ids and object references
  lib/private/User/SyncService.php
  tests/lib/User/SyncServiceTest.php
Labels: 3 - To Review

#34263 Move log level to debug for missing local and distributed Memcache ov…
  lib/private/Memcache/Factory.php
Labels: 3 - To Review, backport-request

#34489 Infinite loop in stream_read() for invalid/corrupt chunks
  apps/dav/lib/Upload/AssemblyStream.php
Labels: 4 - To release, backport-request

#34556 [stable10] cronjob is not changeable in the docker containers
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
Labels: 4 - To release

#34468 [CalDAV] In case of a cancel message the status has to be set inside …
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: 4 - To release, backport-request

#34547 Fix static tags filtering in the backend
  apps/dav/lib/SystemTag/SystemTagsByIdCollection.php
  apps/dav/tests/unit/SystemTag/SystemTagsByIdCollectionTest.php
Labels: 4 - To release

#34557 [stable10] Backport of Fix static tags filtering in the backend
  apps/dav/lib/SystemTag/SystemTagsByIdCollection.php
  apps/dav/tests/unit/SystemTag/SystemTagsByIdCollectionTest.php
Labels: 3 - To Review

#29963 Change the styling of the active settings navigation menu item
  core/css/apps.css
  settings/templates/settingsPage.php
Labels: 3 - To Review, backport-request

#34553 [stable10] Use sabre/vobject ^4.2 to fix issues in ITip messages
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  composer.json
  composer.lock
Labels: 3 - To Review

#34564 Update sabre/vobject (4.2.0-alpha1 => 4.2.0)
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  composer.lock
Labels: 3 - To Review, dependencies

#34426 [stable10] fixes issue file picker choose button disabled for directory selectiom
  core/js/oc-dialogs.js
Labels: 3 - To Review

#34561 [stable10] Change the styling of the active settings navigation menu item
  core/css/apps.css
  settings/templates/settingsPage.php
Labels: 3 - To Review

#34558 [stable10] Throw exception in stream_read() if attempting to read the same node multiple times
  apps/dav/lib/Upload/AssemblyStream.php
Labels: 3 - To Review

#34570 [stable10] do not trim content of downloaded file in acceptance tests
  tests/acceptance/features/bootstrap/OccContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34560 [stable10] [CalDAV] In case of a cancel message the status has to be …
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
  apps/dav/tests/unit/CalDAV/Schedule/IMipPluginTest.php
Labels: 4 - To release

#34554 set the skeletondirectory by using the testing app
  tests/TestHelpers/Asserts/WebDav.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34573 [stable10] set the skeletondirectory by using the testing app
  tests/TestHelpers/Asserts/WebDav.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34574 fix use statements
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34555 cronjob is not changeable in the docker containers
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
Labels: 4 - To release

#34577 Check the HTTP status of federated share test uploads
  tests/acceptance/features/apiFederation/etagPropagation.feature
  tests/acceptance/features/apiFederation/federated.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34578 [stable10] Check the HTTP status of federated share test uploads
  tests/acceptance/features/apiFederation/etagPropagation.feature
  tests/acceptance/features/apiFederation/federated.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34579 move reading skeleton file in tests to own helper
  tests/TestHelpers/Asserts/WebDav.php
  tests/TestHelpers/SetupHelper.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34580 [stable10] move reading skeleton file in tests to own helper
  tests/TestHelpers/Asserts/WebDav.php
  tests/TestHelpers/SetupHelper.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34582 Throw exception in getOCSResponseStatusCode if responseXml has no OCS status
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34583 [stable10] Throw exception in getOCSResponseStatusCode if responseXml has no OCS status
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#33936 Improve speed accessing all apps by caching result of integrity check
  lib/private/IntegrityCheck/Checker.php
  lib/private/legacy/app.php
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: backport-request

#34585 [stable10] make usage of admin auth tokens public
  tests/acceptance/features/bootstrap/Auth.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34584 [stable10] Backport of Improve speed accessing all apps by caching re…
  lib/private/IntegrityCheck/Checker.php
  lib/private/legacy/app.php
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: 4 - To release
