Repository owncloud/core, pull requests merged in 2019-04, with the labels that each got.

#34933 [stable10] Add a command to poll incoming federated shares for updates
  apps/federatedfilesharing/appinfo/info.xml
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/Command/PollIncomingShares.php
  apps/federatedfilesharing/tests/Command/PollIncomingSharesTest.php
Labels: 3 - To Review

#34934 [stable10] group shares should respect to users auto accept choice
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
Labels: 3 - To Review

#34939 [stable10] read files from skeleton folder by providing absolute path
  .drone.yml
  tests/TestHelpers/SetupHelper.php
Labels: 4 - To release

#34862 allow users to opt-out autocomplete in share dialog
  apps/files_sharing/lib/Controller/PersonalSettingsController.php
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/lib/Panels/Personal/PersonalPanel.php
  apps/files_sharing/templates/settings-personal.php
  apps/files_sharing/tests/API/ShareesTest.php
  apps/files_sharing/tests/Panels/Personal/PersonalPanelTest.php
  tests/acceptance/features/lib/PersonalSharingSettingsPage.php
Labels: 4 - To release, backport-request

#34938 read files from skeleton folder by providing absolute path
  .drone.yml
  tests/TestHelpers/SetupHelper.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34947 [stable10] Update changelost post sprint 25
  CHANGELOG.md
Labels: 3 - To Review

#31483 Directly honour robots.txt if htaccess.RewriteBase
  lib/private/Setup.php
Labels: 3 - To Review

#34949 [stable10] Directly honour robots.txt if htaccess.RewriteBase
  lib/private/Setup.php
Labels: 4 - To release

#33994 View-only dav plugin using IShare attributes
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/DAV/ViewOnlyPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
  apps/files/download.php
  apps/files/js/fileinfomodel.js
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/lib/Hooks.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/ViewOnly.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  apps/files_sharing/tests/HooksTest.php
  apps/files_sharing/tests/MountProviderTest.php
  core/Migrations/Version20181220085457.php
  core/js/sharedialogshareelistview.js
  core/js/shareitemmodel.js
  lib/private/Files/Meta/MetaFileVersionNode.php
  lib/private/Files/Meta/MetaVersionCollection.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  lib/private/Share20/Share.php
  lib/private/Share20/ShareAttributes.php
  lib/private/legacy/files.php
  lib/public/Share/IAttributes.php
  lib/public/Share/IShare.php
  tests/lib/Share20/DefaultShareProviderTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 4 - To release, backport-request, p2-high

#34953 Bump symfony v3.4.23 => v3.4.24
  composer.lock
Labels: 4 - To release, dependencies

#34954 [stable10] Bump symfony v3.4.23 => v3.4.24
  composer.lock
Labels: 4 - To release, QA-team

#34956 [stable10] Pass admin username, password, base URL from readSkeletonFile to runOcc
  tests/TestHelpers/SetupHelper.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34955 Pass admin username, password, base URL from readSkeletonFile to runOcc
  tests/TestHelpers/SetupHelper.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34942 [stable10] allow users to opt-out autocomplete in share dialog
  apps/files_sharing/lib/Controller/PersonalSettingsController.php
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/lib/Panels/Personal/PersonalPanel.php
  apps/files_sharing/templates/settings-personal.php
  apps/files_sharing/tests/API/ShareesTest.php
  apps/files_sharing/tests/Panels/Personal/PersonalPanelTest.php
  tests/acceptance/features/lib/PersonalSharingSettingsPage.php
Labels: 3 - To Review

#34811 Add acceptance tests for files:scan --groups
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/cliMain/files.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34964 [stable10] Add acceptance tests for files:scan --groups
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/cliMain/files.feature
Labels: 4 - To release, QA-team

#34966 [stable10] delete newly created core config parameters after scenario
  tests/acceptance/features/bootstrap/AppConfiguration.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34967 delete newly created core config parameters after scenario
  tests/acceptance/features/bootstrap/AppConfiguration.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34965 Type::JSON not supported in current Doctrine
  core/Migrations/Version20181220085457.php
Labels: 4 - To release, p2-high

#34958 Update federatedfilesharing version to 0.4
  apps/federatedfilesharing/appinfo/info.xml
Labels: 3 - To Review

#34959 [stable10] Update federatedfilesharing version to 0.4
  apps/federatedfilesharing/appinfo/info.xml
Labels: 3 - To Review

#34960 Fix public link share, default expiration behavior
  lib/private/Share20/Manager.php
  settings/templates/panels/admin/filesharing.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review, backport-request

#34971 [stable10] Fix public link share default expiration behavior
  lib/private/Share20/Manager.php
  settings/templates/panels/admin/filesharing.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#34951 [stable10] View-only dav plugin using IShare attributes
  apps/dav/lib/Connector/Sabre/ServerFactory.php
  apps/dav/lib/DAV/ViewOnlyPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/DAV/ViewOnlyPluginTest.php
  apps/files/download.php
  apps/files/js/fileinfomodel.js
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/lib/Hooks.php
  apps/files_sharing/lib/MountProvider.php
  apps/files_sharing/lib/ViewOnly.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  apps/files_sharing/tests/HooksTest.php
  apps/files_sharing/tests/MountProviderTest.php
  core/Migrations/Version20181220085457.php
  core/js/sharedialogshareelistview.js
  core/js/shareitemmodel.js
  lib/private/Files/Meta/MetaFileVersionNode.php
  lib/private/Files/Meta/MetaVersionCollection.php
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  lib/private/Share20/Share.php
  lib/private/Share20/ShareAttributes.php
  lib/private/legacy/files.php
  lib/public/Share/IAttributes.php
  lib/public/Share/IShare.php
  tests/lib/Share20/DefaultShareProviderTest.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#34952 Use upsert for subshare updates
  lib/private/Share20/DefaultShareProvider.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 3 - To Review

#34886 [stable10] Improve files error handling
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  apps/files/js/files.js
  apps/files/tests/js/filesSpec.js
Labels: 3 - To Review

#34968 Strict comparison for cookie token
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
Labels: 4 - To release

#34901 [stable10] invitation sender name from master to stable10
  apps/dav/lib/CalDAV/Schedule/IMipPlugin.php
Labels: 4 - To release

#34969 [stable10] extra options to run config setting steps
  tests/acceptance/features/bootstrap/OccContext.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34970 [stable10] delete new config settings after tests
  tests/acceptance/features/bootstrap/AppConfiguration.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34973 extra options to run config setting steps
  tests/acceptance/features/bootstrap/OccContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34769 [stable10] Protect group share concurrent updates with upsert
  lib/private/Share20/DefaultShareProvider.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 3 - To Review

#34974 delete new config settings after tests
  tests/acceptance/features/bootstrap/AppConfiguration.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34687 Renaming and adding new options for public link
  apps/files/js/file-upload.js
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/lib/Controllers/ShareController.php
  apps/files_sharing/templates/public.php
  apps/files_sharing/tests/Controllers/ShareControllerTest.php
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
  tests/TestHelpers/SharingHelper.php
  tests/acceptance/features/apiShareManagement/createShare.feature
  tests/acceptance/features/apiShareOperations/uploadToShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: 3 - To Review

#34978 [stable10] substitute complete dav path in acceptance test steps
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 3 - To Review, QA-team, backport-request, dev:acceptance-tests

#34980 [stable10] Update changelog post sprint 26
  CHANGELOG.md
Labels: 3 - To Review

#34976 phpunit6 enable failOnRisky
  tests/lib/Files/PathVerificationTest.php
  tests/phpunit-autotest-external.xml
  tests/phpunit-autotest.xml
Labels: 4 - To release, dev:phpunit-tests

#34977 [stable10] phpunit6 enable failOnRisky
  apps/encryption/tests/Crypto/EncryptAllTest.php
  apps/encryption/tests/Hooks/UserHooksTest.php
  tests/lib/Files/PathVerificationTest.php
  tests/phpunit-autotest-external.xml
  tests/phpunit-autotest.xml
Labels: 4 - To release, dev:phpunit-tests

#34983 [stable10] Backport of Renaming and adding new options for public link
  apps/files/js/file-upload.js
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/lib/Controllers/ShareController.php
  apps/files_sharing/templates/public.php
  apps/files_sharing/tests/Controllers/ShareControllerTest.php
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
  tests/TestHelpers/SharingHelper.php
  tests/acceptance/features/apiShareManagement/createShare.feature
  tests/acceptance/features/apiShareOperations/uploadToShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: 3 - To Review

#34979 substitute complete dav path in acceptance test steps
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34984 test step to delete tag of own file
  tests/acceptance/features/bootstrap/TagsContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34985 [stable10] test step to delete tag of own file
  tests/acceptance/features/bootstrap/TagsContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#31617 Add background:execute occ command for running cron jobs manually
  core/Command/Background/Queue/Delete.php
  core/Command/Background/Queue/Execute.php
  core/Command/Background/Queue/Status.php
  core/register_command.php
  lib/private/BackgroundJob/Job.php
  lib/private/BackgroundJob/JobList.php
  lib/private/BackgroundJob/TimedJob.php
  lib/private/Log/CommandLogger.php
  tests/Core/Command/Background/Queue/DeleteTest.php
  tests/Core/Command/Background/Queue/ExecuteTest.php
  tests/Core/Command/Background/Queue/StatusTest.php
Labels: 4 - To release, v11

#34783 [stable10] Adding background:queue commands: status and delete
  core/Command/Background/Queue/Delete.php
  core/Command/Background/Queue/Status.php
  core/register_command.php
  db_structure.xml
  lib/private/BackgroundJob/JobList.php
  lib/public/BackgroundJob/IJobList.php
  tests/Core/Command/Background/Queue/DeleteTest.php
  tests/Core/Command/Background/Queue/StatusTest.php
Labels: 3 - To Review, comp:console-occ

#34992 Improve error handling for incoming shares poll command
  apps/federatedfilesharing/lib/Command/PollIncomingShares.php
  apps/federatedfilesharing/tests/Command/PollIncomingSharesTest.php
Labels: 3 - To Review, backport-request

#34995 [stable10] Add background:execute occ command for running cron jobs manually
  core/Command/Background/Queue/Delete.php
  core/Command/Background/Queue/Execute.php
  core/Command/Background/Queue/Status.php
  core/register_command.php
  lib/private/BackgroundJob/Job.php
  lib/private/BackgroundJob/JobList.php
  lib/private/BackgroundJob/TimedJob.php
  lib/private/Log/CommandLogger.php
  tests/Core/Command/Background/Queue/DeleteTest.php
  tests/Core/Command/Background/Queue/ExecuteTest.php
  tests/Core/Command/Background/Queue/StatusTest.php
Labels: 3 - To Review

#34723 [stable10] Log exception when background job class not found
  lib/private/BackgroundJob/JobList.php
  lib/private/Server.php
  lib/private/legacy/app.php
  lib/public/BackgroundJob/IJobList.php
  tests/lib/BackgroundJob/JobListTest.php
Labels: 4 - To release

#34994 Update since tag for listJobs removeById
  lib/public/BackgroundJob/IJobList.php
Labels: 3 - To Review

#34993 [stable10] Improve error handling for incoming shares poll command
  apps/federatedfilesharing/lib/Command/PollIncomingShares.php
  apps/federatedfilesharing/tests/Command/PollIncomingSharesTest.php
Labels: 3 - To Review

#35005 Update changelog for 10.2.0 RC1
  CHANGELOG.md
Labels: 3 - To Review

#35007 Get job id only if sauce environment variables are set
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
Labels: 4 - To release, QA-team, backport-request

#35008 [stable10] Get job id only if sauce environment variables are set
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#35003 vfsstream tokenizer deep-copy dependency bumps
  composer.lock
Labels: 3 - To Review, dependencies

#35004 [stable10] vfsstream tokenizer dependency bumps
  composer.lock
Labels: 3 - To Review, dependencies

#34987 [stable10] fix multi gdrive external storage bug
  apps/files_external/js/gdrive.js
Labels: 3 - To Review

#35000 [stable10] Backport of Add encryption version fix command
  apps/encryption/appinfo/info.xml
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/tests/Command/FixEncryptedVersionTest.php
Labels: 4 - To release

#35013 [stable10] Remove unused use statements in encryption
  apps/encryption/lib/Command/HSMDaemon.php
  apps/encryption/lib/Command/RecreateMasterKey.php
  apps/encryption/lib/Crypto/DecryptAll.php
  apps/encryption/lib/KeyManager.php
  apps/encryption/tests/Command/RecreateMasterKeyTest.php
  apps/encryption/tests/Crypto/DecryptAllTest.php
Labels: 3 - To Review

#35014 [stable10] Apply code style to encryption app files bundled in stable10
  .php_cs.dist
  apps/encryption/appinfo/Migrations/Version20170913113840.php
  apps/encryption/appinfo/routes.php
  apps/encryption/lib/Command/MigrateKeys.php
  apps/encryption/lib/Command/RecreateMasterKey.php
  apps/encryption/lib/Command/SelectEncryptionType.php
  apps/encryption/lib/Controller/RecoveryController.php
  apps/encryption/lib/Controller/SettingsController.php
  apps/encryption/lib/Controller/StatusController.php
  apps/encryption/lib/Crypto/DecryptAll.php
  apps/encryption/lib/Crypto/EncryptAll.php
  apps/encryption/lib/Crypto/Encryption.php
  apps/encryption/lib/Exceptions/MultiKeyDecryptException.php
  apps/encryption/lib/Exceptions/MultiKeyEncryptException.php
  apps/encryption/lib/Exceptions/PrivateKeyMissingException.php
  apps/encryption/lib/Exceptions/PublicKeyMissingException.php
  apps/encryption/lib/HookManager.php
  apps/encryption/lib/Hooks/Contracts/IHook.php
  apps/encryption/lib/Migration.php
  apps/encryption/lib/Panels/Admin.php
  apps/encryption/lib/Panels/Personal.php
  apps/encryption/lib/Session.php
  apps/encryption/lib/Util.php
  apps/encryption/templates/altmail.php
  apps/encryption/templates/settings-admin.php
  apps/encryption/templates/settings-personal.php
  apps/encryption/tests/Command/RecreateMasterKeyTest.php
  apps/encryption/tests/Command/TestEnableMasterKey.php
  apps/encryption/tests/Command/TestEnableUserKey.php
  apps/encryption/tests/Controller/RecoveryControllerTest.php
  apps/encryption/tests/Controller/SettingsControllerTest.php
  apps/encryption/tests/Controller/StatusControllerTest.php
  apps/encryption/tests/Crypto/CryptTest.php
  apps/encryption/tests/Crypto/DecryptAllTest.php
  apps/encryption/tests/Crypto/EncryptAllTest.php
  apps/encryption/tests/Crypto/EncryptionTest.php
  apps/encryption/tests/HookManagerTest.php
  apps/encryption/tests/Hooks/UserHooksTest.php
  apps/encryption/tests/KeyManagerTest.php
  apps/encryption/tests/MigrationTest.php
  apps/encryption/tests/Panels/AdminTest.php
  apps/encryption/tests/Panels/PersonalTest.php
  apps/encryption/tests/RecoveryTest.php
  apps/encryption/tests/SessionTest.php
  apps/encryption/tests/Users/SetupTest.php
  apps/encryption/tests/UtilTest.php
Labels: 3 - To Review

#35015 [stable10] consistent code with the separated encryption app repo
  apps/encryption/appinfo/Migrations/Version20170913113840.php
  apps/encryption/appinfo/app.php
  apps/encryption/appinfo/routes.php
  apps/encryption/css/settings-admin.css
  apps/encryption/lib/AppInfo/Application.php
  apps/encryption/lib/Command/FixEncryptedVersion.php
  apps/encryption/lib/Command/HSMDaemon.php
  apps/encryption/lib/Command/MigrateKeys.php
  apps/encryption/lib/Command/RecreateMasterKey.php
  apps/encryption/lib/Command/SelectEncryptionType.php
  apps/encryption/lib/Controller/RecoveryController.php
  apps/encryption/lib/Controller/SettingsController.php
  apps/encryption/lib/Controller/StatusController.php
  apps/encryption/lib/Crypto/Crypt.php
  apps/encryption/lib/Crypto/CryptHSM.php
  apps/encryption/lib/Crypto/DecryptAll.php
  apps/encryption/lib/Crypto/EncryptAll.php
  apps/encryption/lib/Crypto/Encryption.php
  apps/encryption/lib/Exceptions/MultiKeyDecryptException.php
  apps/encryption/lib/Exceptions/MultiKeyEncryptException.php
  apps/encryption/lib/Exceptions/PrivateKeyMissingException.php
  apps/encryption/lib/Exceptions/PublicKeyMissingException.php
  apps/encryption/lib/HookManager.php
  apps/encryption/lib/Hooks/Contracts/IHook.php
  apps/encryption/lib/Hooks/UserHooks.php
  apps/encryption/lib/JWT.php
  apps/encryption/lib/KeyManager.php
  apps/encryption/lib/Migration.php
  apps/encryption/lib/Panels/Admin.php
  apps/encryption/lib/Panels/Personal.php
  apps/encryption/lib/Recovery.php
  apps/encryption/lib/Session.php
  apps/encryption/lib/Users/Setup.php
  apps/encryption/lib/Util.php
  apps/encryption/templates/altmail.php
  apps/encryption/templates/mail.php
  apps/encryption/templates/settings-admin.php
  apps/encryption/templates/settings-personal.php
  apps/encryption/tests/Command/RecreateMasterKeyTest.php
  apps/encryption/tests/Command/TestEnableMasterKey.php
  apps/encryption/tests/Command/TestEnableUserKey.php
  apps/encryption/tests/Controller/RecoveryControllerTest.php
  apps/encryption/tests/Controller/SettingsControllerTest.php
  apps/encryption/tests/Controller/StatusControllerTest.php
  apps/encryption/tests/Crypto/CryptTest.php
  apps/encryption/tests/Crypto/DecryptAllTest.php
  apps/encryption/tests/Crypto/EncryptAllTest.php
  apps/encryption/tests/Crypto/EncryptionTest.php
  apps/encryption/tests/HookManagerTest.php
  apps/encryption/tests/Hooks/UserHooksTest.php
  apps/encryption/tests/KeyManagerTest.php
  apps/encryption/tests/MigrationTest.php
  apps/encryption/tests/Panels/AdminTest.php
  apps/encryption/tests/Panels/PersonalTest.php
  apps/encryption/tests/RecoveryTest.php
  apps/encryption/tests/SessionTest.php
  apps/encryption/tests/Users/SetupTest.php
  apps/encryption/tests/UtilTest.php
Labels: 3 - To Review

#35033 Bump symfony (v3.4.24 => v3.4.25)
  composer.lock
Labels: 3 - To Review, dependencies

#35034 [stable10] Bump symfony (v3.4.24 => v3.4.25)
  composer.lock
Labels: 3 - To Review, dependencies

#35036 Point to current installation instructions in README
  README.md
Labels: 4 - To release

#35038 Wrong translation file refererenced for accepting and declining shares
  apps/files_sharing/js/app.js
Labels: 4 - To release

#35037 [stable10] Point to current installation instructions in README
  README.md
Labels: 3 - To Review

#35045 [stable10] Wrong translation file referenced for accept & decline share
  apps/files_sharing/js/app.js
Labels: 4 - To release

#35039 [stable10] Backport of Fixing encrypted version test
  apps/encryption/tests/Command/FixEncryptedVersionTest.php
Labels: 3 - To Review

#35046 Bump symfony (v3.4.25 => v3.4.26)
  composer.lock
Labels: 3 - To Review, dependencies

#35048 [stable10] Bump symfony (v3.4.25 => v3.4.26)
  composer.lock
Labels: 3 - To Review, dependencies

#35041 Get translations from correct app
  apps/federatedfilesharing/js/public.js
  apps/files_sharing/js/app.js
  apps/files_trashbin/js/app.js
  apps/files_trashbin/js/filelist.js
  apps/files_versions/js/versionstabview.js
Labels: 3 - To Review

#35043 [stable10] Get translations from correct app
  apps/federatedfilesharing/js/public.js
  apps/files_sharing/js/app.js
  apps/files_trashbin/js/app.js
  apps/files_trashbin/js/filelist.js
  apps/files_versions/js/versionstabview.js
Labels: 3 - To Review

#35044 Use consistent app name in writeLog() calls
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/files_sharing/lib/Helper.php
  apps/files_sharing/lib/SharedMount.php
  apps/files_trashbin/ajax/delete.php
  apps/files_trashbin/ajax/undelete.php
Labels: 3 - To Review, backport-request

#35049 [stable10] Use consistent app name in writeLog() calls
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/files_sharing/lib/Helper.php
  apps/files_sharing/lib/SharedMount.php
  apps/files_trashbin/ajax/delete.php
  apps/files_trashbin/ajax/undelete.php
Labels: 2 - Developing

#35032 Fix missing progress bar in files drop view
  apps/files_sharing/js/PublicUploadView.js
Labels: backport-request, bug, regression

#35064 [10.2] Point to current installation instructions in README
  README.md
Labels: 3 - To Review

#35059 [10.2.0] Fix missing progress bar in files drop view
  apps/files_sharing/js/PublicUploadView.js
Labels: 4 - To release

#35062 [10.2] Dependency bumps for release 10.2.0
  composer.lock
Labels: 4 - To release, dependencies

#35063 [10.2] Wrong translation file referenced for accept & decline share
  apps/federatedfilesharing/js/public.js
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/files_sharing/js/app.js
  apps/files_sharing/lib/Helper.php
  apps/files_sharing/lib/SharedMount.php
  apps/files_trashbin/ajax/delete.php
  apps/files_trashbin/ajax/undelete.php
  apps/files_trashbin/js/app.js
  apps/files_trashbin/js/filelist.js
  apps/files_versions/js/versionstabview.js
Labels: 4 - To release

#35010 Filter unavailable users and remove unavailable shares on polling
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/Command/PollIncomingShares.php
  apps/federatedfilesharing/tests/Command/PollIncomingSharesTest.php
  apps/files_sharing/lib/External/Manager.php
Labels: 3 - To Review, backport-request

#35060 Remove share permission check from the file upload
  apps/files/js/file-upload.js
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: 3 - To Review

#35082 [10.2.0] Backport of Remove share permission check from the file up…
  apps/files/js/file-upload.js
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: 4 - To release

#35087 change method shareWithUserOrGroup from private to public
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#35090 [stable10]change method shareWithUserOrGroup from private to public
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#35072 Respect 'writable' appdir flag on update
  lib/private/Installer.php
  lib/private/legacy/app.php
  tests/lib/InstallerTest.php
Labels: 4 - To release, backport-request, p2-high

#35073 [10.2.0] Filter unavailable users and remove unavailable shares on polling
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/Command/PollIncomingShares.php
  apps/federatedfilesharing/tests/Command/PollIncomingSharesTest.php
  apps/files_sharing/lib/External/Manager.php
Labels: 4 - To release

#35016 Share attribute required feature
  core/js/sharedialogshareelistview.js
  core/js/shareitemmodel.js
  core/js/tests/specs/sharedialogshareelistview.js
  core/js/tests/specs/shareitemmodelSpec.js
Labels: 3 - To Review, backport-request, p2-high

#35002 OCM Convert providerId/remoteId into string
  apps/federatedfilesharing/appinfo/Migrations/Version20190410160725.php
  apps/federatedfilesharing/appinfo/info.xml
  apps/federatedfilesharing/lib/FedShareManager.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/Notifications.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/federatedfilesharing/tests/appinfo/Migrations/Version20190410160725Test.php
  apps/files_sharing/lib/External/Manager.php
  lib/public/Share/Events/ShareEvent.php
Labels: 3 - To Review

#35101 add new capability privateLinksDetailsParam
  apps/files/lib/Capabilities.php
  apps/files/tests/CapabilitiesTest.php
Labels: 3 - To Review, backport-request

#34998 Limiting the maximum width of .fileName in #app-sidebar
  apps/files/css/detailsView.css
Labels: 3 - To Review, backport-request, blue-ticket

#35097 [10.2.0] Respect 'writable' appdir flag on update
  lib/private/Installer.php
  lib/private/legacy/app.php
  tests/lib/InstallerTest.php
Labels: 4 - To release, p2-high

#35099 Avoid headers set twice in some situations
  .htaccess
Labels: 4 - To release, backport-request

#35120 [Stable10] createUser function changed from private to public
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#35117 createUser function changed from private to public
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, backport-request

#35118 [release-10.2.0] Avoid headers set twice in some situations
  .htaccess
Labels: 3 - To Review

#34803 Fix for File Drop view
  apps/files_sharing/css/public.css
  core/css/styles.css
Labels: 3 - To Review, backport-request

#35122 [stable10] OCM Convert providerId/remoteId into string
  apps/federatedfilesharing/appinfo/Migrations/Version20190410160725.php
  apps/federatedfilesharing/appinfo/info.xml
  apps/federatedfilesharing/lib/FedShareManager.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/Notifications.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/federatedfilesharing/tests/appinfo/Migrations/Version20190410160725Test.php
  apps/files_sharing/appinfo/Migrations/Version20190426123324.php
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/lib/External/Manager.php
  lib/public/Share/Events/ShareEvent.php
Labels: 3 - To Review

#35115 Wait for form to load when following password reset link
  tests/acceptance/features/lib/LoginPage.php
Labels: 3 - To Review, QA-team, backport-request, dev:acceptance-tests

#35123 [stable10] Wait for form to load when following password reset link
  tests/acceptance/features/lib/LoginPage.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#35095 [10.2.0] share attribute required feature
  core/js/sharedialogshareelistview.js
  core/js/shareitemmodel.js
  core/js/tests/specs/sharedialogshareelistview.js
  core/js/tests/specs/shareitemmodelSpec.js
Labels: 3 - To Review
