Repository owncloud/core, pull requests merged in 2019-03, with the labels that each got.

#34647 [stable10] allow user to configure automatically accept incoming shares
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/js/settings-personal.js
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/lib/Controller/PersonalSettingsController.php
  apps/files_sharing/lib/Panels/Personal/PersonalPanel.php
  apps/files_sharing/lib/Panels/Personal/Section.php
  apps/files_sharing/templates/settings-personal.php
  apps/files_sharing/tests/Controller/PersonalSettingsControllerTest.php
  apps/files_sharing/tests/Panels/Personal/PersonalPanelTest.php
  apps/files_sharing/tests/Panels/Personal/SectionTest.php
Labels: 3 - To Review

#34650 test deleting remote shares
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/bootstrap/FederationContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34651 [stable10] test deleting remote shares
  tests/acceptance/features/apiFederation/federated.feature
  tests/acceptance/features/bootstrap/FederationContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34649 [stable10] Update the help links to point to the online documentation
  core/doc/admin/index.html
  core/doc/user/index.html
  settings/templates/help.php
Labels: 4 - To release

#30889 Add per default the apps-external directory in config.php during installation
  Makefile
  apps-external/.gitkeep
  lib/private/Setup.php
Labels: 3 - To Review

#34656 [stable10] Add per default the apps-external directory in config.php during installation
  Makefile
  apps-external/.gitkeep
  lib/private/Setup.php
Labels: 3 - To Review

#34662 Bump symfony v3.4.22 => v3.4.23
  composer.lock
Labels: 3 - To Review, dependencies

#34663 [stable10] Bump symfony v3.4.22 => v3.4.23
  composer.lock
Labels: 3 - To Review, dependencies

#34667 [stable10] Update changelog post sprint 21
  CHANGELOG.md
Labels: 4 - To release

#34676 accept error 500 in failing test run
  tests/acceptance/features/apiFederation/federated.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34677 [stable10] accept error 500 in failing test run
  tests/acceptance/features/apiFederation/federated.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34682 [stable10] test response of files_external ocs endpoint
  tests/acceptance/features/apiMain/external-storage.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34680 test response of files_external ocs endpoint
  tests/acceptance/features/apiMain/external-storage.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34678 Fix unit test of RecreateMasterKey
  apps/encryption/tests/Command/RecreateMasterKeyTest.php
Labels: 4 - To release

#34683 [stable10] test OCS response of pending shares endpoint
  tests/acceptance/features/apiShareManagement/acceptShares.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34681 test OCS response of pending shares endpoint
  tests/acceptance/features/apiShareManagement/acceptShares.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34688 [stable10] Rename openSettingsMenu to openAppSettingsMenu
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UsersPage.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34665 test ocs endpoints with CORS headers
  tests/TestHelpers/OcsApiHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/CorsContext.php
Labels: 3 - To Review, QA-team, backport-request, dev:acceptance-tests

#34693 [stable10] test ocs endpoints with CORS headers
  tests/TestHelpers/OcsApiHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/CorsContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34622 Handle accept decline with invalid share id
  apps/dav/lib/Connector/Sabre/CorsPlugin.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/tests/Controller/RequestHandlerTest.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  lib/public/AppFramework/OCSController.php
  tests/acceptance/features/apiAuth/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuth/ocsGETAuth.feature
  tests/acceptance/features/apiAuth/ocsPOSTAuth.feature
  tests/acceptance/features/apiAuth/ocsPUTAuth.feature
Labels: 4 - To release, backport-request

#34695 [stable10] move OCS related steps to own context
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34694 move OCS related steps to own context
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34697 more tests, testing the CORS headers on OCS routes
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/bootstrap/OCSContext.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34655 allow user to configure automatically accept incoming federated share…
  apps/federatedfilesharing/appinfo/info.xml
  apps/federatedfilesharing/appinfo/routes.php
  apps/federatedfilesharing/css/settings-personal-general.css
  apps/federatedfilesharing/js/settings-personal-general.js
  apps/federatedfilesharing/js/settings-personal-sharing.js
  apps/federatedfilesharing/lib/Controller/SharingPersonalSettingsController.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/Panels/AdminPanel.php
  apps/federatedfilesharing/lib/Panels/GeneralPersonalPanel.php
  apps/federatedfilesharing/lib/Panels/SharingPersonalPanel.php
  apps/federatedfilesharing/templates/settings-personal-general.php
  apps/federatedfilesharing/templates/settings-personal-sharing.php
  apps/federatedfilesharing/tests/Controller/SharingPersonalSettingsControllerTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/federatedfilesharing/tests/Panels/AdminPanelTest.php
  apps/federatedfilesharing/tests/Panels/GeneralPersonalPanelTest.php
  apps/federatedfilesharing/tests/Panels/SharingPersonalPanelTest.php
Labels: 3 - To Review, backport-request

#34685 Adjust log level on drone to 2 (warning)
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34686 [stable10] Adjust log level on drone to 2 (warning)
  .drone.yml
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34654 Each generated birthday or death event gets a new UID
  apps/dav/lib/CalDAV/BirthdayService.php
Labels: 3 - To Review, backport-request

#34703 [stable10] get response from featureContext
  tests/acceptance/features/bootstrap/OCSContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34702 get response from featureContext
  tests/acceptance/features/bootstrap/OCSContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34701 [stable10] Fixes #34653 - each generated birthday or death event gets…
  apps/dav/lib/CalDAV/BirthdayService.php
Labels: 3 - To Review

#34700 Improve Drone caching
  .drone.yml
  .gitignore
  Makefile
Labels: 3 - To Review

#34711 test user-based 'Automatically accept new incoming local user shares' setting
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalSharingSettingsContext.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/lib/PersonalSharingSettingsPage.php
  tests/acceptance/features/lib/SharingSettingsPage.php
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34707 Check for iterable responseXML->data in isUserOrGroupInSharedData
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34712 [stable10] test user-based 'Automatically accept new incoming local user shares'…
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalSharingSettingsContext.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/lib/PersonalSharingSettingsPage.php
  tests/acceptance/features/lib/SharingSettingsPage.php
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34534 Bump stable10 to 10.2.0
  version.php
Labels: 3 - To Review

#34709 [stable10] Check for iterable responseXML->data in isUserOrGroupInSharedData
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34714 [stable10] Add missing insulated disablePreviews tags to settingsMenu.feature
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34715 Add missing insulated disablePreviews tags to webUI feature files
  tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIAdminSettings/helpAndTips.feature
  tests/acceptance/features/webUIComments/comments.feature
  tests/acceptance/features/webUIFiles/versions.feature
  tests/acceptance/features/webUILogin/resetPassword.feature
  tests/acceptance/features/webUILogin/resetPasswordUsingEmail.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnEmailAddress.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnFullName.feature
  tests/acceptance/features/webUIPersonalSettings/changePasswordFromSetting.feature
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34716 [stable10] Add missing insulated disablePreviews tags to webUI feature files
  tests/acceptance/features/webUIAdminSettings/adminAppsSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIAdminSettings/helpAndTips.feature
  tests/acceptance/features/webUIComments/comments.feature
  tests/acceptance/features/webUIFiles/versions.feature
  tests/acceptance/features/webUILogin/resetPassword.feature
  tests/acceptance/features/webUILogin/resetPasswordUsingEmail.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnEmailAddress.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnFullName.feature
  tests/acceptance/features/webUIPersonalSettings/changePasswordFromSetting.feature
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34720 [stable10] Wait for settings menu animation on users page
  tests/acceptance/features/lib/UsersPage.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34721 Remove incompatible script for generating DB changeset
  core/Command/Db/GenerateChangeScript.php
  core/register_command.php
Labels: 4 - To release, backport-request

#34691 [stable10] Dont't expose hashed password in ocs api
  apps/files_sharing/lib/API/Share20OCS.php
  apps/files_sharing/tests/API/Share20OCSTest.php
Labels: 3 - To Review, backport-request

#34722 [stable10] Remove incompatible script for generating DB changeset
  core/Command/Db/GenerateChangeScript.php
  core/register_command.php
Labels: 4 - To release

#34726 [master] Don't expose hashed password in ocs api
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
Labels: 4 - To release

#34725 [stable10] more tests, testing the CORS headers on OCS routes
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/bootstrap/OCSContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34727 Adjust acceptance test files to match stable10
  tests/acceptance/features/apiAuth/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuth/ocsGETAuth.feature
  tests/acceptance/features/apiAuth/ocsPOSTAuth.feature
  tests/acceptance/features/apiAuth/ocsPUTAuth.feature
  tests/acceptance/features/apiWebdavMove/moveFileAsync.feature
  tests/acceptance/features/apiWebdavOperations/deleteFile.feature
  tests/acceptance/features/apiWebdavUpload/uploadFileAsyncUsingNewChunking.feature
  tests/acceptance/features/bootstrap/CommandLine.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/lib/PersonalSecuritySettingsPage.php
  tests/acceptance/features/webUILogin/resetPasswordUsingEmail.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnEmailAddress.feature
  tests/acceptance/features/webUISharingInternalGroups/shareWithGroups.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34729 [stable10] move encryption steps
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/acceptance/features/bootstrap/OccContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34706 [stable10] allow user to configure automatically accept incoming federated share…
  apps/federatedfilesharing/appinfo/info.xml
  apps/federatedfilesharing/appinfo/routes.php
  apps/federatedfilesharing/css/settings-personal-general.css
  apps/federatedfilesharing/js/settings-personal-general.js
  apps/federatedfilesharing/js/settings-personal-sharing.js
  apps/federatedfilesharing/lib/Controller/SharingPersonalSettingsController.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/Panels/AdminPanel.php
  apps/federatedfilesharing/lib/Panels/GeneralPersonalPanel.php
  apps/federatedfilesharing/lib/Panels/SharingPersonalPanel.php
  apps/federatedfilesharing/templates/settings-personal-general.php
  apps/federatedfilesharing/templates/settings-personal-sharing.php
  apps/federatedfilesharing/tests/Controller/SharingPersonalSettingsControllerTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/federatedfilesharing/tests/Panels/AdminPanelTest.php
  apps/federatedfilesharing/tests/Panels/GeneralPersonalPanelTest.php
  apps/federatedfilesharing/tests/Panels/SharingPersonalPanelTest.php
Labels: 3 - To Review

#34724 [stable10] Move log level to debug for missing local and distributed Memcache ov…
  lib/private/Memcache/Factory.php
Labels: 3 - To Review

#34744 Session passing in acceptance tests and other code review issues
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/CorsContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/TransferOwnershipContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/bootstrap/WebUIAdminGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUIHelpAndTipsContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/bootstrap/WebUIWebDavLockingContext.php
  tests/acceptance/features/lib/AdminGeneralSettingsPage.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/lib/FavoritesPage.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageCRUD.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/lib/FilesPageElement/FavoritesFileRow.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/lib/FilesPageElement/LockDialog.php
  tests/acceptance/features/lib/FilesPageElement/LockDialogElement/LockEntry.php
  tests/acceptance/features/lib/FilesPageElement/SharedWithOthersFileRow.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php
  tests/acceptance/features/lib/FilesPageElement/TrashBinFileRow.php
  tests/acceptance/features/lib/LoginPage.php
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/lib/PersonalSecuritySettingsPage.php
  tests/acceptance/features/lib/SharedByLinkPage.php
  tests/acceptance/features/lib/SharedWithOthersPage.php
  tests/acceptance/features/lib/TagsPage.php
  tests/acceptance/features/lib/TrashbinPage.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34713 test user-based auto accepting of federation shares
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIPersonalSharingSettingsContext.php
  tests/acceptance/features/lib/PersonalSharingSettingsPage.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34745 [stable10] session passing in acceptance tests and other code review issues
  tests/acceptance/features/bootstrap/AppConfiguration.php
  tests/acceptance/features/bootstrap/BasicStructure.php
  tests/acceptance/features/bootstrap/CorsContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/TransferOwnershipContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/bootstrap/WebUIAdminGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUIHelpAndTipsContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/bootstrap/WebUIWebDavLockingContext.php
  tests/acceptance/features/lib/AdminGeneralSettingsPage.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/lib/FavoritesPage.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageCRUD.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/lib/FilesPageElement/FavoritesFileRow.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/lib/FilesPageElement/LockDialog.php
  tests/acceptance/features/lib/FilesPageElement/LockDialogElement/LockEntry.php
  tests/acceptance/features/lib/FilesPageElement/SharedWithOthersFileRow.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php
  tests/acceptance/features/lib/FilesPageElement/TrashBinFileRow.php
  tests/acceptance/features/lib/LoginPage.php
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/lib/PersonalSecuritySettingsPage.php
  tests/acceptance/features/lib/SharedByLinkPage.php
  tests/acceptance/features/lib/SharedWithOthersPage.php
  tests/acceptance/features/lib/TagsPage.php
  tests/acceptance/features/lib/TrashbinPage.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34746 [stable10] test user-based auto accepting of federation shares
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIPersonalSharingSettingsContext.php
  tests/acceptance/features/lib/PersonalSharingSettingsPage.php
  tests/acceptance/features/webUISharingExternal/federationSharing.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34608 uniquify drone pipeline steps
  .drone.yml
Labels: 4 - To release, Drone, QA-team, backport-request

#34747 Do not use underscore in drone service names
  .drone.yml
  tests/drone/configs/config.files_external.smb-samba.php
  tests/drone/configs/config.files_external.webdav-apache.php
  tests/drone/test-phpunit.sh
Labels: 4 - To release, Drone, QA-team

#34748 [stable10] Do not use underscore in drone service names
  .drone.yml
  tests/drone/configs/config.files_external.smb-samba.php
  tests/drone/configs/config.files_external.webdav-apache.php
  tests/drone/test-phpunit.sh
Labels: 3 - To Review, Drone, QA-team

#34749 [stable10] uniquify drone pipeline steps
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#34750 [stable10] fix method comment
  apps/federation/lib/Controller/SettingsController.php
Labels: 4 - To release

#34698 [stable10] drop php 5.6 support
  .drone.yml
  .gitignore
  Makefile
  composer.json
  composer.lock
  console.php
  index.php
Labels: 3 - To Review, dependencies

#34752 Update changelog post sprint 22
  CHANGELOG.md
Labels: 3 - To Review

#34755 [stable10] bump dependencies
  build/OCPSinceChecker.php
  composer.json
  composer.lock
  lib/private/App/CodeChecker/CodeChecker.php
  lib/private/Mail/Mailer.php
  tests/lib/Command/AsyncBusTest.php
  tests/lib/Mail/MailerTest.php
  tests/lib/Share/MailNotificationsTest.php
  tests/lib/UtilTest.php
Labels: 3 - To Review, QA-team, dependencies

#34756 [stable10] server container interface should inherit from icontainer,…
  lib/public/IServerContainer.php
Labels: 3 - To Review

#34758 [stable10] First time login was not properly handled by \OC\User\Sess…
  lib/private/User/Session.php
Labels: 4 - To release

#34759 [stable10] Test email verification with international email address - fixes #13586
  tests/lib/Mail/MailerTest.php
Labels: 3 - To Review

#34743 fix method comment
  apps/federation/lib/Controller/SettingsController.php
Labels: 3 - To Review

#34753 Put back files:scan --groups option for backward-compatibility
  apps/files/lib/Command/Scan.php
  apps/files/tests/Command/ScanTest.php
Labels: 3 - To Review, app:files, backport-request, comp:console-occ

#34754 [stable10] files:scan --group and --groups options
  apps/files/lib/Command/Scan.php
  apps/files/tests/Command/ScanTest.php
Labels: 3 - To Review, app:files, comp:console-occ

#34762 [stable10] Implement waitTillPageIsLoaded for UsersPage
  tests/acceptance/features/lib/UsersPage.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34765 [stable10] Catch waitTillXpathIsVisible() in setQuotaOfUserTo()
  tests/acceptance/features/lib/UsersPage.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34766 [stable10] Align acceptance test code with user_management app
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UserPageElement/GroupList.php
  tests/acceptance/features/lib/UsersPage.php
  tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
  tests/acceptance/features/webUIManageUsersGroups/addUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34767 allow to check log entries with regular expressions
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34768 test step for simple public download
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34770 [stable10] Sync encryption app test code to core
  tests/acceptance/features/bootstrap/WebUIAdminEncryptionSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalEncryptionSettingsContext.php
  tests/acceptance/features/lib/AdminEncryptionSettingsPage.php
  tests/acceptance/features/lib/PersonalEncryptionSettingsPage.php
  tests/acceptance/features/webUIEncryptionUserKeysType/userKeys.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34772 [stable10] test step for simple public download
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34771 [stable10] allow to check log entries with regular expressions
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34761 fix occ url when running acceptance tests on build-it server
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34775 [stable10] fix occ url when running acceptance tests on build-it server
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34776 [stable10] wait longer in UsersPage waitTillPageIsLoaded
  tests/acceptance/features/lib/UsersPage.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34774 normalize path when moving chunks to final destination
  apps/dav/lib/Connector/Sabre/Directory.php
Labels: 3 - To Review

#34777 [stable10] normalize path when moving chunks to final destination
  apps/dav/lib/Connector/Sabre/Directory.php
Labels: 3 - To Review

#34659 allow admins to enable medial search on group and user
  config/config.sample.php
  lib/private/Group/Database.php
Labels: 3 - To Review, backport-request

#34779 [stable10] allow admins to enable medial search on group and user
  config/config.sample.php
  lib/private/Group/Database.php
Labels: 3 - To Review

#34788 [master] unit test files_primary_s3 on core - from stable10 31733
  .drone.yml
Labels: 3 - To Review, QA-team

#34790 Tidy variable references in .drone.yml
  .drone.yml
Labels: 3 - To Review, QA-team

#34791 [stable10] Tidy variable references in .drone.yml
  .drone.yml
Labels: 3 - To Review, QA-team

#34792 [stable10] Add drone step to print the server logs in case of failure
  .drone.yml
Labels: 3 - To Review, QA-team

#34793 [stable10] Check for yarn only when needed for selected build rule
  Makefile
Labels: 4 - To release, QA-team

#34794 Adjust yarn nodejs Makefile like stable10 33665
  Makefile
Labels: 4 - To release, QA-team

#34786 [stable10] Backport of #34622 and #33180
  apps/dav/lib/Connector/Sabre/CorsPlugin.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/tests/Controller/RequestHandlerTest.php
  apps/files_sharing/appinfo/routes.php
  apps/files_sharing/lib/API/OCSShareWrapper.php
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/lib/Notifier.php
  apps/files_sharing/tests/ApiTest.php
  apps/files_sharing/tests/AppInfo/ApplicationTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  apps/files_sharing/tests/Service/NotificationPublisherTest.php
  core/ajax/share.php
  core/js/sharedialogshareelistview.js
  core/js/shareitemmodel.js
  core/js/tests/specs/sharedialogshareelistview.js
  lib/private/AppFramework/DependencyInjection/DIContainer.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  lib/private/Share/MailNotifications.php
  lib/private/Share20/DefaultShareProvider.php
  lib/public/AppFramework/OCSController.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 3 - To Review

#34784 [stable10] add composer cleaner
  build/package.json
  build/yarn.lock
  composer.json
  composer.lock
Labels: 3 - To Review, dependencies

#34795 Adjust composer.json order to match more closely with stable10
  composer.json
  composer.lock
Labels: 4 - To release, QA-team

#34796 Fixing node components
  .gitignore
  build/modclean-patterns-owncloud/index.js
  build/modclean-patterns-owncloud/package.json
  build/modclean-patterns-owncloud/patterns.json
  build/package.json
  build/yarn.lock
Labels: 3 - To Review, QA-team

#34804 [stable10] Backport user_management 169
  tests/acceptance/features/lib/UsersPage.php
Labels: 4 - To release, QA-team

#34805 [stable10] remove todo message for sleep
  tests/acceptance/features/lib/UsersPage.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34806 [stable10] Use files:scan --group in acceptance tests to match master
  tests/acceptance/features/bootstrap/OccContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34809 [stable10] Apply code style to tests/data like happened in master
  tests/data/app/code-checker/test-extends.php
  tests/data/app/code-checker/test-implements.php
Labels: 4 - To release, QA-team

#34812 [stable10] don't get default displayName or Email is not requested
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34814 [stable10] Add test case for files:scan --group with commas in the group name
  tests/acceptance/features/cliMain/files.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34808 Remove duplicate ZEND_DONT_UNLOAD_MODULES=1 from test-phpunit.sh
  tests/drone/test-phpunit.sh
Labels: 4 - To release, QA-team

#34810 don't get default displayName or Email is not requested
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34813 Add test case for files:scan --group with commas in the group name
  tests/acceptance/features/cliMain/files.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34798 Fix Webdav error page, include CSP and message
  apps/dav/lib/Files/BrowserErrorPagePlugin.php
  apps/dav/templates/exception.php
Labels: 3 - To Review, backport-request

#34815 do not check empty table fields for their existance in the log file
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34821 [stable10] Update changelog post sprint 23
  CHANGELOG.md
Labels: 4 - To release

#34818 [stable10] do not check empty table fields for their existance in the log file
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34822 Add a template changelog to master branch
  CHANGELOG.md
  Makefile
Labels: 4 - To release

#34819 Sync code for 'add events for user preference changes' 31266 and 31307
  lib/private/AllConfig.php
  tests/lib/AllConfigTest.php
Labels: 4 - To release

#34820 [stable10] Sync code for 'add events for user preference changes' 31266 and 31307
  lib/private/AllConfig.php
  tests/lib/AllConfigTest.php
Labels: 3 - To Review

#34817 [stable10] Fix Webdav error page, include CSP and message
  apps/dav/lib/Files/BrowserErrorPagePlugin.php
  apps/dav/templates/exception.php
Labels: 3 - To Review

#34826 [stable10] travis drop php56
  .travis.yml
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34824 Remove Saucelabs build status badge
  README.md
Labels: 3 - To Review, backport-request

#34827 Sync db_structure.xml with stable10
  db_structure.xml
Labels: 4 - To release

#34823 [stable10] Apply README.md diffs from master
  README.md
Labels: 4 - To release

#34828 [stable10] Happy new year for status.php Copyright
  status.php
Labels: 4 - To release

#34829 [stable10] sync little files with what is in master
  .gitignore
  .mention-bot
  .scrutinizer.yml
Labels: 3 - To Review

#34816 Check the retypepassword exist in the dom before processing
  core/js/lostpassword.js
Labels: 3 - To Review

#34825 Remove lines in .htaccess added by PR 31810
  .htaccess
Labels: 3 - To Review

#34831 [stable10] Update .github/PULL_REQUEST_TEMPLATE.md with latest from master
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 4 - To release

#34830 [stable10] Remove Saucelabs build status badge
  README.md
Labels: 4 - To release

#34832 [stable10] Apply code style to build dir in stable10
  build/OCPSinceChecker.php
  build/gen-coverage-badge.php
  build/license.php
Labels: 4 - To release

#34833 Apply code style to build dir in master
  build/OCPSinceChecker.php
  build/gen-coverage-badge.php
  build/license.php
Labels: 4 - To release

#34834 [stable10] Backport of Check the retypepassword exist in the dom befo…
  core/js/lostpassword.js
Labels: 4 - To release

#34836 [stable10] Fix url for shiels.io
  build/gen-coverage-badge.php
Labels: 3 - To Review

#34837 [stable10] some comment on testing with psql
  build/autotest.sh
Labels: 4 - To release

#34840 [stable10] test step to read the log but ignore some lines
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34839 [stable10] more licenses in license tool
  build/license.php
Labels: 3 - To Review

#34838 test step to read the log but ignore some lines
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34841 Keep build folder ... kills circular-json
  build/modclean-patterns-owncloud/patterns.json
  build/package.json
  build/yarn.lock
Labels: 4 - To release

#34845 Add an acceptance test step form for ignoring the last line of the log file
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34846 [stable10] Add an acceptance test step form for ignoring the last line of the log file
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34847 decode only the first level of JSON from log-files
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34849 [stable10] decode only the first level of JSON from log-files
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34852 Set proper value when upgrading app patch version
  lib/private/legacy/app.php
Labels: 4 - To release

#34859 [stable10] Set proper value when upgrading app patch version
  lib/private/legacy/app.php
Labels: 3 - To Review

#34863 Remove unused use statements from TestHelpers
  tests/TestHelpers/Asserts/WebDav.php
  tests/TestHelpers/Unit/DeleteHelperTest.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34864 [stable10] Remove unused use statements from TestHelpers
  tests/TestHelpers/Asserts/WebDav.php
  tests/TestHelpers/Unit/DeleteHelperTest.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34867 behat step to search the complete logfile for particular lines
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, backport-request, dev:acceptance-tests

#34869 [stable10] cache phpcs results
  Makefile
Labels: 4 - To release, QA-team

#34868 cache phpcs results
  Makefile
Labels: 4 - To release, QA-team

#34875 decode only the first level of JSON from log-files
  tests/acceptance/features/bootstrap/Logging.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34873 [stable10] behat step to search the complete logfile for particular lines
  tests/acceptance/features/bootstrap/Logging.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#34861 Prepare for 10.1.1
  CHANGELOG.md
  version.php
Labels: 3 - To Review

#34878 [10.1.1] Set proper value when upgrading app patch version
  CHANGELOG.md
  lib/private/legacy/app.php
Labels: 3 - To Review, p2-high

#34883 Composer bumps at 20190324
  composer.lock
Labels: 3 - To Review, dependencies

#34882 [stable10] composer bumps at 20190324
  composer.lock
Labels: 3 - To Review, dependencies

#34844 [stable10] Bump @bower_components/bowser from 1.6.0 to 1.9.4 in /build
  build/package.json
  build/yarn.lock
Labels: 3 - To Review, dependencies

#34889 [stable10] substitute ocs path in feature files
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34888 substitute ocs path in feature files
  tests/acceptance/features/bootstrap/BasicStructure.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34893 use array_key_exists and not isset for the case the value is NULL
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#34894 [stable10] use array_key_exists and not isset for the case the value is NULL
  tests/acceptance/features/bootstrap/Logging.php
Labels: 4 - To release, QA-team, dev:acceptance-tests
