Repository owncloud/core, pull requests merged in 2019-09, with the labels that each got.

#36125 Add capability for roles api in files_sharing
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/tests/CapabilitiesTest.php
  core/Controller/RolesController.php
  core/js/sharedialoglinkshareview.js
Labels: 3 - To Review

#36129 Update changelog for 10.3.0alpha2
  CHANGELOG.md
Labels: 3 - To Review

#36138 Bump nikic/php-parser from 4.2.3 to 4.2.4 in changelog
  CHANGELOG.md
Labels: 4 - To release, release:10.3.0

#36140 regenerate .drone.yml
  .drone.yml
Labels: 4 - To release, Drone, QA-team

#36131 Add password enforcement for Download/View/Edit option
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/tests/CapabilitiesTest.php
  core/js/config.php
  core/js/shareconfigmodel.js
  core/js/sharedialoglinkshareview.js
  core/js/tests/specs/sharedialoglinkshareviewSpec.js
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  settings/Panels/Admin/FileSharing.php
  settings/templates/panels/admin/filesharing.php
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
  tests/acceptance/features/webUISharingPublic/shareByPublicLink.feature
  tests/lib/Share20/ManagerTest.php
Labels: 4 - To release

#36153 we can't invalidate the token if there isn't a user session active
  lib/base.php
Labels: 3 - To Review, release:10.3.0

#36154 changelog typo
  CHANGELOG.md
Labels: 4 - To release

#36150 Allow specifying a different PHP version for the federated server in acceptance tests
  .drone.jsonnet
  pipeline.libsonnet
Labels: 4 - To release, Drone, QA-team, dev:acceptance-tests

#36152 fixed typos in 'phoenix.baseUrl' documentation
  config/config.sample.php
Labels: 4 - To release, QA-team

#36158 Dont check the CSRF token on public link email API
  apps/files_sharing/lib/Controller/NotificationController.php
Labels: 3 - To Review

#36124 Disable trashbin and public webdav API by default
  .drone.yml
  apps/dav/lib/Capabilities.php
  apps/dav/lib/RootCollection.php
  apps/dav/lib/Server.php
  config/config.sample.php
  pipeline.libsonnet
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareOperations/changingFilesShare.feature
  tests/acceptance/features/apiShareOperations/downloadFromShare.feature
  tests/acceptance/features/apiShareOperations/uploadToShare.feature
  tests/acceptance/features/apiShareUpdate/updateShare.feature
  tests/acceptance/features/apiTrashbin/trashbinAPIDisabled.feature
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks2/resharedShares.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavOperations/publicWebDAVAPIDisabled.feature
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/cliMain/transfer-ownership.feature
Labels: 4 - To release, p1-urgent

#36084 Add new migrations to dav app
  apps/dav/appinfo/Migrations/Version20190823065724.php
  apps/dav/appinfo/info.xml
  tests/Core/Command/Apps/AppsListTest.php
Labels: 3 - To Review

#36170 Improve share_folder checks in rmdir
  lib/private/Files/View.php
  tests/lib/Files/ViewTest.php
Labels: 3 - To Review

#36038 Fix invalid foreach in SharingBlacklist.php
  apps/files_sharing/lib/SharingBlacklist.php
  apps/files_sharing/tests/SharingBlacklistTest.php
Labels: 3 - To Review

#36161 obey to config in share mail notifications APIs
  apps/files_sharing/lib/Controller/NotificationController.php
  lib/private/Share/MailNotifications.php
  tests/lib/Share/MailNotificationsTest.php
Labels: 3 - To Review

#36127 Remove hardcoded protocol.
  apps/files/ajax/list.php
  apps/files/download.php
  apps/files_sharing/public.php
  apps/files_trashbin/ajax/list.php
  lib/base.php
  lib/private/legacy/api.php
  lib/private/legacy/files.php
  public.php
Labels: technical debt

#36192 Updating sabre/http (5.0.0 => 5.0.2)
  composer.lock
Labels: 3 - To Review, dependencies, php

#36180 Improve logging when a remote host went down suddenly
  lib/private/Files/Storage/DAV.php
Labels: 2 - Developing

#36193 shareowner can edit re-share permissions without any restriction
  apps/files_sharing/tests/EtagPropagationTest.php
  apps/files_sharing/tests/SharedMountTest.php
  lib/private/Server.php
  lib/private/Share20/Manager.php
  tests/acceptance/features/apiShareReshare/reShare.feature
Labels: 3 - To Review

#36189 Bump sabre uri
  composer.lock
Labels: 3 - To Review, dependencies, php

#36197 [Release 10.3.0] Prepare Changelog for RC1
  CHANGELOG.md
Labels: 3 - To Review

#36200 Updating phpseclib/phpseclib (2.0.22 => 2.0.23)
  composer.lock
Labels: 3 - To Review, dependencies, php

#36196 [release-10.3.0] Updating phpseclib/phpseclib (2.0.21 => 2.0.23)
  composer.lock
Labels: 3 - To Review, dependencies, php

#36203 Tool dependency bumps 20190918
  composer.lock
Labels: 3 - To Review, dependencies, php

#36206 Enhance acceptance test runOcc exceptions
  tests/TestHelpers/SetupHelper.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#36207 Make sure to parse only if attributes are json string in reshare
  core/js/shareitemmodel.js
Labels: 3 - To Review, bug, enhancement

#36209 Add coverage-upload to phpunit pipelines which generate coverage
  .drone.yml
  pipeline.libsonnet
Labels: 3 - To Review, Drone, dev:phpunit-tests

#36214 [release-10.3.0] Make sure to parse only if attributes are json string in reshare
  core/js/shareitemmodel.js
Labels: 3 - To Review

#36215 Fix #36114: Update documentation about uploadwriteonly permission
  tests/TestHelpers/SharingHelper.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#36219 Update the CA bundle for 10.3.0 Release
  resources/config/ca-bundle.crt
Labels: 3 - To Review, release:10.3.0

#36218 Added missing item to changelog
  CHANGELOG.md
Labels: 3 - To Review

#36216 [API] user-sync OCS API
  core/Application.php
  core/Command/User/SyncBackend.php
  core/Controller/UserSyncController.php
  core/routes.php
  lib/private/User/SyncService.php
  tests/Core/Controller/UserSyncControllerTest.php
  tests/lib/User/SyncServiceTest.php
Labels: 3 - To Review

#36221 cron.php calls occ system:cron as fallback
  cron.php
Labels: 3 - To Review

#36224 10.3.0 rc changelog
  CHANGELOG.md
Labels: 4 - To release
