Repository owncloud/core, pull requests merged in 2020-12, with the labels that each got.

#38168 [tests-only] Update phpunit/phpunit (8.5.11 => 8.5.12)
  composer.lock
Labels: 3 - To Review, dependencies, php

#38176 [tests-only] Purge cache after sonar analysis
  .drone.star
Labels: 3 - To Review, QA-team

#38161 Allow subfolders for Google Drive mounts
  apps/files_external/lib/Lib/Backend/Google.php
  apps/files_external/lib/Lib/Storage/Google.php
  changelog/unreleased/38161
Labels: 3 - To Review

#38177 [tests-only] TUS tests for upload to moved file
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
Labels: 4 - To release, QA-team

#38178 [tests-only] first low-level tests for the creation extension of the TUS protocol
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelCreationExtension.feature
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: QA-team, dev:acceptance-tests

#38180 [tests-only] relax expected Location regex
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelCreationExtension.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38179 [tests-only] move TUS related test-steps
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA-team, dev:acceptance-tests

#38183 Make the scrollbar on the right darker and wider in favor of beeing more visual present
  changelog/unreleased/38183
  core/css/styles.css
Labels: 3 - To Review

#38185 [tests-only]added tus tests for OPTIONS request
  tests/acceptance/features/apiWebdavUploadTUS/optionsRequest.feature
Labels: QA-team

#38187 [tests-only] change the expectation of TUS OPTIONS tests to match reva behaviour
  tests/acceptance/features/apiWebdavUploadTUS/optionsRequest.feature
Labels: Acceptance tests, QA-team

#38163 Update Symfony components to 4.4.17
  changelog/unreleased/38163
  composer.lock
Labels: dependencies, php

#38147 Fix some of the issues reported by SonarCloud
  changelog/unreleased/38147
  lib/private/Files/Storage/CacheableFlysystem.php
  lib/private/Log/Owncloud.php
  lib/private/Repair/RepairMimeTypes.php
  lib/private/User/AccountMapper.php
  lib/private/User/Manager.php
  lib/public/Share.php
  settings/ajax/togglesubadmins.php
Labels: 3 - To Review

#38188 Update laminas/laminas-servicemanager (3.4.1 => 3.5.1)
  changelog/unreleased/38187
  composer.lock
Labels: 3 - To Review, dependencies, php

#38189 [tests-only] Update phpunit/phpunit (8.5.12 => 8.5.13)
  composer.lock
Labels: 4 - To release, dependencies, php

#38191 Update nikic/php-parser (4.10.2 => 4.10.3)
  changelog/unreleased/38191
  composer.lock
Labels: 3 - To Review, dependencies, php

#38184 [tests-only] low level TUS tests for uploading chunks
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelUpload.feature
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: QA-team, dev:acceptance-tests

#38190 Catch StorageNotAvailableException while formatting the share
  apps/files_sharing/lib/Controller/Share20OcsController.php
  changelog/unreleased/38190
Labels: 3 - To Review

#38192 Remove use of non-existent return value of setDriveFileHelper
  apps/files_external/lib/Lib/Storage/Google.php
  changelog/unreleased/38161
Labels: 3 - To Review

#38198 Update swiftmailer/swiftmailer (v6.2.3 => v6.2.4)
  changelog/unreleased/38198
  composer.lock
Labels: 3 - To Review, dependencies, php

#38199 Rename Phoenix to Web
  changelog/unreleased/38199
  config/config.sample.php
  core/routes.php
  lib/private/NavigationManager.php
Labels: 3 - To Review

#38202 [10.6.0] Rename phoenix.svg to web.svg
  changelog/10.6.0_2020-11-25/38199
  core/img/apps/web.svg
  lib/private/NavigationManager.php
Labels: 3 - To Review

#38201 Rename phoenix.svg to web.svg
  changelog/unreleased/38199
  core/img/apps/web.svg
  lib/private/NavigationManager.php
Labels: 3 - To Review

#38204 [tests-only] Add step to check failing download from inside a public link folder
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38181 Do not redirect if browser asks for a .properties file
  changelog/unreleased/38181
  lib/private/Setup.php
Labels: 3 - To Review

#38209 [tests-only] reword 'switch to the tab' test step
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITags/deleteTags.feature
  tests/acceptance/features/webUITags/editTags.feature
  tests/acceptance/features/webUITags/removeTags.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#38210 [tests-only] Update phar-io/version (3.0.3 => 3.0.4)
  composer.lock
Labels: dependencies, php

#38193 [Tests-Only]TUS upload to non existing folder
  tests/acceptance/features/apiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: 4 - To release, QA-team

#38211 [Tests-Only] Check if versions are created correctly when uploading files withTUS
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
Labels: 3 - To Review, QA-team

#38217 [tests-only] tus test for file with invalid-name
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
Labels: QA-team, in progress

#38225 [tests-only] test trashbin with multi level folders
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
Labels: 3 - To Review, Acceptance tests, QA-team

#38226 [tests-only] small change in tus test for file with invalid-name
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
Labels: QA-team

#38132 Context menu for files in case multiple (default-)actions apply
  .drone.star
  apps/files/css/files.css
  apps/files/js/fileactions.js
  apps/files/js/fileactionsapplicationselectmenu.js
  apps/files/js/fileactionsmenu.js
  apps/files/js/filelist.js
  apps/files/lib/Controller/ViewController.php
  apps/files/tests/js/fileactionsSpec.js
  apps/files/tests/js/fileactionsmenuSpec.js
  apps/files/tests/js/filelistSpec.js
  changelog/unreleased/38132
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIFileActionsMenuContext.php
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/webUIFileActionsMenu/fileActionsMenu.feature
Labels: 3 - To Review

#38233 [Tests-Only] Added tus tests to upload file using resource location URL
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
Labels: QA-team

#38235 [tests-only] skip new fileActionsMenu tests on old oC10 versions
  tests/acceptance/features/webUIFileActionsMenu/fileActionsMenu.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38234 Update Symfony components to 4.4.18
  changelog/unreleased/38234
  composer.lock
Labels: 3 - To Review, dependencies, php

#38237 [tests-only] Add app-required tag to fileActionsMenu.feature
  tests/acceptance/features/webUIFileActionsMenu/fileActionsMenu.feature
Labels: 3 - To Review, QA-team

#38194 [tests-only] added tus tests for creation with upload
  tests/acceptance/features/apiWebdavUploadTUS/creationWithUplaodExtension.feature
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: QA-team

#38238 Update nikic/php-parser (4.10.3 => 4.10.4)
  changelog/unreleased/38191
  composer.lock
Labels: 3 - To Review, dependencies, php

#38241 [tests-only] Skip changed webUITags tests on old oC10 versions
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITags/deleteTags.feature
  tests/acceptance/features/webUITags/editTags.feature
  tests/acceptance/features/webUITags/removeTags.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
Labels: 3 - To Review, QA-team

#38205 [Tests-Only] added api test for share shared to deleted user
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, QA-team

#38246 Fix a regression with theming of settings menu icons
  changelog/unreleased/38246
  lib/base.php
Labels: 3 - To Review

#38239 [tests-only] Adds API tests to check the file deletion time
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA-team

#38242 Change fix mixed.
  changelog/unreleased/38187
  changelog/unreleased/38188
Labels: 4 - To release

#38240 [tests-only] tests for file version and upload to share
  tests/acceptance/features/apiShareOperationsToShares/uploadToShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
Labels: 3 - To Review, QA-team

#38244 Update phpseclib/phpseclib (2.0.29 => 2.0.30)
  changelog/unreleased/38244
  composer.lock
Labels: dependencies, php

#38250 [tests-only] sync at end of tests to get all test log output
  tests/acceptance/run.sh
Labels: 3 - To Review, QA-team

#38255 Update egulias/email-validator (2.1.24 => 2.1.25)
  changelog/unreleased/38255
  composer.lock
Labels: 3 - To Review, dependencies, php

#38247 [Tests-Only] add tests for downloading file with range request
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 4 - To release, QA-team

#38259 [docs-only] Change codecov badge to SonarCloud badges
  README.md
Labels: 3 - To Review
