Repository owncloud/core, pull requests merged in 2020-04, with the labels that each got.

#37197 Update 37135
  changelog/10.4.1_2020-03-30/37135
Labels: 4 - To release

#37198 [Tests-only] Add changelog step to makefile
  Makefile
Labels: 4 - To release

#37199 Update laminas/laminas-validator from 2.13.3 to 2.13.4
  changelog/unreleased/37199
  composer.lock
Labels: 3 - To Review, dependencies, php

#37202 [Tests-Only] Use newadmin for invalid auth tests
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37203 [Tests-Only] [10.4.1] Use newadmin for invalid auth tests
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37205 [Tests-Only] [10.4.1] Add skipOnBruteForceProtection test tags due to issue 112
  tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37204 [Tests-Only] Add skipOnBruteForceProtection test tags due to issue 112
  tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37195 [Tests-Only] User can update the permission in share when max expiry date is enforced
  tests/acceptance/features/apiShareUpdate/updateShare.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37207 [Tests-Only] Acceptance test typos and skipOnOcis
  tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/cliLocalStorage/showBackendsForMount.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37208 [Tests-Only] [10.4.1] Acceptance test typos 10.4.1
  tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/cliLocalStorage/showBackendsForMount.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37209 [Tests-Only] Always use the API to process membership of the admin group
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37210 [Tests-Only] [10.4.1] Always use the API to process membership of the admin group
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37212 [10.4.1] [Security] Bump minimist from 1.2.2 to 1.2.3 in /build
  build/package.json
  build/yarn.lock
Labels: 3 - To Review, dependencies

#37214 PHP dependencies 20200406
  changelog/unreleased/37214-1
  changelog/unreleased/37214-2
  composer.lock
Labels: 4 - To release, dependencies, php

#37215 [10.4.1] PHP dependencies 20200406 10.4.1
  changelog/10.4.1_2020-03-30/37188
  changelog/10.4.1_2020-03-30/37193
  changelog/10.4.1_2020-03-30/37199
  changelog/10.4.1_2020-03-30/37214-1
  changelog/10.4.1_2020-03-30/37214-2
  composer.lock
Labels: 3 - To Review, dependencies, php

#37169 [Tests-Only] Adjust unit tests for the future
  apps/dav/tests/unit/DAV/CopyPluginTest.php
  apps/dav/tests/unit/Files/FileLocksBackendTest.php
  apps/dav/tests/unit/Files/PreviewPluginTest.php
  tests/bootstrap.php
  tests/lib/ConfigTest.php
  tests/lib/Files/MetaVersionCollectionTest.php
  tests/lib/Files/ObjectStore/ObjectStoreTest.php
  tests/lib/Files/Storage/Wrapper/JailTest.php
  tests/lib/User/SyncServiceTest.php
Labels: 4 - To release, dev:phpunit-tests

#36586 php unit test changes to address issues that php7.4 will report
  lib/private/AppFramework/Utility/ControllerMethodReflector.php
  lib/private/Files/Cache/Cache.php
  tests/lib/Cache/FileCacheTest.php
  tests/lib/Command/Integrity/SignAppTest.php
  tests/lib/Command/Integrity/SignCoreTest.php
  tests/lib/Files/Cache/CacheTest.php
  tests/lib/Files/Cache/HomeCacheTest.php
  tests/lib/Files/Cache/Wrapper/CacheJailTest.php
  tests/lib/Util/User/MemoryAccountMapper.php
Labels: 3 - To Review

#37206 [Tests-Only]Try to update date and permission at the same time when max date is enforced
  tests/acceptance/features/apiShareUpdate/updateShare.feature
Labels: 4 - To release, QA-team

#37216 Do not extend share info from FS for pending federated shares
  apps/files_sharing/lib/Controller/RemoteOcsController.php
  changelog/unreleased/37216
  tests/acceptance/features/apiFederation/federated.feature
Labels: 3 - To Review

#37224 [Tests-Only] skip test that was adjusted in PR 37216 on old oC10
  tests/acceptance/features/apiFederation/federated.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37219 Stop writing data to the output buffer in case the connection is no l…
  changelog/unreleased/37219
  lib/private/Files/View.php
  lib/private/legacy/files.php
Labels: 3 - To Review

#37225 Delete unused config option and help page
  changelog/unreleased/37225
  config/config.sample.php
  settings/css/settings.css
  settings/help.php
  settings/templates/help.php
Labels: 4 - To release

#37166 [tests-only] test webdav previews
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiWebdavPreviews/previews.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37229 [Tests-Only] escape plus in uid when creating ldap user
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37227 [Tests-Only] [10.4.1] Add another skipOnBruteForceProtection test tag due to issue 112
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPOSTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavDELETEAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavLOCKAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavMOVEAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPOSTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPROPFINDAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPROPPATCHAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPUTAuth.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37237 Update nikic/php-parser (4.3.0 => 4.4.0)
  changelog/unreleased/37237
  composer.lock
Labels: 3 - To Review, dependencies, php

#37242 [10.4.1] Update nikic/php-parser (4.3.0 => 4.4.0)
  changelog/10.4.1_2020-03-30/37237
  composer.lock
Labels: 3 - To Review, dependencies

#37238 Replace jeremeamia/superclosure with opis/closure
  changelog/unreleased/37238
  composer.json
  composer.lock
  lib/private/Command/AsyncBus.php
  lib/private/Command/ClosureJob.php
Labels: 4 - To release, dependencies, php

#37254 [Tests-Only] Bump phpstan to 0.12
  apps/files_external/lib/Lib/Storage/SMB.php
  apps/files_sharing/lib/Controller/ShareesController.php
  lib/private/Files/Config/UserMountCache.php
  lib/private/Files/Storage/Wrapper/Encoding.php
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 3 - To Review

#37245 [Tests-Only] Remove out-of-date comments about ldap-users.ldif
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37246 RepairUnmergedShares: sum up users across all backends
  changelog/unreleased/37246
  lib/private/Repair/RepairUnmergedShares.php
Labels: 3 - To Review

#37255 Update PHPdoc of Group get methods
  lib/private/Group/Manager.php
  lib/public/IGroupManager.php
Labels: 4 - To release

#37228 [Tests-Only] Set max preview size and download previews of various size
  tests/acceptance/features/apiWebdavPreviews/previews.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37256 Remove console.warn(response) to prevent potential malicious output t…
  changelog/unreleased/37256
  core/js/tags.js
Labels: 3 - To Review

#37261 [Tests-only] improve code readability
  tests/TestHelpers/OcisHelper.php
Labels: QA-team, dev:acceptance-tests

#37231 [Tests-only] test href property in PROPFIND response
  tests/acceptance/features/apiWebdavProperties/getFileProperties.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37260 [tests-only] test the OCIS implementation of the previews
  tests/acceptance/features/apiWebdavPreviews/previews.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37263 [Tests-Only] Bump phan 2.7
  .phan/config.php
  lib/private/Comments/Comment.php
  lib/private/Comments/Manager.php
  lib/public/Comments/IComment.php
  settings/Controller/UsersController.php
  vendor-bin/phan/composer.json
Labels: 4 - To release, QA-team

#37270 Bump master to 10.5.0alpha1
  version.php
Labels: 4 - To release

#37271 Update league/flysystem (1.0.66 => 1.0.67)
  changelog/unreleased/37271
  composer.lock
Labels: 4 - To release, dependencies, php

#37274 [Tests-Only] Skip on oc v10 for special ocis preview scenarios
  .drone.star
  tests/acceptance/features/apiWebdavPreviews/previews.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37100 Drop support for PHP 7.1
  .drone.star
  .travis.yml
  changelog/unreleased/36510
  composer.json
  composer.lock
  console.php
  index.php
Labels: 3 - To Review

#37275 [Tests-Only] Updating bamarni/composer-bin-plugin (v1.3.0 => 1.4.0)
  composer.json
  composer.lock
Labels: 4 - To release, dependencies, php

#37276 Changelog link fix wrong number.
  changelog/10.4.1_2020-03-30/37173
Labels: 4 - To release

#37218 Include option to allow scanner to reuse etags only for files
  changelog/unreleased/37218
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Cache/Watcher.php
  lib/public/Files/Cache/IScanner.php
Labels: 3 - To Review

#37278 [Tests-Only] Remove OC_Theme not found from ignored errors
  phpstan.neon
Labels: 3 - To Review

#37232 Hide add to your OC at the public page when sending shares is not all…
  apps/federatedfilesharing/appinfo/app.php
  apps/federatedfilesharing/lib/AppInfo/Application.php
  apps/federatedfilesharing/lib/HookHandler.php
  apps/federatedfilesharing/tests/appinfo/ApplicationTest.php
  changelog/unreleased/37232
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/PublicLinkFilesPage.php
  tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature
Labels: 4 - To release

#37281 Check get result against false when removing file from cache
  lib/private/Files/Cache/Cache.php
Labels: 3 - To Review

#37285 [Tests-Only] skip 'add to your owncloud button' test on old oC versions
  tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature
Labels: 4 - To release, QA-team

#37279 Handle cache watcher update checks when cache is empty
  lib/private/Files/Cache/Watcher.php
Labels: 3 - To Review

#36944 [Tests-only] remove unneeded xml namespace registrations
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37287 [Tests-Only] Updated phpDoc
  lib/private/Files/External/FrontendDefinitionTrait.php
Labels: QA-team

#37288 [Tests-Only] Fix Creating default object from empty value
  apps/dav/tests/unit/Connector/Sabre/FilesPluginTest.php
Labels: 3 - To Review

#37289 [Tests-Only] Updated phpDoc for get/set customJs
  lib/private/Files/External/FrontendDefinitionTrait.php
Labels: 4 - To release, QA-team

#37290 Fix access array offset on bool for FederatedShareProvider tests
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
Labels: 3 - To Review

#37222 Keep the same mtime as in the ownCloud's FS for files inside
  changelog/unreleased/37222
  lib/private/Streamer.php
  lib/private/legacy/files.php
Labels: 3 - To Review

#37292 [Tests-Only] Php 7.4 fix more tests
  apps/files/tests/Controller/ViewControllerTest.php
  apps/files_sharing/lib/Controllers/ExternalSharesController.php
  apps/files_sharing/tests/Controller/RemoteOcsControllerTest.php
  apps/files_sharing/tests/Controllers/ExternalShareControllerTest.php
  apps/provisioning_api/tests/UsersTest.php
  tests/Core/Controller/AvatarControllerTest.php
Labels: 2 - Developing

#37293 [Tests-Only] Php 7.4 another pack of fixes
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/CardDAV/SyncServiceTest.php
  apps/dav/tests/unit/Meta/MetaPluginTest.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
  tests/lib/Files/Stream/EncryptionTest.php
  tests/lib/Files/ViewTest.php
Labels: 3 - To Review

#37297 [Tests-Only] Php7.4 fix more tests vol 2
  lib/private/Setup.php
  lib/private/Share/Share.php
Labels: 4 - To release

#37295 [tests-only] Refactor function convertTrashbinHref to restore deleted file
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: 3 - To Review, QA-team

#37296 [Tests-Only] Run apiVersions test on Oracle db
  .drone.star
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37298 PHP-7.4 Fix litmus
  apps/dav/lib/DAV/FileCustomPropertiesBackend.php
Labels: 3 - To Review

#37300 Fix hasUpdated for webdav storage
  lib/private/Files/Storage/DAV.php
Labels: 4 - To release

#37301 [Tests-Only] Test against federated server running core 10.3.2
  .drone.star
Labels: 4 - To release, QA-team

#37304 [Tests-Only] Correct mount option read_only in manageOptionsForLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/manageOptionsForLocalStorage.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37302 Support PHP 7.4
  .drone.star
  changelog/unreleased/36509
  console.php
  index.php
Labels: 3 - To Review

#37310 [Tests-Only] Use assertContainsEquals to compare status codes that could be in string or int form
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37312 [Tests-Only] Do not run Oracle issue 37026 in CI
  .drone.star
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37311 [PHP7.4] Fix array access in FederatedShareProvider and Storage/DAV
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  changelog/unreleased/37311
  lib/private/Files/Storage/DAV.php
Labels: 3 - To Review

#37316 [Tests-Only] Updating phpdocumentor/reflection-common (2.0.0 => 2.1.0)
  composer.lock
Labels: 3 - To Review, dependencies

#37318 [Tests-Only] Fix checkingAttributesInLastShareResponse acceptance test method
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37319 Update Symfony components to 4.4.8
  changelog/unreleased/37319
  composer.lock
Labels: 3 - To Review, dependencies, php

#37320 Adjust IConfig PHP doc for value parameter
  lib/public/IConfig.php
Labels: 4 - To release
