Repository owncloud/core, pull requests merged in 2020-11, with the labels that each got.

#38061 Update egulias/email-validator (2.1.22 => 2.1.23)
  changelog/unreleased/38061
  composer.lock
Labels: 3 - To Review, dependencies, php

#38066 [tests-only] Use PHP 7.4 for behat acceptance test dependencies
  .drone.star
  Makefile
Labels: 4 - To release, QA-team

#38069 [Tests-Only] Refactor GET request to a pending remote share
  tests/acceptance/features/apiFederationToRoot1/federated.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
Labels: 3 - To Review, QA-team

#38068 [Tests-Only] Adjust then steps for the unsuccessful sharing scenarios
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/apiShareReshareToShares1/reShare.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
Labels: 3 - To Review

#38071 [Tests-Only] add api tests for checking etag propagation on copy operations
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38054 Add the getSharesByPath share method to the interface
  apps/files_sharing/lib/SharedMount.php
  changelog/unreleased/38054
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
Labels: 3 - To Review

#38072 Use the right l10n object if the template is loaded from another app
  changelog/unreleased/38072
  lib/private/Template/Base.php
Labels: 3 - To Review

#38075 [Tests-Only] Remove skipOnOcis tags
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareOperationsToShares/gettingShares.feature
  tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature
Labels: 4 - To release, QA-team

#38079 [Tests-Only] unskip etag propagation tests for oc storage in ocis
  tests/acceptance/features/apiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/restoreFromTrash.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/restoreVersion.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/upload.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38080 [tests-only] Adjust skipOnOcis-OC-Storage for etag test scenarios
  tests/acceptance/features/apiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/restoreFromTrash.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/upload.feature
Labels: 3 - To Review, QA-team

#38053 Refactor getSharesInDir method and allow new interaction in params
  apps/files_sharing/lib/Controller/Share20OcsController.php
  changelog/unreleased/38053
Labels: 3 - To Review

#37956 Retry moving mountpoint sane amount of times
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/lib/External/Mount.php
  changelog/unreleased/37956
  config/config.sample.php
  lib/private/Files/Config/MountProviderCollection.php
Labels: 3 - To Review

#38091 PHP dependencies 20201109
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  changelog/unreleased/38091
  changelog/unreleased/38091-2
  composer.lock
Labels: 3 - To Review, dependencies, php

#38092 Update sabre/dav (4.1.2 => 4.1.3)
  changelog/unreleased/38092
  composer.lock
  tests/acceptance/features/apiAuthWebDav/webDavLOCKAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPUTAuth.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingNewChunking.feature
Labels: 3 - To Review, dependencies, php

#38095 [Tests-Only] Refactored Oc10 bug demonstration scenarios that were tagged issue-core-nnnn
  tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/apiSharePublicLink2/copyFromPublicLinkOc10Issue37683.feature
Labels: QA-team

#38093 [Tests-Only] fix user initialize and check on ocis
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA-team, dev:acceptance-tests

#38096 [tests-only] skip on old oCV10 for scenarios that were added or changed by issue 38089
  tests/acceptance/features/apiAuthWebDav/webDavLOCKAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPUTAuth.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingNewChunking.feature
Labels: 3 - To Review, QA-team

#38097 [tests-only] Fix acceptance test exit status when running a single scenario
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, dev:acceptance-tests

#38098 [tests-only] Only use user 'moss' when isTestingOnOcis
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team

#38100 [tests-only] Update phpunit/phpunit (8.5.8 => 8.5.9)
  composer.lock
Labels: 3 - To Review, dependencies, dev:phpunit-tests

#38076 [Tests-Only] Remove toImplementOnOcis tags from the scenarios
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavDELETEAuth.feature
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiFederationToShares1/etagPropagation.feature
  tests/acceptance/features/apiFederationToShares1/federated.feature
  tests/acceptance/features/apiFederationToShares2/federated.feature
  tests/acceptance/features/apiMain/caldav.feature
  tests/acceptance/features/apiMain/carddav.feature
  tests/acceptance/features/apiMain/userSync.feature
  tests/acceptance/features/apiProvisioning-v1/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v1/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v2/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/getSubAdmins.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareWhenExcludedFromSharing.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupCaseSensitive.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/apiShareOperationsToShares/accessToShare.feature
  tests/acceptance/features/apiShareOperationsToShares/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiShareOperationsToShares/gettingShares.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
  tests/acceptance/features/apiTranslation/translation.feature
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/folder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToShares.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToRoot.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
Labels: 3 - To Review, QA-team

#38019 check request token on cookie authenticated request
  apps/files_sharing/lib/Controller/Share20OcsController.php
  changelog/unreleased/38019
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
Labels: 3 - To Review

#38055 avoid retrieving user root iteratively in share controller
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  changelog/unreleased/38055
Labels: 4 - To release

#38106 [tests-only] Update composer/semver (3.2.2 => 3.2.3)
  composer.lock
Labels: 3 - To Review, dependencies, php

#38112 [tests-only] Fix test steps for when REPLACE_USERNAMES is in effect
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38114 update ca-bundle.crt
  resources/config/ca-bundle.crt
Labels: 4 - To release

#38113 [tests-only] Update composer/semver (3.2.3 => 3.2.4) myclabs/deep-copy (1.10.1 => 1.10.2)
  composer.lock
Labels: 3 - To Review, dependencies, php

#38107 This solves the issue, while generating a public link ssl check conne…
  apps/files_sharing/ajax/external.php
  changelog/unreleased/38107
Labels: 3 - To Review

#38103 adapted solution for 5xx error on i10n vsprintf
  changelog/unreleased/38103
  lib/private/legacy/l10n/string.php
  tests/lib/L10N/L10nTest.php
Labels: 3 - To Review

#38116 Update egulias/email-validator (2.1.23 => 2.1.24)
  changelog/unreleased/38116
  composer.lock
Labels: 4 - To release, dependencies, php

#38117 [tests-only] Add test for adding a public link shared file to your ownCloud
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#38110 [Tests-Only] enable group tests on ocis
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/deleteGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/removeFromGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/deleteGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/removeFromGroup.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#38119 Wrong app is used in some calls for translation in javascript
  changelog/unreleased/38119
  core/js/multiselect.js
  settings/js/admin-apps.js
  settings/js/certificates.js
  settings/js/panels/authtoken_view.js
  settings/js/panels/profile.js
  settings/js/setpassword.js
  settings/js/settings.js
  settings/js/users/users.js
Labels: 4 - To release

#38120 [Tests-Only] Update issue tags for test scenarios
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
  tests/acceptance/features/apiProvisioningGroups-v2/deleteGroup.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
Labels: 4 - To release, QA-team

#38121 [tests-only] Minor cleanup in .drone.star
  .drone.star
Labels: 4 - To release, QA-team

#38122 [tests-only] Bump test tool dependencies
  apps/dav/lib/CalDAV/BirthdayService.php
  apps/dav/lib/CalDAV/CalendarObject.php
  apps/files_external/lib/Lib/Storage/SFTP.php
  vendor-bin/behat/composer.json
  vendor-bin/phan/composer.json
Labels: QA-team

#38127 [tests-only] Fix tests WebDav.php BadResponseException
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, QA-team

#38130 [tests-only] Use phpunit9 in acceptance tests
  .phan/config.php
  vendor-bin/behat/composer.json
Labels: 4 - To release, QA-team

#38131 [tests-only] Use assertStringContainsString in PublicWebDavContext test code
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#38138 [Tests-Only] edit users only when running with oc10 backend
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38133 Revert PR 37875
  changelog/unreleased/37875
  core/css/styles.css
  core/img/actions/close-red.svg
  core/img/actions/exclamation-triangle-solid.svg
  core/js/integritycheck-failed-notification.js
  core/js/js.js
  core/js/license-state-notification.js
  core/js/tests/specs/coreSpec.js
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/lib/OwncloudPage.php
  tests/acceptance/features/webUIAddUsers/addUsers.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: 3 - To Review

#38101 CORS add url only allow http or https protocol
  changelog/unreleased/37664
  settings/Controller/CorsController.php
  tests/Settings/Controller/CorsControllerTest.php
Labels: 3 - To Review

#38141 [Tests-Only] add more tests to cover ocis issues
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38142 [tests-only] first TUS upload tests
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: Acceptance tests, QA-team, dev:acceptance-tests

#38144 [tests-only] Add ankitpokhrel/tus-php for acceptance tests
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team

#38146 [tests-only] make mtime upload step upload data
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA-team, dev:acceptance-tests

#38148 [tests-only] tests for TUS uploads with mtime
  tests/acceptance/features/apiWebdavUploadTUS/uploadFileMtime.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA-team

#38149 [tests-only] Update phpunit/phpunit (8.5.9 => 8.5.10)
  composer.lock
Labels: 3 - To Review, dependencies, php

#38160 [tests-only] Make CI run on various databases
  .drone.star
  tests/acceptance/features/apiTrashbin/trashbinFilesFoldersOc10Issue23151.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: QA-team

#38162 [tests-only] Update phpunit/phpunit (8.5.10 => 8.5.11)
  composer.lock
Labels: dependencies, php

#38150 [tests-only] tests for TUS upload to share
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
Labels: QA-team

#38164 [tests-only] simple TUS chunking tests
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA-team, dev:acceptance-tests

#38166 [tests-only] Adjust and add skipOnDbOracle tags
  tests/acceptance/features/apiTrashbin/trashbinFilesFoldersOc10Issue23151.feature
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
Labels: 4 - To release, QA-team

#38167 [tests-only] Tus tests fixes
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 4 - To release, QA-team, dev:acceptance-tests
