Repository owncloud/core, pull requests merged in 2020-08, with the labels that each got.

#37767 [Tests-Only] Report the total scenarios that passed and failed across all suites
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37768 Update doctrine/event-manager (1.1.0 => 1.1.1)
  changelog/unreleased/37768
  composer.lock
Labels: 3 - To Review, dependencies, php

#37769 [Tests-Only] Remove old skipOnOcV10.* tags
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/folder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks2/resharedShares.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks2/unlock.feature
  tests/acceptance/features/webUIAddUsers/addUsers.feature
  tests/acceptance/features/webUILogin/resetPassword.feature
  tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
  tests/acceptance/features/webUIManageUsersGroups/manageGroups.feature
  tests/acceptance/features/webUISharingPublic1/permissionsShareByPublicLink.feature
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37766 add values to the invalid uids list
  changelog/unreleased/37765
  lib/private/User/Manager.php
  tests/lib/User/ManagerTest.php
Labels: 3 - To Review

#37772 Update symfony/polyfill (1.18.0 => 1.18.1)
  changelog/unreleased/37772
  composer.lock
Labels: 3 - To Review, dependencies, php

#37775 Bump version to 10.5.1alpha1
  version.php
Labels: 3 - To Review

#37781 [Tests-Only] Skip favorites capability scenario on 10.5.0
  .drone.star
  tests/acceptance/features/apiCapabilities/capabilities.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37782 Add openid client secret to the sensitive values list
  changelog/unreleased/37782
  lib/private/SystemConfig.php
Labels: 3 - To Review

#37783 Fix exit codes of security:certificates commands
  .drone.star
  changelog/unreleased/35364
  core/Command/Security/ImportCertificate.php
  core/Command/Security/RemoveCertificate.php
  lib/private/Security/CertificateManager.php
  tests/Core/Command/Security/ImportCertificateTest.php
  tests/Core/Command/Security/RemoveCertificateTest.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/cliMain/securityCertificates.feature
  tests/lib/Security/CertificateManagerTest.php
Labels: 3 - To Review

#37790 Update egulias/email-validator (2.1.18 => 2.1.19)
  changelog/unreleased/37790
  composer.lock
Labels: 3 - To Review, dependencies, php

#37787 [Tests-only] copy certificates to server storage during testing
  .gitignore
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/cliLocalStorage/importLocalStorage.feature
  tests/acceptance/features/cliMain/securityCertificates.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37793 [Tests-Only] find data file relative to test-runner root
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37794 [tests-only] display a warning when reva data root folder does not exist
  tests/TestHelpers/OcisHelper.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37797 [tests-only] export TESTING_REMOTE_SYSTEM variable
  Makefile
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37801 [Tests-Only] Bump phpunit version in autotest scripts
  build/autotest-external.sh
  build/autotest.sh
Labels: 3 - To Review, dev:phpunit-tests

#37802 [Tests-Only] skipOnOcV10.5.0 cliMain securityCertificates features
  tests/acceptance/features/cliMain/securityCertificates.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37795 [Tests-Only] Added tests for change in etag
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
Labels: 3 - To Review, QA-team

#37803 [Tests-Only] remember actualUsername in acceptance tests
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37804 Update opis/closure (3.5.5 => 3.5.6)
  changelog/unreleased/37804
  composer.lock
Labels: 3 - To Review, dependencies, php

#37773 [Tests-Only] Remove OCIS bug demo scenarios
  tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPOSTAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavLOCKAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavMOVEAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPROPFINDAuth.feature
  tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
  tests/acceptance/features/apiFavorites/favorites.feature
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiMain/main.feature
  tests/acceptance/features/apiShareCreateSpecial2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareManagementBasic/deleteShare.feature
  tests/acceptance/features/apiShareOperations/accessToShare.feature
  tests/acceptance/features/apiShareOperations/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiShareOperations/gettingShares.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/apiShareUpdate/updateShare.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiWebdavMove1/moveFolder.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/apiWebdavPreviews/previews.feature
  tests/acceptance/features/apiWebdavProperties1/createFolder.feature
  tests/acceptance/features/apiWebdavProperties1/setFileProperties.feature
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37805 [Tests-Only] Add toImplementOnOCIS to etag test because it is intermittent on OCIS
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37785 [Tests-Only] Do not exit acceptance test if a test suite has a failure
  tests/acceptance/run.sh
Labels: QA-team

#37809 [tests-only] run more tests in ocis
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37811 [Tests-Only] Check for http status code 204
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37826 Translate 'Passwords do not match' messages
  changelog/unreleased/37826
  core/js/lostpassword.js
  settings/js/setpassword.js
Labels: 3 - To Review

#37819 [Tests-Only] Wait for ajax call
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UsersPage.php
Labels: 4 - To release, QA-team

#37825 [Tests-Only] Wait for choose as profile picture button
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
Labels: 3 - To Review, QA-team

#37774 [Tests-Only] Remove skip/toImplementOnOcis tags for passing sharing tests
  tests/acceptance/features/apiShareManagement/acceptShares.feature
  tests/acceptance/features/apiShareOperations/accessToShare.feature
  tests/acceptance/features/apiShareOperations/gettingShares.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
Labels: QA-team

#37820 [Tests-Only] Handle expected failures or success for webui rerun
  tests/acceptance/run.sh
Labels: QA-team

#37824 [Tests-Only] Fix intermittent fail in public link removal using webUI
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
Labels: 4 - To release, QA-team

#37837 [Tests-Only] Support skipOnFedOcV tags in acceptance tests
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37831 [Tests-Only] This PR runs trashbin api tests on ocis
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
Labels: 3 - To Review, QA-team

#37838 [Tests-Only] allow acceptance testing against fed server from PR branch
  .drone.star
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37835 extend share_external name column length to 255
  apps/files_sharing/appinfo/Migrations/Version20200823121322.php
  apps/files_sharing/appinfo/info.xml
  changelog/unreleased/37835
  tests/acceptance/features/webUISharingExternal1/federationSharing.feature
Labels: 3 - To Review

#37841 [Tests-Only] Used unexpected array length to determine passed or failed behat status
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37844 [Tests-Only] Improve error reporting when getArrayOfShareesResponded response has missing data
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37839 [Tests-Only] Assert created user
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
Labels: 3 - To Review, QA-team

#37548 Add support to expire outgoing federated shares
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/files_sharing/lib/Capabilities.php
  apps/files_sharing/tests/CapabilitiesTest.php
  changelog/unreleased/37548
  core/js/config.php
  core/js/shareconfigmodel.js
  core/js/sharedialogshareelistview.js
  core/js/shareitemmodel.js
  lib/private/Share20/Manager.php
  settings/Panels/Admin/FileSharing.php
  settings/js/admin.js
  settings/templates/panels/admin/filesharing.php
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiFederation2/federated.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
  tests/acceptance/features/webUISharingExternal2/createFederationSharing.feature
Labels: 3 - To Review, QA-team

#37848 Obfuscate metrics shared secret
  changelog/unreleased/37848
  lib/private/SystemConfig.php
Labels: enhancement, security

#37849 [Tests-Only] remove UI tests from expected failures if rerun is successful
  tests/acceptance/run.sh
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37847 [Tests-Only] Improve header response checks in theHeaderChecksumShoudMatch
  tests/acceptance/features/bootstrap/ChecksumContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37846 Fix application id used for sharing settings translation
  changelog/unreleased/37846
  lib/private/Settings/SettingsManager.php
  settings/Panels/Admin/FileSharing.php
  tests/Settings/Panels/Admin/FileSharingTest.php
Labels: 3 - To Review

#37851 [Tests-Only] Fix theseUsersHaveBeenCreatedUsingTheOccCommand so it works with mixed-case usernames
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37855 [Tests-Only] Process unexpected Behat exit status in acceptance tests
  tests/acceptance/run.sh
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37750 Fix decoding of calendars uri
  apps/dav/lib/CalDAV/CalendarHome.php
  changelog/unreleased/37750
Labels: 3 - To Review

#37852 [Tests-Only] Reporting expected failures when running a single feature
  tests/acceptance/run.sh
Labels: 3 - To Review, QA-team

#37791 Exclude reshares from files:transfer-ownership as ownership cannot be transfered
  apps/files/lib/Command/TransferOwnership.php
  apps/files/tests/Command/TransferOwnershipTest.php
  changelog/unreleased/37791
  tests/acceptance/features/cliMain/transfer-ownership.feature
Labels: app:files, bug

#37862 Update Symfony components to 4.4.12
  changelog/unreleased/37862
  composer.lock
Labels: 3 - To Review, dependencies
