Repository owncloud/core, pull requests merged in 2020-05, with the labels that each got.

#37328 [Tests-only] adjust tests to demonstrate ocis-reva issue 163
  tests/acceptance/features/apiWebdavProperties/getFileProperties.feature
Labels: QA-team, dev:acceptance-tests

#37329 [tests-only] remove unneded tag in tests
  tests/acceptance/features/apiWebdavProperties/getFileProperties.feature
Labels: QA-team

#37103 Add force option to delete user home folder
  apps/dav/lib/CardDAV/SyncService.php
  apps/dav/lib/HookManager.php
  apps/dav/tests/unit/CardDAV/SyncServiceTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  apps/files_sharing/tests/NotifierTest.php
  changelog/unreleased/37103
  core/Command/User/Delete.php
  lib/private/User/DeletedUser.php
  lib/private/User/Manager.php
  lib/public/IUserManager.php
  tests/Core/Command/User/DeleteTest.php
  tests/Core/Controller/AvatarControllerTest.php
  tests/Core/Controller/LostControllerTest.php
  tests/lib/Command/User/SyncBackendTest.php
  tests/lib/Group/GroupTest.php
  tests/lib/Share20/DefaultShareProviderTest.php
  tests/lib/Share20/ManagerTest.php
  tests/lib/User/DeletedUserTest.php
  tests/lib/User/ManagerTest.php
  tests/lib/User/TokenAuthModuleTest.php
Labels: 3 - To Review

#37330 [tests-only] fix tags in MKCOL test and add example
  tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37331 Adjust test tag issue number for ocis reva comments
  tests/acceptance/features/apiComments/comments.feature
  tests/acceptance/features/apiComments/createComments.feature
  tests/acceptance/features/apiComments/deleteComments.feature
  tests/acceptance/features/apiComments/editComments.feature
Labels: 4 - To release

#37335 [Tests-Only] Remove unneeded phpstan ignoreErrors entry
  phpstan.neon
Labels: 4 - To release, QA-team

#37334 [tests-only] test creating folder with the name of an existing resource
  tests/acceptance/features/apiWebdavProperties/createFolder.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37333 [tests-only] unmark test of reva-issue-165
  tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37306 [Tests-Only] Test for hidden files
  tests/acceptance/features/webUIFiles/hiddenFile.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37268 Do not allow various special usernames (UIDs)
  changelog/unreleased/32547
  lib/private/User/Manager.php
  tests/acceptance/features/webUIAddUsers/addUsers.feature
  tests/lib/User/ManagerTest.php
Labels: 3 - To Review

#37314 Complex webdav properties support
  apps/dav/appinfo/Migrations/Version20200427142541.php
  apps/dav/appinfo/info.xml
  apps/dav/lib/DAV/AbstractCustomPropertiesBackend.php
  apps/dav/lib/DAV/FileCustomPropertiesBackend.php
  apps/dav/lib/DAV/MiscCustomPropertiesBackend.php
  apps/dav/tests/unit/DAV/FileCustomPropertiesBackendTest.php
  changelog/unreleased/37314
  tests/Core/Command/Apps/AppsListTest.php
  tests/acceptance/features/apiWebdavProperties/setFileProperties.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: 3 - To Review

#37345 [Tests-Only] Fix scanLocalStorage scenario
  tests/acceptance/features/cliLocalStorage/scanLocalStorage.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37347 [Tests-Only] Skip fixed complex dav property test on old ownCloud 10.3 and 10.4
  tests/acceptance/features/apiWebdavProperties/setFileProperties.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37349 [Tests-Only] Skip meta username test on 10.4
  tests/acceptance/features/webUIAddUsers/addUsers.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37336 Fix sharing with uids in numerical format
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/tests/API/ShareesTest.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  changelog/unreleased/37324
  tests/acceptance/features/webUISharingInternalUsers1/createShareWithUsers.feature
Labels: 3 - To Review

#37351 [Tests-Only] Fix testCreateShareGroupNoValidShareWith issue 37350
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
Labels: 4 - To release, dev:phpunit-tests

#37339 fix the output of error messages
  changelog/unreleased/37338
  core/Controller/LostController.php
Labels: 3 - To Review

#37353 [Tests-Only] Run phpunit from the tests dir
  tests/drone/test-phpunit.sh
Labels: 3 - To Review, QA-team

#37360 [Tests-Only] Refactor unit test calls
  tests/lib/AppFramework/Db/EntityTest.php
  tests/lib/Files/External/Backend/BackendTest.php
  tests/lib/Files/Storage/DavTest.php
  tests/lib/Repair/RemoveGetETagEntriesTest.php
  tests/lib/Repair/RepairSubSharesTest.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 3 - To Review, QA-team, dev:phpunit-tests

#37354 [Tests-Only] Added default capabilities scenario for a normal user
  tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
Labels: 3 - To Review, QA-team

#37362 [Tests-Only] Improve tests and increase coverage
  apps/files_trashbin/tests/ExpirationTest.php
  apps/files_versions/tests/ExpirationTest.php
  tests/lib/SystemConfigTest.php
  tests/lib/Template/ResourceLocatorTest.php
Labels: 4 - To release

#37262 [Tests-Only] Add acceptance tests to share top-level of read-only storage
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/WebUIAdminStorageSettingsContext.php
  tests/acceptance/features/cliLocalStorage/createLocalStorageReadOnlyAndShare.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageReadWriteAndShare.feature
  tests/acceptance/features/lib/AdminStorageSettingsPage.php
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37365 [Tests-Only] Skip local-storage read-only test UI test on ceph and scality object storage
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37367 Update symfony polyfill components to v1.16.0
  changelog/unreleased/37367
  composer.lock
Labels: 4 - To release, dependencies, php

#37368 Use return void phpdoc when a function is not supposed to have any return
  lib/private/Activity/Manager.php
  lib/private/DB/PgSqlTools.php
  lib/private/Log/CommandLogger.php
  lib/private/Notification/Manager.php
  lib/private/Share/Share.php
  lib/public/Activity/IConsumer.php
  lib/public/Activity/IManager.php
  lib/public/ILogger.php
  lib/public/Notification/IApp.php
  lib/public/Notification/IManager.php
  lib/public/Share/IShare.php
  settings/Controller/UsersController.php
Labels: 3 - To Review

#37369 Update sabre/xml (2.2.0 => 2.2.1)
  changelog/unreleased/37369
  composer.lock
Labels: 4 - To release, dependencies, php

#37375 [Tests-Only] Explicitly specify empty glue in implode calls
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/lib/FilesPageCRUD.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/lib/SharedWithYouPage.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37376 adjust method signatures in Encryption.php
  lib/private/Files/Stream/Encryption.php
Labels: 3 - To Review

#35969 Improve description of 'skeletondirectory' key in config.sample.php
  config/config.sample.php
Labels: 3 - To Review

#37381 [Tests-Only] Added check for special characters in username while creating a user
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team

#37379 [Tests-Only] Fix apiProvisioning-v2 createSubAdmin test scenario
  tests/acceptance/features/apiProvisioning-v2/createSubAdmin.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37383 Update react/promise (v2.7.1 => v2.8.0)
  changelog/unreleased/37383
  composer.lock
Labels: 3 - To Review, dependencies, php

#37385 PHP dependencies 20200513
  changelog/unreleased/37385-1
  changelog/unreleased/37385-2
  composer.lock
Labels: 3 - To Review, dependencies, php

#37363 [Tests-only] Copy skeleton directory to data directory of ocis
  tests/TestHelpers/OcisHelper.php
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, QA-team

#37387 [Tests-Only] remove out-of-date user_ldap comments
  tests/acceptance/features/apiShareCreateSpecial1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecial2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareManagement/acceptShares.feature
  tests/acceptance/features/apiShareManagement/disableSharing.feature
  tests/acceptance/features/apiShareManagement/mergeShare.feature
  tests/acceptance/features/apiShareManagement/moveReceivedShare.feature
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareManagementBasic/deleteShare.feature
  tests/acceptance/features/apiShareReshare2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareUpdate/updateShare.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37389 [Tests-Only] Adjust test step wording
  tests/acceptance/features/apiShareCreateSpecial1/createShareWhenExcludedFromSharing.feature
  tests/acceptance/features/apiShareManagementBasic/deleteShare.feature
  tests/acceptance/features/apiShareManagementBasic/excludeGroupFromReceivingShares.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37392 [Tests-Only] Adjust user roles in acceptance tests
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuthOcs/ocsDELETEAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPUTAuth.feature
  tests/acceptance/features/apiComments/comments.feature
  tests/acceptance/features/apiComments/createComments.feature
  tests/acceptance/features/apiComments/deleteComments.feature
  tests/acceptance/features/apiComments/editComments.feature
  tests/acceptance/features/apiFavorites/favorites.feature
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v1/enableUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroups.feature
  tests/acceptance/features/apiShareManagementBasic/createShare.feature
  tests/acceptance/features/apiShareManagementBasic/excludeGroupFromReceivingShares.feature
  tests/acceptance/features/apiShareOperations/changingFilesShare.feature
  tests/acceptance/features/apiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/apiShareReshare1/reShare.feature
  tests/acceptance/features/apiShareReshare2/reShareChain.feature
  tests/acceptance/features/apiShareReshare2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareReshare2/reShareWithExpiryDate.feature
  tests/acceptance/features/apiShareUpdate/updateShare.feature
  tests/acceptance/features/apiTags/assignTags.feature
  tests/acceptance/features/apiTags/assignTagsGroup.feature
  tests/acceptance/features/apiTags/createTags.feature
  tests/acceptance/features/apiTags/deleteTags.feature
  tests/acceptance/features/apiTags/editTags.feature
  tests/acceptance/features/apiTags/retreiveTags.feature
  tests/acceptance/features/apiTags/unassignTags.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/apiWebdavProperties/getFileProperties.feature
  tests/acceptance/features/bootstrap/CommentsContext.php
  tests/acceptance/features/bootstrap/FavoritesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageForGroups.feature
  tests/acceptance/features/cliLocalStorage/scanLocalStorage.feature
  tests/acceptance/features/cliProvisioning/addGroup.feature
  tests/acceptance/features/cliProvisioning/addToGroup.feature
  tests/acceptance/features/cliProvisioning/addUser.feature
  tests/acceptance/features/cliProvisioning/disableUser.feature
  tests/acceptance/features/cliProvisioning/enableUser.feature
  tests/acceptance/features/cliProvisioning/getGroup.feature
  tests/acceptance/features/cliProvisioning/getGroups.feature
  tests/acceptance/features/cliProvisioning/getUser.feature
  tests/acceptance/features/cliProvisioning/getUserGroups.feature
  tests/acceptance/features/cliProvisioning/getUsers.feature
  tests/acceptance/features/cliProvisioning/removeFromGroup.feature
  tests/acceptance/features/cliProvisioning/userReport.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37393 [Tests-Only] Fixup federation test steps that specify the user
  tests/acceptance/features/bootstrap/FederationContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37394 Allow reading params of PUT with empty body more than once
  changelog/unreleased/37394
  lib/private/AppFramework/Http/Request.php
  tests/lib/AppFramework/Http/RequestTest.php
Labels: 3 - To Review

#37405 [Tests-Only] Remove useless comment fields in acceptance tests
  tests/acceptance/features/bootstrap/CommentsContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37399 [Tests-Only] Adjust user and display names in shareAutocompletion tests
  tests/acceptance/features/webUISharingAutocompletion1/shareAutocompletion.feature
  tests/acceptance/features/webUISharingAutocompletion2/shareAutocompletionWithDifferentPatterns.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37391 Add fed shares scanner batched cronjob
  apps/federatedfilesharing/lib/Command/PollIncomingShares.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/lib/Panels/AdminPanel.php
  apps/federatedfilesharing/templates/settings-admin.php
  apps/federatedfilesharing/tests/Command/PollIncomingSharesTest.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/federatedfilesharing/tests/Panels/AdminPanelTest.php
  apps/files_sharing/appinfo/Migrations/Version20200504211654.php
  apps/files_sharing/appinfo/info.xml
  apps/files_sharing/lib/External/ScanExternalSharesJob.php
  apps/files_sharing/tests/External/ScanExternalSharesJobTest.php
  changelog/unreleased/37391
  lib/public/Files/Cache/IScanner.php
Labels: feature:federated-cloud-sharing, p2-high

#37398 Use BackendUserIterator with uid filter for user:sync --uid
  changelog/unreleased/37398
  core/Command/User/SyncBackend.php
  core/Migrations/Version20170221114437.php
  lib/private/User/Sync/BackendUsersIterator.php
  tests/lib/Command/User/SyncBackendTest.php
  tests/lib/User/Sync/BackendUsersIteratorTest.php
  tests/lib/User/SyncServiceTest.php
Labels: 3 - To Review, app:user_ldap

#37406 [Tests-Only] Updated created users list after user update and delete
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/webUIAddUsers/addUsers.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37416 [Tests-Only] Use plugins/codecov:latest
  .drone.star
Labels: 3 - To Review

#37408 [Tests-only] Run basic file move scenarios on OCIS
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature
Labels: 3 - To Review, QA-team

#37388 [Tests-Only] Update issue tags for ocis tags
  tests/acceptance/features/apiWebdavProperties/getFileProperties.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37418 [Tests-Only] Delete groups in after scenario only if it exists and possible to delete
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37421 Updating laminas/laminas-zendframework-bridge (1.0.3 => 1.0.4)
  changelog/unreleased/37421
  composer.lock
Labels: 3 - To Review, dependencies, php

#37422 [Tests-Only] Improve acceptance test createdUsers when a user is created twice in a test
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37426 [Tests-Only] Test that displayname can be cleared using the Provisioning API
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37414 [Tests-Only] Run file move tests on OCIS
  tests/acceptance/features/apiWebdavMove1/moveFolder.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature
Labels: 3 - To Review, QA-team

#37431 Update opis/closure (3.5.1 => 3.5.2)
  changelog/unreleased/37431
  composer.lock
Labels: 3 - To Review, dependencies, php

#37434 [Tests-Only] Fixes for scenarios where user should not be able to share resource using sharing API
  tests/acceptance/features/webUISharingInternalUsers1/miscShareWithUsers.feature
Labels: 4 - To release, QA-team

#36814 Initial draft for license management
  changelog/unreleased/36814
  core/Application.php
  core/Controller/LicenseController.php
  core/Controller/LoginController.php
  core/js/license-state-notification.js
  core/js/license-trial-notification.js
  core/routes.php
  core/templates/login.php
  lib/private/License/BasicLicense.php
  lib/private/License/ILicense.php
  lib/private/License/LicenseFetcher.php
  lib/private/License/LicenseManager.php
  lib/private/License/MessageService.php
  lib/private/Server.php
  lib/private/Settings/SettingsManager.php
  lib/private/TemplateLayout.php
  lib/private/legacy/util.php
  lib/public/IServerContainer.php
  lib/public/License/ILicenseManager.php
  settings/Panels/Admin/License.php
  settings/js/panels/license.js
  settings/templates/panels/admin/license.php
  tests/Core/Controller/LicenseControllerTest.php
  tests/Core/Controller/LoginControllerTest.php
  tests/Settings/Panels/Admin/LicenseTest.php
  tests/lib/License/LicenseFetcherTest.php
  tests/lib/License/LicenseManagerTest.php
  tests/lib/License/MessageServiceTest.php
  tests/lib/Settings/ManagerTest.php
Labels: 3 - To Review

#37427 Allow the email address to be cleared via the Provisioning API
  apps/provisioning_api/lib/Users.php
  apps/provisioning_api/tests/UsersTest.php
  changelog/unreleased/37424-2
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
Labels: 3 - To Review

#37425 Allow setting an empty email address or display name with user:modify
  changelog/unreleased/37424-1
  core/Command/User/Modify.php
  tests/Core/Command/User/ModifyTest.php
  tests/acceptance/features/cliProvisioning/editUser.feature
Labels: 3 - To Review

#37435 [Tests-Only] Clear admin email address in acceptance tests afterScenario
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37439 [Tests-Only] Updating phpunit/phpunit (8.5.4 => 8.5.5)
  composer.lock
Labels: 3 - To Review, dependencies, php

#37440 [Tests-Only] Skip new tests for clearing display name and email when testing on old oC10
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
  tests/acceptance/features/cliProvisioning/editUser.feature
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#37433 [Tests-Only] Add test to rename a file to the banned name (part3)
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature
Labels: 3 - To Review, QA-team

#37448 Update doctrine/lexer (1.2.0 => 1.2.1)
  changelog/unreleased/37448
  composer.lock
Labels: 4 - To release, dependencies, php

#37438 emit events for before-after-failed link password checks
  changelog/unreleased/37438
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#37436 Allow the get demo key link to be configurable
  config/config.sample.php
  core/js/license-trial-notification.js
  lib/private/License/LicenseManager.php
  tests/lib/License/LicenseManagerTest.php
Labels: 3 - To Review

#37450 [Tests-Only] Collect unit test coverage for newer PHP versions
  .drone.star
Labels: 3 - To Review, QA-team

#37442 Set samesite=strict coockies - will work starting php 7.3
  changelog/unreleased/37442
  lib/private/Session/CryptoWrapper.php
Labels: 4 - To release

#37452 [Tests-Only] Added when step to create a user with any combination of attributes using the provisioning API
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
Labels: 4 - To release, QA-team, dev:acceptance-tests

#37454 Fix logging when logger has no writeExtra method
  changelog/unreleased/37453
  lib/private/Log.php
  tests/lib/LoggerWithoutWriteExtraTest.php
Labels: 3 - To Review

#37457 Add option to show or not the grace period popup
  config/config.sample.php
  lib/private/TemplateLayout.php
Labels: 3 - To Review

#37458 Update doctrine/cache (1.10.0 => 1.10.1)
  changelog/unreleased/37458
  composer.lock
Labels: 4 - To release, dependencies, php

#37451 Add additional caching in the RootCollection and SMB classes
  apps/dav/lib/Files/RootCollection.php
  apps/files_external/lib/Lib/Storage/SMB.php
  changelog/unreleased/37451
Labels: 3 - To Review

#37459 [Tests-Only] Remove old unsupported .codecov.yml ci section settings
  .codecov.yml
Labels: 3 - To Review

#36775 Change the wording in the additional tab to not confuse users
  changelog/unreleased/36775
  settings/templates/settingsPage.php
Labels: 3 - To Review

#37462 [Tests-only] Get content-length response header of an image and a pdf
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
Labels: 4 - To release, QA-team

#37464 Update doctrine/instantiator (1.3.0 => 1.3.1)
  changelog/unreleased/37464
  composer.lock
Labels: 3 - To Review, dependencies, php

#37465 Update Symfony components to 4.4.9
  changelog/unreleased/37465
  composer.lock
Labels: 4 - To release, QA-team, dev:acceptance-tests
