Repository owncloud/core, pull requests merged in 2021-12, with the labels that each got.

#39518 fix: tear down the file system before setting up the file system for …
  apps/dav/appinfo/v1/publicwebdav.php
  apps/dav/lib/Connector/PublicAuth.php
  changelog/unreleased/39518
Labels: 3 - To Review

#39541 Allow setting multiple default file actions
  apps/files/js/fileactions.js
  apps/files/js/fileactionsapplicationselectmenu.js
  apps/files/js/fileactionsmenu.js
  apps/files/js/filelist.js
  apps/files/tests/js/favoritespluginspec.js
  apps/files/tests/js/fileactionsSpec.js
  apps/files/tests/js/filelistSpec.js
  apps/files_sharing/tests/js/appSpec.js
  apps/files_trashbin/tests/js/appSpec.js
  changelog/unreleased/39541
Labels: enhancement, 3 - To Review, javascript

#39545 patch CVE-2016-7103 regarding jquery dialog
  changelog/unreleased/39545
  core/js/js.js
Labels: security

#39563 Fix x-icon position in select2 search fields
  changelog/unreleased/39146
  core/css/share.css
Labels: 3 - To Review, 10.9-regression

#39569 Fix directory name in error message when file name already exists
  apps/files/js/filelist.js
  changelog/unreleased/39569
Labels: Type:Bug, 3 - To Review, javascript

#39575 Use ViewOnlyPlugin when requesting a meta endpoint using WebDAV v2
  apps/dav/lib/Server.php
  changelog/unreleased/39575
Labels: Type:Bug, 3 - To Review, app:dav, php

#39579 Add user:home:list-dirs and user:home:list-users commands
  changelog/unreleased/39579
  core/Command/User/HomeListDirs.php
  core/Command/User/HomeListUsers.php
  core/register_command.php
  tests/Core/Command/User/HomeListDirsTest.php
  tests/Core/Command/User/HomeListUsersTest.php
Labels: enhancement, php

#39516 Version Metadata Continued
  apps/files_trashbin/lib/Trashbin.php
  apps/files_versions/lib/AppInfo/Application.php
  apps/files_versions/lib/Hooks.php
  apps/files_versions/lib/MetaStorage.php
  apps/files_versions/lib/Storage.php
  apps/files_versions/tests/VersioningTest.php
  changelog/unreleased/39126
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 2 - Developing

#39585 Set page title for the tags file list
  apps/systemtags/js/systemtagsfilelist.js
  changelog/unreleased/39585
Labels: 3 - To Review, javascript

#39594 Add support for the x-office/drawing mimetype
  apps/files/appinfo/app.php
  changelog/10.9.0_2021-12-09/39594
  core/img/filetypes/x-office-drawing.svg
  core/js/mimetypelist.js
  core/templates/filetemplates/template.odg
  resources/config/mimetypealiases.dist.json
  resources/config/mimetypemapping.dist.json
Labels: enhancement, 3 - To Review

#39599 [tests-only] Add spaces as a new WebDAV url type
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39526 [full-ci] Bump PHP dependencies (since release-10.9.0)
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  changelog/unreleased/PHPdependencies20211123onward
  changelog/unreleased/PHPdependencies20211123onwardSymfony
  composer.lock
Labels: dependencies, php

#39612 [tests-only] Acceptance test changes pending for master
  .drone.star
  apps/provisioning_api/lib/Groups.php
  apps/provisioning_api/tests/GroupsTest.php
  changelog/unreleased/39540
  lib/private/Group/Manager.php
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/OcisHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiAuthWebDav/webDavPUTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPUTAuthOC10Issue39597.feature
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroups.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/copyFromPublicLinkOc10Issue37683.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/TransferOwnershipContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/cliDbConversion/dbConversion.feature
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
  tests/acceptance/features/cliMain/transfer-ownership.feature
  tests/acceptance/features/cliProvisioning/addGroup.feature
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/lib/Group/ManagerTest.php
Labels: QA:team

#39562 [tests-only] wait for services in drone acceptance tests
  .drone.star
Labels: QA:team

#39614 Add config.json file to gitignore
  .gitignore
Labels: 3 - To Review, technical debt

#39618 [tests-only] skip version author test on S3 object store
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA:team

#39619 [tests-only] skip new group name test on old oC10
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
Labels: QA:team

#39623 Prevent encrypted files from being corrupted when overwriting them
  changelog/unreleased/39623
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 10.9-regression

#39626 delete storage imports created by filesExternalWebdavOwncloud.feature:193
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
Labels: QA:team

#39629 [tests-only] skip new group name test on oC 10.9.1
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
Labels: QA:team

#39632 [Tests-Only]Skipped failing test on ldap with issue 702
  tests/acceptance/features/apiSharePublicLink2/copyFromPublicLinkOc10Issue37683.feature
Labels: QA:team
