Repository owncloud/core, pull requests merged in 2021-06, with the labels that each got.

#38796 [Tests-Only] fix getlastShareId function for acceptance tests
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38794 Skip initial permission check on setName method for shared mounts
  apps/dav/lib/Connector/Sabre/Node.php
  changelog/unreleased/38794
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShare.feature
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShareOc10Issue30325.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
  tests/acceptance/features/webUIRenameFolders/renameFoldersOc10Issue30325.feature
Labels: 3 - To Review

#38750 Change favicons and color references to match the new CI
  apps/dav/lib/HookManager.php
  apps/dav/tests/unit/DAV/HookManagerTest.php
  apps/federatedfilesharing/templates/settings-personal-general.php
  changelog/unreleased/38750
  core/css/apps.css
  core/css/header.css
  core/css/inputs.css
  core/css/jquery-ui-fixes.css
  core/css/systemtags.css
  core/img/favicon-fb.png
  core/img/favicon-mask.svg
  core/img/favicon-touch.png
  core/img/favicon-touch.svg
  core/img/favicon.ico
  core/img/favicon.png
  core/img/favicon.svg
  core/img/logo-mail.gif
  core/img/logo.svg
  core/templates/layout.base.php
  core/templates/layout.guest.php
  core/templates/layout.user.php
  lib/private/legacy/defaults.php
Labels: 3 - To Review

#38797 Update symfony to v4.4.25
  changelog/unreleased/38598-1
  composer.lock
Labels: dependencies, php

#38798 [tests-only] skip on old oC10 tests that were fixed in PR 38794
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShare.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: QA:team

#38801 Files versioning config
  config/config.apps.sample.php
  config/config.sample.php
Labels: 3 - To Review

#38737 Expose some license information through the LicenseManager
  changelog/unreleased/38737
  lib/private/License/BasicLicense.php
  lib/private/License/ILicense.php
  lib/private/License/LicenseManager.php
  lib/public/License/AbstractLicense.php
  lib/public/License/Exceptions/LicenseException.php
  lib/public/License/Exceptions/LicenseManagerException.php
  lib/public/License/Exceptions/LicenseRemoteException.php
  lib/public/License/ILicenseManager.php
Labels: 3 - To Review

#38793 Optional skip expiration validation for update share
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#38807 Fix config.sample and preview provider
  config/config.sample.php
  lib/private/PreviewManager.php
Labels: 3 - To Review

#38808 [tests-only] Update phpunit/phpunit (8.5.15 => 8.5.16)
  composer.lock
Labels: dependencies, php

#38810 Fix PDF preview provider
  config/config.sample.php
Labels: 3 - To Review

#38809 [tests-only] skip changed webUIAdminSettings tests on old oC10
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettingsOC10Issue36803.feature
Labels: QA:team

#38805 [Tests-Only] Add expire share tests
  .drone.star
  tests/acceptance/features/apiFederationToRoot2/federated.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/FederationContext.php
Labels: QA:team

#38811 Improved config key description for auto-provision for OIDC
  config/config.apps.sample.php
Labels: 4 - To release

#38812 [CI] Dont show apache logs for owncloud server in CI
  .drone.star
Labels: 3 - To Review, Drone, QA:team

#38789 [Tests-Only]earlyFail
  .drone.star
Labels: 3 - To Review

#38816 Add Workflow / Tagging config key
  config/config.apps.sample.php
Labels: 3 - To Review

#38823 [tests-only] Rename .php_cs.dist -> .php-cs-fixer.dist.php for v2.19
  .php-cs-fixer.dist.php
Labels: QA:team

#38819 Check a local attribute for the SMB log switch instead
  apps/files_external/lib/Lib/Storage/SMB.php
  changelog/unreleased/38819
Labels: 3 - To Review

#38767 Use file_exists instead of getting the file info
  apps/files/lib/Command/TransferOwnership.php
  changelog/unreleased/38767
  lib/private/Files/Node/Root.php
  tests/drone/test-phpunit.sh
  tests/lib/Files/Node/FolderTest.php
  tests/lib/Files/Node/RootTest.php
Labels: 3 - To Review

#38804 New cache state
  changelog/unreleased/38804
  lib/private/Files/Cache/Cache.php
  lib/private/Files/Cache/Propagator.php
  lib/private/Files/Cache/Scanner.php
  lib/private/Files/Cache/Wrapper/CacheJail.php
  lib/private/Files/Cache/Wrapper/CacheWrapper.php
  lib/private/Files/View.php
  lib/public/Files/Cache/ICache.php
  lib/public/Files/Cache/IScanner.php
  tests/lib/Files/Cache/CacheTest.php
  tests/lib/Files/Cache/ScannerTest.php
  tests/lib/Files/ViewTest.php
Labels: 3 - To Review

#38834 [tests-only] Support full-ci in PR title for CI
  .drone.star
Labels: QA:team

#38832 [tests-only] Tag userSync tests notToImplementOnOCIS
  tests/acceptance/features/apiMain/userSync.feature
Labels: QA:team

#38825 [Tests-Only]Add `notToImplementOnOcis` tags for old public link webdav tests
  tests/acceptance/features/apiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToRoot.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesOldDav.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/cliMain/transfer-ownership.feature
Labels: QA:team

#38840 New WND config key for Ldapmembership cache
  config/config.apps.sample.php
Labels: 3 - To Review

#38827 [Tests-Only] update test scenarios to work with ocis
  tests/TestHelpers/Asserts/WebDav.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiMain/checksums-TestOc10Issue38835.feature
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team, dev:acceptance-tests

#38787 fix search highlights for REPORT request
  apps/dav/lib/Connector/Sabre/FilesSearchReportPlugin.php
  apps/dav/tests/unit/Connector/Sabre/FilesSearchReportPluginTest.php
  changelog/unreleased/38787
Labels: 3 - To Review, minor-release

#38848 [tests-only] split apiShareOperationsTo... suites to reduce run time
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiShareOperationsToRoot1/accessToShare.feature
  tests/acceptance/features/apiShareOperationsToRoot1/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToRoot1/gettingShares.feature
  tests/acceptance/features/apiShareOperationsToRoot1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/apiShareOperationsToRoot1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/apiShareOperationsToRoot1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/apiShareOperationsToRoot1/gettingSharesSharedFilteredEmpty.feature
  tests/acceptance/features/apiShareOperationsToRoot2/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiShareOperationsToRoot2/shareAccessByID.feature
  tests/acceptance/features/apiShareOperationsToRoot2/uploadToShare.feature
  tests/acceptance/features/apiShareOperationsToShares1/accessToShare.feature
  tests/acceptance/features/apiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingSharesPendingFiltered.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingSharesReceivedFiltered.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingSharesReceivedFilteredEmpty.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingSharesSharedFiltered.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingSharesSharedFilteredEmpty.feature
  tests/acceptance/features/apiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/apiShareOperationsToShares2/uploadToShare.feature
Labels: QA:team

#38854 [tests-only] Skip bug demo for issue-38835 on S3 storage
  tests/acceptance/features/apiMain/checksums-TestOc10Issue38835.feature
Labels: QA:team

#38855 [Tests-Only] fix trashbin tests for ocis
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38841 introduce patch for CVE-2019-11358
  changelog/unreleased/38841
  core/js/js.js
Labels: 3 - To Review

#38857 [tests-only] Skip changed login tests on old oC10
  tests/acceptance/features/webUILogin/login.feature
Labels: QA:team

#38864 Make text for the http.cookie.samesite config value more clear
  config/config.sample.php
Labels: 3 - To Review

#38869 [tests-only] Cleanup good scenario for trashbinRestore issue-35974
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
Labels: QA:team

#38868 [tests-only] Allow for no unit tests with coverage in CI
  .drone.star
Labels: QA:team

#38872 [tests-only] Fix timing of browseToHomePage in acceptance tests
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPage.php
Labels: QA:team

#38875 [tests-only] Adjust GitHub comment on acceptance test fail
  .drone.star
Labels: QA:team

#38874 fix login form alignment
  core/css/styles.css
Labels: 3 - To Review

#38878 Bump doctrine/dbal (2.13.1 => 2.13.2)
  changelog/unreleased/38598-2
  composer.lock
Labels: dependencies, php

#38879 [tests-only] Update phpunit/phpunit (8.5.16 => 8.5.17)
  composer.lock
Labels: dependencies, php

#38876 [tests-only] Update issue tag and expected failures following product#207
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithDisabledUserOc10Issue32068.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupCaseSensitive.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/apiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/apiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToRoot.feature
  tests/acceptance/features/apiShareReshareToShares1/reShare.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareWithExpiryDateOc10Issue37013.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShareGroupAndUserWithSameName.feature
  tests/acceptance/features/apiSharingNotificationsToShares/sharingNotifications.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
Labels: QA:team

#38887 [tests-only] skip on old oC10 the test scenarios modified in PR 38880
  tests/acceptance/features/cliExternalStorage/cliIncomingShares.feature
Labels: QA:team

#38890 [tests-only] Updated tagged issue for share related scenarios after issue #1303
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/apiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA:team

#38896 [tests-only] [full-ci] Fix notifications tests due to changes in notifications PR 342
  tests/acceptance/features/apiSharingNotificationsToRoot/sharingNotifications.feature
  tests/acceptance/features/apiSharingNotificationsToShares/sharingNotifications.feature
Labels: QA:team

#38891 Bump PHP dependencies 2021-06-25
  changelog/unreleased/PHPdependencies20210625onward
  composer.json
  composer.lock
Labels: dependencies, php

#38919 [tests-only] Skip restrictSharing.feature:53 due to issue-38908
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
Labels: QA:team

#38914 [Tests-Only] skip tests for async file operations in ocis
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedNameAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectoryAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToBlacklistedNameUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunking.feature
Labels: 3 - To Review, QA:team, dev:acceptance-tests
