Repository owncloud/core, pull requests merged in 2021-02, with the labels that each got.

#38362 [tests-only] Fix minor typos noticed while sorting out expected-failures
  apps/files_sharing/lib/Controller/ShareesController.php
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/apiWebdavProperties1/getQuota.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
Labels: 3 - To Review, QA-team

#38364 [tests-only] Add replaceUsernames option to .drone.star
  .drone.star
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA-team

#38370 [tests-only] Fix tests with latest phpstan 0.12.71 release
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: 4 - To release, QA-team

#38380 Update sabre/vobject (4.3.3 => 4.3.4)
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  changelog/unreleased/38380
  composer.lock
Labels: 3 - To Review, dependencies, php

#38361 [tests-only] Expand API test coverage for hidden file
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavOperations/deleteFile.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#38374 [Tests-Only]make escaping/encoding case insensitive
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
Labels: 3 - To Review, QA:team

#38379 Allow passing DB platform
  changelog/unreleased/38379
  config/config.sample.php
  lib/private/DB/ConnectionFactory.php
Labels: 3 - To Review

#38387 Update christophwurst/id3parser (v0.1.1 => v0.1.2)
  changelog/unreleased/38387
  composer.lock
Labels: 3 - To Review, dependencies, php

#38385 Trigger events once
  apps/files/js/filelist.js
  apps/files_sharing/js/share.js
  changelog/unreleased/38385
Labels: 3 - To Review

#38389 Hide federated user suggestions when sharing if system users are found
  changelog/unreleased/38389
  core/js/sharedialogview.js
Labels: 3 - To Review

#38390 Prevent getting a version expiry list when no versions available
  apps/files_versions/lib/Storage.php
  changelog/unreleased/38373
Labels: 3 - To Review

#38366 [tests-only] Expand test coverage in apiTrashbin for unusual files/folders
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#38386 Added connection_parameters to redis and redis.cluster config section in order to allow redis with TLS/SSL
  changelog/unreleased/38386
  config/config.sample.php
  lib/private/RedisFactory.php
Labels: 3 - To Review

#38391 [tests-only] Add test for versions of renamed file
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: 3 - To Review, QA:team

#38393 [tests-only] Do not run occ group:list in OCIS CI
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA:team

#38396 Add the owner to public link shares
  changelog/unreleased/38396
  core/js/sharemodel.js
Labels: 3 - To Review

#38399 Update sabre dependencies
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  changelog/unreleased/38285
  changelog/unreleased/38380
  composer.lock
Labels: 4 - To release, dependencies, php

#38411 [tests-only] Refactor starlark
  .drone.star
Labels: QA:team

#38152 Allow removing shares which are invalid due to missing source fileid
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  changelog/unreleased/38152
  lib/private/Share20/DefaultShareProvider.php
  lib/private/Share20/Manager.php
  lib/public/Share/IManager.php
  lib/public/Share/IShareProvider.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 3 - To Review, minor-release

#38417 remove apps that are no longer in core from gitignore
  .gitignore
Labels: 3 - To Review

#38416 Expose non-generic messages for 403 HTTP status to the end user
  apps/files/js/file-upload.js
  changelog/unreleased/38416
Labels: 3 - To Review

#38369 [Tests-Only] add api test for webdav requests with multiple slashes in the endpoints
  tests/acceptance/features/apiAuthWebDav/webDavSpecialURLs.feature
  tests/acceptance/features/apiAuthWebDav/webdavMultiShashOC10Issue34365.feature
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38419 Update symfony/polyfill (1.22.0 => 1.22.1)
  changelog/unreleased/38275-3
  composer.lock
Labels: 3 - To Review, dependencies, php

#38415 Fix issues with duplicated file names in the same directory
  apps/files/js/fileactions.js
  apps/files/js/filelist.js
  changelog/unreleased/38415
  tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature
  tests/acceptance/features/webUISharingPublic2/shareByPublickLinkOc10Issue35177.feature
Labels: 3 - To Review

#38424 [Tests-Only] reduce runocc calls for acceptance tests
  tests/TestHelpers/LoggingHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38375 Fix problem with user-encryption when the a shared file is moved
  apps/files_trashbin/ajax/preview.php
  changelog/unreleased/38375
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3 - To Review

#38429 [tests-only] Specify a relative path to multiLanguageErrors.json in tests
  tests/acceptance/features/bootstrap/OCSContext.php
Labels: 3 - To Review, QA:team

#38433 [Tests-Only] Refactor api scenario outline examples
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v1/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v2/deleteUser.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, QA:team

#38443 [tests-only] Update phar-io/version (3.0.4 => 3.1.0)
  composer.lock
Labels: 3 - To Review, dependencies, php

#38446 [tests-only] Remove skeletondirectory
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/cliProvisioning/addUser.feature
  tests/acceptance/features/cliProvisioning/editUser.feature
  tests/acceptance/run.sh
Labels: 3 - To Review, QA:team

#38439 [Tests-Only] Adds API tests for counting number of etag elements in response of a versioned file
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#38450 [tests-only] Process unexpected passes for test suites that contain dash in the name
  tests/acceptance/run.sh
Labels: 3 - To Review, QA:team
