Repository owncloud/core, pull requests merged in 2021-03, with the labels that each got.

#38453 Update phpseclib/phpseclib from 2.0.30 to 3.0.3
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/Storage/SFTP.php
  changelog/unreleased/38453
  composer.json
  composer.lock
  core/Command/Integrity/SignApp.php
  core/Command/Integrity/SignCore.php
  lib/private/Files/External/LegacyUtil.php
  lib/private/IntegrityCheck/Checker.php
  lib/private/Security/Crypto.php
  tests/lib/IntegrityCheck/CheckerTest.php
Labels: 3 - To Review, dependencies, php

#38459 [tests-only] Adds API tests for sharing a same file twice to the same group
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: QA:team

#38464 [Tests-Only]Removed unused with/and skeleton files step from core
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#38466 [tests-only] TUS tests for checksum
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: 3 - To Review, QA:team

#38467 [tests-only] Skip new subadmin tests on old oC10
  tests/acceptance/features/apiProvisioningGroups-v1/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getSubAdminGroups.feature
Labels: 4 - To release, QA:team

#38376 pre-signed download urls for password protected public links
  apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
  apps/dav/lib/Files/PublicFiles/PublicShareSigner.php
  apps/dav/lib/Files/PublicFiles/PublicSharingAuth.php
  apps/dav/tests/unit/Files/PublicFiles/PublicShareSignerTest.php
  changelog/unreleased/38376
Labels: 3 - To Review, enhancement

#38473 [tests-only] skip password-reset test on user-keys encryption
  tests/acceptance/features/cliProvisioning/editUser.feature
Labels: 4 - To release, QA:team

#38452 Fix regression that occurred after #38375
  changelog/unreleased/38375
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3 - To Review

#38229 Integrity locks fixes
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/tests/unit/DAV/LockPluginTest.php
  lib/private/Lock/AbstractLockingProvider.php
  lib/private/Lock/MemcacheLockingProvider.php
  lib/private/legacy/files.php
  lib/public/IMemcache.php
Labels: 3 - To Review

#38482 [Tests-Only]Skip intermittent etag propagation tests on ocis on oc storage
  tests/acceptance/features/apiWebdavEtagPropagation2/restoreFromTrash.feature
Labels: QA:team

#38471 [tests-only]TUS tests for chunking with checksum
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: 3 - To Review, QA:team

#38477 feat: add samesite cookie attribute to session cookie
  changelog/10.7.0_2021-03-08/38458
  config/config.sample.php
  lib/private/Session/CryptoWrapper.php
  lib/private/Session/Internal.php
Labels: 3 - To Review

#38481 Add exceptions messages whenever a node cannot be moved
  apps/dav/lib/Connector/Sabre/Directory.php
  changelog/unreleased/38481
Labels: enhancement

#38487 Update PHP dependencies
  changelog/unreleased/38487
  composer.lock
Labels: 3 - To Review, dependencies, php

#38444 [Tests-Only] Refactor api scenario outline examples (part2)
  tests/acceptance/features/apiComments/comments.feature
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v1/enableUser.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addGroupOc10Issue31015.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/deleteGroupOc10Issue31015.feature
  tests/acceptance/features/apiProvisioningGroups-v1/removeFromGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroup.feature
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, QA:team

#38483 Disable sharing on files_external if auth mechanism is not compatible
  apps/files_external/js/settings.js
  changelog/unreleased/38483
Labels: 3 - To Review

#38448 [Tests-Only] Refactor api scenario outline examples (part3)
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/apiProvisioningGroups-v1/removeFromGroupOc10Issue31015.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addGroupOc10Issue31015.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroupOc10Issue31015.feature
  tests/acceptance/features/apiProvisioningGroups-v2/deleteGroupOc10Issue31015.feature
  tests/acceptance/features/apiProvisioningGroups-v2/removeFromGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/removeFromGroupOc10Issue31015.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, QA:team

#38488 [tests-only] Add tests for issue-ocis-1747
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/apiWebdavUploadTUS/optionsRequest.feature
Labels: 3 - To Review, QA:team

#38484 [tests-only] Tus tests for uploading to shared files with checksums
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
Labels: 3 - To Review, QA:team

#38489 fix: require search param to not be empty
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/tests/API/ShareesTest.php
  changelog/unreleased/38489
Labels: 3 - To Review

#38491 [Tests-Only] Add acceptance tests for sharees min search length
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiSharees/sharees.feature
  tests/acceptance/features/apiSharees/shareesIssue38501.feature
  tests/acceptance/features/bootstrap/ShareesContext.php
Labels: QA:team, dev:acceptance-tests

#38509 [tests-only] skip new user.search_min_length tests on old oC10
  tests/acceptance/features/apiSharees/sharees.feature
Labels: 3 - To Review, QA:team

#38492 [tests-only] Added tests for overwriting file with checksum
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
  tests/acceptance/features/bootstrap/TUSContext.php
Labels: 3 - To Review, QA:team

#38490 [Tests-Only] Add acceptance tests for resharing deleted file
  tests/acceptance/features/apiShareReshareToRoot1/reShare.feature
  tests/acceptance/features/apiShareReshareToShares1/reShare.feature
Labels: 3 - To Review, QA:team

#38470 [tests-only] send occ commands in bulk to the testing app
  tests/acceptance/run.sh
Labels: QA:team

#38511 [tests-only] added comment in tests for encoded filename
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
Labels: 3 - To Review, QA:team

#38493 [Tests-Only] Refactor scenario steps
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroup.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, QA:team

#38504 [tests-only] Adds api tests for overwiting file with checksums
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
Labels: QA:team

#38527 [tests-only] Remove accidentally-added unlockOnDelete.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockOnDelete.feature
Labels: 3 - To Review, QA:team

#38528 [docs-only] Fixup changelogs edited in PR 38524
  changelog/unreleased/38462
  changelog/unreleased/38462-3
  changelog/unreleased/38462-4
  changelog/unreleased/38524
  changelog/unreleased/38524-3
  changelog/unreleased/38524-4
Labels: 3 - To Review

#38546 [tests-only] Update phpunit/phpunit (8.5.14 => 8.5.15)
  composer.lock
Labels: QA:team

#38512 [tests-only] Adds API tests to create tag in lowercase and uppercase
  tests/acceptance/features/apiTags/createTags.feature
Labels: QA:team

#38532 fix downloadURL of public links
  apps/dav/lib/Files/PublicFiles/PublicFilesPlugin.php
  changelog/10.7.0_2021-03-15/38376
Labels: 3 - To Review

#38533 [Tests-Only] used skeleton files more wisely on api share operations to features
  tests/acceptance/features/apiShareOperationsToRoot/accessToShare.feature
  tests/acceptance/features/apiShareOperationsToRoot/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToRoot/gettingShares.feature
  tests/acceptance/features/apiShareOperationsToRoot/uploadToShare.feature
  tests/acceptance/features/apiShareOperationsToShares/accessToShare.feature
  tests/acceptance/features/apiShareOperationsToShares/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToShares/gettingShares.feature
  tests/acceptance/features/apiShareOperationsToShares/uploadToShare.feature
Labels: QA:team

#38550 [Tests-Only] removed phpstan skip
  lib/private/legacy/util.php
Labels: QA:team

#38548 [10.7.0] Compress changelogs for 10.7.0 release
  changelog/10.7.0_2021-03-15/38188
  changelog/10.7.0_2021-03-15/38191
  changelog/10.7.0_2021-03-15/38198
  changelog/10.7.0_2021-03-15/38244
  changelog/10.7.0_2021-03-15/38255
  changelog/10.7.0_2021-03-15/38275
  changelog/10.7.0_2021-03-15/38275-2
  changelog/10.7.0_2021-03-15/38285
  changelog/10.7.0_2021-03-15/38306
  changelog/10.7.0_2021-03-15/38312
  changelog/10.7.0_2021-03-15/38344
  changelog/10.7.0_2021-03-15/38380
  changelog/10.7.0_2021-03-15/38387
  changelog/10.7.0_2021-03-15/38453
  changelog/10.7.0_2021-03-15/38462
  changelog/10.7.0_2021-03-15/38462-2
  changelog/10.7.0_2021-03-15/38462-3
  changelog/10.7.0_2021-03-15/38487
  changelog/10.7.0_2021-03-15/38508
Labels: 3 - To Review

#38516 [Tests-Only] used skeleton files more wisely on capabilites and comments part of API tests
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiComments/comments.feature
  tests/acceptance/features/apiComments/createComments.feature
  tests/acceptance/features/apiComments/deleteComments.feature
  tests/acceptance/features/apiComments/editComments.feature
Labels: QA:team

#38515 [Tests-Only] used skeleton files more wisely on favorites and main part of API tests
  tests/acceptance/features/apiMain/caldav.feature
  tests/acceptance/features/apiMain/carddav.feature
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiMain/quota.feature
Labels: QA:team, dev:acceptance-tests

#38541 [Tests-Only] used skeleton files more wisely on api tags, translation and trashbin test features
  tests/acceptance/features/apiTags/assignTags.feature
  tests/acceptance/features/apiTags/assignTagsGroup.feature
  tests/acceptance/features/apiTags/createTags.feature
  tests/acceptance/features/apiTags/deleteTags.feature
  tests/acceptance/features/apiTags/editTags.feature
  tests/acceptance/features/apiTags/retreiveTags.feature
  tests/acceptance/features/apiTags/unassignTags.feature
  tests/acceptance/features/apiTranslation/translation.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToRoot.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToShares.feature
Labels: QA:team

#38537 [Tests-Only] used skeleton files more wisely on api share reshare features
  tests/acceptance/features/apiShareReshareToRoot1/reShare.feature
  tests/acceptance/features/apiShareReshareToRoot2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToRoot2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToRoot2/reShareSubfolder.feature
  tests/acceptance/features/apiShareReshareToRoot2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareReshareToRoot3/reShareUpdate.feature
  tests/acceptance/features/apiShareReshareToRoot3/reShareWithExpiryDate.feature
  tests/acceptance/features/apiShareReshareToShares1/reShare.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareWithExpiryDateOc10Issue37013.feature
Labels: QA:team

#38576 [10.7] config.apps.sample update for wnd
  config/config.apps.sample.php
Labels: 3 - To Review

#38578 [Tests-Only] Fix duplicate scenario names and remove duplicate scenarios
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiComments/deleteComments.feature
  tests/acceptance/features/apiProvisioning-v1/getUsers.feature
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
  tests/acceptance/features/apiProvisioning-v2/getUsers.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/removeFromGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/removeFromGroup.feature
  tests/acceptance/features/apiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/apiShareOperationsToShares/gettingShares.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharees/sharees.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFoldersOc10Issue23151.feature
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToRoot.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavProperties1/createFolder.feature
  tests/acceptance/features/cliMain/transfer-ownership.feature
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUIWebdavLocks/locksOc10Issue33867.feature
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38468 [Tests-Only] Refactor scenarios with large skeleton files
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIFiles/fileDetails.feature
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUIManageQuota/manageUserQuota.feature
  tests/acceptance/features/webUIManageUsersGroups/deleteUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/disableUsers.feature
  tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAutocompletion1/shareAutocompletion.feature
  tests/acceptance/features/webUISharingAutocompletion2/shareAutocompletionWithDifferentPatterns.feature
  tests/acceptance/features/webUISharingInternalGroups1/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroups2/shareWithGroupUsingExpirationDate.feature
  tests/acceptance/features/webUISharingInternalGroups2/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalUsers1/createShareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsers1/miscShareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsers1/miscShareWithUsersOc10Issue35787.feature
  tests/acceptance/features/webUISharingInternalUsers2/shareWithUserUsingExpirationDate.feature
  tests/acceptance/features/webUISharingInternalUsers2/webUIShareDetails.feature
  tests/acceptance/features/webUISharingPublic1/permissionsShareByPublicLink.feature
  tests/acceptance/features/webUITags/createTags.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/locksOc10Issue33867.feature
  tests/acceptance/features/webUIWebdavLocks/locksOc10Issue34315.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: 3 - To Review, QA:team

#38570 [tests-only] prepare required resources rather than using skeleton dirs in API webdav properties and upload test features
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
  tests/acceptance/features/apiWebdavProperties1/getQuota.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedNameAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectoryAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToBlacklistedNameUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToBlacklistedNameUsingOldChunkingOc10Issue36645.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToExcludedDirectoryUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToExcludedDirectoryUsingOldChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToExcludedDirectoryUsingOldChunkingOc10Issue36645.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunkingOc10Issue36115.feature
Labels: QA:team

#38536 [Tests-Only] used small skeletons more wisely on API public link share features
  tests/acceptance/features/apiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareOc10Issue36442.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareOc10Issue37605.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareToShares.feature
  tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToRoot.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesOldDav.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShareOc10Issue37653.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
Labels: QA:team

#38564 [tests-only] Prepare required resources rather than using skeleton director on API WebDav lock tests
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/exclusiveLocksOc10Issue34358.feature
  tests/acceptance/features/apiWebdavLocks/folder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkOc10Issue36064.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithTokenOc10Issue34338.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithTokenOc10Issue34360.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesOc10Issue36064.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToShares.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocks.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockOc10Issue34302.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToRoot.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
Labels: QA:team

#38569 [tests-only] prepare required resources rather than using skeleton directories in API WebDav move, operations and preview features
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/apiWebdavOperations/search.feature
Labels: QA:team

#38594 [tests-only] used small skeleton files in getQuota feature
  tests/acceptance/features/apiWebdavProperties1/getQuota.feature
Labels: QA:team

#38581 when creating self group-reshare do not share to self
  changelog/unreleased/38581
  lib/private/Share20/Manager.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/webUISharingInternalGroups2/shareWithGroupsEdgeCases.feature
  tests/lib/Share20/ManagerTest.php
Labels: 4 - To release

#38538 [Tests-Only] used skeleton files more wisely on api share update to and share notifications to features
  tests/acceptance/features/apiShareUpdateToRoot/updateShare.feature
  tests/acceptance/features/apiShareUpdateToRoot/updateShareOc10Issue37217.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShareOc10Issue37217.feature
  tests/acceptance/features/apiSharingNotificationsToRoot/sharingNotifications.feature
  tests/acceptance/features/apiSharingNotificationsToShares/sharingNotifications.feature
Labels: QA:team

#38517 [Tests-Only] used small skeleton directory more wisely on API share create special features
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareWhenExcludedFromSharing.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareGroupCaseSensitive.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithDisabledUser.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithDisabledUserOc10Issue32068.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareWhenExcludedFromSharing.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupCaseSensitive.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWithDisabledUser.feature
Labels: QA:team

#38579 [tests-only] prepare required resources rather than using skeleton files in API federation test features
  tests/acceptance/features/apiFederationToRoot1/etagPropagation.feature
  tests/acceptance/features/apiFederationToRoot1/federated.feature
  tests/acceptance/features/apiFederationToRoot1/federatedOc10Issue31276.feature
  tests/acceptance/features/apiFederationToRoot2/federated.feature
  tests/acceptance/features/apiFederationToRoot2/federatedOc10Issue35839.feature
  tests/acceptance/features/apiFederationToShares1/etagPropagation.feature
  tests/acceptance/features/apiFederationToShares1/federated.feature
  tests/acceptance/features/apiFederationToShares2/federated.feature
Labels: QA:team

#38514 [Tests-Only] used small skeleton dirs more wisely on apiAuth feature tests
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuth/corsOc10Issue34679.feature
  tests/acceptance/features/apiAuth/filesAppAuth.feature
  tests/acceptance/features/apiAuth/tokenAuth.feature
  tests/acceptance/features/apiAuth/webDavAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsPOSTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavDELETEAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavLOCKAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavMOVEAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPOSTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPROPFINDAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPROPPATCHAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPUTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webdavMultiShashOC10Issue34365.feature
Labels: QA:team
