Repository owncloud/core, pull requests merged in 2021-10, with the labels that each got.

#39314 Fix file version names for share recipients
  changelog/unreleased/39314
  lib/private/Files/Meta/MetaFileVersionNode.php
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToSharesIssue36228.feature
Labels: 3 - To Review

#39317 Upgrading doctrine/dbal (2.13.3 => 2.13.4)
  .drone.star
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39313 [tests-only] added scenario to assert Devanagari in file preview
  tests/acceptance/features/apiWebdavPreviews/previews.feature
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/fixtures/सिमसिमे-पानी.png
Labels: QA:team

#39276 [tests-only] added scenarios for public quick links uniqueness for a resource
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/webUISharingPublic1/createPublicLinkShares.feature
Labels: QA:team

#39161 [tests-only] testing under given browser's SCREEN_RESOLUTION
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUINotificationsContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/lib/NotificationsEnabledOwncloudPage.php
  tests/acceptance/features/lib/TrashbinPage.php
  tests/acceptance/features/webUICreateDelete/createFolders.feature
  tests/acceptance/features/webUICreateDelete/createFoldersEdgeCases.feature
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFavorites/unfavoriteFile.feature
  tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
  tests/acceptance/features/webUIFiles/hiddenFile.feature
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUILogin/login.feature
  tests/acceptance/features/webUILogin/resetPassword.feature
  tests/acceptance/features/webUILogin/resetPasswordUsingEmail.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUIRenameFiles/renameFile.feature
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingAutocompletion1/shareAutocompletion.feature
  tests/acceptance/features/webUISharingInternalGroups1/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers1/createShareWithUsers.feature
  tests/acceptance/features/webUISharingNotifications/notificationLink.feature
  tests/acceptance/features/webUISharingNotifications/shareWithUsers.feature
  tests/acceptance/features/webUISharingPublic1/createPublicLinkShares.feature
  tests/acceptance/features/webUISharingPublic2/reShareByPublicLink.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
  tests/acceptance/features/webUIUpload/upload.feature
  tests/acceptance/features/webUIUpload/uploadEdgecases.feature
  tests/acceptance/features/webUIUpload/uploadFileGreaterThanQuotaSize.feature
Labels: QA:team

#39318 [tests-only] Fix default value of parameter to assertLogFileContainsAtLeastOneEntryMatchingTable
  tests/acceptance/features/bootstrap/LoggingContext.php
Labels: QA:team

#39319 [tests-only] [full-ci] Fix call to matchNotification in acceptance tests
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
Labels: QA:team

#39323 [Tests-Only][CI] added step to wait for selenium for acceptance test suites
  .drone.star
Labels: QA:team

#39322 [tests-only] added previews update scenarios for user and group sharing
  tests/acceptance/features/apiWebdavPreviews/previews.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39439 [tests-only] Bump phpunit/php-code-coverage (9.2.7 => 9.2.8)
  composer.lock
Labels: dependencies, php

#39440 Bump symfony/console (v4.4.30 => v4.4.33)
  changelog/unreleased/PHPdependencies20210727onwardSymfony
  composer.lock
Labels: dependencies, php
