Repository owncloud/core, pull requests merged in 2021-09, with the labels that each got.

#39162 Fix file conflict dialog when dragging a file into a folder
  apps/files/js/file-upload.js
  changelog/unreleased/39162
Labels: 3 - To Review

#39168 Return proper error if part file name is too long
  apps/dav/lib/Connector/Sabre/Exception/FileNameTooLong.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/tests/unit/Connector/Sabre/FileTest.php
  changelog/unreleased/39088
  changelog/unreleased/39168
  config/config.sample.php
  lib/private/Files/Filesystem.php
  lib/private/Files/Stream/Checksum.php
  tests/lib/Files/FilesystemTest.php
Labels: 3 - To Review

#39108 Update appinfo cache only if the app version is newer
  changelog/unreleased/39108
  lib/private/App/AppManager.php
Labels: 2 - Developing

#39167 Avoid duplication of public quick links on the same resource
  apps/files_sharing/js/share.js
  apps/files_sharing/tests/js/shareSpec.js
  changelog/unreleased/39130
Labels: 3 - To Review

#39164 [tests-only]Public quick link button uitests
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php
  tests/acceptance/features/webUISharingPublic1/createPublicLinkShares.feature
Labels: QA:team

#39180 [tests-only] skip changed tests on old oC10
  tests/acceptance/features/webUIAdminSettings/adminSharingSettings.feature
  tests/acceptance/features/webUISharingExternal2/createFederationSharing.feature
  tests/acceptance/features/webUITags/deleteTags.feature
  tests/acceptance/features/webUITags/editTags.feature
Labels: QA:team

#39198 Set files_list to empty array if we don't have any selected files
  apps/files/ajax/download.php
  changelog/unreleased/39198
Labels: 3 - To Review

#39200 [tests-only] Enable and fix acceptance tests for issue #37217
  tests/acceptance/features/apiShareUpdateToRoot/updateShare.feature
  tests/acceptance/features/apiShareUpdateToRoot/updateShareOc10Issue37217.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShareOc10Issue37217.feature
Labels: 3 - To Review

#39204 fix: use correct controller name in dav routes.php
  apps/dav/appinfo/routes.php
  changelog/unreleased/38838
Labels: 3 - To Review

#39201 Bump laminas dependencies
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39186 Don't show exact search results with empty sharee search query
  apps/files_sharing/lib/Controller/ShareesController.php
  apps/files_sharing/tests/API/ShareesTest.php
  changelog/unreleased/39186
  tests/acceptance/features/apiSharees/sharees.feature
  tests/acceptance/features/apiSharees/shareesIssue38501.feature
Labels: 3 - To Review

#39209 [tests-only] Update phpspec/prophecy (1.13.0 => 1.14.0)
  composer.lock
Labels: dependencies, php

#39203 Fix preview rendering for sharees
  changelog/unreleased/39202
  lib/private/Preview.php
  tests/lib/PreviewTest.php
Labels: 2 - Developing

#39174 [tests-only]Adds UI tests for local external storage
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/ExternalStoragePage.php
  tests/acceptance/features/webUIFiles/externalStorage.feature
Labels: QA:team

#39214 Upgrading doctrine/dbal (2.13.2 => 2.13.3)
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39219 [tests-only] skip intermittent test - issue 39213
  tests/acceptance/features/webUIComments/comments.feature
Labels: QA:team

#39218 fix: login redirect url has to hold the msofba-success route which wa…
  apps/dav/lib/Connector/Sabre/MSOFBAPlugin.php
  apps/dav/tests/unit/Connector/Sabre/MSOFBAPluginTest.php
  changelog/unreleased/38838
Labels: 3 - To Review

#39228 Add option to hide the upload estimation in WebUI
  apps/files/js/file-upload.js
  apps/files/lib/App.php
  apps/files/tests/js/fileUploadSpec.js
  changelog/unreleased/39228
Labels: 3 - To Review

#39136 feat: new command to move a user's home folder - occ user:move-home
  changelog/unreleased/39136
  core/Command/User/MoveHome.php
  core/register_command.php
  lib/private/User/DeletedUser.php
  lib/private/User/RemoteUser.php
  lib/private/User/User.php
  lib/public/IUser.php
  tests/Core/Command/User/MoveHomeTest.php
Labels: 3 - To Review

#39231 [tests-only] Refactor create read-only link function to avoid flakyness
  tests/acceptance/features/bootstrap/WebUISharingContext.php
Labels: QA:team

#39235 Return proper error when destination header is missing
  apps/dav/lib/Connector/Sabre/FilesPlugin.php
  changelog/unreleased/39235
  tests/acceptance/features/apiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestoreOc10Issue38898.feature
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: 3 - To Review

#39105 Include a flag to mark if the loginName2userName has been processed
  apps/federatedfilesharing/lib/Address.php
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  changelog/unreleased/39105
  lib/private/Share/Helper.php
  lib/private/User/Database.php
  lib/private/User/Session.php
Labels: 3 - To Review

#39184 Display clickable links in upgrade process
  changelog/unreleased/39184
  core/js/update.js
Labels: 3 - To Review

#39251 [tests-only] Fix Guzzle7 exception handling in HttpRequestHelper
  tests/TestHelpers/HttpRequestHelper.php
Labels: QA:team

#39245 [full-ci][tests-only] Add type declarations in tests part 1
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/AppManagementContext.php
Labels: QA:team

#39220 [tests-only] Adds uitests for downloading resources
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/webUIFiles/download.feature
Labels: QA:team

#39241 [full-ci] Hide share owner file path for share receiver
  apps/files_sharing/lib/Controller/Share20OcsController.php
  changelog/unreleased/39241
  tests/acceptance/features/apiFavorites/favoritesOc10Issue38027.feature
  tests/acceptance/features/apiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareFromLocalStorageToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShareFromLocalStorage.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/apiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToSharesIssue38027.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToShares.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 2 - Developing

#39265 [tests-only][full-ci]Add type declaration and return type in functions part 2
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/ChecksumContext.php
Labels: QA:team

#39267 Fix doc placeholder URL in general-settings
  changelog/unreleased/39267
  core/js/setupchecks.js
Labels: 3 - To Review

#39270 [tests-only] [full-ci]Add type declaration and return type in functions part 3
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/CommentsContext.php
  tests/acceptance/features/bootstrap/CorsContext.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/acceptance/features/bootstrap/FavoritesContext.php
  tests/acceptance/features/bootstrap/FederationContext.php
Labels: QA:team

#39274 Added wait before click on share quick action button and removed skip…
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
Labels: QA:team

#39268 [tests-only] added api acceptance tests for previews update feature after change in file content
  tests/acceptance/features/apiWebdavPreviews/previews.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39272 Fix issues when setting 0 as user display name
  changelog/unreleased/39272
  lib/private/User/Database.php
  lib/private/User/User.php
Labels: 3 - To Review

#39277 [tests-only] Skip editUsers test that was changed in PR 39262 on old oC10
  tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
Labels: QA:team

#39284 [tests-only] Fix acceptance tests for oCIS
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiWebdavPreviews/previews.feature
Labels: QA:team

#39289 [tests-only] Bump phpunit/phpunit (8.5.20 => 8.5.21) and other dependencies
  composer.lock
Labels: dependencies, php

#39293 Use original UID when setting the share receiver
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  changelog/unreleased/39293
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: 3 - To Review

#39300 Fix versions for files named '0'
  apps/files_versions/lib/Storage.php
  apps/files_versions/tests/VersioningTest.php
  changelog/unreleased/39300
Labels: 3 - To Review

#39299 Change user casing log level to 'debug'
  changelog/unreleased/39299
  lib/private/Files/Filesystem.php
Labels: 3 - To Review

#39302 Hide the 'Remove Password' button on public links
  changelog/unreleased/39302
  core/js/sharedialoglinkshareview.js
Labels: 3 - To Review

#39305 [tests-only] skip more sharing scenarios on old oC10
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UsersPage.php
Labels: QA:team

#39304 [tests-only] [full-ci] Add type declarations to functions part-5
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/IpContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
Labels: QA:team

#39309 [tests-only][full-ci] Add type declarations to functions part-6
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/OccAppManagementContext.php
  tests/acceptance/features/bootstrap/OccContext.php
Labels: QA:team
