Repository owncloud/core, pull requests merged in 2021-05, with the labels that each got.

#38680 Update symfony components to 4.4.22
  changelog/unreleased/38598-1
  composer.lock
Labels: dependencies, php

#38688 Update psr/log (1.1.3 to 1.1.4)
  changelog/unreleased/38598-2
  composer.lock
Labels: dependencies, php

#38695 [Tests-Only]Reverts unwanted changes
  tests/TestHelpers/OcisHelper.php
Labels: QA:team

#38696 [Tests-only] Refactors API tests so that they follow appropriate grammatical order
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/apiShareOperationsToRoot/uploadToShare.feature
  tests/acceptance/features/apiShareOperationsToShares/uploadToShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareOc10Issue37605.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/apiTags/createTags.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavOperations/deleteFolder.feature
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#38700 [tests-only] Bump phan analysis to v4.0
  vendor-bin/phan/composer.json
Labels: QA:team

#38701 [tests-only] Add ability to skip pipelines in CI
  .drone.star
Labels: QA:team

#38687 [tests-only] Adds API test to create share from local storage
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareFromLocalStorageToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareFromLocalStorageToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShareFromLocalStorage.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShareFromLocalStorage.feature
Labels: QA:team

#38714 Adjust the return type of the querybuilder's execute method
  changelog/unreleased/38714
  lib/public/DB/QueryBuilder/IQueryBuilder.php
Labels: technical debt

#38718 [tests-only] Skip some local storage tests on user-keys encryption
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareFromLocalStorageToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareFromLocalStorageToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShareFromLocalStorage.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShareFromLocalStorage.feature
Labels: QA:team

#38693 Regenerate session for anonymous user after succesfully auth
  apps/files_sharing/lib/AppInfo/Application.php
  apps/files_sharing/lib/Controllers/ShareController.php
  apps/files_sharing/tests/Controllers/ShareControllerTest.php
  changelog/unreleased/38693
Labels: 3 - To Review

#38719 use filter_var instead of (bool)
  apps/dav/lib/SystemTag/SystemTagPlugin.php
  changelog/unreleased/38719
Labels: 3 - To Review

#38720 [tests-only] Feature to debug specific test suites in CI
  .drone.star
Labels: QA:team

#38465 fix: use trusted domains to verify the signature
  changelog/unreleased/38465
  lib/private/Security/SignedUrl/Verifier.php
  tests/lib/Security/SignedUrl/VerifierTest.php
Labels: 3 - To Review

#38730 Update symfony components to 4.4.23
  changelog/unreleased/38598-1
  composer.lock
Labels: dependencies, php

#38354 [Tests-Only] Files external php unit tests
  .drone.star
  apps/files_external/tests/Storage/OwncloudTest.php
  tests/drone/configs/config.files_external.owncloud.php
  tests/drone/test-phpunit.sh
  tests/lib/Files/Storage/Storage.php
Labels: QA:team

#38622 [tests-only] Specify path of server under test
  .drone.star
Labels: QA:team, dev:acceptance-tests

#38736 [tests-only] Only do composer install if composer.json exists in the notifications app
  .drone.star
Labels: QA:team

#38656 Allow easier rename of shared mount
  apps/files_sharing/lib/SharedMount.php
  changelog/unreleased/38656
Labels: 3 - To Review, minor-release

#38734 [tests-only] Fix path encoding in tests steps
  tests/acceptance/features/apiFederationToRoot1/federatedOc10Issue31276.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
  tests/acceptance/features/webUISharingExternal2/acceptDeclineFederatedShares.feature
  tests/acceptance/features/webUISharingExternal2/acceptDeclineFederatedSharesOc10Issue34742.feature
Labels: QA:team

#38740 [Tests-Only] do not use remember capabilities for acceptance tests
  tests/TestHelpers/AppConfigHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team, dev:acceptance-tests

#38755 Update symfony components to 4.4.24
  changelog/unreleased/38598-1
  composer.lock
Labels: dependencies, php

#38756 [tests-only] add commas in .drone.star and skip some tests on old oC10 versions
  .drone.star
  tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature
Labels: QA:team

#38753 Add new options to config.sample.php
  changelog/unreleased/38753
  config/config.apps.sample.php
Labels: 2 - Developing

#38649 Improve move performance by doing only one query if possible
  changelog/unreleased/38649
  lib/private/AppFramework/Db/Db.php
  lib/private/DB/AdapterOCI8.php
  lib/private/Files/Cache/Cache.php
  lib/public/IDBConnection.php
Labels: 3 - To Review

#38699 Fix potential problems with the cache due to removing wrong data
  apps/files_external/lib/Lib/Storage/SMB.php
Labels: 3 - To Review

#38728 Mount encrypt password
  apps/files_external/appinfo/Migrations/Version20210511082903.php
  apps/files_external/appinfo/info.xml
  apps/files_external/lib/Command/ListCommand.php
  changelog/unreleased/38728
  lib/private/Files/External/Service/DBConfigService.php
  lib/private/Files/External/Service/StoragesService.php
  lib/private/Files/External/Service/UserGlobalStoragesService.php
  lib/private/Files/External/Service/UserStoragesService.php
  lib/private/Server.php
  tests/acceptance/features/cliLocalStorage/manageBackendConfig.feature
  tests/lib/Files/External/Service/GlobalStoragesServiceDeleteUserTest.php
  tests/lib/Files/External/Service/GlobalStoragesServiceTest.php
  tests/lib/Files/External/Service/StoragesServiceTest.php
  tests/lib/Files/External/Service/UserGlobalStoragesServiceTest.php
  tests/lib/Files/External/Service/UserStoragesServiceTest.php
Labels: 3 - To Review

#38762 [tests-only] Remove tech_preview steps from feature files
  tests/acceptance/features/apiFavorites/favoritesOc10Issue38027.feature
  tests/acceptance/features/apiFavorites/favoritesSharingToShares.feature
  tests/acceptance/features/apiShareOperationsToRoot/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToShares/changingFilesShare.feature
  tests/acceptance/features/apiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareToShares.feature
  tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/apiSharePublicLink2/copyFromPublicLinkOc10Issue37683.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFoldersOc10Issue23151.feature
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/apiTrashbin/trashbinRestoreOc10Issue35900.feature
  tests/acceptance/features/apiTrashbin/trashbinRestoreOc10Issue35974.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToRoot.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToSharesIssue38027.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/restoreFromTrash.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkOc10Issue36064.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesOc10Issue36064.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToShares.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/bootstrap/OccContext.php
Labels: QA:team

#38761 [Tests-Only]Add tests containing `[` and `]` in path names
  .drone.star
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
Labels: 3 - To Review

#38768 [tests-only] Add more test cases for issue 30325
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShareOc10Issue30325.feature
Labels: 3 - To Review, QA:team

#38721 [tests-only] Test creating tags with true/false string settings
  tests/TestHelpers/TagsHelper.php
  tests/acceptance/features/apiTags/createTags.feature
  tests/acceptance/features/bootstrap/TagsContext.php
Labels: QA:team

#38757 [Tests-Only] add api tests for accessing shares by id
  tests/acceptance/features/apiShareOperationsToRoot/shareAccessByID.feature
  tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38744 [Tests-Only] preview tests modified for ocis server
  tests/acceptance/features/apiWebdavPreviews/previews.feature
Labels: QA:team

#38603 Configurable web rewrite
  changelog/unreleased/38602
  config/config.sample.php
  core/routes.php
  lib/private/NavigationManager.php
Labels: 3 - To Review

#38778 Fix image preview for file versions
  changelog/unreleased/38778
  lib/private/Preview/Image.php
Labels: 3 - To Review

#38776 [tests-only] clear the dependency cache on merge CI
  .drone.star
Labels: QA:team

#38764 [tests-only] Add webUI test coverage for adding public share to oC
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/PublicLinkFilesPage.php
  tests/acceptance/features/webUISharingPublic2/savePublicLinkShare.feature
  tests/acceptance/features/webUISharingPublic2/savePublicLinkShareOc10Issue38763.feature
Labels: QA:team

#38773 Fix migration by loading the app without checking, after correct update
  apps/files_external/appinfo/Migrations/Version20210511082903.php
Labels: 3 - To Review

#38783 Switch order to prevent double-replacement in the query
  lib/private/Files/Cache/Cache.php
Labels: 3 - To Review

#38785 Prevent files:checksum:verify from crashing on exception
  apps/files/lib/Command/VerifyChecksums.php
  changelog/unreleased/38785
Labels: 3 - To Review

#38780 [Tests-Only] add tests for sharing the shares_folder
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38786 Update PHP dependencies
  changelog/unreleased/38598-1
  changelog/unreleased/38598-2
  composer.lock
Labels: dependencies, php

#38784 [tests-only] skip some tags tests on old oC10
  tests/acceptance/features/apiTags/assignTags.feature
  tests/acceptance/features/apiTags/assignTagsGroup.feature
  tests/acceptance/features/apiTags/createTags.feature
  tests/acceptance/features/apiTags/deleteTags.feature
  tests/acceptance/features/apiTags/editTags.feature
  tests/acceptance/features/apiTags/retreiveTags.feature
  tests/acceptance/features/apiTags/unassignTags.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
Labels: QA:team

#38781 [tests-only] Minor adjustments to tests added in 38757
  tests/acceptance/features/apiShareOperationsToShares/shareAccessByID.feature
Labels: QA:team

#38790 [tests-only] skip new savePublicLinkShare tests on old oC10
  tests/acceptance/features/webUISharingPublic2/savePublicLinkShare.feature
  tests/acceptance/features/webUISharingPublic2/savePublicLinkShareOc10Issue38763.feature
Labels: QA:team

#38747 [Tests-Only] add api tests for trashbin skip config
  tests/acceptance/features/apiTrashbin/trashbinSkip.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUITags/tagsSuggestion.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUITrashbin/trashbinRestore.feature
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38792 [tests-only] skip new trashbinSkip tests on old oC10
  tests/acceptance/features/apiTrashbin/trashbinSkip.feature
Labels: QA:team
