Repository owncloud/core, pull requests merged in 2021-01, with the labels that each got.

#38260 [tests-only] Refactor check deleted_mtime tests
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: 3 - To Review, QA-team, dev:acceptance-tests

#38268 [tests-only] skipOnOcis-OC-Storage for test scenarios that are intermittent
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
Labels: 3 - To Review, QA-team

#38270 [tests-only] Zend to laminas
  tests/Core/Command/Db/ConvertTypeTest.php
  tests/Core/Command/User/DeleteTest.php
  tests/Core/Controller/LostControllerTest.php
  tests/Core/Controller/UserSyncControllerTest.php
  tests/Settings/Controller/CorsControllerTest.php
  tests/Settings/Panels/Admin/LicenseTest.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/TransferOwnershipContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/lib/DB/ConnectionTest.php
  tests/lib/Files/MetaVersionCollectionTest.php
  tests/lib/Files/Storage/LocalTest.php
  tests/lib/Files/Storage/Wrapper/JailTest.php
  tests/lib/LoggerTest.php
  tests/lib/LoggerWithoutWriteExtraTest.php
  tests/lib/Share20/DefaultShareProviderTest.php
Labels: 3 - To Review, QA-team

#38275 PHP dependencies 20210108
  changelog/unreleased/38275
  changelog/unreleased/38275-2
  changelog/unreleased/38275-3
  composer.lock
Labels: 3 - To Review, dependencies, php

#38262 [Tests-only] Adds api tests for renaming received shares
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: 3 - To Review, QA-team

#38277 [tests-only] Make findLines a static function in SetupHelper
  tests/TestHelpers/SetupHelper.php
Labels: 3 - To Review, QA-team

#38285 Update sabre/dav (4.1.3 => 4.1.4)
  changelog/unreleased/38285
  composer.lock
Labels: 3 - To Review, dependencies, php

#38286 remove patchwork/utf8 due not needed
  changelog/unreleased/38286
  composer.json
  composer.lock
  lib/base.php
  lib/private/legacy/util.php
Labels: 3 - To Review

#38289 Fix position of the user afterLogin-event
  changelog/unreleased/38289
  lib/private/User/Session.php
Labels: 3 - To Review

#38292 [Tests-Only] Put back the useful code removed in PR 38133
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/lib/OwncloudPage.php
Labels: 3 - To Review, QA-team

#38288 Improve UI success/error while adding storages
  apps/files_external/css/settings.css
  apps/files_external/js/settings.js
  changelog/unreleased/38288
Labels: 3 - To Review

#38290 [tests-only] Add API tests for various actions of a disabled user
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
Labels: 4 - To release, QA-team

#38249 determine unencrypted block size after begin operation
  changelog/unreleased/38249
  lib/private/Files/Stream/Encryption.php
Labels: enhancement, minor-release

#38295 Do not prepended share_folder to file_target for public link shares
  changelog/unreleased/38291
  lib/private/Share20/Manager.php
  tests/acceptance/features/apiShareOperationsToShares/gettingSharesSharedFiltered.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareToShares.feature
Labels: 3 - To Review

#38299 [tests-only] Add API tests for sharing of renamed folder when another share exists
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
Labels: QA-team

#38301 [tests-only] Add API test to check shares exists when shared file is restored to previous version
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
Labels: QA-team

#38306 Update PHP dependencies
  changelog/unreleased/38188
  changelog/unreleased/38306
  composer.lock
Labels: dependencies, php

#38307 [tests-only] skip createPublicLinkShareToShares on core 10.5 and 10.6
  tests/acceptance/features/apiShareOperationsToShares/gettingSharesSharedFiltered.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareToShares.feature
Labels: 3 - To Review, QA-team

#38313 [Tests-Only] Matching the expected failure markdown file
  tests/acceptance/run.sh
Labels: 4 - To release, QA-team

#38309 Show app located path while running the occ app: list command
  changelog/unreleased/38309
  core/Command/App/ListApps.php
  tests/Core/Command/Apps/AppsListTest.php
  tests/acceptance/features/bootstrap/AppManagementContext.php
  tests/acceptance/features/cliAppManagement/listApps.feature
Labels: 3 - To Review

#38314 [tests-only] skip more apiWebdavEtagPropagation1/moveFileFolder tests on OCIS OC storage
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
Labels: 3 - To Review, QA-team

#38315 Prevent setlocale()-calls from overwriting themselves
  changelog/unreleased/38286
  lib/private/legacy/util.php
Labels: 4 - To release

#38317 [tests-only] Adjust regex for SUITE_SCENARIO in acceptance tests
  tests/acceptance/run.sh
Labels: QA-team

#38322 [tests-only] skip test scenario on old oC10 due to encryption issue 229
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
Labels: 4 - To release, QA-team

#37272 Use OcsController and routes instead of API::register and static methods
  changelog/unreleased/37272
  core/Controller/OcsController.php
  core/routes.php
  lib/private/OCS/Config.php
  lib/private/OCS/Person.php
  lib/private/OCS/PrivateData.php
  lib/private/Route/Router.php
  lib/private/legacy/ocs/config.php
  lib/private/legacy/ocs/person.php
  lib/private/legacy/ocs/privatedata.php
  ocs/routes.php
  tests/Core/Controller/OcsControllerTest.php
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuth/corsOc10Issue34664.feature
  tests/lib/OCS/PrivatedataTest.php
Labels: 3 - To Review

#38323 [Tests-Only] Add API test for searching resources across various folders by tag using REPORT
  tests/acceptance/features/apiWebdavOperations/search.feature
Labels: 4 - To release, QA-team

#38324 [Tests-Only] Tag issue number in sharing back to resharer test
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
Labels: 3 - To Review, QA-team

#38318 [Tests-Only] Add test to check response of webdav url with invalid fileId
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA-team

#38325 [tests-only] check if webdav locks don't influece each other
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiWebdavLocks3/independentLocks.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToRoot.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToShares.feature
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
Labels: QA-team

#38329 [tests-only] improve user-creation error
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA-team

#38331 [tests-only] delete duplicated tests
  tests/acceptance/features/apiWebdavLocks3/independentLocks.feature
Labels: QA-team

#38333 [tests-only] improve error reporting for locking tests
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA-team

#38334 [tests-only] check that unlocking does not unlock other items with the same name
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/exclusiveLocksOc10Issue34358.feature
  tests/acceptance/features/apiWebdavLocks/folder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkOc10Issue36064.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithTokenOc10Issue34338.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithTokenOc10Issue34360.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesOc10Issue36064.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToShares.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocks.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToRoot.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToShares.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockOc10Issue34302.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToRoot.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/webUIWebdavLockProtection/delete.feature
  tests/acceptance/features/webUIWebdavLockProtection/move.feature
  tests/acceptance/features/webUIWebdavLockProtection/upload.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/locksOc10Issue33867.feature
  tests/acceptance/features/webUIWebdavLocks/locksOc10Issue34315.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: QA-team

#38339 [tests-only] Pin behat/gherkin because of Gherkin issue 187
  vendor-bin/behat/composer.json
Labels: 3 - To Review, QA-team

#38345 [tests-only] skip refactored tests on old oC10
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
Labels: 3 - To Review, QA-team

#38327 [Tests-Only] Expand API tests for getUser, removeSubAdmin and resetUserPassword
  tests/acceptance/features/apiProvisioning-v1/getUser.feature
  tests/acceptance/features/apiProvisioning-v1/removeSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
  tests/acceptance/features/apiProvisioning-v2/getUser.feature
  tests/acceptance/features/apiProvisioning-v2/removeSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
Labels: QA-team

#38320 [tests-only] Fixed regex pattern used in download content matching
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 4 - To release, QA-team

#38336 [Tests-Only] Add API test for deleting a share with wrong authentication
  tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
  tests/acceptance/features/apiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA-team

#38326 [Tests-Only] Expand API tests for addUser, createSubAdmin, deleteUser, disableUser, enableUser and editUser
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v1/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v1/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v1/enableUser.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/apiProvisioning-v2/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA-team

#38349 [tests-only] Skip new resetUserPassword tests on user-keys encryption
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
Labels: 3 - To Review, 4 - To release, QA-team

#38351 [Tests-Only] Refactor API tests added in PRs #38336 and #38326
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v1/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v1/enableUser.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/apiProvisioning-v2/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team

#38355 Update Symfony components to 4.4.19
  changelog/unreleased/38163
  changelog/unreleased/38234
  changelog/unreleased/38355
  composer.lock
Labels: 3 - To Review, dependencies, php

#38347 [tests-only] Bump behat/gherkin to 4.7.1
  vendor-bin/behat/composer.json
Labels: QA-team

#38356 [tests-only] Add API tests to expand addUser tests
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA-team

#38298 Prevent group assignment in Web UI if not supported
  changelog/unreleased/38298
  core/js/multiselect.js
  lib/private/Group/Manager.php
  lib/public/IGroupManager.php
  settings/Controller/GroupsController.php
  settings/js/users/users.js
  settings/routes.php
  tests/Settings/Controller/GroupsControllerTest.php
  tests/acceptance/features/lib/UsersPage.php
Labels: 4 - To release

#38357 [tests-only] Add extra checks for file content of files restored from trashbin
  tests/acceptance/features/apiTrashbin/trashbinRestore.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToRoot.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToShares.feature
Labels: 4 - To release, QA-team

#38358 [tests-only] Refactor examples table tags related to PRs 38345 and 37272
  tests/acceptance/features/apiAuth/cors.feature
Labels: 3 - To Review, QA-team

#38352 [Tests-Only] api tests for moving file
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/bootstrap/WebUISharingContext.php
Labels: 3 - To Review, QA-team

#38330 [Tests-Only] Expand API tests for getGroups, getSubAdminGroups and getUserGroups
  tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 4 - To release, QA-team
