Repository owncloud/core, pull requests merged in 2021-08, with the labels that each got.

#39082 [tests-only] Upgrading phpunit/phpunit (8.5.18 => 8.5.19)
  composer.lock
Labels: dependencies, php

#39083 [tests-only] Run federated tests against latest and 10.7.0
  .drone.star
Labels: QA:team

#39092 [tests-only] [full-ci] Refactor previews tests so they can run on oC10 or OCIS
  tests/acceptance/features/apiWebdavPreviews/previews.feature
  tests/acceptance/features/apiWebdavPreviews/previewsAutoAdustedSizing.feature
  tests/acceptance/features/apiWebdavPreviews/previewsExactSizing.feature
Labels: QA:team

#39088 Use md5 hash for chunk name
  apps/dav/lib/Connector/Sabre/File.php
  changelog/unreleased/39088
  lib/private/Files/Filesystem.php
  lib/private/Files/Stream/Checksum.php
  tests/lib/Files/FilesystemTest.php
Labels: 3 - To Review

#39050 [tests-only] [full-ci] additional test for share of matching file and folder name
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
Labels: QA:team

#38997 [tests-only] [full-ci] Test case for groupadmin being able to see email and password in users page
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UsersPage.php
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: QA:team

#39068 [tests-only] [full-ci] adds test for occ dav commands
  tests/acceptance/config/behat.yml
  tests/acceptance/features/bootstrap/CalDavContext.php
  tests/acceptance/features/bootstrap/CardDavContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/cliMain/webdavCalendar.feature
  tests/acceptance/features/cliMain/webdavContacts.feature
Labels: QA:team

#39070 Do not try to remove the same file twice
  apps/files_trashbin/lib/Storage.php
  apps/files_trashbin/lib/Trashbin.php
  changelog/unreleased/39070
Labels: 3 - To Review

#39102 [tests-only] Add bug demonstration scenario for upload chunk test
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunkingOc10Issue36115.feature
Labels: QA:team

#39100 [tests-only] Adds api tests for multiple expiration date in public link
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#39110 [tests-only] Tag new share expiration date test notToImplementOnOCIS
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#39107 PHP dependencies 20210812
  composer.json
  composer.lock
Labels: dependencies, php

#39117 [full-ci][tests-only] Add @notToImplementOnOCIS tag on tests
  tests/acceptance/features/apiWebdavOperations/deleteFolder.feature
Labels: QA:team

#39113 [tests-only] @issue-ocis-reva-163 removed
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#39120 [tests-only] tag lockBreakersGroups scenarios notToImplementOnOCIS
  tests/acceptance/features/apiWebdavLocksUnlock/lockBreakersGroups.feature
Labels: QA:team

#39121 [full-ci][tests-only]Add notToImplementOnOCIS tag in ocsGETAuth.feature:243
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
Labels: QA:team

#39124 Bump PHP dependencies - punic and flysystem
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39122 [tests-only] [full-ci] adds @notToImplementOnOCIS tag for subadmin scenarios
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v1/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v1/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v1/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v1/getUser.feature
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
  tests/acceptance/features/apiProvisioning-v2/addUser.feature
  tests/acceptance/features/apiProvisioning-v2/createSubAdmin.feature
  tests/acceptance/features/apiProvisioning-v2/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/apiProvisioning-v2/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v2/getUser.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/deleteGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/removeFromGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/deleteGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/removeFromGroup.feature
Labels: QA:team

#39101 config_apps_sample changes for WND 2.1.0
  config/config.apps.sample.php
Labels: 3 - To Review

#39125 [tests-only] [full-ci] add some @notToImplementOnOCIS and @skipOnOcV10
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
Labels: QA:team

#39128 [Tests-Only] make method to create group public in acceptance tests
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review, QA:team

#39137 [tests-only]Refactor tests related to file_target issue
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
Labels: QA:team

#39141 [tests-only] Nodejs 14
  .drone.star
  build/package.json
  build/yarn.lock
Labels: QA:team

#36257 Do not try to login via auth module if the user is disabled
  changelog/unreleased/36257
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#39140 Fix image orientation method
  changelog/unreleased/39140
  core/Controller/AvatarController.php
  lib/private/Preview/Image.php
  lib/private/legacy/image.php
  tests/Core/Controller/AvatarControllerTest.php
Labels: 3 - To Review

#39130 Implement quick action for creating public links
  apps/files_sharing/js/share.js
  apps/files_sharing/js/sharedialogview.js
  apps/files_sharing/lib/Hooks.php
  apps/files_sharing/tests/HooksTest.php
  apps/files_sharing/tests/js/shareSpec.js
  apps/files_sharing/tests/js/sharedfilelistSpec.js
  changelog/unreleased/39130
  config/config.sample.php
  core/css/icons.css
  core/img/actions/public-create-white.svg
  core/img/actions/public-create.svg
  core/js/shareconfigmodel.js
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
Labels: 3 - To Review

#39155 Keep pagination active with empty search queries
  apps/files/js/filelist.js
  changelog/unreleased/39155
Labels: 3 - To Review

#39154 [tests-only] [full-ci] adds function param and return type declaration
  tests/acceptance/features/bootstrap/CalDavContext.php
  tests/acceptance/features/bootstrap/CardDavContext.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
Labels: QA:team

#39156 [tests-only] Update phpunit/phpunit (8.5.19 => 8.5.20)
  composer.lock
Labels: dependencies, php

#39146 fix display of tags selection box
  changelog/unreleased/39146
  core/css/share.css
  core/css/systemtags.css
  core/js/systemtags/systemtagsinputfield.js
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
Labels: 3 - To Review
