Repository owncloud/core, pull requests merged in 2021-11, with the labels that each got.

#39435 [tests-only] [full-ci] Enable declare(strict_types=1) for FeatureContext
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OccContext.php
Labels: QA:team

#39429 [tests-only] [full-ci] Return early from manuallyAddSkeletonFiles when using emptySkeleton
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#39444 [tests-only] [full-ci] waitForDavRequestsToFinish before deleting users
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39449 Add missing 'remoteshare.accepted' event parameters
  apps/files_sharing/lib/Controllers/ExternalSharesController.php
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/tests/Controllers/ExternalShareControllerTest.php
  changelog/unreleased/39449
Labels: 3 - To Review

#39450 Remove unused activity messages
  apps/files/lib/Activity.php
  apps/files/tests/ActivityTest.php
  changelog/unreleased/39430
Labels: 3 - To Review

#39442 [tests-only]Add tests to check downloaded content
  .drone.star
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/webUIFiles/download.feature
Labels: QA:team

#39453 Bump sabre dependencies
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39457 [tests-only] Skip changed getUser tests on old oC10
  tests/acceptance/features/apiProvisioning-v1/getUser.feature
  tests/acceptance/features/apiProvisioning-v2/getUser.feature
Labels: QA:team

#39456 Bump sabre/uri (2.2.1 => 2.2.2)
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39451 [full-ci] Patch jquery UI
  changelog/unreleased/39451
  core/js/js.js
Labels: security

#39459 [tests-only] Bump phpstan to v0.12 to v1.0
  phpstan.neon
  vendor-bin/phpstan/composer.json
Labels: QA:team

#39461 [tests-only] Fix return type of getLastShareId()
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#39463 [tests-only] Add more error checking in SetupHelper runOcc
  tests/TestHelpers/SetupHelper.php
Labels: QA:team

#39471 [Test-Only] Add tests for propfind on the external storage folder
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/cliLocalStorage/propfindOnLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/propfindOnLocalStorageOc10Issue39470.feature
Labels: dev:acceptance-tests, QA:team

#39481 [tests-only] skip new propfindOnLocalStorage tests on old oC10
  tests/acceptance/features/cliLocalStorage/propfindOnLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/propfindOnLocalStorageOc10Issue39470.feature
Labels: QA:team

#39479 Update laminas/laminas-stdlib (3.6.0 => 3.6.1)
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39477 Fix group administrator permissions
  changelog/unreleased/39477
  settings/Controller/UsersController.php
  tests/Settings/Controller/UsersControllerTest.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/webUIAddUsers/addUsers.feature
  tests/acceptance/features/webUIAddUsers/addUsersBySubAdmin.feature
Labels: Type:Bug, settings:users, php

#39485 Update doctrine/dbal (2.13.4 => 2.13.5)
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: QA:team

#39488 Fix some broken links in config.sample
  config/config.apps.sample.php
  config/config.sample.php
Labels: 3 - To Review

#39480 [Tests-Only] [full-ci] enforce strict type checking on acceptance test code
  tests/TestHelpers/LoggingHelper.php
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/AppManagementContext.php
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/CalDavContext.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/CardDavContext.php
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/CommentsContext.php
  tests/acceptance/features/bootstrap/CorsContext.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/acceptance/features/bootstrap/FavoritesContext.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/IpContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/OccAppManagementContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/TransferOwnershipContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/bootstrap/WebUIAdminAppsSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIAdminEncryptionSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIAdminGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIAdminStorageSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIFileActionsMenuContext.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUIHelpAndTipsContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/bootstrap/WebUINewFileMenuContext.php
  tests/acceptance/features/bootstrap/WebUINotificationsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalEncryptionSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalSecuritySettingsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalSharingSettingsContext.php
  tests/acceptance/features/bootstrap/WebUISearchContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/bootstrap/WebUITagsContext.php
  tests/acceptance/features/bootstrap/WebUIUserContext.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/bootstrap/WebUIWebDavLockingContext.php
  tests/acceptance/features/bootstrap/bootstrap.php
  tests/acceptance/features/lib/LoginPage.php
Labels: 3 - To Review, dev:acceptance-tests, QA:team

#39487 Update sabre/vobject (4.3.7 to 4.3.8)
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39482 Load l10n js files from correct app folder
  changelog/unreleased/39482
  lib/private/Template/JSResourceLocator.php
  tests/lib/Template/JSResourceLocatorTest.php
Labels: Type:Bug, php

#39489 [tests-only][full-ci]Fix type of functions
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
Labels: QA:team

#39486 [Tests-Only] [full-ci] enforce strict type checking page objects of acceptance tests
  tests/acceptance/features/lib/AdminAppsSettingsPage.php
  tests/acceptance/features/lib/AdminEncryptionSettingsPage.php
  tests/acceptance/features/lib/AdminGeneralSettingsPage.php
  tests/acceptance/features/lib/AdminSharingSettingsPage.php
  tests/acceptance/features/lib/AdminStorageSettingsPage.php
  tests/acceptance/features/lib/DisabledUserPage.php
  tests/acceptance/features/lib/ExternalStoragePage.php
  tests/acceptance/features/lib/FavoritesPage.php
  tests/acceptance/features/lib/FilesPage.php
  tests/acceptance/features/lib/FilesPageBasic.php
  tests/acceptance/features/lib/FilesPageCRUD.php
  tests/acceptance/features/lib/FilesPageElement/ConflictDialog.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/lib/FilesPageElement/FavoritesFileRow.php
  tests/acceptance/features/lib/FilesPageElement/FileActionsMenu.php
  tests/acceptance/features/lib/FilesPageElement/FileRow.php
  tests/acceptance/features/lib/FilesPageElement/LockDialog.php
  tests/acceptance/features/lib/FilesPageElement/LockDialogElement/LockEntry.php
  tests/acceptance/features/lib/FilesPageElement/NewFileMenu.php
  tests/acceptance/features/lib/FilesPageElement/SharedByLinkFileRow.php
  tests/acceptance/features/lib/FilesPageElement/SharedWithOthersFileRow.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/EditPublicLinkPopup.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialogElement/PublicLinkTab.php
  tests/acceptance/features/lib/FilesPageElement/TrashBinFileRow.php
  tests/acceptance/features/lib/GeneralErrorPage.php
  tests/acceptance/features/lib/GeneralExceptionPage.php
  tests/acceptance/features/lib/HelpAndTipsPage.php
  tests/acceptance/features/lib/LoginPage.php
  tests/acceptance/features/lib/Notification.php
  tests/acceptance/features/lib/NotificationsAppDialog.php
  tests/acceptance/features/lib/NotificationsEnabledOwncloudPage.php
  tests/acceptance/features/lib/OwncloudPage.php
  tests/acceptance/features/lib/OwncloudPageElement/OCDialog.php
  tests/acceptance/features/lib/OwncloudPageElement/SettingsMenu.php
  tests/acceptance/features/lib/PersonalEncryptionSettingsPage.php
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/lib/PersonalSecuritySettingsPage.php
  tests/acceptance/features/lib/PersonalSharingSettingsPage.php
  tests/acceptance/features/lib/PublicLinkFilesPage.php
  tests/acceptance/features/lib/SearchResultInOtherFoldersPage.php
  tests/acceptance/features/lib/SharedByLinkPage.php
  tests/acceptance/features/lib/SharedWithOthersPage.php
  tests/acceptance/features/lib/SharedWithYouPage.php
  tests/acceptance/features/lib/SharingSettingsPage.php
  tests/acceptance/features/lib/TagsPage.php
  tests/acceptance/features/lib/TrashbinPage.php
  tests/acceptance/features/lib/UserPageElement/GroupList.php
  tests/acceptance/features/lib/UsersPage.php
Labels: 3 - To Review, dev:acceptance-tests, QA:team

#39492 Update sabre/vobject (4.3.8 => 4.4.0)
  apps/dav/tests/unit/CalDAV/CalDavBackendTest.php
  apps/dav/tests/unit/CardDAV/BirthdayServiceTest.php
  apps/dav/tests/unit/CardDAV/ConverterTest.php
  apps/dav/tests/unit/CardDAV/ImageExportPluginTest.php
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39493 Add capability for blacklisted files regex
  apps/files/lib/Capabilities.php
  apps/files/tests/CapabilitiesTest.php
  changelog/unreleased/39493
  tests/acceptance/features/apiCapabilities/capabilities.feature
Labels: enhancement, php

#39495 Update punic/punic (3.6.1 => 3.7.0)
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39491 [tests-only][full-ci] tests for apps password is preserved when resetting login password
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
Labels: QA:team

#39497 [Tests-Only][full-ci] enforce strict type checking on test helpers
  tests/TestHelpers/AppConfigHelper.php
  tests/TestHelpers/Asserts/WebDav.php
  tests/TestHelpers/DeleteHelper.php
  tests/TestHelpers/DownloadHelper.php
  tests/TestHelpers/EmailHelper.php
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/IpHelper.php
  tests/TestHelpers/LoggingHelper.php
  tests/TestHelpers/MoveCopyHelper.php
  tests/TestHelpers/OcisHelper.php
  tests/TestHelpers/OcsApiHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/TestHelpers/SharingHelper.php
  tests/TestHelpers/TagsHelper.php
  tests/TestHelpers/TranslationHelper.php
  tests/TestHelpers/Unit/DeleteHelperTest.php
  tests/TestHelpers/Unit/WebDavHelperTest.php
  tests/TestHelpers/UploadHelper.php
  tests/TestHelpers/UserHelper.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: 3 - To Review

#39496 Update sabre/dav (4.1.5 to 4.2.0)
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
  tests/acceptance/features/apiWebdavLocks/requestsWithTokenOc10Issue34338.feature
Labels: dependencies, php

#39499 chore: remove msofba
  apps/dav/appinfo/routes.php
  apps/dav/lib/Connector/Sabre/MSOFBAPlugin.php
  apps/dav/lib/Controller/MSOFBAController.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Connector/Sabre/MSOFBAPluginTest.php
  changelog/unreleased/38838
Labels: 3 - To Review

#39498 [tests-only] Fix trim in OcisHelper
  tests/TestHelpers/OcisHelper.php
Labels: QA:team

#39501 Smaller ownCloud logo in mail image
  changelog/unreleased/39501
  core/img/logo-mail.gif
Labels: 3 - To Review

#39503 [tests-only] Tag app password tests notToImplementOnOCIS
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
Labels: QA:team

#39505 [tests-only][full-ci]Add type declaration to SetupHelper
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
Labels: QA:team

#39126 Feature/version metadata
  apps/dav/lib/Meta/MetaFile.php
  apps/dav/lib/Meta/MetaPlugin.php
  apps/files_trashbin/lib/Trashbin.php
  apps/files_versions/js/versioncollection.js
  apps/files_versions/js/versionstabview.js
  apps/files_versions/lib/Hooks.php
  apps/files_versions/lib/Storage.php
  apps/files_versions/tests/VersioningTest.php
  changelog/unreleased/39126
  config/config.sample.php
  lib/private/Files/Meta/MetaFileVersionNode.php
  lib/public/Files/IProvidesVersionAuthor.php
Labels: 3 - To Review

#39500 Fix search inside a shared external storage
  changelog/unreleased/39500
  lib/private/Files/Cache/Wrapper/CacheJail.php
Labels: 3 - To Review

#39517 Change way how to show/hide tag edit actions
  changelog/unreleased/39146
  core/js/systemtags/systemtagsinputfield.js
Labels: 10.9-regression

#39529 Fix several PR links in changelog items
  apps/files/l10n/ca_ES.js
  apps/files/l10n/ca_ES.json
  changelog/unreleased/39185
  changelog/unreleased/39351
  tests/data/apptheme/apps/files/l10n/ca_ES.js
  tests/data/apptheme/apps/files/l10n/ca_ES.json
  tests/data/themes/abc/apps/files/l10n/ca_ES.js
  tests/data/themes/abc/apps/files/l10n/ca_ES.json
Labels: technical debt
