Repository owncloud/core, pull requests merged in 2021-04, with the labels that each got.

#38606 [tests-only] Fix tests that accidentally depended on welcome.txt
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature
Labels: 3 - To Review, QA:team

#38610 Config apps sample apps update
  config/config.apps.sample.php
  config/config.sample.php
Labels: 3 - To Review

#38611 Typo and rendering fix in config.apps.sample
  config/config.apps.sample.php
Labels: 4 - To release

#38534 [Tests-Only] used small skeletons more wisely on share management test features
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/excludeGroupFromReceivingShares.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/apiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiShareManagementToRoot/disableSharing.feature
  tests/acceptance/features/apiShareManagementToRoot/mergeShare.feature
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShare.feature
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShareOc10Issue30325.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptSharesToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/apiSharees/sharees.feature
  tests/acceptance/features/apiSharees/shareesIssue38501.feature
Labels: QA:team

#38591 if source and target owners are different, check quota on move
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
  apps/files/js/filelist.js
  changelog/unreleased/38591
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiMain/quota.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review

#38616 add html template for calens
  .drone.star
  CHANGELOG.html
  Makefile
  changelog/CHANGELOG-html.tmpl
  changelog/unreleased/38616
Labels: 3 - To Review

#38618 [Tests-Only] replace consequent test steps with same type as And
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuth/corsOc10Issue34679.feature
  tests/acceptance/features/apiFederationToRoot1/federated.feature
  tests/acceptance/features/apiFederationToRoot2/federated.feature
  tests/acceptance/features/apiFederationToShares1/federated.feature
  tests/acceptance/features/apiFederationToShares2/federated.feature
  tests/acceptance/features/apiMain/quota.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/excludeGroupFromReceivingShares.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/apiShareOperationsToRoot/uploadToShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiSharees/sharees.feature
  tests/acceptance/features/apiSharingNotificationsToRoot/sharingNotifications.feature
  tests/acceptance/features/apiSharingNotificationsToShares/sharingNotifications.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavProperties1/setFileProperties.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunkingOc10Issue36115.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageForGroups.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageForUsers.feature
  tests/acceptance/features/cliTrashbin/trashbin.feature
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
  tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
  tests/acceptance/features/webUISharingInternalGroups1/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalGroups2/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalUsers2/adminDisablesSharePermissions.feature
  tests/acceptance/features/webUISharingInternalUsers2/shareWithUserUsingExpirationDate.feature
  tests/acceptance/features/webUISharingPublic1/createPublicLinkShares.feature
  tests/acceptance/features/webUITrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
  tests/acceptance/features/webUIWebdavLocks/unlock.feature
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38623 [tests-only] removed welcome.txt occurrences from acceptance tests with no skeleton files
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithDisabledUser.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareWithDisabledUserOc10Issue32068.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/excludeGroupFromReceivingShares.feature
  tests/acceptance/features/apiShareManagementToRoot/disableSharing.feature
  tests/acceptance/features/apiShareOperationsToRoot/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToShares/changingFilesShare.feature
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavOperations/deleteFolderContents.feature
Labels: QA:team

#38605 Automations in activity stream
  apps/files/lib/Activity.php
  apps/systemtags/lib/Activity/Extension.php
  apps/systemtags/lib/Activity/Listener.php
  changelog/unreleased/38605
  lib/private/Activity/Manager.php
  lib/public/Activity/IEvent.php
  lib/public/Activity/IManager.php
  tests/lib/Activity/ManagerTest.php
Labels: 3 - To Review

#38626 [tests-only] Skip quota test added in 38591, on old oC10 versions
  tests/acceptance/features/apiMain/quota.feature
Labels: QA:team

#38627 [tests-only] Skip cors scenarios changed in PR 38486 on old oC10
  tests/acceptance/features/apiAuth/cors.feature
Labels: QA:team

#38437 [tests-only] use oC10 tarball installation as system under test in drone
  .drone.star
Labels: QA:team

#38574 Fix warning about an ignored lock release
  apps/dav/lib/Connector/Sabre/LockPlugin.php
Labels: 3 - To Review

#38631 Translation in the activity stream for shares which expired automatically
  apps/files_sharing/lib/Activity.php
  apps/files_sharing/lib/ExpireSharesJob.php
  apps/files_sharing/tests/ExpireSharesJobTest.php
  changelog/unreleased/38631
  lib/private/Server.php
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#38638 Update OIDC section of config.apps.sample.php
  config/config.apps.sample.php
Labels: 3 - To Review

#38639 Save notification url as relative instead of absolute
  apps/federatedfilesharing/lib/FedShareManager.php
  apps/files_sharing/lib/Service/NotificationPublisher.php
  apps/files_sharing/tests/Service/NotificationPublisherTest.php
  apps/updatenotification/lib/Notification/BackgroundJob.php
  apps/updatenotification/tests/Notification/BackgroundJobTest.php
  changelog/unreleased/38639
  tests/acceptance/features/apiSharingNotificationsToRoot/sharingNotifications.feature
  tests/acceptance/features/apiSharingNotificationsToShares/sharingNotifications.feature
Labels: 3 - To Review

#38640 Add Microsoft Teams Bridge to config.apps.sample
  config/config.apps.sample.php
Labels: 3 - To Review

#38474 Do not remove federated share on CURLE errors, provide improved notification in UI and exception handling
  apps/files/js/filelist.js
  apps/files_sharing/ajax/external.php
  apps/files_sharing/lib/External/Storage.php
  changelog/unreleased/38474
  lib/private/Files/Storage/DAV.php
  tests/lib/Files/Storage/DavTest.php
Labels: app:federation

#38635 [tests-only] created resources rather than using skeleton dirs with users in webUI suites
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
  tests/acceptance/features/webUIFavorites/favoritesFile.feature
  tests/acceptance/features/webUIFiles/browseDirectlyToDetailsTab.feature
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFiles.feature
  tests/acceptance/features/webUITrashbin/trashbinDelete.feature
  tests/acceptance/features/webUIWebdavLocks/locks.feature
Labels: QA:team

#38648 Update phpseclib/phpseclib (3.0.7 to 3.0.8)
  apps/files_external/3rdparty/composer.lock
  apps/files_external/3rdparty/composer/InstalledVersions.php
  apps/files_external/3rdparty/composer/installed.json
  apps/files_external/3rdparty/composer/installed.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Blowfish.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Common/AsymmetricKey.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Common/SymmetricKey.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/DES.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/DH/PrivateKey.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/EC/Curves/Ed25519.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/EC/Formats/Keys/Common.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/RC2.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/Rijndael.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Crypt/TripleDES.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/File/X509.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Net/SFTP.php
  apps/files_external/3rdparty/phpseclib/phpseclib/phpseclib/Net/SSH2.php
  changelog/unreleased/38598-2
  composer.lock
Labels: 3 - To Review, dependencies, php

#38659 Update doctrine/cache (1.10.2 to 1.11.0)
  changelog/unreleased/38598-2
  composer.lock
Labels: dependencies, php

#38658 [tests-only] Adjust trashbinFilesFolders test setups
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
Labels: QA:team

#38660 [tests-only] Be more strict when checking Given user has deleted file
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/cliBackground/backgroundQueue.feature
Labels: QA:team

#38661 [tests-only] Tidy up user cleanup when running on OCIS or reva
  tests/TestHelpers/OcisHelper.php
Labels: 3 - To Review, QA:team

#38652 [tests-only] test if a user can delete a share after loosing resharing permissions
  tests/acceptance/features/apiShareReshareToRoot3/reShareUpdate.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#38601 Fix web rewrites for private and public links
  changelog/unreleased/38600
  core/routes.php
Labels: 3 - To Review

#38676 [tests-only] Remove unused DIR_URL in acceptance tests run.sh
  tests/acceptance/run.sh
Labels: QA:team
