Repository owncloud/core, pull requests merged in 2021-07, with the labels that each got.

#38899 [Tests-Only] [full-ci] add tests for trashbin restore to different location
  .drone.star
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestoreOc10Issue35900.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestoreOc10Issue35974.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestoreOc10Issue38898.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/webUIRestrictSharing/restrictSharing.feature
Labels: QA:team

#38924 Bump symfony 4.4.26
  changelog/unreleased/38598-1
  composer.lock
Labels: dependencies, php

#38911 Close the directory after reading
  lib/private/Files/Cache/Scanner.php
Labels: 3 - To Review

#38927 [Tests-Only] skip tests for async file move operations
  tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature
Labels: QA:team, dev:acceptance-tests

#38936 Move preview content to docs
  config/config.sample.php
  lib/private/PreviewManager.php
Labels: 3 - To Review

#38938 [tests-only] Skip on old oC10 public link tests changed by PR 38922
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
Labels: QA:team

#38939 [tests-only] do not run tests that share to root folder on ocis
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToRoot.feature
Labels: QA:team

#38943 [tests-only] DRY the dirs mentioned in .drone.star
  .drone.star
Labels: QA:team

#38921 [tests-only][full-ci] test downloading old file versions
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToSharesIssue36228.feature
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#38951 [tests-only] Skip new restore version test on files_primary_s3
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA:team

#38958 [tests-only] Add test scenarios for trashbinSkip issue-38952
  tests/acceptance/features/apiTrashbin/trashbinSkip.feature
  tests/acceptance/features/apiTrashbin/trashbinSkipOc10Isssue38952.feature
Labels: QA:team

#38930 [tests-only] adds api test for multi sharing with different permission
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38968 [tests-only] skip helpAndTips tests on old oC10
  tests/acceptance/features/webUIAdminSettings/helpAndTips.feature
Labels: QA:team

#38975 Fixes a config sample typo
  config/config.sample.php
Labels: 3 - To Review

#38977 [Tests-Only] update issue tag for versions test for files_primary_s3
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: 3 - To Review, QA:team, dev:acceptance-tests

#38978 [Tests-Only] skip web login test for ocis
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
Labels: QA:team, dev:acceptance-tests

#38950 [Tests-Only] Adds test for sharing resource with sharee that has an existing resource with diff. case name
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#38969 [full-ci][tests-only] add api tests for lock breaker group
  tests/acceptance/features/apiWebdavLocksUnlock/lockBreakersGroups.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#38983 [tests-only] Adjust minor words in API sharing test steps
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#39001 [tests-only] Do not try to access the log file when isTestingOnOcisOrReva
  tests/TestHelpers/LoggingHelper.php
  tests/acceptance/features/bootstrap/LoggingContext.php
Labels: QA:team

#39003 [tests-only] skip new configKey scenarios on old oC10
  tests/acceptance/features/cliMain/configKey.feature
Labels: QA:team

#39005 Prevent checksum verify command from crashing on single files
  apps/files/lib/Command/VerifyChecksums.php
  changelog/10.8.0_2021-07-13/38785
Labels: 3 - To Review

#39012 [tests-only] Include nonCoverageTests in CI pipelines
  .drone.star
Labels: QA:team

#39015 Log number of mounts when moving encryption keys fails
  changelog/unreleased/39015
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3 - To Review, enhancement

#39018 Update config.sample.php (url-typo)
  config/config.apps.sample.php
  config/config.sample.php
Labels: 3 - To Review

#39019 [release-10.8.0] [PR 39018] Update config.sample.php (url-typo)
  config/config.apps.sample.php
  config/config.sample.php
Labels: 3 - To Review

#39020 [tests-only] skip new subadmin test scenarios on old oC10
  tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroup.feature
Labels: QA:team

#38984 [Tests-Only] adds tests for accepting or declining share which is already removed
  tests/acceptance/features/webUISharingAcceptShares/acceptShares.feature
Labels: QA:team

#38995 [Tests-Only][full-ci] Add api tests for listing files with propfind
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/config/behat.yml
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavOperations/listFiles.feature
  tests/acceptance/features/apiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingNewChunking.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/bootstrap/WebUIAdminStorageSettingsContext.php
  tests/acceptance/features/cliProvisioning/addUser.feature
  tests/acceptance/features/webUIAddUsers/addUsers.feature
Labels: QA:team

#38791 [tests-only] [full-ci] Add API test coverage for saving public share to oC
  .drone.star
  tests/acceptance/features/apiFederationToRoot1/savePublicShare.feature
  tests/acceptance/features/apiFederationToShares1/savePublicShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#39024 update ca-bundle.crt
  resources/config/ca-bundle.crt
Labels: 3 - To Review

#39025 [Tests-Only] skip old public dav api test on ocis
  tests/acceptance/features/apiWebdavOperations/listFiles.feature
Labels: QA:team

#39027 [tests-only] Tidy up 'on the webUI' in acceptance tests
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUITagsContext.php
  tests/acceptance/features/bootstrap/WebUIUserContext.php
  tests/acceptance/features/webUIManageUsersGroups/editUsers.feature
  tests/acceptance/features/webUIPersonalSettings/accessToChangeFullNameThroughConfig.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnFullName.feature
  tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature
  tests/acceptance/features/webUITags/createTags.feature
Labels: QA:team

#39041 [tests-only] skip the TUS upload test on OCIS due to OCIS issue 1141
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
Labels: QA:team

#39036 [tests-only] [full-ci] Send X-Request-Id string in test API requests
  tests/TestHelpers/AppConfigHelper.php
  tests/TestHelpers/Asserts/WebDav.php
  tests/TestHelpers/DeleteHelper.php
  tests/TestHelpers/DownloadHelper.php
  tests/TestHelpers/EmailHelper.php
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/LoggingHelper.php
  tests/TestHelpers/MoveCopyHelper.php
  tests/TestHelpers/OcisHelper.php
  tests/TestHelpers/OcsApiHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/TestHelpers/SharingHelper.php
  tests/TestHelpers/TagsHelper.php
  tests/TestHelpers/Unit/DeleteHelperTest.php
  tests/TestHelpers/Unit/WebDavHelperTest.php
  tests/TestHelpers/UploadHelper.php
  tests/TestHelpers/UserHelper.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/AppManagementContext.php
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/CalDavContext.php
  tests/acceptance/features/bootstrap/CardDavContext.php
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/CommentsContext.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/FavoritesContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/bootstrap/WebUIAdminGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIAdminSharingSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIAdminStorageSettingsContext.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUIHelpAndTipsContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
Labels: QA:team

#39045 [tests-only] Match getcontenttype starting with text/plain in test
  tests/acceptance/features/apiWebdavProperties1/setFileProperties.feature
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#39047 Update PHP dependencies
  changelog/unreleased/PHPdependencies20210721onward
  composer.lock
Labels: dependencies, php

#39049 [tests-only] skip new configKey CLI tests on 10.8
  tests/acceptance/features/cliMain/configKey.feature
Labels: 3 - To Review, QA:team

#39051 [tests-only] [full-ci] Split out new chunking tests and tag them notToImplementOnOCIS and newChunking
  tests/TestHelpers/UploadHelper.php
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiMain/quota.feature
  tests/acceptance/features/apiShareOperationsToShares2/uploadToShare.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedNameAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectoryAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToBlacklistedNameUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToExcludedDirectoryUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingNewChunking.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39054 [tests-only] skip tests for new public link sharing options on old oC10
  tests/acceptance/features/apiSharePublicLink2/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/webUISharingPublic2/allowGroupToCreatePublicLinks.feature
Labels: QA:team

#39059 [tests-only] Add scenarios demonstrating access directly to the Shares folder
  tests/acceptance/features/apiShareOperationsToShares1/accessToSharesFolder.feature
Labels: QA:team

#39033 [Tests-Only] Web UI test for file and folder with emoji in the name
  tests/acceptance/features/webUICreateDelete/createFoldersEdgeCases.feature
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
  tests/acceptance/features/webUIFiles/search.feature
  tests/acceptance/features/webUIMoveFilesFolders/moveFolders.feature
  tests/acceptance/features/webUIRenameFiles/renameFile.feature
  tests/acceptance/features/webUIRenameFolders/renameFolders.feature
Labels: QA:team

#39057 [full-ci][tests-only]Refactor sharing related tests and add notToImplementOnOCIS tag
  tests/acceptance/features/apiProvisioning-v1/disableUser.feature
  tests/acceptance/features/apiProvisioning-v2/disableUser.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiWebdavPreviews/previews.feature
Labels: QA:team

#39072 [tests-only] Format starlark
  .drone.star
Labels: QA:team

#39073 [tests-only] skip new create-folder-with-create-button tests on oC10.8.0
  tests/acceptance/features/cliMain/configKey.feature
  tests/acceptance/features/webUICreateDelete/createFolders.feature
Labels: QA:team

#39079 Bump PHP Symfony dependencies
  changelog/unreleased/PHPdependencies20210727onwardSymfony
  composer.lock
Labels: dependencies, php
