Repository owncloud/core, pull requests merged in 2022-12, with the labels that each got.

#40523 [tests-only][full-ci]Change function name in core
  tests/TestHelpers/WebDavHelper.php
Labels: QA:team

#40528 Fix config.sample example rendering
  config/config.sample.php
Labels: 4 - To release

#40529 [tests-only] Do not use owncloudci/php latest in CI
  .drone.star
Labels: QA:team

#40527 [tests-only][full-ci] Filter out cors tests for oCIS
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/bootstrap/CorsContext.php
Labels: QA:team

#40534 [tests-only][full-ci]Refactor acceptance test scenarios with public WebDAV API checks
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToRoot.feature
  tests/acceptance/features/apiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
Labels: QA:team

#40540 [tests-only][full-ci]Remove notToImplementOnOcis tag from a test
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#40539 [tests-only]Add creation-with-upload extension
  tests/acceptance/features/apiWebdavUploadTUS/creationWithUploadExtension.feature
Labels: QA:team

#40545 [tests-only]Skip public link sharing only for certain group related tests on ocis
  tests/acceptance/features/apiSharePublicLink3/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/webUISharingPublic2/allowGroupToCreatePublicLinks.feature
Labels: QA:team

#40483 Encryption copy keys first3
  changelog/unreleased/40433
  lib/private/Encryption/Keys/Storage.php
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 2 - Developing

#40513 Set checksum if not seeked
  changelog/unreleased/40513
  lib/private/Files/Stream/Checksum.php
  tests/lib/Files/Stream/ChecksumTest.php
Labels: 3 - To Review

#40552 [tests-only]Removed skip tag @skipOnAllVersionsGreaterThanOcV10.8.0 from acceptance tests
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareFromLocalStorageToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShareFromLocalStorage.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/apiShareOperationsToShares2/shareAccessByID.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/run.sh
Labels: QA:team
