Repository owncloud/core, pull requests merged in 2022-02, with the labels that each got.

#39731 Bump symfony 4.4.37 and opis/closure 3.6.3
  changelog/unreleased/PHPdependencies20211123onward
  changelog/unreleased/PHPdependencies20211123onwardSymfony
  composer.lock
Labels: dependencies, php

#39733 [tests-only][full-ci]Adds spaces tests on `apiWebdavProperties1`
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
  tests/acceptance/features/apiWebdavProperties1/createFileFolderWhenSharesExist.feature
  tests/acceptance/features/apiWebdavProperties1/createFolder.feature
  tests/acceptance/features/apiWebdavProperties1/getQuota.feature
  tests/acceptance/features/apiWebdavProperties1/setFileProperties.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#39723 [tests-only] added spaces examples for TUS related upload features
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/apiWebdavUploadTUS/creationWithUplaodExtension.feature
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelCreationExtension.feature
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelUpload.feature
  tests/acceptance/features/apiWebdavUploadTUS/optionsRequest.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFileMtime.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39732 Add wnd.listen.reconnectAfterTime config sample
  config/config.apps.sample.php
Labels: 3 - To Review

#39743 [tests-only] Fix typos in feature names
  tests/acceptance/features/apiAuthWebDav/webDavMultiSlashOC10Issue34365.feature
  tests/acceptance/features/apiMain/appManagement.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedMultipleWaysIssue39347.feature
  tests/acceptance/features/apiWebdavUploadTUS/creationWithUploadExtension.feature
  tests/acceptance/features/cliMain/transferOwnership.feature
Labels: QA:team

#39740 [tests-only][full-ci]Added spaces on `apiWebDavEtagPropagation1` suite
  tests/acceptance/features/apiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/cliExternalStorage/cliIncomingShares.feature
Labels: QA:team

#39744 [tests-only][full-ci]Update `apiWebdavEtagPropagation2` suite for spaces webdav
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#39748 Autoprovisioning update in config.apps.sample
  config/config.apps.sample.php
Labels: 3 - To Review

#39746 [tests-only] [full-ci] Refactor and fix dav-path-spaces test code
  tests/TestHelpers/MoveCopyHelper.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39751 [tests-only] [full-ci] getPersonalSpaceIdForUser from webdav propfind
  tests/TestHelpers/WebDavHelper.php
Labels: QA:team

#39745 [tests-only][full-ci]Add spaces tests for apiWebdavMove1 suite
  tests/acceptance/features/apiWebdavMove1/moveFolder.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39749 [tests-only] added spaces examples in the api WebDAV locks suite
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/folder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
Labels: QA:team

#39747 [tests-only][full-ci] Add spaces example for apiTranslation suite
  tests/acceptance/features/apiTranslation/translation.feature
Labels: QA:team

#39729 [tests-only] [full-ci] Added spaces for suite `apiWebdavOperations`
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiWebdavOperations/deleteFile.feature
  tests/acceptance/features/apiWebdavOperations/deleteFolder.feature
  tests/acceptance/features/apiWebdavOperations/deleteFolderContents.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavOperations/listFiles.feature
  tests/acceptance/features/apiWebdavOperations/propfind.feature
  tests/acceptance/features/apiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/apiWebdavOperations/search.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39757 [tests-only] [full-ci] Remove special tests for issue 37026
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiVersions/fileVersionsOc10Issue37026.feature
Labels: QA:team

#39759 [tests-only] Added spaces examples in apiWebdavLocks2 suite
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToShares.feature
Labels: QA:team

#39604 Add warnings for commands that are incompatible with object storage
  changelog/unreleased/39604
  core/Command/User/HomeListDirs.php
  core/Command/User/HomeListUsers.php
  core/Command/User/MoveHome.php
  core/Command/User/Report.php
  lib/private/Files/Filesystem.php
  tests/Core/Command/User/HomeListDirsTest.php
  tests/Core/Command/User/HomeListUsersTest.php
  tests/Core/Command/User/MoveHomeTest.php
  tests/Core/Command/User/ReportTest.php
Labels: enhancement, 3 - To Review, php

#39770 [tests-only] [full-ci] Fix call to setSystemConfig in WebUIGeneralContext
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
Labels: QA:team

#39771 [tests-only][full-ci] Add spaces example for apiWebdavUpload1 suite
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectory.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39760 [tests-only] added spaces examples in `apiWebdavLocks3` suite
  tests/acceptance/features/apiWebdavLocks3/independentLocks.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToShares.feature
Labels: QA:team

#39781 Add composer allow-plugins
  composer.json
Labels: dependencies, php

#39773 [tests-only] added spaces examples for features inside `apiWebdavLocksUnlock` suite
  tests/acceptance/features/apiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
Labels: QA:team

#39782 [tests-only] Lint expected-failures files
  tests/acceptance/lint-expected-failures.sh
  tests/acceptance/run.sh
Labels: QA:team

#39772 [tests-only] [full-ci] Added scenarios for moving file and folder to external storage
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
Labels: QA:team

#39787 [tests-only] [full-ci] Acceptance test for zero byte copy
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavOperations/deleteFile.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/filesForUpload/zerobyte.txt
Labels: QA:team

#39194 Unify API responses when setting permissions for public links
  apps/files_sharing/lib/Controller/Share20OcsController.php
  changelog/unreleased/39194
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareOc10Issue36442.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
Labels: 3 - To Review, technical debt, php

#39721 Remove the user count if the number isn't positive.
  settings/js/users/groups.js
Labels: 3 - To Review

#39669 Fix the preview of text files containing BOM for utf8
  changelog/unreleased/39669
  lib/private/Preview/TXT.php
  lib/private/Utf8Analyzer.php
  tests/lib/Utf8AnalyzerTest.php
Labels: 3 - To Review

#39792 [tests-only] added spaces examples in the suite `apiSharePublicLink2`
  tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
Labels: QA:team

#39794 [tests-only] [full-ci] Added `Then` steps to improve checks in tests for apiComments suite
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
  tests/acceptance/features/apiComments/comments.feature
  tests/acceptance/features/apiComments/createComments.feature
  tests/acceptance/features/apiComments/deleteComments.feature
Labels: QA:team

#39798 Upgrading bamarni/composer-bin-plugin (1.4.1 => 1.4.2)
  composer.lock
Labels: dependencies, php

#39800 [tests-only] skip changed createPublicLinkShare test scenarios on old oC10
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#39797 Public-files endpoint won't stream multistatus
  apps/dav/lib/Server.php
  changelog/unreleased/39797
  tests/acceptance/features/webUIUpload/upload.feature
Labels: 3 - To Review

#39804 [tests-only] allow underscore in expected-failures links
  tests/acceptance/lint-expected-failures.sh
Labels: QA:team

#39801 [tests-only][full-ci]Added Then step for suite apiWebdavUpload1
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
Labels: QA:team

#39806 [tests-only][full-ci]Add Then step for suite apiWebdavUpload2
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature
Labels: QA:team

#39808 [tests-only] Bump phpunit (9.5.13 => 9.5.14)
  composer.lock
Labels: dependencies, php

#39809 [tests-only] Add test step 'the user count of group should not be displayed
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UsersPage.php
Labels: QA:team

#39812 [tests-only][full-ci]Add then step to apiWebdavUploadTUS suite
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/apiWebdavUploadTUS/creationWithUploadExtension.feature
  tests/acceptance/features/apiWebdavUploadTUS/optionsRequest.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFileMtime.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFileMtimeShares.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToNonExistingFolder.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
Labels: QA:team

#39813 [tests-only] Improve statusPhpRespondedShouldMatch test
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#39811 [tests-only] [full-ci] Added `Then` steps to improve checks in tests for apiFavorites suite
  tests/acceptance/features/apiFavorites/favorites.feature
  tests/acceptance/features/apiFavorites/favoritesOc10Issue33840.feature
  tests/acceptance/features/apiFavorites/favoritesSharingToShares.feature
Labels: QA:team

#39819 [tests-only] [full-ci] Added Then steps to improve checks in tests for apiWebdavProperties suites
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
  tests/acceptance/features/apiWebdavProperties1/createFolder.feature
  tests/acceptance/features/apiWebdavProperties1/getQuota.feature
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39823 [tests-only] Bump dev tool dependencies composer-bin-plugin php-code-coverage
  composer.lock
Labels: dependencies, php

#39821 [tests-only]Add tests for renaming a file after public link share
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
Labels: QA:team

#39825 [tests-only] Upgrading phpunit/phpunit (9.5.15 => 9.5.16)
  composer.lock
Labels: dependencies, php

#39802 [tests-only][full-ci]added then steps for apiMain suite
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39143 default pollinterval 30000 msec
  changelog/unreleased/39143
  config/config.sample.php
  lib/private/OCS/CoreCapabilities.php
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
Labels: QA:team

#39826 [tests-only][full-ci]Add then step to suite apiWebdavOperations
  tests/acceptance/features/apiWebdavOperations/deleteFolder.feature
  tests/acceptance/features/apiWebdavOperations/deleteFolderContents.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavOperations/listFiles.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39832 [tests-only] skip changed pollinterval tests on old oC10
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
Labels: QA:team

#39752 Show only assignable groups to the subadmin
  changelog/unreleased/39752
  settings/Controller/GroupsController.php
  tests/Settings/Controller/GroupsControllerTest.php
Labels: 3 - To Review

#39829 Fix encryption when the file is moved out of a share
  changelog/unreleased/39829
  lib/private/Encryption/Util.php
Labels: 3 - To Review

#39822 Fix issue restoring versions from the trashbin after sharing
  changelog/unreleased/39822
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3 - To Review
