Repository owncloud/core, pull requests merged in 2022-07, with the labels that each got.

#40184 [tests-only] Allow specifying the expected feature-file path in the expected-failures file
  tests/acceptance/lint-expected-failures.sh
Labels: QA:team

#40180 [full-ci] [tests-only] Handle 425 'too early' on oCIS and reva
  tests/TestHelpers/HttpRequestHelper.php
Labels: QA:team

#39600 Add default app setting on a user basis
  changelog/unreleased/39600
  lib/private/legacy/util.php
  tests/lib/UtilTest.php
Labels: enhancement, php

#40188 Update README.md
  README.md
Labels: 4 - To release

#40193 [tests-only] Bump bamarni/composer-bin-plugin (1.7.0)
  composer.lock
Labels: QA:team

#40194 [tests-only] Remove copy api tests including shares folder for personal spaces DAV version
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
Labels: QA:team

#40186 Update config.apps.sample - openidconnect auto-update
  config/config.apps.sample.php
Labels: 4 - To release

#40200 [tests-only] Updated the preview image content for `apiWebdavPreviews/previews.feature:210`
  tests/acceptance/fixtures/सिमसिमे-पानी.png
Labels: QA:team

#40173 [tests-only][full-ci]Added more tests scenarios for `COPY` request for better test coverage
  tests/acceptance/features/apiMain/external-storage.feature
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
Labels: QA:team

#40210 [tests-only] Skip flaky tests related to tus in ocis
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
Labels: QA:team

#40176 Restore remember me feature
  core/Controller/LoginController.php
  lib/base.php
  lib/private/User/Session.php
  lib/private/legacy/api.php
  tests/Core/Controller/LoginControllerTest.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#40217 [tests-only][full-ci]Adjust status code assertion step to accept 404 and 403
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
Labels: QA:team

#40213 [tests-only] Skip tests related to issue-ocis-1328 on ocis
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareWhenExcludedFromSharing.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink3/uploadToPublicLinkShare.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiTranslation/translation.feature
Labels: QA:team

#40218 [tests-only] Allow tests skipped by 40210 on ocis
  tests/acceptance/features/apiWebdavUploadTUS/uploadToShare.feature
Labels: QA:team

#40214 [tests-only][full-ci]Adjust test for limit search assertion
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40219 [tests-only] Add skipOnReva tag to tests not applicable for reva
  tests/acceptance/features/apiCapabilities/capabilities.feature
Labels: QA:team

#40220 [tests-only][full-ci]Skip multiple slash fixes on latest(stable) and older core
  tests/acceptance/features/apiAuthWebDav/webDavSpecialURLs.feature
Labels: QA:team

#40224 [full-ci] [tests-only] Skipped scenario for encryption app
  tests/acceptance/features/apiMain/quota.feature
Labels: QA:team

#40225 [tests-only] Skip the flaky etag propagation tests when running with oCIS CI
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
Labels: QA:team

#40230 [tests-only][full-ci]Add Test for updating (removing) password for a public link
  tests/acceptance/features/apiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#40226 [tests-only] Skip `Shares` folder including eTag propagation scenarios for `space` DAV version
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/upload.feature
Labels: QA:team

#40234 [tests-only] check for test mentioned in unexpected pattern inside the expected failures file
  tests/acceptance/lint-expected-failures.sh
Labels: QA:team

#40235 [tests-only] check for the links but not a list item in expected failures file
  tests/acceptance/lint-expected-failures.sh
Labels: QA:team

#40239 [tests-only][full-ci]Remove `/Shares` related scenarios from core
  tests/acceptance/features/apiWebdavProperties1/createFileFolderWhenSharesExist.feature
Labels: QA:team

#40229 Use the displayname of the groups
  changelog/unreleased/40229
  lib/private/Group/MetaData.php
  settings/Controller/UsersController.php
  settings/Panels/Personal/Profile.php
  settings/js/users/users.js
  settings/templates/panels/personal/profile.php
  settings/templates/users/part.grouplist.php
  tests/Settings/Controller/GroupsControllerTest.php
  tests/Settings/Controller/UsersControllerTest.php
  tests/Settings/Panels/Personal/ProfileTest.php
  tests/lib/Group/MetaDataTest.php
Labels: 3 - To Review

#40240 Init encryption module before calculating unencrypted block-size
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: Type:Bug, 2 - Developing

#40238 [tests-only][full-ci]Adjust Robots.txt for ocis
  tests/TestHelpers/OcsApiHelper.php
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team
