Repository owncloud/core, pull requests merged in 2022-04, with the labels that each got.

#39915 [CI] [tests-only] Update drone.star file
  .drone.star
Labels: QA:team

#39940 Bump symfony to 4.4.40
  changelog/unreleased/PHPdependencies20211123onwardSymfony
  composer.lock
Labels: dependencies, php

#39947 [tests-only] decode href value before assertions
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#39944 [tests-only][full-ci] Improve Then step in apiWebdavEtagPropagation1 suite
  tests/acceptance/features/apiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
Labels: QA:team

#39861 [tests-only][full-ci]added then steps for apiShareCreateSpecialToRoot1 suite
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39925 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite apiTrashbin
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFoldersOc10Issue23151.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToRoot.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/apiTrashbin/trashbinSkip.feature
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39950 [tests-only][full-ci] Improve Then step in apiWebdavEtagPropagation2 suite
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/restoreFromTrash.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/restoreVersion.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/upload.feature
Labels: QA:team

#39957 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiShareOperationToRoot1`
  tests/acceptance/features/apiShareOperationsToRoot1/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToRoot1/gettingShares.feature
Labels: QA:team

#39929 [tests-only][full-ci] Improve Then step in apiWebdavLocksUnlocks suite
  tests/acceptance/features/apiWebdavLocksUnlock/lockBreakersGroups.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#39923 [tests-only][full-ci]Improve Then steps in `apiShareCreateSpecialToRoot2` suite
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot2/createShareGroupCaseSensitive.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#39964 [tests-only] Remove jarnaiz\JUnitFormatter\JUnitFormatterExtension from acceptance tests
  tests/acceptance/config/behat.yml
  tests/acceptance/run.sh
  vendor-bin/behat/composer.json
Labels: QA:team

#39963 [tests-only][full-ci] Improve Then step in apiShareReshareToShares2 suite
  tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
Labels: QA:team

#39951 [tests-only][full-ci] Improve Then step in apiShareReshareToShares1 suite
  tests/acceptance/features/apiShareReshareToShares1/reShare.feature
Labels: QA:team

#39967 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiShareOperationToRoot2`
  tests/acceptance/features/apiShareOperationsToRoot2/getWebDAVSharePermissions.feature
Labels: QA:team

#39974 [tests-only][full-ci] Improve Then step in apiShareUpdateToShares suite
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
Labels: QA:team

#39969 [tests-only][full-ci] Improve Then step in apiShareUpdateToRoot suite
  tests/acceptance/features/apiShareUpdateToRoot/updateShare.feature
Labels: QA:team

#39938 [tests-only][full-ci]Improve then steps in apiShareCreateSpecialToShares1 suite
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedMultipleWaysIssue39347.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareResourceCaseSensitiveName.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#39975 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiShareOperationsToShares2`
  tests/acceptance/features/apiShareOperationsToShares2/getWebDAVSharePermissions.feature
Labels: QA:team

#39981 [tests-only][full-ci] Improve Then step in apiShareReshareToRoot suites
  tests/acceptance/features/apiShareReshareToRoot2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToRoot3/reShareUpdate.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#39993 [tests-only] Run tests in CI if code is changed in apps
  .drone.star
Labels: QA:team

#39996 [tests-only] Adjust regex patterns for matching source code in apps folders
  .drone.star
Labels: QA:team

#39932 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiVersion`
  tests/acceptance/features/apiVersions/fileVersionAuthor.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39987 [tests-only][full-ci] Fixes for graph API setup
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#39953 [tests-only] [full-ci] Added Then steps to improve checks in tests for apiShareManagementBasicToRoot suite
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
Labels: QA:team

#39983 [tests-only][full-ci] Improve Then step in apiSharingNotificationsToShares suites
  tests/acceptance/features/apiSharingNotificationsToShares/sharingNotifications.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#39972 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiShareOperationsToShares1`
  tests/acceptance/features/apiShareOperationsToShares1/accessToSharesFolder.feature
  tests/acceptance/features/apiShareOperationsToShares1/changingFilesShare.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39965 [tests-only][full-ci] Improve Then step in apiShareReshareToShares3 suite
  tests/acceptance/features/apiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareWithExpiryDate.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareWithExpiryDateOc10Issue37013.feature
Labels: QA:team

#39986 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiFederationToRoot1`
  tests/acceptance/features/apiFederationToRoot1/etagPropagation.feature
  tests/acceptance/features/apiFederationToRoot1/federated.feature
  tests/acceptance/features/apiFederationToRoot1/savePublicShare.feature
  tests/acceptance/features/bootstrap/FederationContext.php
Labels: QA:team

#40009 [full-ci][tests-only]Update test to match ocis behaviour
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
Labels: QA:team

#40014 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiSharingNotificationToRoot`
  tests/acceptance/features/apiSharingNotificationsToRoot/sharingNotifications.feature
Labels: QA:team

#39935 Sftp key handling
  apps/files_external/appinfo/Migrations/Version20220329110116.php
  apps/files_external/appinfo/info.xml
  apps/files_external/js/public_key.js
  apps/files_external/lib/Controller/AjaxController.php
  apps/files_external/lib/Lib/Auth/PublicKey/RSA.php
  apps/files_external/lib/Lib/RSAStore.php
  apps/files_external/lib/Lib/Storage/SFTP.php
  apps/files_external/tests/RSAStoreTest.php
  changelog/unreleased/39935
  lib/private/Files/External/FrontendDefinitionTrait.php
  lib/private/Files/External/StorageConfig.php
  tests/lib/Files/External/StorageConfigTest.php
Labels: 3 - To Review

#39916 Improve session cookie handling
  changelog/unreleased/39916
  config/config.sample.php
  core/js/config.php
  core/js/js.js
  core/routes.php
  lib/base.php
  lib/private/Server.php
  lib/private/Session/CryptoWrapper.php
  lib/private/User/Session.php
Labels: 3 - To Review

#40019 [tests-only][full-ci]Improve then steps in apiShareCreateSpecialToShares2 suite
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareDefaultFolderForReceivedShares.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareGroupAndUserWithSameName.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWithInvalidPermissions.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40026 Bump Symfony to 4.4.41
  changelog/unreleased/PHPdependencies20211123onwardSymfony
  composer.lock
Labels: dependencies, php

#40020 [tests-only] Improve then steps for suite 'apiFederationToShares1'
  tests/acceptance/features/apiFederationToShares1/etagPropagation.feature
  tests/acceptance/features/apiFederationToShares1/federated.feature
  tests/acceptance/features/apiFederationToShares1/savePublicShare.feature
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#39982 [tests-only][full-ci] Added webdav spaces in apiTrashbin suite
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFoldersOc10Issue23151.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToRoot.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/apiTrashbin/trashbinSkip.feature
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40022 [tests-only][full-ci] Improve Then step in apiShareManagementToRoot suites
  tests/acceptance/features/apiShareManagementToRoot/acceptShares.feature
  tests/acceptance/features/apiShareManagementToRoot/mergeShare.feature
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShare.feature
  tests/acceptance/features/apiShareManagementToRoot/moveShareInsideAnotherShare.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40023 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiShareMangementToShares`
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiShareManagementToShares/acceptSharesToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShare.feature
  tests/acceptance/features/apiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40036 [tests-only] [full-ci] Remove pushToLastStatusCodesArrays from AppConfigurationContext
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiSharingNotificationsToRoot/sharingNotifications.feature
  tests/acceptance/features/apiSharingNotificationsToShares/sharingNotifications.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
Labels: QA:team
