Repository owncloud/core, pull requests merged in 2022-11, with the labels that each got.

#40429 [tests-only]Add provisioning app required tag to a tests
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
Labels: QA:team

#40467 [tests-only] Refactored inter scenarios space
  tests/acceptance/features/apiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/copyFromPublicLink.feature
  tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToRoot.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
  tests/acceptance/features/apiSharePublicLink3/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/apiShareReshareToRoot1/reShare.feature
  tests/acceptance/features/apiShareReshareToRoot2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToRoot2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToRoot2/reShareSubfolder.feature
  tests/acceptance/features/apiShareReshareToRoot2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareReshareToRoot3/reShareUpdate.feature
  tests/acceptance/features/apiShareReshareToShares1/reShare.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareSubfolder.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareReshareToShares3/reShareUpdate.feature
  tests/acceptance/features/apiShareUpdateToRoot/updateShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiSharingNotificationsToRoot/sharingNotifications.feature
  tests/acceptance/features/apiSharingNotificationsToShares/sharingNotifications.feature
  tests/acceptance/features/apiTags/createTags.feature
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinSkip.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiWebdavDelete/deleteFolderContents.feature
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature
  tests/acceptance/features/apiWebdavOperations/listFiles.feature
  tests/acceptance/features/apiWebdavOperations/search.feature
  tests/acceptance/features/apiWebdavPreviews/previews.feature
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
  tests/acceptance/features/apiWebdavProperties1/getQuota.feature
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedNameAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectoryAsyncUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToBlacklistedNameUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileToExcludedDirectoryUsingNewChunking.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/apiWebdavUploadTUS/creationWithUploadExtension.feature
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelCreationExtension.feature
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelUpload.feature
  tests/acceptance/features/apiWebdavUploadTUS/optionsRequest.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFileMtime.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToNonExistingFolder.feature
Labels: QA:team

#40468 [tests-only] Refactored inter scenarios space
  tests/acceptance/features/cliBackground/backgroundJobs.feature
  tests/acceptance/features/cliBackground/backgroundQueue.feature
  tests/acceptance/features/cliCreateLocalStorage/createLocalStorage.feature
  tests/acceptance/features/cliCreateLocalStorage/createLocalStorageForGroups.feature
  tests/acceptance/features/cliCreateLocalStorage/createLocalStorageForGroupsAndUsers.feature
  tests/acceptance/features/cliCreateLocalStorage/createLocalStorageForUsers.feature
  tests/acceptance/features/cliCreateLocalStorage/createLocalStorageOc10Issue36719.feature
  tests/acceptance/features/cliCreateLocalStorage/createLocalStorageReadOnly.feature
  tests/acceptance/features/cliCreateLocalStorage/createLocalStorageReadOnlyAndShare.feature
  tests/acceptance/features/cliCreateLocalStorage/createLocalStorageReadWriteAndShare.feature
  tests/acceptance/features/cliExternalStorage/Sharing.feature
  tests/acceptance/features/cliExternalStorage/cliIncomingShares.feature
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
  tests/acceptance/features/cliLocalStorage/deleteLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/exportLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/listLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/manageBackendConfig.feature
  tests/acceptance/features/cliLocalStorage/manageOptionsForLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/scanLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/scanLocalStorageOc10Issue33670.feature
  tests/acceptance/features/cliLocalStorage/showBackendsForMount.feature
  tests/acceptance/features/cliLocalStorage/verifyMountConfiguration.feature
  tests/acceptance/features/cliMain/configKey.feature
  tests/acceptance/features/cliMain/filesChecksum.feature
  tests/acceptance/features/cliMain/logManage.feature
  tests/acceptance/features/cliMain/logOwnCloud.feature
  tests/acceptance/features/cliMain/maintenance.feature
  tests/acceptance/features/cliMain/occMigrationStatus.feature
  tests/acceptance/features/cliMain/securityCertificates.feature
  tests/acceptance/features/cliManageApps/appUpgrade.feature
  tests/acceptance/features/cliManageApps/listApps.feature
  tests/acceptance/features/cliProvisioning/addGroup.feature
  tests/acceptance/features/cliProvisioning/addToGroup.feature
  tests/acceptance/features/cliProvisioning/addUser.feature
  tests/acceptance/features/cliProvisioning/deleteGroup.feature
  tests/acceptance/features/cliProvisioning/deleteUser.feature
  tests/acceptance/features/cliProvisioning/disableApp.feature
  tests/acceptance/features/cliProvisioning/disableUser.feature
  tests/acceptance/features/cliProvisioning/editUser.feature
  tests/acceptance/features/cliProvisioning/enableApp.feature
  tests/acceptance/features/cliProvisioning/enableUser.feature
  tests/acceptance/features/cliProvisioning/getAppInfo.feature
  tests/acceptance/features/cliProvisioning/getApps.feature
  tests/acceptance/features/cliProvisioning/getGroup.feature
  tests/acceptance/features/cliProvisioning/getGroups.feature
  tests/acceptance/features/cliProvisioning/getUser.feature
  tests/acceptance/features/cliProvisioning/getUserGroups.feature
  tests/acceptance/features/cliProvisioning/getUsers.feature
  tests/acceptance/features/cliProvisioning/removeFromGroup.feature
  tests/acceptance/features/cliProvisioning/resetUserPassword.feature
  tests/acceptance/features/cliProvisioning/userLastSeen.feature
  tests/acceptance/features/cliProvisioning/userReport.feature
  tests/acceptance/features/cliProvisioning/userSettings.feature
  tests/acceptance/features/cliTrashbin/trashbin.feature
Labels: QA:team

#40473 Add a genrenic config sample description for S3 Primary
  config/config.apps.sample.php
Labels: 3 - To Review

#40435 [tests-only] Remove the similar step for exporting mount storage
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
Labels: QA:team

#40475 Revert "Copy encryption keys first and then rename the files"
  changelog/unreleased/40433
  lib/private/Files/Storage/Wrapper/Encryption.php
  tests/lib/Files/Storage/Wrapper/EncryptionTest.php
Labels: 3 - To Review

#40451 [tests-only] Refactored step implementation for adding public link to server
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/PublicLinkFilesPage.php
Labels: QA:team

#40481 Config Sample update for openidconnect
  config/config.apps.sample.php
Labels: 4 - To release

#40476 [tests-only] Determine group existence using group name
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#40291 Restore and delete operations in trashbin will affect versions
  apps/dav/lib/TrashBin/TrashBinManager.php
  apps/files_trashbin/ajax/delete.php
  apps/files_trashbin/ajax/undelete.php
  apps/files_trashbin/lib/TrashExpiryManager.php
  apps/files_trashbin/lib/Trashbin.php
  apps/files_trashbin/tests/TrashbinTest.php
  changelog/unreleased/40291
Labels: 3 - To Review

#40412 Files_external mount config will show group displaynames
  apps/files_external/ajax/applicable.php
  changelog/unreleased/40412
Labels: 3 - To Review

#40442 [tests-only]Replace `mailhog` email service with `inbucket` mail service
  .drone.star
  tests/TestHelpers/EmailHelper.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/bootstrap/WebUILoginContext.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/cliProvisioning/resetUserPassword.feature
  tests/acceptance/features/cliProvisioning/resetUserPasswordOc10Issue36985.feature
  tests/acceptance/features/lib/AdminGeneralSettingsPage.php
  tests/acceptance/features/webUIAddUsers/addUsers.feature
  tests/acceptance/features/webUIAddUsers/addUsersBySubAdmin.feature
  tests/acceptance/features/webUIAdminSettings/adminGeneralSettings.feature
  tests/acceptance/features/webUILogin/resetPassword.feature
  tests/acceptance/features/webUILogin/resetPasswordUsingEmail.feature
  tests/acceptance/features/webUIPersonalSettings/changeOwnEmailAddress.feature
  tests/acceptance/features/webUISharingInternalGroups1/shareWithGroups.feature
  tests/acceptance/features/webUISharingInternalUsers1/miscShareWithUsers.feature
  tests/acceptance/features/webUISharingPublic1/createPublicLinkShares.feature
  tests/acceptance/features/webUISharingPublic1/permissionsShareFileByPublicLink.feature
  tests/acceptance/features/webUISharingPublic1/permissionsShareFolderByPublicLink.feature
  tests/acceptance/features/webUISharingPublic2/reShareByPublicLink.feature
  tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature
  tests/acceptance/run.sh
Labels: QA:team

#40479 [tests-only] Add conditional checking for users and groups between graph and provisioning APIs
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#40495 [tests-only][full-ci]Refactor `MCKOL` request to non-existence user and to another users endpoint
  tests/TestHelpers/SpaceNotFoundException.php
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiAuthWebDav/webDavMCKOLAuthOC10Issue40485.feature
  tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team
