Repository owncloud/core, pull requests merged in 2022-06, with the labels that each got.

#40112 [tests-only] Bump phpstan 1.7.1 to 1.7.7
  vendor-bin/phpstan/composer.json
Labels: 3 - To Review, QA:team

#40114 [tests-only] [full-ci] More flexible tests for share ids
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareExpirationDate.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/deleteShareFromRoot.feature
  tests/acceptance/features/apiShareManagementBasicToShares/deleteShareFromShares.feature
  tests/acceptance/features/apiSharePublicLink1/changingPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareOc10Issue37605.feature
  tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToRoot.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesNewDav.feature
  tests/acceptance/features/apiSharePublicLink2/reShareAsPublicLinkToSharesOldDav.feature
  tests/acceptance/features/apiSharePublicLink3/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/apiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink3/updatePublicLinkShareOc10Issue37653.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettingsOC10Issue36803.feature
  tests/acceptance/features/webUISharingInternalGroups2/shareWithGroupUsingExpirationDate.feature
  tests/acceptance/features/webUISharingInternalGroups2/shareWithGroupsEdgeCases.feature
  tests/acceptance/features/webUISharingInternalUsers1/createShareWithUsers.feature
  tests/acceptance/features/webUISharingInternalUsers2/adminDisablesSharePermissions.feature
  tests/acceptance/features/webUISharingInternalUsers2/shareWithUserUsingExpirationDate.feature
  tests/acceptance/features/webUISharingPublic1/createPublicLinkShares.feature
  tests/acceptance/features/webUISharingPublic2/reShareByPublicLink.feature
  tests/acceptance/features/webUISharingPublic2/shareByPublicLink.feature
Labels: QA:team

#40115 [tests-only][full-ci]Added meta api request on root folder
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA:team

#40094 [tests-only] [full-ci] added test for occ migration command
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/cliMain/occMigrationStatus.feature
Labels: QA:team

#40117 [tests-only] [full-ci] Add test step for 'the info of the last public link share should include
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#40118 [full-ci] [tests-only] Implemented some missing steps of activity and admin audit app
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#40124 [tests-only] Remove useless owncloudLog drone steps
  .drone.star
Labels: QA:team

#40129 [tests-only][full-ci]Skip migration status for app test on OC stable
  tests/acceptance/features/cliMain/occMigrationStatus.feature
Labels: QA:team

#40133 [tests-only] [full-ci] Fix deleteLastShareUsingSharingApi
  tests/acceptance/features/bootstrap/Sharing.php
Labels: QA:team

#40141 [tests-only] Add copy tests with reduced quota for issue-40140
  tests/acceptance/features/apiMain/quota.feature
  tests/acceptance/features/apiMain/quotaOc10Issue40140.feature
Labels: QA:team

#40146 [tests-only] Skip failing quota tests on encryption app
  tests/acceptance/features/apiMain/quotaOc10Issue40140.feature
Labels: QA:team

#40143 Add missing js file
  apps/files_sharing/templates/public.php
  changelog/unreleased/40143
Labels: 3 - To Review

#39988 Ignore thumbnails when propagating in home
  changelog/unreleased/39988
  lib/private/Files/Cache/HomePropagator.php
Labels: 3 - To Review

#40150 [tests-only] [full-ci] Remove special files_primary_s3 guzzle code from CI
  .drone.star
Labels: QA:team

#40091 Ensure the /user/files directory is always present in the FS
  apps/dav/tests/unit/Connector/Sabre/RequestTest/DeleteTest.php
  changelog/unreleased/40091
  lib/private/Files/Node/Folder.php
  lib/private/Files/Node/LazyRoot.php
  lib/private/Files/Node/NonExistingFolder.php
  lib/private/Files/Node/Root.php
  lib/private/User/Session.php
  lib/private/User/User.php
  lib/public/IUser.php
  tests/lib/Files/Node/NodeTest.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#40152 Do not invalidate app tokens in case LDAP connection is temporary una…
  changelog/unreleased/40152
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#40166 [tests-only] skip new 'add group' test on older oC10
  tests/acceptance/features/webUIManageUsersGroups/addGroup.feature
Labels: QA:team

#40168 [tests-only][full-ci] Make webdav changes made in PR40159 only for oCIS
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40142 Do not overlap the author's comment with other things on small screens
  apps/comments/css/comments.css
  changelog/unreleased/40142
Labels: 3 - To Review
