Repository owncloud/core, pull requests merged in 2022-01, with the labels that each got.

#39634 [tests-only] skip new group-name tests on 10.9.1
  tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
Labels: QA:team

#39622 [tests-only]Add more test scenarios for the new version metadata feature
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA:team

#39635 [tests-only] Added scenario to check for the user access to a pending share
  tests/acceptance/features/apiShareOperationsToRoot1/accessToShare.feature
Labels: QA:team

#39631 Bump PHP dependencies
  changelog/unreleased/PHPdependencies20211123onward
  changelog/unreleased/PHPdependencies20211123onwardSymfony
  composer.lock
Labels: dependencies, php

#39636 [tests-only] [full-ci] Version author refactor
  tests/acceptance/features/apiVersions/fileVersionAuthor.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39638 [tests-only] [full-ci] Run CI against federated 10.8.0 server
  .drone.star
Labels: QA:team

#39640 [tests-only] Update PHP tool dependencies
  composer.lock
Labels: dependencies, php

#39641 [tests-only] Get personal space id from the request helper
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39646 Bump symfony/polyfill to v1.24.0
  changelog/unreleased/PHPdependencies20211123onwardSymfony
  composer.lock
Labels: dependencies, php

#39643 [tests-only][mobile-screen] wait till settings button is visible before clicking
  tests/acceptance/features/lib/FilesPageBasic.php
Labels: QA:team

#39648 [tests-only] Remember space id for users after the first fetch
  tests/TestHelpers/WebDavHelper.php
Labels: QA:team

#39661 [tests-only] Skip new group tests on old oC10
  tests/acceptance/features/cliProvisioning/addGroup.feature
Labels: QA:team

#39649 Upgrading doctrine/dbal (2.13.6 => 2.13.7)
  changelog/unreleased/PHPdependencies20211123onward
  composer.lock
Labels: dependencies, php

#39668 [tests-only] [full-ci] Fix install core from tarball
  .drone.star
Labels: QA:team

#39670 Fix getting the file owner for share recipients
  apps/files_versions/lib/MetaStorage.php
  apps/files_versions/lib/Storage.php
  changelog/10.9.1_2021-12-28/39670
Labels: 10.9-regression

#39673 Fix issue with wrong version authors being saved
  apps/files_versions/lib/MetaStorage.php
  apps/files_versions/lib/Storage.php
  changelog/10.9.1_2021-12-28/39673
Labels: 10.9-regression

#39681 [tests-only] skip test because of encryption issue 321
  tests/acceptance/features/apiVersions/fileVersionAuthor.feature
Labels: QA:team

#39685 [tests-only] skip propfindOnLocalStorage tests on user-keys encryption due to encryption issue 320
  tests/acceptance/features/cliLocalStorage/propfindOnLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/propfindOnLocalStorageOc10Issue39470.feature
Labels: QA:team

#39693 Bump PHP dependencies
  changelog/unreleased/PHPdependencies20211123onward
  composer.lock
Labels: dependencies, php

#39695 Update paragonie/constant_time_encoding (2.4.0 to 2.5.0)
  .drone.star
  changelog/unreleased/PHPdependencies20211123onward
  composer.lock
Labels: dependencies, php

#39691 [tests-only][full-ci]Fix Intermittent fail webUIUpload/upload.feature:131
  tests/acceptance/features/lib/OwncloudPage.php
Labels: QA:team

#39703 [full-ci] Acceptance tests for deep moves and fix 39702
  changelog/unreleased/39703
  changelog/unreleased/PHPdependencies20211123onward
  composer.lock
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
Labels: dependencies, php

#39705 [tests-only] Test moving a folder into a sub-folder of itself
  tests/acceptance/features/apiWebdavMove1/moveFolder.feature
Labels: QA:team

#39701 [tests-only] run chunking upload tests using the spaces dav path
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39708 [tests-only] enhance theWebdavChecksumShouldMatch test
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/bootstrap/ChecksumContext.php
Labels: QA:team

#39711 [tests-only] Tag scenario for issue-ocis-3023 so we can skip it
  tests/acceptance/features/apiWebdavMove1/moveFolder.feature
Labels: QA:team

#39713 Bump laminas PHP dependencies
  changelog/unreleased/PHPdependencies20211123onward
  composer.lock
Labels: dependencies, php

#39712 [tests-only] use spaces dav path in `apiAuth` suite
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/apiAuth/webDavAuth.feature
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#39719 [tests-only] [full-ci] Add API test coverage for files and folders names like Shares
  tests/acceptance/features/apiWebdavProperties1/createFileFolderWhenSharesExist.feature
Labels: QA:team

#39724 [tests-only] Add tests for moving a share inside another share
  tests/acceptance/features/apiShareManagementToRoot/moveShareInsideAnotherShare.feature
  tests/acceptance/features/apiShareManagementToShares/moveShareInsideAnotherShare.feature
Labels: QA:team

#39726 [tests-only] [full-ci] Check for newline at end of expected-failures file
  tests/acceptance/run.sh
Labels: QA:team

#39728 [tests-only] [full-ci] adjust moveShareInsideAnotherShare tests for oCIS
  tests/acceptance/features/apiShareManagementToShares/moveShareInsideAnotherShare.feature
Labels: QA:team
