Repository owncloud/core, pull requests merged in 2022-03, with the labels that each got.

#39834 [tests-only] [full-ci] Added Then steps to improve checks in tests for apiProvisioning-v1 suite
  tests/acceptance/features/apiProvisioning-v1/addUser.feature
  tests/acceptance/features/apiProvisioning-v1/apiProvisioningUsingAppPassword.feature
  tests/acceptance/features/apiProvisioning-v1/deleteUser.feature
  tests/acceptance/features/apiProvisioning-v1/editUser.feature
  tests/acceptance/features/apiProvisioning-v1/enableUser.feature
  tests/acceptance/features/apiProvisioning-v1/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v1/getUser.feature
  tests/acceptance/features/apiProvisioning-v1/getUsers.feature
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
Labels: QA:team

#39836 [tests-only][full-ci]added then steps for apiProvisioning-v2 suite
  tests/acceptance/features/apiProvisioning-v2/apiProvisioningUsingAppPassword.feature
  tests/acceptance/features/apiProvisioning-v2/editUser.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/apiProvisioning-v2/getSubAdmins.feature
  tests/acceptance/features/apiProvisioning-v2/getUsers.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#39835 [tests-only][full-ci]Add then step to suites apiWebdavMove(1 and 2)
  tests/acceptance/features/apiWebdavMove1/moveFileAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFileToBlacklistedNameAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFileToExcludedDirectoryAsync.feature
  tests/acceptance/features/apiWebdavMove1/moveFolder.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavMove2/moveShareOnOcis.feature
Labels: QA:team

#39846 Use memcache and avoid loading the whole mimetypes table in memory
  lib/private/Files/Type/Loader.php
  lib/private/Server.php
  tests/lib/Files/Type/LoaderTest.php
Labels: 3 - To Review

#39845 [tests-only] [full-ci] Added Then steps to improve checks in tests for apiWebdavPreviews suite
  tests/acceptance/features/apiWebdavPreviews/previews.feature
Labels: QA:team

#39855 Bump symfony/polyfill to v1.25.0
  changelog/unreleased/PHPdependencies20211123onwardSymfony
  composer.lock
Labels: dependencies, php

#39859 Bump dbal and laminas-validator PHP dependencies
  changelog/unreleased/PHPdependencies20211123onward
  composer.lock
Labels: dependencies, php

#39840 [tests-only][full-ci]added then steps for apiProvisioningGroups-v1 suite
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroupsOc10Issue31015.feature
Labels: QA:team

#39850 [tests-only][full-ci]added then steps for apiProvisioningGroups-v2 suite
  tests/acceptance/features/apiProvisioningGroups-v2/getGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getSubAdminGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
Labels: QA:team

#39849 [tests-only] [full-ci] Added Then steps to improve checks in tests for apiWebdavLocks suite
  tests/acceptance/features/apiWebdavLocks/folder.feature
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkLockdiscovery.feature
Labels: QA:team

#39853 [tests-only][full-ci]Add then step to suites apiSharePublicLink(1 and 2)
  tests/acceptance/features/apiSharePublicLink1/accessToPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShareOc10Issue37605.feature
  tests/acceptance/features/apiSharePublicLink2/allowGroupToCreatePublicLinks.feature
  tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink2/updatePublicLinkShareOc10Issue37653.feature
  tests/acceptance/features/apiSharePublicLink2/uploadToPublicLinkShare.feature
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39866 [tests-only] [full-ci] Bump postgres to 10.20 in tests
  .drone.star
Labels: QA:team

#39869 [tests-only] added a @notToImplementOnOcis tag in apiProvisioningV2 suite
  tests/acceptance/features/apiProvisioning-v2/apiProvisioningUsingAppPassword.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#39860 [CI] Updated drone.star file to match latest changes
  .drone.star
  tests/acceptance/cancelBuilds.sh
Labels: QA:team

#39856 [full-ci] Allow disabling the files_external app
  .drone.star
  changelog/unreleased/39856
  core/shipped.json
  lib/private/Files/External/Service/LegacyStoragesService.php
  settings/Panels/Helper.php
  tests/Core/Controller/LoginControllerTest.php
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuth/corsOc10Issue34679.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuth.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuthFilesExternal.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuthFilesExternalOc10Issue32068.feature
  tests/acceptance/features/apiAuthOcs/ocsGETAuthOc10Issue32068.feature
  tests/acceptance/features/apiProvisioning-v1/getApps.feature
  tests/acceptance/features/apiProvisioning-v2/getApps.feature
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
  tests/acceptance/features/cliProvisioning/getApps.feature
  tests/lib/App/ManagerTest.php
  tests/lib/AppTest.php
  tests/lib/Files/External/Service/GlobalStoragesServiceDeleteUserTest.php
Labels: 3 - To Review

#39887 [tests-only] [full-ci] Run files_external acceptance tests in CI
  .drone.star
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiMain/external-storage.feature
  tests/acceptance/features/apiShareManagementBasicToRoot/createShareFromLocalStorageToRootFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareFromLocalStorageToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToRoot/moveReceivedShareFromLocalStorage.feature
  tests/acceptance/features/apiShareManagementToShares/moveReceivedShareFromLocalStorage.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageForGroups.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageForGroupsAndUsers.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageForUsers.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageOc10Issue36713.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageOc10Issue36719.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageReadOnly.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageReadOnlyAndShare.feature
  tests/acceptance/features/cliLocalStorage/createLocalStorageReadWriteAndShare.feature
  tests/acceptance/features/cliLocalStorage/deleteLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/exportLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/importLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/listLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/manageBackendConfig.feature
  tests/acceptance/features/cliLocalStorage/manageOptionsForLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/propfindOnLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/propfindOnLocalStorageOc10Issue39470.feature
  tests/acceptance/features/cliLocalStorage/scanLocalStorage.feature
  tests/acceptance/features/cliLocalStorage/scanLocalStorageOc10Issue33670.feature
  tests/acceptance/features/cliLocalStorage/showBackendsForMount.feature
  tests/acceptance/features/cliLocalStorage/verifyMountConfiguration.feature
  tests/acceptance/features/cliMain/maintenance.feature
  tests/acceptance/features/cliMain/transferOwnership.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettings.feature
  tests/acceptance/features/webUIAdminSettings/adminStorageSettingsOC10Issue36803.feature
  tests/acceptance/features/webUIFiles/externalStorage.feature
Labels: QA:team

#39890 [tests-only] Bump phpunit to 9.5.19
  composer.lock
Labels: dependencies, php

#39892 Keep the previous behavior for remote shares with encryption
  lib/private/Encryption/Util.php
Labels: 3 - To Review

#39886 [tests-only][full-ci] Added WebUI tests for checking version author
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/webUIFiles/versions.feature
Labels: QA:team

#39896 [tests-only] [full-ci] Improve createLocalStorageMount test code
  .drone.star
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/OccContext.php
Labels: QA:team

#39900 Improve FileDrop view
  apps/files_sharing/css/upload.css
  apps/files_sharing/templates/public.php
  changelog/unreleased/39900
  core/css/header.css
Labels: 3 - To Review

#39902 [tests-only] [full-ci] Run all cliExternalStorage tests in CI
  .drone.star
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/cliExternalStorage/filesExternalWebdavOwncloud.feature
Labels: QA:team

#39907 Align "close" for messages
  changelog/unreleased/39907
  core/css/styles.css
Labels: enhancement

#39908 Fix sharing with user-key encryption
  lib/private/Encryption/Util.php
Labels: 3 - To Review

#39909 [tests-only] Fix ldapAdminPassword in tests
  tests/acceptance/features/bootstrap/FeatureContext.php
Labels: QA:team

#39910 [tests-only] Make deleteLdapUsersAndGroups backward-compatible for oC10 user_ldap testing
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#39917 [tests-only] Adjust tests for issue-39347
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareReceivedMultipleWaysIssue39347.feature
Labels: QA:team

#39920 [tests-only][full-ci]Improve Then step in apiWebdavLocks3 suite
  tests/acceptance/features/apiWebdavLocks3/independentLocks.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToRoot.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToShares.feature
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#39921 [tests-only][full-ci]Improve then steps usages inside acceptance tests suite `apiTags`
  tests/acceptance/features/apiTags/assignTags.feature
  tests/acceptance/features/apiTags/assignTagsGroup.feature
  tests/acceptance/features/apiTags/createTags.feature
  tests/acceptance/features/apiTags/editTags.feature
  tests/acceptance/features/apiTags/retreiveTags.feature
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#39919 [tests-only][full-ci] Improve Then step in apiWebdavLocks2 suite
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/resharedSharesToShares.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToRoot.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeoutSharesToShares.feature
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team
