Repository owncloud/core, pull requests merged in 2023-04, with the labels that each got.

#40719 [full-ci] Remove loader in ChunkLocationProvider.php
  apps/dav/lib/Upload/ChunkLocationProvider.php
Labels: 3 - To Review

#40726 fix: do not accept federated shares where the name is too long
  apps/federatedfilesharing/lib/Controller/RequestHandlerController.php
  apps/federatedfilesharing/tests/Controller/RequestHandlerTest.php
  changelog/unreleased/40702
  changelog/unreleased/40726
Labels: 3 - To Review

#40662 [tests-only] update litmus to maintained container in ci
  .drone.star
  tests/litmus/run.sh
Labels: 1 - To develop

#40744 [unit-tests] Restore services in teardown
  tests/Core/Command/User/ReportTest.php
Labels: QA:team

#40747 [tests-only] [full-ci] Run some CI pipelines with Ubuntu 22
  .drone.star
Labels: QA:team

#40754 [tests-only] [full-ci] Cleanup acceptance tests
  tests/acceptance/features/apiVersions/fileVersionAuthor.feature
  tests/acceptance/features/apiVersions/fileVersionAuthorSharingToShares.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
  tests/acceptance/features/apiVersions/fileVersionsSharingToShares.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/AppManagementContext.php
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/bootstrap/CalDavContext.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/CardDavContext.php
  tests/acceptance/features/bootstrap/ChecksumContext.php
  tests/acceptance/features/bootstrap/CommentsContext.php
  tests/acceptance/features/bootstrap/CorsContext.php
  tests/acceptance/features/bootstrap/EmailContext.php
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/acceptance/features/bootstrap/FavoritesContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/FederationContext.php
  tests/acceptance/features/bootstrap/FilesVersionsContext.php
  tests/acceptance/features/bootstrap/IpContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  tests/acceptance/features/bootstrap/OccAppManagementContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/ShareesContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/acceptance/features/bootstrap/TransferOwnershipContext.php
  tests/acceptance/features/bootstrap/TrashbinContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
Labels: QA:team

#40763 [tests-only] Add unit tests pipelines for mariaDB 10.9 10.10 10.11
  .drone.star
Labels: QA:team
