Repository owncloud/core, pull requests merged in 2023-01, with the labels that each got.

#40546 [full-ci] [tests-only]WebUI tests added to share resource with multiple users at once
  tests/acceptance/features/bootstrap/WebUISharingContext.php
  tests/acceptance/features/lib/FilesPageElement/SharingDialog.php
  tests/acceptance/features/webUISharingInternalUsers1/createShareWithUsers.feature
Labels: QA:team

#40520 Refactor login to converge in the same function
  lib/private/User/Session.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#40555 [tests-only][full-ci] Add PROPFIND tests for public link endpoint
  tests/acceptance/features/apiWebdavOperations/propfind.feature
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/WebDavPropertiesContext.php
Labels: QA:team

#40563 fix: set length of oc_calendars.components to 255
  changelog/unreleased/40563
  core/Migrations/Version20230105001100.php
Labels: 3 - To Review

#40521 [full-ci] Adjust symfony deprecated
  changelog/unreleased/PHPdependencies20220920onwardSymfony
  lib/private/L10N/L10N.php
  lib/public/App/ManagerEvent.php
  lib/public/Comments/CommentsEntityEvent.php
  lib/public/Comments/CommentsEvent.php
  lib/public/Console/ConsoleEvent.php
  lib/public/Notification/Events/RegisterConsumerEvent.php
  lib/public/Notification/Events/RegisterNotifierEvent.php
  lib/public/Roles/AddRolesEvent.php
  lib/public/SabrePluginEvent.php
  lib/public/Share/Events/ShareEvent.php
  lib/public/SystemTag/ManagerEvent.php
  lib/public/SystemTag/MapperEvent.php
  lib/public/User/UserExtendedAttributesEvent.php
Labels: 3 - To Review

#40565 Bump version to 10.12.0 prealpha
  version.php
Labels: 3 - To Review

#40570 [tests-only] [full-ci] Revert "Remove fsweb.test.owncloud.com SMB PHP unit test pipeline"
  .drone.star
  tests/drone/configs/config.files_external.smb-windows.php
  tests/drone/test-phpunit.sh
Labels: QA:team

#40571 Fully initialize the FS in the cleanup command (upload folder is moun…
  apps/dav/lib/Command/CleanupChunks.php
  changelog/unreleased/40571
Labels: 3 - To Review

#40569 [full-ci][tests-only]Refactor owncloud log ignore line variable to 1
  tests/acceptance/features/bootstrap/LoggingContext.php
Labels: QA:team

#40573 [tests-only][full-ci] Add tests for checking file versions uploaded with same mtime
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA:team

#40575 [full-ci] Fix event dispatch calls for Symfony
  apps/comments/lib/Dav/RootCollection.php
  apps/dav/appinfo/v1/webdav.php
  apps/dav/lib/CardDAV/CardDavBackend.php
  apps/dav/lib/Connector/Sabre/File.php
  apps/dav/lib/Files/Sharing/PublicLinkEventsPlugin.php
  apps/dav/lib/Server.php
  apps/dav/tests/unit/Files/Sharing/PublicLinkEventsPluginTest.php
  apps/federatedfilesharing/lib/FedShareManager.php
  apps/federatedfilesharing/lib/FederatedShareProvider.php
  apps/federatedfilesharing/tests/FederatedShareProviderTest.php
  apps/federation/lib/TrustedServers.php
  apps/federation/tests/TrustedServersTest.php
  apps/files/download.php
  apps/files/lib/Controller/ViewController.php
  apps/files/tests/Controller/ViewControllerTest.php
  apps/files_sharing/lib/Controller/Share20OcsController.php
  apps/files_sharing/lib/Controllers/ExternalSharesController.php
  apps/files_sharing/lib/Controllers/ShareController.php
  apps/files_sharing/lib/External/Manager.php
  apps/files_sharing/tests/Controller/Share20OcsControllerTest.php
  apps/files_sharing/tests/External/ManagerTest.php
  changelog/unreleased/PHPdependencies20220920onwardSymfony
  lib/private/Share20/Manager.php
  lib/private/User/User.php
  tests/lib/User/UserTest.php
Labels: 3 - To Review

#40557 [tests-only][full-ci] Add API test scenarios for non-existent public links
  tests/acceptance/features/apiSharePublicLink1/accessToPublicLinkShare.feature
Labels: QA:team

#40582 [tests-only][full-ci]Add test for checking the href of the public link file
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
Labels: QA:team

#40583 [tests-only][full-ci] Skip recently added file versions tests on s3 storage
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA:team

#40581 [tests-only] [full-ci] remove scenario examples that are only for ocis/reva
  tests/acceptance/features/apiAuth/webDavAuth.feature
  tests/acceptance/features/apiFavorites/favorites.feature
  tests/acceptance/features/apiMain/checksums.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/apiShareOperationsToShares2/getWebDAVSharePermissions.feature
  tests/acceptance/features/apiSharePublicLink2/multilinkSharing.feature
  tests/acceptance/features/apiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink3/uploadToPublicLinkShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiTranslation/translation.feature
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbin/trashbinSharingToShares.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/apiWebdavDelete/deleteFile.feature
  tests/acceptance/features/apiWebdavDelete/deleteFolder.feature
  tests/acceptance/features/apiWebdavDelete/deleteFolderContents.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/deleteFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation1/moveFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/copyFileFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/createFolder.feature
  tests/acceptance/features/apiWebdavEtagPropagation2/upload.feature
  tests/acceptance/features/apiWebdavLocks/exclusiveLocks.feature
  tests/acceptance/features/apiWebdavLocks/requestsWithToken.feature
  tests/acceptance/features/apiWebdavLocks2/setTimeout.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocks.feature
  tests/acceptance/features/apiWebdavLocks3/independentLocksShareToShares.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlock.feature
  tests/acceptance/features/apiWebdavLocksUnlock/unlockSharingToShares.feature
  tests/acceptance/features/apiWebdavMove1/moveFolder.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToBlacklistedName.feature
  tests/acceptance/features/apiWebdavMove1/moveFolderToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavMove2/moveFileToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavOperations/listFiles.feature
  tests/acceptance/features/apiWebdavOperations/propfind.feature
  tests/acceptance/features/apiWebdavOperations/refuseAccess.feature
  tests/acceptance/features/apiWebdavOperations/search.feature
  tests/acceptance/features/apiWebdavProperties1/copyFile.feature
  tests/acceptance/features/apiWebdavProperties1/createFileFolder.feature
  tests/acceptance/features/apiWebdavProperties1/getQuota.feature
  tests/acceptance/features/apiWebdavProperties1/setFileProperties.feature
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFile.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToBlacklistedName.feature
  tests/acceptance/features/apiWebdavUpload1/uploadFileToExcludedDirectory.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature
Labels: QA:team

#40228 test encryption corner cases
  tests/data/string-zero-2269944.txt
  tests/data/string-zero-6073.txt
  tests/data/string-zero.txt
  tests/lib/Files/Stream/EncryptionTest.php
Labels: 2 - Developing

#40497 [full-ci] Files and folder won't be deleted from the "shared with others" section
  apps/files_sharing/js/app.js
  changelog/unreleased/40497
  tests/acceptance/features/webUICreateDelete/deleteFilesFolders.feature
Labels: 3 - To Review

#40592 Add a default Event to dispatch events with just a name
  apps/files/lib/Controller/ViewController.php
  apps/files_sharing/lib/Controllers/ShareController.php
  changelog/unreleased/PHPdependencies20220920onwardSymfony
  settings/users.php
Labels: 3 - To Review

#40585 [tests-only][full-ci] Removed scenarios that are only for ocis/reva
  tests/acceptance/features/apiAuth/webDavAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavCOPYAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavDELETEAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavLOCKAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavMKCOLAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavMOVEAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPOSTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPROPFINDAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPROPPATCHAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavPUTAuth.feature
  tests/acceptance/features/apiAuthWebDav/webDavSpecialURLs.feature
  tests/acceptance/features/apiProvisioning-v1/resetUserPassword.feature
  tests/acceptance/features/apiProvisioning-v2/resetUserPassword.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getUserGroups.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getUserGroups.feature
  tests/acceptance/features/apiShareManagementToShares/moveShareInsideAnotherShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareChain.feature
  tests/acceptance/features/apiWebdavOperations/downloadFile.feature
  tests/acceptance/features/apiWebdavUploadTUS/checksums.feature
  tests/acceptance/features/apiWebdavUploadTUS/creationWithUploadExtension.feature
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelCreationExtension.feature
  tests/acceptance/features/apiWebdavUploadTUS/lowLevelUpload.feature
  tests/acceptance/features/apiWebdavUploadTUS/optionsRequest.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFile.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadFileMtime.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToMoveFolder.feature
  tests/acceptance/features/apiWebdavUploadTUS/uploadToNonExistingFolder.feature
Labels: QA:team

#40597 [tests-only][full-ci] Remove scenario tag `skipOnOcis` from feature files
  tests/acceptance/features/apiAuth/cors.feature
  tests/acceptance/features/apiAuthWebDav/webDavCOPYAuthOC10Issue40144.feature
  tests/acceptance/features/apiAuthWebDav/webDavMCKOLAuthOC10Issue40485.feature
  tests/acceptance/features/apiAuthWebDav/webDavPUTAuthOC10Issue39597.feature
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareUniqueReceivedNames.feature
  tests/acceptance/features/apiShareCreateSpecialToShares1/createShareWhenExcludedFromSharing.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareManagementBasicToShares/excludeGroupFromReceivingSharesToSharesFolder.feature
  tests/acceptance/features/apiShareManagementToShares/mergeShare.feature
  tests/acceptance/features/apiSharePublicLink1/createPublicLinkShare.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareDisabled.feature
  tests/acceptance/features/apiShareReshareToShares2/reShareWhenShareWithOnlyMembershipGroups.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
  tests/acceptance/features/apiTranslation/translation.feature
  tests/acceptance/features/apiTrashbin/trashbinDelete.feature
  tests/acceptance/features/apiTrashbin/trashbinFilesFolders.feature
  tests/acceptance/features/apiTrashbinRestore/trashbinRestore.feature
  tests/acceptance/features/apiWebdavMove1/moveFolder.feature
  tests/acceptance/features/apiWebdavMove2/moveFile.feature
  tests/acceptance/features/apiWebdavPreviews/previewsExactSizing.feature
  tests/acceptance/features/apiWebdavProperties2/getFileProperties.feature
  tests/acceptance/features/cliMain/configKey.feature
Labels: QA:team

#40598 [tests-only][full-ci] Remove scenario tag @toImplementOnOcis from feature files
  tests/acceptance/features/apiProvisioningGroups-v1/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/deleteGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/getGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v1/removeFromGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/addToGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/deleteGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/getGroup.feature
  tests/acceptance/features/apiProvisioningGroups-v2/removeFromGroup.feature
Labels: QA:team

#40602 chore: remove unused dependency patchwork/jsqueeze
  composer.json
  composer.lock
Labels: 3 - To Review

#40604 chore: remove unused and abandoned jakub-onderka/php-console-highlighter
  composer.json
  composer.lock
Labels: 3 - To Review

#40574 Add support for login policies
  changelog/unreleased/40574
  config/config.sample.php
  lib/private/Authentication/LoginPolicies/GroupLoginPolicy.php
  lib/private/Authentication/LoginPolicies/LoginPolicyManager.php
  lib/private/Server.php
  lib/private/User/Session.php
  lib/public/Authentication/LoginPolicies/ILoginPolicy.php
  lib/public/Authentication/LoginPolicies/ILoginPolicyManager.php
  lib/public/IServerContainer.php
  tests/lib/Authentication/LoginPolicies/GroupLoginPolicyTest.php
  tests/lib/Authentication/LoginPolicies/LoginPolicyManagerTest.php
  tests/lib/User/SessionTest.php
Labels: 3 - To Review

#40588 [full-ci] Add account creation time
  apps/provisioning_api/lib/Users.php
  apps/provisioning_api/tests/UsersTest.php
  changelog/unreleased/40588
  core/Command/User/ListUsers.php
  core/Migrations/Version20230120101715.php
  lib/private/User/Account.php
  lib/private/User/AccountMapper.php
  lib/private/User/DeletedUser.php
  lib/private/User/RemoteUser.php
  lib/private/User/User.php
  lib/public/IUser.php
  settings/Controller/UsersController.php
  settings/css/settings.css
  settings/js/users/users.js
  settings/templates/users/main.php
  settings/templates/users/part.userlist.php
  settings/users.php
  tests/Settings/Controller/UsersControllerTest.php
  tests/acceptance/features/apiProvisioning-v1/getUser.feature
  tests/acceptance/features/apiProvisioning-v2/getUser.feature
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/lib/UsersPage.php
  tests/acceptance/features/webUIAddUsers/addUsers.feature
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
  version.php
Labels: 3 - To Review

#40608 [tests-only][full-ci]Skip user creation related test below OcV10.12
  tests/acceptance/features/apiProvisioning-v1/getUser.feature
  tests/acceptance/features/apiProvisioning-v2/getUser.feature
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: QA:team

#40609 [docs-only] Fix config.sample.php
  config/config.sample.php
Labels: 3 - To Review

#40510 [full-ci] Show Username on personal profile settings page
  changelog/unreleased/40510
  settings/Panels/Personal/Profile.php
  settings/css/settings.css
  settings/templates/panels/personal/profile.php
  tests/Settings/Panels/Personal/ProfileTest.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/webUIPersonalSettings/personalGeneralSettings.feature
Labels: 3 - To Review

#40613 [docs-only] Fix auto-provision in config.apps.sample
  config/config.apps.sample.php
Labels: 3 - To Review
