Repository owncloud/core, pull requests merged in 2023-09, with the labels that each got.

#40962 fix: disallow pre-signed url access if the signing key is not initialized
  changelog/unreleased/40962
  lib/private/Security/SignedUrl/Verifier.php
  tests/lib/Security/SignedUrl/VerifierTest.php
Labels: 3 - To Review

#40972 [tests-only] fix the line syntax
  tests/acceptance/features/apiFederationToRoot2/federated.feature
  tests/acceptance/features/apiFederationToShares2/federated.feature
  tests/acceptance/features/apiProvisioning-v2/enableUser.feature
  tests/acceptance/features/apiShareCreateSpecialToRoot1/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareCreateSpecialToShares2/createShareReceivedInMultipleWays.feature
  tests/acceptance/features/apiShareManagementToShares/acceptShares.feature
  tests/acceptance/features/apiSharePublicLink3/uploadToPublicLinkShare.feature
  tests/acceptance/features/apiWebdavPreviews/previews.feature
  tests/acceptance/features/apiWebdavUpload2/uploadFileUsingOldChunking.feature
  tests/acceptance/features/webUICreateDelete/createFolders.feature
  tests/acceptance/features/webUIPersonalSettings/personalGeneralSettings.feature
  tests/acceptance/features/webUISharingInternalUsers2/adminDisablesSharePermissions.feature
Labels: QA:team

#40969 Use app config to disable background jobs and prevent them from running
  changelog/unreleased/40969
  lib/private/BackgroundJob/JobList.php
Labels: 3 - To Review

#40980 Update config.apps.sample.php: add new wopi.proxy.key
  config/config.apps.sample.php
Labels: 4 - To release

#40959 fix: delete all files from object store when user is deleted
  lib/private/Files/ObjectStore/ObjectStoreStorage.php
  lib/private/Files/View.php
  lib/private/User/User.php
  tests/lib/Files/ObjectStore/ObjectStoreDeleteAllTest.php
Labels: 3 - To Review

#40991 Check for existence of creation time when running migrations
  changelog/unreleased/40991
  core/Migrations/Version20230120101715.php
Labels: 3 - To Review

#40961 Allow subadmins to read app config values
  changelog/unreleased/40961
  core/js/config.js
  settings/Application.php
  settings/Controller/AppConfigController.php
  settings/routes.php
  tests/Settings/Controller/AppConfigControllerTest.php
  tests/acceptance/features/bootstrap/WebUIUsersContext.php
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: 3 - To Review

#40990 Remove regexp from PreviewManager list
  changelog/unreleased/40990
  lib/private/PreviewManager.php
Labels: 3 - To Review

#40995 fix: drop usage of ${}
  apps/dav/appinfo/Migrations/Version20170116170538.php
  apps/dav/appinfo/Migrations/Version20170202220512.php
  apps/dav/appinfo/Migrations/Version20170519091921.php
  apps/dav/appinfo/Migrations/Version20170711193427.php
  apps/dav/appinfo/Migrations/Version20170927201245.php
  apps/dav/appinfo/Migrations/Version20180622095921.php
  apps/dav/appinfo/Migrations/Version20190823065724.php
  apps/dav/appinfo/Migrations/Version20200114181454.php
  apps/dav/appinfo/Migrations/Version20210714123001.php
  apps/dav/lib/DAV/Sharing/Backend.php
  apps/federatedfilesharing/appinfo/Migrations/Version20170804201253.php
  apps/federatedfilesharing/appinfo/Migrations/Version20190410160725.php
  apps/files_sharing/appinfo/Migrations/Version20170804201253.php
  apps/files_sharing/appinfo/Migrations/Version20170830112305.php
  apps/files_sharing/appinfo/Migrations/Version20171115154900.php
  apps/files_sharing/appinfo/Migrations/Version20171215103657.php
  apps/files_sharing/appinfo/Migrations/Version20190426123324.php
  apps/files_sharing/appinfo/Migrations/Version20200504211654.php
  apps/files_sharing/appinfo/Migrations/Version20200823121322.php
  apps/files_trashbin/appinfo/Migrations/Version20170804201253.php
  core/Migrations/Version20170101010100.php
  core/Migrations/Version20170101215145.php
  core/Migrations/Version20170111103310.php
  core/Migrations/Version20170213215145.php
  core/Migrations/Version20170315173825.php
  core/Migrations/Version20170320173955.php
  core/Migrations/Version20170516100103.php
  core/Migrations/Version20170711191432.php
  core/Migrations/Version20170804201253.php
  core/Migrations/Version20170928120000.php
  core/Migrations/Version20181220085457.php
  core/Migrations/Version20190125162909.php
  core/Migrations/Version20230105001100.php
  core/Migrations/Version20230120101715.php
  lib/base.php
  lib/private/App/AppManager.php
  lib/private/L10N/L10N.php
  lib/private/Repair/Apps.php
  lib/private/Security/SignedUrl/Verifier.php
  lib/private/Setup/MySQL.php
  tests/acceptance/features/bootstrap/NotificationsCoreContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/OccUsersGroupsContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/TagsContext.php
  tests/lib/DateTimeFormatterTest.php
  tests/lib/L10N/L10nTest.php
  tests/lib/UtilTest.php
Labels: 3 - To Review

#40997 [tests-only] Skip changed repair step test on recently released oC10 versions
  tests/acceptance/features/cliMain/maintenance.feature
Labels: QA:team

#40998 [tests-only][full-ci] skip tag add on recent release ocV10 versions
  tests/acceptance/features/webUISettingsMenu/settingsMenu.feature
Labels: QA:team

#40974 Improve query to cleanup the previews
  apps/files/lib/BackgroundJob/PreviewCleanupJob.php
  changelog/unreleased/40974
  lib/private/PreviewCleanup.php
  tests/acceptance/features/cliTrashbin/previewsCleanup.feature
Labels: 3 - To Review

#40999 [tests-only] Skip cleanup shared files preview test on recently released oc10 versions
  tests/acceptance/features/cliTrashbin/previewsCleanup.feature
Labels: QA:team

#41000 chore: drop APCIterator as apc is long dead + require ext-apcu
  composer.json
  composer.lock
  lib/private/Memcache/APCu.php
Labels: 3 - To Review

#41002 chore: use laravel/serializable-closure instead of opis/closure
  composer.json
  composer.lock
  lib/private/Command/AsyncBus.php
Labels: 3 - To Review

#41003 chore: no dynamic properties
  apps/files/tests/Command/ScanTest.php
  apps/files_sharing/tests/ShareTest.php
  core/ajax/update.php
  tests/Settings/Controller/AppConfigControllerTest.php
  tests/Settings/Controller/AuthSettingsControllerTest.php
  tests/Settings/Controller/UsersControllerTest.php
  tests/TestHelpers/Unit/DeleteHelperTest.php
  tests/acceptance/features/bootstrap/AuthContext.php
  tests/acceptance/features/lib/OwncloudPage.php
  tests/acceptance/features/lib/UsersPage.php
  tests/lib/DB/MySqlToolsTest.php
  tests/lib/Encryption/Keys/StorageTest.php
  tests/lib/Files/Node/NodeTest.php
  tests/lib/Files/ViewTest.php
  tests/lib/Repair/RepairMimeTypesTest.php
  tests/lib/Share20/ShareTest.php
Labels: 3 - To Review
