Repository owncloud/core, pull requests merged in 2023-07, with the labels that each got.

#40859 Improve query performance
  apps/files/lib/Command/RemoveStorageCache.php
  changelog/unreleased/40859
Labels: 3 - To Review

#40865 Update config.apps.sample.php
  config/config.apps.sample.php
Labels: documentation

#40841 Disable online updater for enterprise
  apps/updatenotification/lib/Controller/AdminController.php
  apps/updatenotification/templates/enterprise.php
  changelog/unreleased/40841
Labels: 3 - To Review

#40856 fix: use empty() to check if header exists
  apps/files_sharing/lib/Controller/Share20OcsController.php
  changelog/unreleased/40856
  core/Controller/OcsController.php
  lib/private/AppFramework/Middleware/Security/SecurityMiddleware.php
  tests/lib/AppFramework/Middleware/Security/SecurityMiddlewareTest.php
Labels: 3 - To Review

#40875 Improve log messages for encryption rename
  lib/private/Files/Storage/Wrapper/Encryption.php
Labels: 3 - To Review

#40878 Bump files app version
  apps/files/appinfo/info.xml
  changelog/unreleased/40878
  tests/Core/Command/Apps/AppsListTest.php
Labels: 3 - To Review

#40883 [tests-only][full-ci] Use of publicWebDAVAPIVersion on publicLocksFileLastSharedFolder function
  tests/acceptance/features/apiWebdavLocks/publicLink.feature
  tests/acceptance/features/apiWebdavLocks/publicLinkOc10Issue40882.feature
  tests/acceptance/features/bootstrap/WebDavLockingContext.php
Labels: QA:team

#40888 [tests-only] Add test step to set the system skeleton for a scenario
  tests/acceptance/features/bootstrap/Provisioning.php
Labels: QA:team

#40885 Minimum search length will be applied for all shares
  apps/files_sharing/lib/Controller/ShareesController.php
  changelog/unreleased/40885
Labels: 3 - To Review
