Repository owncloud/core, pull requests merged in 2023-02, with the labels that each got.

#40509 [full-ci] Add Webdav Token endpoint by App Passwords
  settings/templates/panels/personal/tokens.php
Labels: 3 - To Review

#40614 chore: add changelog entry for #40509
  changelog/unreleased/40509
Labels: 3 - To Review

#40514 fix: optimize preview cleanup sql
  lib/private/PreviewCleanup.php
Labels: 3 - To Review

#40511 [full-ci] Show Legal statement by personal settings
  changelog/unreleased/40511
  settings/Panels/Personal/Profile.php
  settings/templates/panels/personal/profile.php
  tests/acceptance/features/bootstrap/WebUIPersonalGeneralSettingsContext.php
  tests/acceptance/features/lib/PersonalGeneralSettingsPage.php
  tests/acceptance/features/webUIPersonalSettings/personalGeneralSettings.feature
Labels: 3 - To Review

#40623 chore: add missing changelog/unreleased/40514
  changelog/unreleased/40514
Labels: 3 - To Review

#40625 [tests-only][full-ci] Remove isTestingOnReva() and isTestingOnOcis() and their references
  tests/TestHelpers/OcisHelper.php
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40617 Fix two-factor enable over API
  apps/provisioning_api/lib/Users.php
  apps/provisioning_api/tests/UsersTest.php
  changelog/unreleased/40617
Labels: 3 - To Review

#40600 Adjust stream chunk size to load big exif metadata
  changelog/unreleased/40600
  lib/private/legacy/image.php
  tests/data/bigexif.jpg
  tests/lib/ImageTest.php
Labels: 3 - To Review

#40628 [tests-only][full-ci] Remove isTestingOnOcisOrReva() method and its references
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/LoggingHelper.php
  tests/TestHelpers/OcisHelper.php
  tests/TestHelpers/SetupHelper.php
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/CorsContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40630 [tests-only][full-ci] Remove ocis bug demonstration scenarios and leftover ocis skip tags
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiShareManagementBasicToShares/createShareToSharesFolder.feature
  tests/acceptance/features/apiShareOperationsToShares1/gettingShares.feature
  tests/acceptance/features/apiSharePublicLink3/updatePublicLinkShare.feature
  tests/acceptance/features/apiShareUpdateToShares/updateShare.feature
Labels: QA:team

#40629 [tests-only][full-ci] Remove OcisHelper class and its references
  tests/TestHelpers/HttpRequestHelper.php
  tests/TestHelpers/OcisHelper.php
  tests/acceptance/features/bootstrap/CorsContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/LoggingContext.php
  tests/acceptance/features/bootstrap/OccContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/PublicWebDavContext.php
  tests/acceptance/features/bootstrap/SearchContext.php
  tests/acceptance/features/bootstrap/Sharing.php
  tests/acceptance/features/bootstrap/WebDav.php
Labels: QA:team

#40632 [tests-only][full-ci] Remove remaining ocis related code
  tests/TestHelpers/WebDavHelper.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/Provisioning.php
  tests/acceptance/features/bootstrap/TUSContext.php
  tests/acceptance/features/bootstrap/WebDav.php
  tests/acceptance/features/bootstrap/bootstrap.php
Labels: QA:team

#40636 [docs-only] Fix headline in config.sample
  config/config.sample.php
Labels: documentation

#40633 fix: add index on oc_filecache over size, parent and storage to speed…
  changelog/unreleased/40633
  core/Migrations/Version20230210073645.php
  version.php
Labels: 3 - To Review

#40499 Remove empty directories from the files_versions
  apps/files_trashbin/lib/Trashbin.php
  apps/files_trashbin/tests/StorageTest.php
  apps/files_versions/lib/Storage.php
  changelog/unreleased/40499
Labels: 3 - To Review

#40640 feat: occ user:sync - support abbreviations for backend classes for e…
  changelog/unreleased/40640
  core/Command/User/SyncBackend.php
Labels: 3 - To Review

#40619 [full-ci][tests-only]Try `JSON` response drilling with library
  tests/acceptance/features/apiCapabilities/capabilities.feature
  tests/acceptance/features/apiCapabilities/capabilitiesWithNormalUser.feature
  tests/acceptance/features/bootstrap/AppConfigurationContext.php
  tests/acceptance/features/bootstrap/CapabilitiesContext.php
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
  vendor-bin/behat/composer.json
Labels: QA:team

#40644 [tests-only]Skip tests on old oc10 versions
  tests/acceptance/features/apiVersions/fileVersionAuthor.feature
  tests/acceptance/features/apiVersions/fileVersionAuthorSharingToShares.feature
  tests/acceptance/features/apiVersions/fileVersions.feature
Labels: QA:team

#40647 [tests-only][full-ci]Skip `versions` related `webUI` test on old `oc10` versions
  tests/acceptance/features/webUIFiles/versions.feature
Labels: QA:team

#40645 [tests-only] allow plain acceptance test output
  tests/acceptance/lint-expected-failures.sh
  tests/acceptance/run.sh
Labels: QA:team

#40648 [tests-only][full-ci]Donot use static xpath for rename tag input
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
Labels: QA:team

#40650 [tests-only][full-ci] Get ocs code from the provided response
  tests/acceptance/features/bootstrap/FeatureContext.php
  tests/acceptance/features/bootstrap/OCSContext.php
Labels: QA:team

#40612 Fix share into share move scenario
  apps/files_sharing/lib/Updater.php
  changelog/unreleased/40612
Labels: 3 - To Review

#40651 [tests-only] Fix command format in tests/acceptance/run.sh
  tests/acceptance/run.sh
Labels: QA:team

#40652 Adjust parameters for guzzle7
  apps/federatedfilesharing/lib/Notifications.php
  apps/federation/lib/BackgroundJob/RequestSharedSecret.php
  apps/federation/tests/BackgroundJob/RequestSharedSecretTest.php
  lib/private/HTTPHelper.php
  lib/private/Http/Client/Client.php
  lib/public/Http/Client/IClient.php
  tests/lib/HTTPHelperTest.php
Labels: 3 - To Review

#40567 [full-ci] Prevent creation of empty files/folders for accounts having no available quota
  apps/dav/lib/Connector/Sabre/Directory.php
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
  apps/dav/lib/Upload/ChunkLocationProvider.php
  apps/dav/tests/unit/Upload/ChunkLocationProviderTest.php
  changelog/unreleased/40567
  tests/acceptance/features/apiMain/quota.feature
Labels: 3 - To Review

#40659 Allow stream wrappers not to provide the underlying stream
  lib/private/legacy/image.php
Labels: 3 - To Review
