Repository owncloud/core, pull requests merged in 2023-11, with the labels that each got.

#41077 fix: proper error handling when deleting users/groups is failing
  changelog/unreleased/41077
  settings/js/users/deleteHandler.js
  settings/js/users/groups.js
  settings/js/users/users.js
  settings/tests/js/users/deleteHandlerSpec.js
Labels: 3 - To Review

#41080 [docs-only] add toc to changelog
  changelog/CHANGELOG.tmpl
Labels: 3 - To Review, documentation

#41083 [docs-only] fix changelog template for the date field
  changelog/CHANGELOG.tmpl
Labels: 3 - To Review

#41082 fix: drop code related to php version 7.3 and ealier
  lib/private/Session/CryptoWrapper.php
  lib/private/Session/Internal.php
  settings/Application.php
  settings/Controller/CheckSetupController.php
  tests/Settings/Controller/CheckSetupControllerTest.php
Labels: 3 - To Review

#41089 Update config.sample files
  config/config.apps.sample.php
  config/config.sample.php
Labels: 3 - To Review, documentation

#41091 [docs-only] missing word in changelog.tmpl
  changelog/CHANGELOG.tmpl
Labels: 3 - To Review, documentation

#41095 chore: drop deprecated API since ownCloud 6.0.0
  lib/kernel.php
  lib/private/AppFramework/Core/API.php
  lib/private/BackgroundJob/Legacy/QueuedJob.php
  lib/private/BackgroundJob/Legacy/RegularJob.php
  lib/public/BackgroundJob.php
  tests/Core/Command/Background/Queue/StatusTest.php
Labels: 3 - To Review

#41100 chore(dependabot): group all symfony dependencies
  .github/dependabot.yml
Labels: 3 - To Review

#41078 Revert "Revert "fix: on rejected shares no activities are reported to…
  changelog/unreleased/40421
  lib/private/Share/Share.php
  lib/public/Share/IShare.php
  tests/lib/Share/GetUsersSharingFileTest.php
  tests/lib/TestCase.php
  tests/lib/Traits/GroupTrait.php
Labels: 3 - To Review

#41063 Fix issue with LDAP groups in the applicable field
  apps/files_external/appinfo/routes.php
  apps/files_external/js/settings.js
  apps/files_external/lib/Controller/ApplicableController.php
  apps/files_external/tests/Controller/ApplicableControllerTest.php
  changelog/unreleased/41063
Labels: 3 - To Review

#41093 feat: in debug mode write sql queries to the log file
  config/config.sample.php
  lib/kernel.php
  lib/private/Diagnostics/Query.php
  tests/lib/Diagnostics/QueryLoggerTest.php
Labels: 2 - Developing

#41099 fix: drop JavaScript function `tipsy()` in favor of bootstrap tooltip
  apps/federatedfilesharing/js/settings-admin.js
  apps/files/js/breadcrumb.js
  apps/files/js/file-upload.js
  core/js/backgroundjobs.js
  core/js/js.js
  core/js/share.js
  core/js/singleselect.js
  core/js/tests/specs/shareSpec.js
  settings/js/admin-apps.js
  settings/js/certificates.js
  settings/js/panels/backgroundjobs.js
  settings/js/users/users.js
  settings/templates/panels/admin/backgroundjobs.php
  settings/templates/users/part.setquota.php
Labels: 3 - To Review

#41104 docs: add missing WND Kerberos settings to config.apps.sample
  config/config.apps.sample.php
Labels: 3 - To Review, documentation

#41106 docs: clarify missing wnd config parameter
  config/config.apps.sample.php
Labels: 3 - To Review, documentation

#41092 fix: user can only delete own external storage
  apps/files_external/lib/Controller/UserStoragesController.php
  changelog/unreleased/41092
  lib/private/Files/External/Service/DBConfigService.php
  lib/private/Files/External/Service/UserStoragesService.php
  tests/lib/Files/External/Service/UserStoragesServiceTest.php
Labels: 3 - To Review

#41105 feat: check conventional commits in drone
  .drone.star
Labels: 3 - To Review

#41094 chore: set autoload-dev in composer.json
  composer.json
  phpstan.neon
  tests/Core/Command/Apps/AppsDisableTest.php
  tests/Core/Command/Apps/AppsEnableTest.php
  tests/Core/Command/Apps/AppsGetPathTest.php
  tests/Core/Command/Apps/AppsListTest.php
  tests/Core/Command/Apps/CheckCodeTest.php
  tests/Core/Command/Maintenance/RepairTest.php
  tests/Core/Controller/AppRegistryControllerTest.php
  tests/Core/Controller/TwoFactorChallengeControllerTest.php
  tests/Core/Middleware/AccountModuleMiddlewareTest.php
  tests/Core/Middleware/TwoFactorMiddlewareTest.php
  tests/Core/Templates/TemplatesTest.php
  tests/Settings/Controller/AuthSettingsControllerTest.php
  tests/Settings/Controller/LegalSettingsControllerTest.php
  tests/bootstrap.php
  tests/lib/Settings/SettingsManagerTest.php
  tests/lib/Share/Filters/MailNotificationFilterTest.php
  tests/lib/Shutdown/ShutdownManagerTest.php
Labels: 3 - To Review

#41112 chore: remove CHANGELOG.html and its creation
  .drone.star
  CHANGELOG.html
  changelog/CHANGELOG-html.tmpl
Labels: 3 - To Review

#41113 chore: drop unused api /displaynames
  core/Application.php
  core/Controller/UserController.php
  core/routes.php
Labels: 3 - To Review

#41117 docs: OIDC config sample update
  config/config.apps.sample.php
Labels: 3 - To Review, documentation

#41056 fix: file list visual fixes on expirations date and decuplicate elements on shared files
  apps/files/js/filelist.js
  apps/files_sharing/js/sharedfilelist.js
  changelog/unreleased/41056
Labels: 3 - To Review, app:files

#41125 fix: `user:list -a` command now correctly displays user's creation time
  changelog/unreleased/41125
  core/Command/User/ListUsers.php
Labels: 3 - To Review
