Repository owncloud/core, pull requests merged in 2023-03, with the labels that each got.

#40661 Fix issue if no version has been created yet
  apps/files_versions/lib/Storage.php
Labels: 3 - To Review

#40671 Make sender display name in mail notifications configurable
  changelog/unreleased/40671
  config/config.sample.php
  core/l10n/en_GB.js
  core/l10n/en_GB.json
  core/l10n/fa.js
  core/l10n/fa.json
  lib/l10n/fa.js
  lib/l10n/fa.json
  lib/private/Share/MailNotifications.php
  settings/l10n/en_GB.js
  settings/l10n/en_GB.json
  settings/l10n/fa.js
  settings/l10n/fa.json
  tests/lib/Share/MailNotificationsTest.php
Labels: 3 - To Review

#40675 [tests-only][full-ci] Implement new webui steps to check sidebar navs and details tabs
  tests/acceptance/features/bootstrap/WebUIFilesContext.php
  tests/acceptance/features/bootstrap/WebUIGeneralContext.php
  tests/acceptance/features/lib/FilesPageElement/DetailsDialog.php
  tests/acceptance/features/lib/OwncloudPage.php
Labels: QA:team

#40688 chore: remove unused openidconnect config option `use-token-introspec…
  config/config.apps.sample.php
Labels: 3 - To Review

#40693 Use getHome in ChunkLocationProvider.php
  apps/dav/lib/Upload/ChunkLocationProvider.php
Labels: 3 - To Review

#40694 Add changelog for PR 40693
  changelog/unreleased/40693
Labels: 3 - To Review

#40697 Add rewrite base to generated .htaccess rules
  lib/private/Setup.php
Labels: 2 - Developing

#40709 Prevent 507 Insufficient Storage on 32-bit systems
  apps/dav/lib/Connector/Sabre/QuotaPlugin.php
  changelog/unreleased/40709
Labels: 3 - To Review

#40701 fix permission bits when enforcing rw links
  core/js/sharedialoglinkshareview.js
  lib/private/Share20/Manager.php
  tests/lib/Share20/ManagerTest.php
Labels: 3 - To Review

#40712 [full-ci] fix: remove `php occ encryption:select-encryption-type` from drone
  .drone.star
  tests/acceptance/features/bootstrap/EncryptionContext.php
  tests/acceptance/features/bootstrap/OccContext.php
Labels: 3 - To Review

#40677 fix: in case root on CacheJail is an empty string we should not prefi…
  lib/private/Files/Cache/Wrapper/CacheJail.php
Labels: 3 - To Review
